### ISSUE TITLE
[Tooling] Add script for checking pin dependencies

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#100]
We should have the `throw-if-pinned-dependency-version-changes.js` script that we use in the MC FE in this repo as well and update the list accordingly.

**Comment by tdeekens** [comment]
That'd be very reasonable. I wonder if that is actually a nice separate Open Source package.

**Comment by emmenko** [comment]
Or to include it in like renovate & co.?

**Comment by tdeekens** [comment]
After thinking about this some more I'd recommend making this a Probot over a script. Given it's a script it would have to integrate with Renovate and potentially any other service. Given it's a Probot it can hook into things on a GitHub level. Just like the "WIP bot". It would assign a label or generally just reject a review.

**Comment by emmenko** [comment]
A bot would be cool yes. It's a bit more work though, so maybe the script as a first step is enough.

In any case, if someone wants to spend some time on this I'm all for it 💯

**Comment by tdeekens** [comment]
Given that we removed the script from the mc-fe and Renovate is configured to not update deps I would go ahead and close this.
