### ISSUE TITLE
How to build a search form

### ISSUE THREAD

**Issue by timonag** [commercetools/merchant-center-application-kit#1012]
Can anyone explain how to build a search form with displaying results? I'm trying to combine _Formik_ with _Query_  however with no luck. I've managed to put form values into a state and how to make a request  but it's totally unclear how it should work together.

**Comment by tdeekens** [comment]
Thanks for creating the issue. Personally, I don't see this as documentation for app-kit. It's more general and can be applied to any project or application. 

What I would suggest doing:

1. Build the search without GraphQL/Apollo and Formik with static data
2. Replace static data with fetching through a GraphQL API and Apollo
   - Note that Apollo isn't stricly needed to do this
3. Maybe add Formik if it eases things

Generally, I don't think that Formik is a good fit for the problem as you seem to not build a form but rather a single input search without much valiation. I would rather focus on dealing with "overlapping" requests or cancelling them.

**Comment by timonag** [comment]
Unfortunately it's incomprehensible for me being a backend developer who has to build an MC custom application. 
I've got two inputs and a submit button. How the search is triggered? Should I use states or redux store?

**Comment by emmenko** [comment]
Can you explain a bit more what's the expected outcome and what the interaction should do? For example, what are the 2 inputs for? Is the button the only way to trigger the search?

If we can understand a bit more the required functionality, we can try to provide a sandbox example for you.

**Comment by timonag** [comment]
I need a search form with two product attributes values to search with a button. Both are used to create _where_ variable for gql search. Then I need to display all products found.

**Comment by montezume** [comment]
This is more questions of how to use React / front end development

Maybe it would be best to start by doing a tutorial on how to build a TODO list in React with search, etc, before trying something this complicated?

I don't think it's feasible to be able to have this kind of documentation.

**Comment by emmenko** [comment]
@timonag if you still need help with the code please let us know.

**Comment by timonag** [comment]
I'll follow an advise to rtfm and will try to find a good enough React developer on my side.

**Comment by emmenko** [comment]
Let me clarify something first, as I feel there is some tension in this thread.

We're here to help in any way possible and our priority is around topics related to developing Custom Applications. Obviously your question does not relate directly to that but it's more as a general question around building a UI with, in this case, React and GraphQL.
You can image that teaching how to write a UI in React is not our main priority, as there are much better resources out there to do so (tutorials, video lessons, etc).

Nevertheless, we are still offering our help to get you started, so the more info you get give us, the better we can try to help you.

I hope this clarifies things out, let us know how you wish to proceed ☺️
