### ISSUE TITLE
Package l10n:  Unsupported countries

### ISSUE THREAD

**Issue by islam3zzat** [commercetools/merchant-center-application-kit#1032]
**Describe the bug**
Package @commercetools-frontend/l10n

Adding any of the [addedd countries](https://github.com/commercetools/merchant-center-application-kit/pull/988/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) in  #988
 e.g `cg-alt-variant `, `un-alt-short `, ...`us-alt-short` in the zones
causes issue.
![issue](https://user-images.githubusercontent.com/7680511/64244358-2e4d8b80-cf09-11e9-99a0-199e8af7fc94.gif)
After checking the Graphql definition for the ZoneLocation
- ![image](https://user-images.githubusercontent.com/7680511/64244559-91d7b900-cf09-11e9-9ada-6a62f7f5c81d.png)
- ![image](https://user-images.githubusercontent.com/7680511/64244649-b764c280-cf09-11e9-86fe-0b541a8a551f.png)

So the supported codes are those
https://en.wikipedia.org/wiki/ISO_3166-1#Officially_assigned_code_elements
**To Reproduce**

1. Go to `settings` the `international` tab;
2. Click on edit icon in the zones pane;
3. Add `un-alt-short` in the `Country codes` column of any row.

**Expected behavior**
The zone to be updated

**Comment by emmenko** [comment]
Thanks for reporting. I guess we need to filter them out in the generate script

https://github.com/commercetools/merchant-center-application-kit/blob/d71122f41dae4ccbf6af2b3775bbc55eb78116d2/packages/l10n/scripts/generate-l10n-data.js#L40-L44

@islam3zzat do you want to open a PR?

**Comment by islam3zzat** [comment]
I'm on it.
