### ISSUE TITLE
Redirect loop issue after register a custom application in Merchant Center

### ISSUE THREAD

**Issue by alochowski** [commercetools/merchant-center-application-kit#1052]
I've deployed my custom application on server. Unfortunately my domain has been blocked by CORS policy.

I've set this domain in "**Application URL**" field in Merchant Center, but when I open my domain I've got redirecting loop with param `?**reason=unauthorized**`

I have the same domain set in **frontendHost** param in **env.prod.json** config file.

Is there something which I missing? I didn't set?

**Comment by emmenko** [comment]
Hi, custom applications only works [behind the MC proxy](https://appkit.commercetools.com/main-concepts/architecture). This means that you need to register your application first and access the app through the Merchant Center. You can't access the app directly from your domain.

Also, did you configure the CSP rules in the `headers.json`?

Have a look a those links first, just to make sure that you followed all the steps:
- https://appkit.commercetools.com/deployment/runtime-configuration
- https://appkit.commercetools.com/register-applications/configuring-a-custom-application

Can I ask also how did you deploy the app? Did you use the [HTTP server library](https://appkit.commercetools.com/deployment/http-server) that we provide or did you use something else?

**Comment by alochowski** [comment]
I've checking our infrastructure and my custom application was only available in VPN, so that was a problem with 502 error. I think we can close this ticket.

Thanks a lots for your help.

**Comment by emmenko** [comment]
Awesome, glad that we could figure it out. Let us know if you have any further questions.
