### ISSUE TITLE
Is there possibility to set main route as a first sub route?

### ISSUE THREAD

**Issue by alochowski** [commercetools/merchant-center-application-kit#1059]
**Is your feature request related to a problem? Please describe.**
As is in the topic. Can't set main route as sub route. In configuration field `Link to` is require and I have to put any string for this field. I can set `/` as main route but this string is concatenated with my main route and then I have: _/<main_route>//_ - this url looks little strange

**Describe the solution you'd like**
If is possibility nice to have will be read `menu.json` file like is it for development environment.

**Describe alternatives you've considered**
Other solution can be set this field as not required.

**Additional context**
I want to get situation similarly like is it for Products tab and sub route **Product list**.
![products_tab](https://user-images.githubusercontent.com/51888654/65026148-445f4100-d938-11e9-9f70-6a0e0bdcb5ba.png)

**Comment by tdeekens** [comment]
Thanks for you issue. There is currently no possibility to "extend" our own applications by adding a sub route there. Custom applications in that live on their own not being able to hook into existing/internal application navigation. There is also, at least for now, no prioritised effort to my knowledge to add this before getting custom applications out of beta.

**Comment by alochowski** [comment]
Thanks for response. Ok, and what about second solution, set this field as not required? or similar solution to set sub route as main route. Is also not possibility for now?

**Comment by emmenko** [comment]
That could be possible, I think it's just a restriction in the UI at the moment. Let me look into that and get back to you.

**Comment by alochowski** [comment]
Ok, thanks.

**Comment by emmenko** [comment]
FYI: I made some changes in the UI to allow this use case. I will let you know when it's live.

**Comment by tdeekens** [comment]
It's not deployed yet but I bet @emmenko is on it. Just wanted to share cause this might look otherwise :).

**Comment by emmenko** [comment]
Yeah, it's a bit weird that we can close issues cross-repository

**Comment by emmenko** [comment]
@alochowski the change is live. Can you please have a look? You need to pass `/` as the link value:

<img width="812" alt="image" src="https://user-images.githubusercontent.com/1110551/65042386-09213a00-d959-11e9-811f-5d9b0f9d9dcb.png">

**Comment by alochowski** [comment]
@emmenko awesome thank you, works great.
