### ISSUE TITLE
External dependency for custom application in Merchant Center (CSP policy)

### ISSUE THREAD

**Issue by alochowski** [commercetools/merchant-center-application-kit#1072]
I've add dependency package, but when I try to use it I've got Content Security Policy error.

_EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' storage.googleapis.com/mc-production-eu/ storage.googleapis.com/mc-production-us/ www.googletagmanager.com/gtm.js www.google-analytics.com/analytics.js localhost:* 'unsafe-inline' localhost"._

Is there something what I missing?

I'm working on local environment, using `headers.json` file and I have `csp` param set.

**headers.json**
```
{
  "csp": {
    "script-src": ["localhost"],
    "connect-src": ["localhost"],
    "style-src": ["localhost"]
  }
}
```

**Comment by amine-benselim** [comment]
as per the documentation from the chrome team here: https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-eval 
you can try adding `unsafe-eval` to your 'script-src'. however please be aware of the risks of doing so

```
The policy against eval() and its relatives like setTimeout(String), 
setInterval(String), and new Function(String) can be relaxed by adding 'unsafe-eval' to your policy:

"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"

However, we strongly recommend against doing this. These functions are notorious XSS attack vectors.
```

**Comment by tdeekens** [comment]
This to me looks like some script of yours wants to perform and unsafe-eval which our CSPs do not allow (or recommend) by default. As a result you see the error. 

Given your carefully review if you actually want to allow it you could enable it using your headers.json. However, I would advise trying to find the source wanting to perform the eval as it might be a security relevant issue. 

In all it may be more an issue with your application or vendor code than a false configuration. The MC custom apps just recommend quite restrictive CSPs to be as secure as possible.

**Comment by alochowski** [comment]
Thanks for answers. Yes, I know that some script wants to perform request and I know what package it is.

Generally I wanted to know if I put domain which that script want to get some resource in `headers.json` file, this allows him to get that resorce or this is not possible in Custom Application and bloked by CSPs.

And what if I want to send a request to get some data from external domain? Will also get CSP error?

**Comment by tdeekens** [comment]
If you add and hence whitelist that domain the request will be allowed as our mc-http-server will then add the respective CSPs headers instructing the browser to not block it. However, whitelisting another origin to allow requests to and enabling unsafe-eval are to different things even if both are and can be controlled via CSP directives.

**Comment by emmenko** [comment]
@alochowski regarding your question about external domains, you just need to whitelist the domain as you already do with the domain where your app is hosted.

**Comment by tdeekens** [comment]
@alochowski is there anything open/unclear from your end. Otherwise we would like to close this issue.

**Comment by alochowski** [comment]
Hi, sorry I forgot about this issue.
I thought that we can't using external domains, but I think now everything is clear. 
Thanks for your helps.
I close this issue.
