### ISSUE TITLE
docs(website): AWS deployment - "Update_Failed" error for "LambdaEdgeFunctionVersion" 

### ISSUE THREAD

**Issue by lefamoffat** [commercetools/merchant-center-application-kit#1074]
**Describe the bug**
The issue happens during the "Update AWS Resources" step of the AWS deployment documentation. After I execute the Lambda Function I get the following error message from AWS:

_"The following resource(s) failed to update: [LambdaEdgeFunctionVersion]."_

**To Reproduce**

1. Create a sample custom app with:
`npx @commercetools-frontend/create-mc-app my-new-custom-application-project --template starter`
2. The only changes I made where the additional files from the [AWS deployment documentation](https://appkit.commercetools.com/deployment/example-aws-s3-cloudfront) 

**Expected behavior**
I expected the Lambda.js to update the stack successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/49285031/65613544-2041d680-dfae-11e9-9dc8-860a92df5ed9.png)

**Comment by tdeekens** [comment]
Thanks for reporting the issue. 

Personally I have not experienced this issue. As a result I struggle meaningful help. Sorry about that. Maybe @stephsprinkle can help out as she has done more work with AWS if I recall correctly.

**Comment by emmenko** [comment]
@stephsprinkle can you try to help out here? Have you seen this error before?

**Comment by stephsprinkle** [comment]
@lefamoffat Does `mc-app-demo-PublishLambdaVersion-YDQEC9045JWY` exist under the `Resources` tab? What parameters did you use when you created your CloudFormation change set?

**Comment by lefamoffat** [comment]
Thank you everyone for looking at my "issue". I deployed another custom application today (my 4th one) and it compiled without any issues. As far as I'm aware, I didn't do anything differently today... Strange, but I'm not complaining :) Thanks again for your help!

**Comment by lefamoffat** [comment]
So I think I've resolved the issue. The problem was with the registration of the application. In the documentation it says that the "Application URL" should be the same as the "frontendHost" in the "env.json" file, which in this deployment would be "mc.commercetools.co". I've changed this value to my CloudFront Domain. Now it's working with the occasional "Sorry! An unexpected error occured." message.

**Comment by emmenko** [comment]
> which in this case would be "mc.commercetools.co"

Hmm no, the `frontendHost` should be the hostname of where your app is hosted.

**Comment by lefamoffat** [comment]
Yeah makes sense now... I copied this from the guide:

{
  "applicationName": "my-app",
  "frontendHost": "mc.commercetools.co",
  "mcApiUrl": "https://mc-api.commercetools.com",
  "location": "eu",
  "env": "production",
  "cdnUrl": "https://[cloudfront-domain]",
  "servedByProxy": true
}

Guessing it should be:

{
  "applicationName": "my-app",
  "frontendHost": "[cloudfront-domain]",
  "mcApiUrl": "https://mc-api.commercetools.com",
  "location": "eu",
  "env": "production",
  "cdnUrl": "https://[cloudfront-domain]",
  "servedByProxy": true
}

**Comment by lefamoffat** [comment]
Ok great, so I did the build again and updated everything on AWS. Since then I haven't received the error message. So the latter issue was just due to the wrong "frontendHost" value inside the env.prod.json configuration. Could you update that in the guide for people like me? 

Thank you everyone for your help! :)

**Comment by tdeekens** [comment]
It seems like the issue has been solved. If I am mistaken in that perception, feel free to re-open :).
