### ISSUE TITLE
Error in rtl test when using ProjectExtensionProviderForImageRegex

### ISSUE THREAD

**Issue by ahmehri** [commercetools/merchant-center-application-kit#1096]
**Describe the bug**
When I `renderApp`, in a rtl test, a component that renders app-kit `ProjectExtensionProviderForImageRegex` I get an error.

**To Reproduce**

1. Create a rtl test
2. use `renderApp` with a component that renders `ProjectExtensionProviderForImageRegex`
3. See error

```
Error: Network error: No more mocked responses for the query: query FetchProjectExtensionImageRegex {
      projectExtension {
        id
        imageRegex {
          thumb {
            ...ImageRegex
          }
          small {
            ...ImageRegex
          }
        }
      }
    }
    
    fragment ImageRegex on ImageRegexOptions {
      flag
      search
      replace
    }
```

**Expected behavior**
No error should occur.

**Comment by emmenko** [comment]
Thanks for reporting. I think we can expose some mocks, or a way to mock this from our app-shell test-utils
