### ISSUE TITLE
createPluginReducer is no longer exported from application-shell

### ISSUE THREAD

**Issue by dlilly** [commercetools/merchant-center-application-kit#1133]
Hi there --

I'm trying to upgrade a MC app and am getting this error.  I am upgrading from application-shell v3.1.0 to the latest.

I've attached the relevant file.  Please let me know if there's any other information I can give to help.

Thanks!

[routes.js.txt](https://github.com/commercetools/merchant-center-application-kit/files/3779714/routes.js.txt)

**Comment by emmenko** [comment]
Uh that's a very old version.

I suggest to look at e.g. the [starter app](https://github.com/commercetools/merchant-center-application-kit/tree/master/application-templates/starter) or the [playground app](https://github.com/commercetools/merchant-center-application-kit/tree/master/playground) and compare the setup.

**Comment by emmenko** [comment]
Also, you have a bunch "internal" apps components that may also be affected as they might also be quite outdated. I'm not sure how much we can help you to be honest.

Try upgrading version by version and see what works and what not.
