### ISSUE TITLE
Custom Applications Menu Icon not showing from other tabs

### ISSUE THREAD

**Issue by ebonertz** [commercetools/merchant-center-application-kit#1146]
**Describe the bug**
When you log into MC and access a project with a registered custom application the Icon and Title of the custom app are displayed when on the Welcome page and the Dashboard page. If you navigate to any of the other tabs like products list, orders list etc. you can no longer see the custom application in the menu. 

**To Reproduce**

1. Log into MC and to a project with a registered custom app and observe in the Nav
2. Navigate to the Orders List page 
3. Observe left navigation and that the custom app Icon and title are no longer displayed

**Expected behavior**
Custom App Icon and Title Should be viewable from any other page or tab in the MC. 

**Additional context**
Appears to be reproducible on any project or custom app.

**Comment by emmenko** [comment]
Hmm thanks for reporting. It looks like it might be a regression to some dependency that got updated. From what I can see, the dashboard and welcome app have last been deployed on October 28th. All deployments after that seem to have the problem.

https://mc.commercetools.com/versions

It seems to be related to the feature toggles, we changed something related to that last week. See also #1107

**Before the `featureFlags` option**

<img width="1746" alt="Screenshot 2019-11-05 at 21 02 27" src="https://user-images.githubusercontent.com/1110551/68242009-074a2d80-0010-11ea-80c2-535958d62474.png">

**After the `featureFlags` option**

<img width="1746" alt="Screenshot 2019-11-05 at 21 03 05" src="https://user-images.githubusercontent.com/1110551/68242043-14ffb300-0010-11ea-8590-bd9f60dc3cd5.png">

@tdeekens can you confirm that? I suppose we need to merge the app-shell internal feature toggles to the given `featureFlags`.

**Comment by emmenko** [comment]
The custom apps menu links are behind a feature flag `projectExtensions`, which is missing after the change.

**Comment by tdeekens** [comment]
I will have a look.

**Comment by tdeekens** [comment]
We identified the problem and are working towards a fix. Our CI pipeline is working for a fix in our apps which we will deploy soon while a PR to app-kit is also up to fix the issue in custom apps.
