### ISSUE TITLE
Cart discount predicates with custom fields don't show values in UI view of cart rule builder

### ISSUE THREAD

**Issue by torihedden** [commercetools/merchant-center-application-kit#1151]
**Describe the bug**
A cart discount (created with a custom application) with a cart predicate containing values for custom fields is not displaying UI elements in the cart discount rule builder. The entire predicate, including the custom fields and their values, is present in the raw predicate. The select element that should contain the value from a custom field of type enum is not present in the cart discount rules builder. (See attached screenshots).

**To Reproduce**

1. Log into MC and navigate to cart discounts.
2. Click on a cart discount that has custom fields set in its cart predicate. In this case, the custom fields and possible values were set on the "carts" resource in a Merchant Center project with the following request body:
```
{
   "key":"monthly-special",
   "name":{
      "en":"Monthly Special"
   },
   "resourceTypeIds":[
      "order"
   ],
   "description":{
      "en":"Additional fields for Monthly Specials custom application"
   },
   "fieldDefinitions":[
      {
         "name":"date",
         "type":{
            "name":"String"
         },
         "required":false,
         "label":{
            "en":"Date"
         },
         "inputHint":"SingleLine"
      },
      {
         "name":"promoType",
         "type":{
            "name":"LocalizedEnum",
            "values":[
               {
                  "key":".com",
                  "label":{
                     "en":".com"
                  }
               },
               {
                  "key":"party-guest",
                  "label":{
                     "en":"Party Guest"
                  }
               },
               {
                  "key":"party-host",
                  "label":{
                     "en":"Party Host"
                  }
               }
            ]
         },
         "required":false,
         "label":{
            "en":"Promo Type"
         },
         "inputHint":"SingleLine"
      }

   ]
}
```
3. The values for custom field `promoType` are not represented by any UI elements in the rule builder.

**Expected behavior**
I expect to see select or input elements for the predicate field identifiers, the operators, AND the values, but there is no element in the UI view of the rule builder to represent values.

**Screenshots**

![Merchant Center Cart Discount Rules - Missing Value](https://user-images.githubusercontent.com/16636389/68395154-3d390000-013d-11ea-9777-06a659b7ae7c.png)
![Merchant Center Cart Discount Rules - Raw Predicate](https://user-images.githubusercontent.com/16636389/68395162-40cc8700-013d-11ea-9bab-06805663c0d1.png)

**Additional context**
The larger, blue box in the first screen shot shows the custom field portion of the cart discount predicate. The red, smaller box indicates where the values of this part of the predicate would be, represented by some elements. The second screenshot is of the raw cart predicate, indicating that the values for the custom field "promoType" ARE present in the cart discount.

**Comment by tdeekens** [comment]
Thanks for the very nice write up! I however don't think, as far as I read it, that this is related to custom apps. It's more within the domain of an internal team. Maybe something for @islam3zzat and @astolzenberger so look into?

**Comment by torihedden** [comment]
Agreed that this issue isn't related to custom apps, I included that this bug originated from a custom app just for context. My assumption is that it is a bug in Merchant Center. Thanks for your quick response @tdeekens!

**Comment by tdeekens** [comment]
I would assume so too. For background, the rule builder is incredibly complex with a built in parser. It might still not, purposefully as per priority, cover all cases of what one can set up via the DSL. It's hard to either say "the rule can't be parsed" or just "parse as much as possible".

**Comment by islam3zzat** [comment]
Thanks, @torihedden for the detailed description which has helped me find the issue.
As mentioned above this is not related to the appkit, and will be addressed in the MC.
I will close this and create an issue in the MC project.

**Comment by torihedden** [comment]
Thanks for moving this to the right project, @islam3zzat !
