### ISSUE TITLE
Is there something changes on Merchant Center?

### ISSUE THREAD

**Issue by alochowski** [commercetools/merchant-center-application-kit#1206]
Hi, 
As is in the topic. Is there something changes on Merchant Center?
On friday my custom application worked but today I've got 500 error message. I didn't deploy anything which can broken something. 
Do you have possibility to check logs on production?

**Comment by tdeekens** [comment]
Thanks for reaching out. We have not made a change which should affect custom applications in any way to our knowledge.

Can you provide more detailed information on the request which is failing. Maybe a sanitised screnshot of Chrome DevTools or request/response logs. Without it's a bit hard ot say what have could gone wrong and on what end the error might be. 

Thanks.

**Comment by alochowski** [comment]
Strange, but now it works again. Maybe there was a problem on infrastructure. 

I didn't have any other informations in console than error 500 after change page to my custom application.

Sorry for the confusion, maybe I opened the ticket too quickly, I think I can close this issue.

Thanks for your help.
