### ISSUE TITLE
Perfomance metrics are not being sent anymore

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#1247]
**Describe the bug**
As I was migrating the `MeasureFirstPaint` component to TS, I noticed that the API of Perfume changed, as the types were complaining that a lot of things we are currently using do not work/exist anymore.

I checked our metrics and confirmed that indeed we are not getting any metrics since at least a couple of weeks.

<img width="898" alt="Screenshot 2020-01-19 at 00 05 27" src="https://user-images.githubusercontent.com/1110551/72678269-ad9cbf80-3aa4-11ea-8d21-af70d4dad290.png">

Not sure what happened. Checking the changelog of perfume shows that there were some breaking changes in between "minor" versions, which is just ridiculous! https://github.com/Zizzamia/perfume.js/blob/master/CHANGELOG.md

If we inspect the `perfume` object, we notice that the things we were using do not exist anymore:

- `perfume.observeFirstContentfulPaint` is `undefined`
- `perfume.firstPaintDuration` is `undefined`

<img width="557" alt="image" src="https://user-images.githubusercontent.com/1110551/72678337-30be1580-3aa5-11ea-81e5-baf0576eb1f8.png">

We also didn't notice this as `Promise.all([undefined])` does not throw any error.

```
> Promise.all([undefined]).then(r => {console.log(r)})
Promise { <pending> }
> [ undefined ]
```

**Expected behavior**
Metrics should be correctly gathered and sent

---

I'm thinking about implementing the metrics on our own, as I don't feel much comfortable anymore relying on this library.

**Comment by emmenko** [comment]
We can try to make it work again first, and then think about how we can maintain this in the future.

**Comment by tdeekens** [comment]
Thanks for writing it down. I also had my frustrations with the library. It is less of what it does but more the release process. Maybe we can downgrade for now and then discuss updating or migrating away. If I am not mistaken 3.0.4 should work as I remember fixing something in October https://github.com/commercetools/merchant-center-application-kit/pull/1091/files

**Comment by emmenko** [comment]
I'm actually looking into using the `analyticsTracker` callback of the library, as you get all the values there. I'm also considering sending all those values to GA instead of our prometheus server, as we can track more information. We should probably also have this tracking as a default in the app-shell, since we already use GA, no need to manually configure it.

I'll try to spin up a PR and we can discuss there if we want to go with that approach or not.

**Comment by emmenko** [comment]
For instance, we can combine that with GA timing: https://developers.google.com/analytics/devguides/collection/analyticsjs/user-timings

**Comment by tdeekens** [comment]
Yeah nice idea. That would be cool to see. If we manage to we would actually use the metrics service for only very few things. Feels like if we send app-shell versions to GA we might be able to decomission it 💀😺🙀

**Comment by emmenko** [comment]
Yeah we can move some of the tracking to GA, at least what concerns the frontend.

We need to add more configs to GTM in order to make this work (eg: the event type `timing`).
Additionally, in general, we can also use/push custom dimensions for things like application name, project key, versions, etc.

**Comment by Zizzamia** [comment]
@emmenko and @tdeekens my personal apologies for the frustration the library caused over some breaking changes I introduced without a correct major release.
I'm glad your team was able to overcome the situation and still have the best out of the library.

In the future please feel free to reach out to me personally with a DM on Twitter (https://twitter.com/Zizzamia) or open an issue on Github. I am going to keep improving and always looking forward to feedback.

Thank you for supporting Perfume.js 💛
