### ISSUE TITLE
Add update-versions command to mc-scripts

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#1289]
**Is your feature request related to a problem? Please describe.**
When a new release is made in appkit, a new version is bumped. This version might include one or more packages.

In order to update the packages in the application code to a newer version, we always need to check each version manually and do a search/replace. It would be good if this can be done automatically by a script.

**Describe the solution you'd like**
An idea is to add a new command, for example `update-versions` to the `mc-scripts` package.
The command receives some options, like the version to update to. When executed, the command will get a list of all packages that need to be updated to that specific version, then it will scan all the `package.json` files and replace the versions.

Then the user can run `yarn`.

**Comment by tdeekens** [comment]
If yarn would have a `yarn upgrade-interactive --next` or another tool allowing that would we have to write something ourselves?

**Comment by emmenko** [comment]
Probably not, I’m not aware of any tool that does what we need though...

**Comment by emmenko** [comment]
I created a package that we can use independently from appkit: https://www.npmjs.com/package/bulk-update-versions
