### ISSUE TITLE
Content Security Policy (CTP) error in  custom application in Merchant Center

### ISSUE THREAD

**Issue by iamzifei** [commercetools/merchant-center-application-kit#1297]
Hi I'm using
```
npx @commercetools-frontend/create-mc-app my-new-custom-application-project --template starter
```
 created a fresh customer application scaffold. Then I put Appollo client as the following try to integrate with a graphql endpoint.

```index.js
import React from 'react';
import ReactDOM from 'react-dom';
import EntryPoint from './components/entry-point';
import { ApolloClient } from "apollo-client";
import { InMemoryCache } from "apollo-cache-inmemory";
import { HttpLink } from "apollo-link-http";
import { ApolloProvider } from "@apollo/react-hooks";

// Name of the localStorage item
const LOCAL_STORAGE_TOKEN = 'apollo-token';

const cache = new InMemoryCache();
const link = new HttpLink({
  uri: "http://localhost:3333"
//   uri: "https://api.commercetools.com/loyaltystore/graphql"
});

const client = new ApolloClient({
  cache,
  link,
  tokenName: LOCAL_STORAGE_TOKEN,
  connectToDevTools: true
});

ReactDOM.render(
<ApolloProvider client={client}><EntryPoint /></ApolloProvider>, document.getElementById('app'));
```

And I have the error in the browser when starting the app at localhost
```
Refused to connect to 'http://localhost:3333/' because it violates the following Content Security Policy directive: "connect-src 'self' mc-api.commercetools.com mc-api.commercetools.co app.launchdarkly.com clientstream.launchdarkly.com events.launchdarkly.com app.getsentry.com sentry.io www.google-analytics.com ws: localhost:8080 webpack-internal:".
```

The mc-script version I'm using is 15.9.0. My localhost:3333 as CORS * enabled. Also tried to connect to `https://api.commercetools.com/loyaltystore/graphql` and get the same error

**Update:**
Also tried the Playground project by `yarn start` and having the same error

**Comment by iamzifei** [comment]
I tried the Playground project by starting `yarn start` and also have the same error.

**Comment by iamzifei** [comment]
turns out I need to add the CTP rules in headers.json, hopefully, there'd be some documentation talked this.

**Comment by tdeekens** [comment]
Thanks for reaching out. Yes, you need to add those rules to the headers.json. Sorry for the inconvenience. We are working on improving documentation at https://docs.commercetools.com/custom-applications/ and this will be included definitely.

**Comment by emmenko** [comment]
@iamzifei hi, thanks for reaching out to us.

In case you haven't seen it yet, the documentation website is a great place to start: https://docs.commercetools.com/custom-applications/

For example, CSP config is documented here: https://docs.commercetools.com/custom-applications/deployment/runtime-configuration#headersjson

From your code snippet I also noticed that you're instantiating a new Apollo Client and that you try to connect to the commercetools API directly.

This is not necessary for two reasons:
- the Apollo Client is already pre-configured in the ApplicationShell
- the https://api.commercetools.com should not be called directly from a single page application, for security reasons. Instead, all requests should go through the Merchant Center API Gateway.

You can read more about those things here:
- [Authentication](https://docs.commercetools.com/custom-applications/main-concepts/authentication)
- [API Gateway](https://docs.commercetools.com/custom-applications/main-concepts/api-gateway)
- [Data Fetching](https://docs.commercetools.com/custom-applications/main-concepts/data-fetching)
- [Proxy Endpoints](https://docs.commercetools.com/custom-applications/main-concepts/proxy-endpoints)

Hope that helps, thanks.

**Comment by iamzifei** [comment]
> @iamzifei hi, thanks for reaching out to us.
> 
> In case you haven't seen it yet, the documentation website is a great place to start: https://docs.commercetools.com/custom-applications/
> 
> For example, CSP config is documented here: https://docs.commercetools.com/custom-applications/deployment/runtime-configuration#headersjson
> 
> From your code snippet I also noticed that you're instantiating a new Apollo Client and that you try to connect to the commercetools API directly.
> 
> This is not necessary for two reasons:
> 
> * the Apollo Client is already pre-configured in the ApplicationShell
> * the https://api.commercetools.com should not be called directly from a single page application, for security reasons. Instead, all requests should go through the Merchant Center API Gateway.
> 
> You can read more about those things here:
> 
> * [Authentication](https://docs.commercetools.com/custom-applications/main-concepts/authentication)
> * [API Gateway](https://docs.commercetools.com/custom-applications/main-concepts/api-gateway)
> * [Data Fetching](https://docs.commercetools.com/custom-applications/main-concepts/data-fetching)
> * [Proxy Endpoints](https://docs.commercetools.com/custom-applications/main-concepts/proxy-endpoints)
> 
> Hope that helps, thanks.

emmenko

Thanks for the details which really helpful. In regards to the Apollo client, is it possible that I can customize the uri of link that the Apollo Client using?

**Comment by emmenko** [comment]
> In regards to the Apollo client, is it possible that I can customize the uri of link that the Apollo Client

You can't at the moment. What would you change it to, if I may ask?

**Comment by iamzifei** [comment]
> > In regards to the Apollo client, is it possible that I can customize the uri of link that the Apollo Client
> 
> You can't at the moment. What would you change it to, if I may ask?

As we have an inhouse graphql API served as a middleware which including some customized functions, and when testing I'd like to use localhost graphql API on my local machine as well.

**Comment by emmenko** [comment]
I see.
We haven't had such a use case yet.

In general, an Apollo Client can only be instantiated with one URL. The Merchant Center talks to multiple GraphQL APIs though, so we came up with a [GraphQL Proxy](https://docs.commercetools.com/custom-applications/main-concepts/graphql) in the Merchant Center API Gateway that forwards the request to a **target**.
This allows to have one endpoint `/graphql` from the frontend point of view.

Your use case is also legit, you have your own backend for specific parts of your app.

If you add another Apollo Client, you need to make sure that requests to that specific endpoint are using the custom client.
You can do that by explicitly passing the new client to the query/mutations, so that Apollo picks that instead of the default one. No extra ApolloProvider is needed though. Here is an article explaining a bit this: https://medium.com/open-graphql/apollo-multiple-clients-with-react-b34b571210a5

Also, depending on how your graphql api is protected and how you want to deal with authentication and stuff, you might want to check out this: https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api

**Comment by emmenko** [comment]
@iamzifei FYI: I documented how to use a custom apollo client: https://docs.commercetools.com/custom-applications/main-concepts/data-fetching#connecting-to-an-external-graphql-api
