### ISSUE TITLE
custom meta or script tags in index.html

### ISSUE THREAD

**Issue by iamzifei** [commercetools/merchant-center-application-kit#1298]
I'd like to add some customized <meta> or <script> tag in the compiled index.html file, not sure where I can put those customizations in.

**Comment by emmenko** [comment]
At the moment we don't support this.
You could do that from a React component though, you inject a script using the DOM API.

Can you give us some examples of what things you might need to inject into the `index.html` document?

**Comment by iamzifei** [comment]
> At the moment we don't support this.
> You could do that from a React component though, you inject a script using the DOM API.
> 
> Can you give us some examples of what things you might need to inject into the `index.html` document?

Hi emmenko

Thanks for reaching out. I'd like to just put some CDN js files in the index.html header section if there's an index.html file, something like the following:
```
<script src="https://checkoutshopper-test.adyen.com/checkoutshopper/sdk/3.3.0/adyen.js"></script>
```

**Comment by emmenko** [comment]
Can you explain why you would do that instead of importing the dependency in the react app, so that it gets bundled with webpack?

**Comment by iamzifei** [comment]
> Can you explain why you would do that instead of importing the dependency in the react app, so that it gets bundled with webpack?

as some CDN js is full customized one and not having any npm packages/dependencies?

**Comment by emmenko** [comment]
I'm not sure I fully understand what you mean. Having it as an external dependency or bundled within the JS app makes no difference.

Is the library you want to use this one? https://docs.adyen.com/development-resources/libraries#javascript

You should just install it as a normal npm dependency.

**Comment by iamzifei** [comment]
> I'm not sure I fully understand what you mean. Having it as an external dependency or bundled within the JS app makes no difference.
> 
> Is the library you want to use this one? https://docs.adyen.com/development-resources/libraries#javascript
> 
> You should just install it as a normal npm dependency.

sorry I used Adyen as an example. The JS code I want to include is an inhouse JS file which hasn't published as an npm package yet, and I cannot share it here as well obviously.

**Comment by emmenko** [comment]
Ok sure. Can't you import the file as well in your app? Or does it need to be loaded as a script tag?

**Comment by iamzifei** [comment]
It needs to be loaded as a script tag

**Comment by emmenko** [comment]
Well, at the moment the only way I can think of it to work is to either:

- inject the script on runtime using react.
- modify the index.html **after** it's generated (read the file, put the script where you want to, write to file).

You also need to update the CSP to whitelist the cdn domain.

**Comment by iamzifei** [comment]
I think modify index.html afterwards works for production deployment but
not for local `yarn start`?

**Comment by emmenko** [comment]
Right.

What speaks against injecting the script using React?

**Comment by emmenko** [comment]
Hi @iamzifei, is this issue still relevant for you? I'm going to close it now, let me know if we should re-open this.
Thanks
