### ISSUE TITLE
Improve documentation of CSP config

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#1343]
For instance, the MC API domain needs to be included in the `connect-src`.

At the moment, the legacy GCP-EU/US hostnames are included by default:

https://github.com/commercetools/merchant-center-application-kit/blob/40230d0606e1358eaa535adbc6bf1c19c1652857/packages/mc-html-template/lib/load-headers.js#L86-L87

This causes more confusion and we should probably remove those defaults and make it clear that people need to explicitly add those domains.

**Comment by tdeekens** [comment]
Yup. I think with a deprecation process (long running) of those hosts and tracking their usage we should remove them. 🤞🏽
