### ISSUE TITLE
Invalid Client Session Error 

### ISSUE THREAD

**Issue by ebonertz** [commercetools/merchant-center-application-kit#1352]
**Describe the bug**
Error Invalid Client Session is thrown when extension app makes initial call to get the customer
info.

**To Reproduce**

Only reproducible when the user didn’t login for 2 days and navigates to mc custom app route directly

1. Go to Merchant Center and open custom app
2. See error  'invalid client session/token'

**Expected behavior**
Instead of throwing error user would be redirected to the login page. 

**Screenshots**
User provided another screenshot with a Sentry GraphQL Error
See attached
<img width="586" alt="customerapperror" src="https://user-images.githubusercontent.com/12550644/74873693-aed43d00-532d-11ea-909a-c3d7c0afe412.png">

**Additional context**
Work around: forcefully logging out and logging back in MC resolve this issue temporarily
[Support Ticket 8007](https://jira.commercetools.com/browse/SUPPORT-8007)

**Comment by tdeekens** [comment]
We released [v16.3.1](https://github.com/commercetools/merchant-center-application-kit/releases/tag/v16.3.1) which contains an attempt to fix the issue. Please update the respective custom application to this version to verify if this issue is fixed.
