### ISSUE TITLE
[Idea] Use terraform to register custom applications

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#1361]
Some users have express an interest in managing the registration of custom applications using Terraform, instead of doing it manually in the Merchant Center.

> This issue is used to track any progress on this topic.

**Comment by emmenko** [comment]
FYI: see https://github.com/labd/terraform-provider-commercetools/pull/109

**Comment by mmaltsev-ct** [comment]
Since we're releasing new org-level Custom Apps and a CLI for them, the idea is not as relevant anymore. Closing the issue.
