### ISSUE TITLE
Trailing slash in mcApiUrl environment variable builds invalid path, leading to authentication error in local dev authentication view

### ISSUE THREAD

**Issue by nbryant-commercetools** [commercetools/merchant-center-application-kit#1376]
**Describe the bug**
Having a trailing slash at the end of the mcApiUrl environment variable like, `https://mc-api.commercetools.co/`, will build an invalid url to the tokens endpoint like `https://mc-api.commercetools.co//tokens` containing double slashes.  This invalid path with double slashes produce a 403 error stating that the manage_project_settings scope is not set and prevents authentication.

**To Reproduce**

1. Set the `mcApiUrl` environment variable in `packages-application/application-dashboard/env.json` of `merchant-center-frontend` to `https://mc-api.commercetools.co/` and the `location` value to `"us"`.
2. Run application-dashboard locally with `yarn start`
3. Note you are redirected to the local dev authentication view
4. Enter credentials and click the Sign in button
5. In the Network tab of the developer console, note that a request was made to `//tokens`
6. Note that you receive the error mentioned in the description of this issue

**Expected behavior**
When clicking the sign in button, any trailing slash in the mcApiUrl value should be removed so that the tokens endpoint computed in `packages/mc-dev-authentication/views/login.pug` will be valid, and the developer can proceed through the authentication flow.

**Additional context**
To avoid unnecessary authentication failures, any trailing slashes should be removed from the mcApiUrl when building the path to the tokens endpoint.

**Comment by emmenko** [comment]
Fixed in #1378
