### ISSUE TITLE
Passing gtmTracking render option doesn't work

### ISSUE THREAD

**Issue by ahmehri** [commercetools/merchant-center-application-kit#1388]
**Describe the bug**

Passing `gtmTracking` render option to `renderApp` doesn’t work. 

**To Reproduce**

In the following test code, the mocked track will never be passed to `MyComponent`.

```js
  const track = jest.fn();
  renderApp(<MyComponent />, {
    gtmTracking: {
      track,
    },
  });
  // some test code
  expect(track).toHaveBeenCalled();
```

The test will fail with `Number of calls: 0`.

**Expected behavior**
The test should pass.

**Additional context**
https://commercetools.slack.com/archives/GCSJ9T12P/p1574956056011000

**Comment by emmenko** [comment]
I opened a PR that shows that it works. Can you check that? #1389

**Comment by tdeekens** [comment]
I always abstracted over the "raw" tracking functionality and mocked that. Gave me a better separation of concerns and encapsulation. Maybe something to look into too.
