### ISSUE TITLE
Apollo's caching overrides values because of the way we extract id from cache

### ISSUE THREAD

**Issue by islam3zzat** [commercetools/merchant-center-application-kit#1390]
**Describe the bug**
According to the way we currently extract id from the object wi prefix with the type only when the `__typename` is 'Reference'
https://github.com/commercetools/merchant-center-application-kit/blob/e8296717b0828e29179c7c139bb772730df5356b/packages/application-shell/src/configure-apollo.ts#L115

But I faced an issue where the cached values has been overridden when the response of a resource that queried `cartDiscount`  including the `supplyChannelRef`

```graphql
query FetchCartDiscountQuery($id: String!) {
  cartDiscount(id: $id) {
    __typename
    value {
      ... on GiftLineItemValue {
        supplyChannelRef {
          id
          typeId
          __typename
        }
       
      }
    }
  }
}
```

the `supplyChannelRef` is of type `__type` = `ChannelReferenceIdentifier` which has a different key and doesn't have name/nameAllLocales

and the response had overridden the result of another query within the view  of type `__type` = `Channel` 

```graphql
 channels {
    results {
      __typename
      id
      key
      name(locale: "en")
    }
  }
```

![2020-03-11 4 23 34 PM](https://user-images.githubusercontent.com/7680511/76433527-baf36d80-63b4-11ea-8d82-6b074e2fb2fe.gif)

I tried changing the `dataIdFromObject` to enable prefixing the id with the `__typename` for `ChannelReferenceIdentifier` also and the issue is gone.
 

**To Reproduce**

1. Go to a view that has both `cartDiscountDetails` of type gift line item (which has a supply channel reference of type `ChannelReferenceIdentifier ` ) query and `channels` query
2. do any mutation on the `cartDiscountDetails`
3. since we don't prepend the `__typename` to the `id` of the cache when it's `ChannelReferenceIdentifier` (we currently only prepend the __typename for `Reference`), the id of the `supplyChannelRef` will override the `channel` of the same id.

**Expected behavior**
Both resources should be available on the cache since they are different resources with different types.

**Screenshots**

**Additional context**

**Comment by emmenko** [comment]
Thanks for the detailed explanation.

I wish there is a better way to configure the data caching map, as we might encounter this issue in the future as well.

Maybe we should expose a way for custom apps to hook into the mapping function to provide any custom logic they need to.

**Comment by islam3zzat** [comment]
> I wish there is a better way to configure the data caching map, as we might encounter this issue in the future as well.

Me too, adding another condition now may fix the problem at hand but I'm almost sure that this can't be the only case.

**Comment by islam3zzat** [comment]
> Maybe we should expose a way for custom apps to hook into the mapping function to provide any custom logic they need to.

I agree. the assumptions that we do here don't have to hold with custom apps.

**Comment by tdeekens** [comment]
> Maybe we should expose a way for custom apps to hook into the mapping function to provide any custom logic they need to.

Yeah but maybe we can also wait for until it becomes a problem 😏.

As mentioned on the in-house issue: to me adding the exception makes sense also if it feels a bit wrong. It's the only way I can think of to make it work apart from changing the CTP API schema.

**Comment by islam3zzat** [comment]
Does it make sense for us to always prefix the `id` for the `__typename` instead of just the reference types?

**Comment by islam3zzat** [comment]
I mean after the `typeNamesWithoutIdAsIdentifier` special handling.

**Comment by islam3zzat** [comment]
1. 
```js
      dataIdFromObject: result => {
        const customResult = result as CustomIdGetterObj;
        if (
          !customResult.id &&
          customResult.key &&
          customResult.__typename &&
          typeNamesWithoutIdAsIdentifier.includes(customResult.__typename)
        )
          return `${customResult.__typename}:${customResult.key}`;
     
        return `${customResult.__typename}:${customResult.id}`;
      },
```

2. or maybe
```js
      dataIdFromObject: result => {
        const customResult = result as CustomIdGetterObj;
        // We default to key, if id is not available
        return `${customResult.__typename}:${customResult.id || customResult.key}`;
      },
```
