### ISSUE TITLE
eslint-config-mc-app dep issue

### ISSUE THREAD

**Issue by dferber90** [commercetools/merchant-center-application-kit#14]
There is a problem of the dependencies of `eslint-config-mc-app` when using the config in any project (observed in ui-kit):

```
 FAIL   eslint  src/components/inputs/money-input/dropdown-chevron.js
  ● Test suite failed to run

    Failed to load plugin import: Cannot find module 'eslint-plugin-import'
    Referenced from: /Users/nick/Sites/ui-kit/.eslintrc.yaml

      at Plugins.load (node_modules/eslint/lib/config/plugins.js:96:29)
          at Array.forEach (<anonymous>)
      at Plugins.loadAll (node_modules/eslint/lib/config/plugins.js:157:21)
      at loadFromDisk (node_modules/eslint/lib/config/config-file.js:506:35)
      at load (node_modules/eslint/lib/config/config-file.js:564:20)
      at configExtends.reduceRight (node_modules/eslint/lib/config/config-file.js:430:36)
          at Array.reduceRight (<anonymous>)
      at applyExtends (node_modules/eslint/lib/config/config-file.js:408
```

Note that this issue is not about `eslint-plugin-import` specifically, it just happens to be the first one to fail. If `eslint-plugin-import` is added as a dependency in ui-kit, then it fails with the next missing dependency `eslint-plugin-jest` and so on.

We are [listing all dependencies as `dependencies`](https://github.com/commercetools/merchant-center-application-kit/blob/c68422b/packages/eslint-config-mc-app/package.json#L23-L37), but this does ensure/indicate that they need to be added to the main project.

Other ESLint config presets list list their dependencies as `peerDependencies`, and also als `devDependencies` (to ensure they are available during development of the config itself). See [eslint-config-airbnb](https://github.com/airbnb/javascript/blob/685f37b/packages/eslint-config-airbnb/package.json) for example.

The recommended approach would be to move the necessary dependencies (all used by the config preset) to `peerDependency`s and to also add them as `devDependency`s for tests/development of `eslint-config-mc-app` itself.

**Comment by dferber90** [comment]
I'd further specify the `peerDependencies` using a range instead of a fixed version. The fixed version currently prevents `ui-kit` from updating to a newer ESLint version 😢

**Comment by dferber90** [comment]
When we do that it might be a good chance to also fix the installation instructions (they are currently recommending to instal `eslint-config-mc-app` as a `dependency` instead of a `devDependency`, which is bad advice.

We also need to add all the peer dependencies to the installation instructions:

```
npm install --save-dev @commercetools-frontend/eslint-config-mc-app eslint eslint-config-airbnb-base eslint-config-prettier eslint-formatter-pretty eslint-plugin-babel eslint-plugin-cypress eslint-plugin-import eslint-plugin-jest eslint-plugin-jsx-a11y eslint-plugin-prefer-object-spread eslint-plugin-prettier eslint-plugin-react 
```

**Comment by tdeekens** [comment]
> I'd further specify the peerDependencies using a range instead of a fixed version. 

I agree. Otherwise consuming it in multiple repos will be unfeasible and people will drop this for their own which is not the intend.

**Comment by dferber90** [comment]
I also stumbled upon this 

```
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration.
```

in the log of https://travis-ci.org/commercetools/ui-kit/builds/441585403?utm_source=github_status&utm_medium=notification.

**Comment by tdeekens** [comment]
Yeah. I somehow remember seeing that one before. We have to specify the version to lint for. Example [here](https://github.com/tdeekens/flopflip/blob/master/.eslintrc.yaml#L43).
