### ISSUE TITLE
Configure Jest setup-tests

### ISSUE THREAD

**Issue by ahmehri** [commercetools/merchant-center-application-kit#1421]
**Is your feature request related to a problem? Please describe.**

Currently, I cannot configure Jest `setup-tests` in my app.

**Describe the solution you'd like**

I would like to be able to configure app-kit Jest `setup-tests` from my app.

**Additional context**

I want to silence some console errors and I don't want to duplicate the logic in my app but instead reuse `setup-tests` `silenceConsoleErrors`. Something like the following.

```js
import { configureTestSetups, testSetup } from '...'

configureTestSetup({
   silenceConsoleWarnings: [
	//,
    //
   ]
})

export testSetup
```

**Comment by tdeekens** [comment]
Thanks. This was a comment of mine in an internal PR, was it?

**Comment by ahmehri** [comment]
Yes, exactly and @emmenko requested me to create an issue here.
