### ISSUE TITLE
Running i18n:build will override core.json messages

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#146]
**Describe the bug**
Recently we introduced a step to sync `en.json` -> `core.json` #124
However, when running `i18n:build`, the `core.json` messages get overridden with the `defaultMessage` values.

**Expected behavior**
After running `i18n:build` only new messages should be added. If a message key already exists, it should not be changed.

**Comment by tdeekens** [comment]
Does this mean that keys will never be cleaned up? Given I add a key and accidentally did so and want to remove it again and assume so by running `i18n:build` again it will stick in there forever unless I remove it manually.

What's the advantage or workflow we want to enable by not overwriting it again?

**Comment by emmenko** [comment]
If the a message gets removed, it will be removed as well (I'll have to check if it's already like this though).
The issue here is only about overriding existing keys.
