### ISSUE TITLE
Custom App Creation Failing

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#1494]
Doing step by step instructions here:
https://docs.commercetools.com/custom-applications/getting-started/installing-a-starter-application

OS: Ubuntu 18.04.4 LTS
OS type: 64-bit
node: v12.16.3
npm: 6.14.4

After npm start it throws error:
`./node_modules/@commercetools-frontend/application-shell/dist/application-shell-index.es.jsModule not found: Can't resolve 'apollo-client/version' in '/dist-to-my-project/v2/custom-order-app/node_modules/@commercetools-frontend/application-shell/dist'`

Steps taken until error:
1. npx @commercetools-frontend/create-mc-app \ my-new-custom-application-project \ --template starter (its successful installed)
2. cd my-new-custom-application-project
3. npm start
4. Above Error Message received

**Comment by tdeekens** [comment]
I can confirm this bug and can reproduce it.

![CleanShot 2020-05-11 at 17 34 32](https://user-images.githubusercontent.com/1877073/81580437-bc89e380-93ad-11ea-8ad3-46affaccb462.png)

It seems to me that it's the apollo-client which again sneaked in a breaking change by removing the export `import { version as apolloVersion } from 'apollo-client/version'` or file.

@emmenko what do you think?

**Comment by emmenko** [comment]
Ah, I forgot about that. The `apollo-client` dep is missing in the starter package.json

**Comment by tdeekens** [comment]
The export is still there. Is the dependency missing altogether?
