### ISSUE TITLE
Custom Application Proxy Endpoint issue

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#1501]
We're running into a problem with the proxy-to endpoint for custom applications. We're getting a 401 using it, but we're not seeing any logs on our backend.

Error Message:
`statusCode: 401
  message: invalid_token`

**Comment by tdeekens** [comment]
Can you provide a more concrete reproduction case? It is not a general error you and others are seeing, correct? What is the time difference between the token being issued and used again? I presume the 401 is when using the .well-known endpoint? Sorry to ask so many questions but it is very scarce information on the issue.

**Comment by shanly-suepaul** [comment]
Hi @tdeekens, we've deployed a custom application to our MC and we're seeing this error. 

I'm attaching a HAR file that contains some sample requests: 
[request.har.txt](https://github.com/commercetools/merchant-center-application-kit/files/4617483/request.har.txt)

Here is some example code that we're using to generate the requests:

```js
const { apiUrl, projectKey, mcApiUrl, env } = window.app;

const sendRequest = (forwardUri, method = 'GET', body = null) => {
    const fetchParameters = {
        method,
        headers: {
            Accept: 'application/json',
            'X-Forward-To': `${apiUrl}${forwardUri}`,
            'X-Project-Key': projectKey
        },
        credentials: 'include'
    };
    if (body) {
        fetchParameters.body = JSON.stringify(body);
    }

    return fetch(`${mcApiUrl}/proxy/forward-to`, fetchParameters);
};


export const writeCredentials = async (credentials) => sendRequest('credentials', 'POST', credentials);
```
![screenshot](https://user-images.githubusercontent.com/858736/81727386-e519e800-9456-11ea-93ee-42eb07c931de.jpg)

**Comment by tdeekens** [comment]
The request to the MC API does not contain the mcAccessToken cookie does it? You are sending this request from within the Custom App, right? Are you there using the SDK we provided or are you assembling the request manually for a specific reason? https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api#usage-for-sdk-actions

**Comment by shanly-suepaul** [comment]
Thanks for the quick reply Tobias. The cookie gets attached automatically to the XHR - you can see it in the HAR file. It was working last week and we don't think we made any changes that would cause this error (but clearly may have). We'll try the SDK.

**Comment by tdeekens** [comment]
Sorry, didn’t check the HAR file yet. Me or @emmenko will do tomorrow. I think the SDK is beneficial regardless but may not solve the issue depending on what it is. Do you use any part of our validation SDK in your own service to validate the JWT „automatically“? It is quite recent but we hoped it would easy setup for users while we also encapsulate things better. https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api#validating-the-json-web-token

**Comment by emmenko** [comment]
@shanly-suepaul regarding the issue, in our logs I see that the `401` error relates to the audience being invalid

```json
{"name":"JWTClaimInvalid","code":"ERR_JWT_CLAIM_INVALID","claim":"aud","reason":"check_failed"}
```

Can you try logging out and make sure there are no cookies, then log in again?

As for making HTTP requests in general, we recommend to use some of the built-in clients and helpers as they come preconfigured with the necessary setup.

**Comment by shanly-suepaul** [comment]
@emmenko I tried clearing all caches and session data as well as using private browsing and the results were the same.

I also tried the SDK and things did not go easily for me, nor did they resolve the problem unfortunately. I swapped the custom code for code following the pattern here: https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api#usage-for-sdk-actions

I won't go into the problems I encountered as they aren't part of the original thread, but swapping in the SDK didn't fix the problem. We don't generate the JWT - it's provided by our session. Do you have further advice?

Thanks again for your help.

**Comment by emmenko** [comment]
Is this problem happening in all applications or only in your custom app?

**Comment by emmenko** [comment]
Also, we recommend to send the `Accept-version: v2` HTTP header, which is built-in if you use the SDK or the Apollo client (as documented).

Another question: do you get this issue when developing the app locally or in production as well?

**Comment by iaindwyer** [comment]
I think we've sorted out what was happening. In production we were logged into the legacy url, but the mcapi value was set to the newer one. That explains the in audience error message.

We're working on porting what we already have over to using the SDK.

**Comment by emmenko** [comment]
Have you been able to solve the issue? Is there anything else you need help with?

**Comment by shanly-suepaul** [comment]
Hi @emmenko thanks for following up and sorry for not updating you. Yes, the problem was that users were logging in at `mc.commercetools.co` and we were using the GCP URL for the API.

We didn't end up switching over to the SDK, though. A weird thing happened where whenever I installed the `@commercetools-frontend/sdk` module, my installation would stop working - the `ApplicationShell` context was never set, which led to a number of strange bugs. I think it's something unique about my local environment, though.

Thanks again.
