### ISSUE TITLE
using variables from dotenv in env.json file

### ISSUE THREAD

**Issue by jamesgongqantas** [commercetools/merchant-center-application-kit#1502]
Hi

I'm new to setup the custom application. I followed the documentation here:
https://docs.commercetools.com/custom-applications/deployment/runtime-configuration#using-environment-variables

I use `npx @commercetools-frontend/create-mc-app` to create a custom application scaffold.

added the `dotenv` dependency, and put a `.env` file with something like the following:
```
MC_API_URL=https://mc-api.commercetools.com
FRONTEND_HOST=localhost:3001
...
```

and change the `env.json` to the following
```
{
  ...
  "frontendHost": "${env:FRONTEND_HOST}",
  "mcApiUrl": "${env:MC_API_URL}",
  ...
}
```

then I use `npm start` try to start the app as normal, get the following error:
```
> mc-scripts start
...
/node_modules/@commercetools-frontend/mc-html-template/build/utils/substitute-env-variable-placeholders.js:39
    throw new Error(`Missing '${requestedEnvVar}' specified in config as 'env:${requestedEnvVar}'.`);
    ^

Error: Missing 'FRONTEND_HOST' specified in config as 'env:FRONTEND_HOST'.
...
```

what did I do wrong?

**Comment by tdeekens** [comment]
Hi,

thanks for filing the issue. I think what you're missing is loading the values from the `.env` file actually as environment variables into the shell before running `mc-scripts start`.

So a run-script in the `pkg.json` could be

```json
"start": "dotenv -e .env -- mc-scripts start",
```

Additional tip. You can have multiple `.env` files and merge them.

```json
"start": "dotenv -e .env.defaults -e .env.local -- mc-scripts start",
```

Hope this helps.

**Comment by emmenko** [comment]
The package for using that is: https://www.npmjs.com/package/dotenv-cli

**Comment by jamesgongqantas** [comment]
thanks for that, do I also need to add the same change to `test`, `build` and `production build` scripts?

**Comment by emmenko** [comment]
> thanks for that, do I also need to add the same change to `test`, `build` and `production build` scripts?

No it’s only for when you pass the `env.json` and the `headers.json`, which is usually when you start the app in dev mode or compile the HTML for production.

**Comment by emmenko** [comment]
Closing. If you need further help feel free to open an new issue or comment here again.
