### ISSUE TITLE
Unable to create a Table within a CollapsiblePanel component

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#1505]
I cannot create Table inside CollapsiblePannel. Here's the code:

````
<CollapsiblePanel isDefaultClosed={true}>
<Card>
<div style={{ display: "flex" }}>
<div className="container" style={{ paddingRight: "10px" }}>
<p><b>Return Date</b></p>
<p>{moment().format('MM/DD/YYYY HH:mm a')}</p>
</div>
<div className="container">
<p><b>Return Date</b></p>
<p>{moment().format('MM/DD/YYYY HH:mm a')}</p>
</div>
</div>
</Card>
<Table
columns={columnsDefinition}
rowCount={items.length}
itemRenderer={(item) => { console.log('p[p[p['); return returnItem.items[item.rowIndex][item.columnKey]}}
onRowClick={() => {}}
shouldFillRemainingVerticalSpace={true}
items=

{items}
defaultHeight=

{768}
/>
<p>232</p>
</CollapsiblePanel>
````

**Comment by tdeekens** [comment]
I think this is an UIKit issue (https://github.com/commercetools/ui-kit). I would open it there. 

Follow up questions to answer before opening it there: what specifically does not work. Can we share visuals, a reproduction case of even a codesandbox.io?

**Comment by Sheryorov** [comment]
https://codesandbox.io/s/dank-snowflake-ngyeb

**Comment by tdeekens** [comment]
Thanks for the sandbox! I am not sure we actually envisioned using the table in a  collapsible. You could try to use the new DataTable which might be able to do this [ref](https://uikit.commercetools.com/?path=/story/components-table-new--datatable).

Maybe @jonnybel can guide some more.
