### ISSUE TITLE
Fail fast on CI

### ISSUE THREAD

**Issue by montezume** [commercetools/merchant-center-application-kit#156]
#### Current situation

If the tests fail on CI, the apps still build. See [here](https://travis-ci.org/commercetools/merchant-center-application-kit/builds/461379125?utm_source=github_status&utm_medium=notification) for an example.

#### Ideal situation

If tests fail on CI, the command `yarn build` should not run.

#### Help / docs

[https://github.com/travis-ci/travis-ci/issues/1066](https://github.com/travis-ci/travis-ci/issues/1066)

**Comment by emmenko** [comment]
Good point 👌
