### ISSUE TITLE
How to make axios request in custom app

### ISSUE THREAD

**Issue by briantomkins** [commercetools/merchant-center-application-kit#1560]
1. Description
I want make axios request in custom app, for example:
axios.post('https://jsonplaceholder.typicode.com/posts',

{ title: 'foo', body: 'bar', userId: 1 }
).then(res => console.log(res)) .catch(err => console.log('err: ', err))

2. Steps
a. npx @commercetools-frontend/create-mc-app my-new-custom-application-project --template starter
b. go to src/components/view-one/view-one.js and replace ViewOne with this:

const ViewOne = () => {
useEffect(() => {
axios.post('https://jsonplaceholder.typicode.com/posts',

{ title: 'foo', body: 'bar', userId: 1 }
).then(res => console.log(res))
.catch(err => console.log('err: ', err))
}, [])

return (
<Text.Body intlMessage=

{messages.title}
/>
)
}

3. Error  attached

Ref Support-9098

**Comment by briantomkins** [comment]
![Screenshot from 2020-06-09 10-19-33](https://user-images.githubusercontent.com/46489759/84135119-d882b280-aa49-11ea-93b8-6d36b3812226.png)

**Comment by emmenko** [comment]
The error in the console is pretty clear: The CSP blocked a request to an external domain.

You need to configure the CSP in the `headers.json` to allow the external domain.
https://docs.commercetools.com/custom-applications/deployment/runtime-configuration#headersjson

**Comment by Sheryorov** [comment]
It error occurs in development mode

**Comment by Sheryorov** [comment]
were i must put headers.json because this file not exists

**Comment by emmenko** [comment]
You need to create one, like the `env.json`. Just follow the instructions in the docs.

**Comment by Sheryorov** [comment]
I think we can close this issue
