### ISSUE TITLE
Expose common messages

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#160]
**Is your feature request related to a problem? Please describe.**
Check this issue: https://github.com/commercetools/ui-kit/issues/249

**Describe the solution you'd like**
As [proposed here](https://github.com/commercetools/ui-kit/issues/249#issuecomment-442030872) we can simply expose some common messages for now.

We can expose those from the `i18n` package I suppose.

**Describe alternatives you've considered**
Have some "preset" components (e.g. `<CancelButton>` etc). However, we would like to try with only messages first.

**Comment by tdeekens** [comment]
To my understanding we started doing this with the new modals and the `AppKit.shared` translations. As a result I would close this. Feel free to re-open if that was too eager.
