### ISSUE TITLE
How to configure and run another Sentry agent 

### ISSUE THREAD

**Issue by tomwscott** [commercetools/merchant-center-application-kit#1615]
**Which part of the documentation does it affect and which topic does it refer to?**
Alerting & Monitoring

Viewing the developer console when running an Application Kit app shows that Sentry is being used by CommerceTools to monitor application errors. 

**Describe what needs to be improved**
It would be nice to have a documented pattern for where and how to configure Sentry and to be confident that it doesn't clash with CommerceTools' instance.

**Comment by tdeekens** [comment]
Thanks for posting the issue. To my knowledge, and @emmenko should verify, you can set a `trackingSentry` value in your `env.json`. This will make it be available on the `window.app.trackingSentry` which is then used to conditionally init the Sentry SDK with the `trackingSentry` as the DSN.

The specific code can be found [here](https://github.com/commercetools/merchant-center-application-kit/blob/1edcf22af850519116ec20a9469eb292b5f13160/packages/sentry/src/sentry.ts#L25).

We haven't publically documented this as we didn't see anybody needing it so far. We also consider it a private API but do not plan to change it. I would say you give it a shot and see if this helps 😄.

**Comment by emmenko** [comment]
Yes, you can set your Sentry DSN as `trackingSentry` in the `env.json`.

Let us know if that works fine for you.

**Comment by tdeekens** [comment]
Will close as I assume it is working as there are no follow-up questions. Feel free to re-open if the assumption is wrong.
