### ISSUE TITLE
Use Application context not working 

### ISSUE THREAD

**Issue by Sheryorov** [commercetools/merchant-center-application-kit#1617]
I wanna use useApplicationContext hook, but after adding this package 

> @commercetools-frontend/application-shell-connectors

I got permission issue like that

> Not enough permissions to access this resource.

But i have all access to the project. if i will delete this package and remove node_modules file and reinstall it, app will works ok. 

my deps:

> dependencies": {
>     "@commercetools-frontend/actions-global": "16.8.0",
>     "@commercetools-frontend/application-components": "16.8.0",
>     "@commercetools-frontend/application-shell": "16.8.0",
>     "@commercetools-frontend/assets": "16.8.0",
>     "@commercetools-frontend/i18n": "16.8.0",
>     "@commercetools-frontend/mc-http-server": "16.8.1",
>     "@commercetools-frontend/permissions": "16.8.0",
>     "@commercetools-frontend/ui-kit": "^10.22.2",
>     "@commercetools-uikit/card": "^10.18.4",
>     "@commercetools-uikit/collapsible-panel": "^10.18.4",
>     "@commercetools-uikit/data-table": "^10.18.4",
>     "@commercetools-uikit/flat-button": "10.18.4",
>     "@commercetools-uikit/icons": "10.18.4",
>     "@commercetools-uikit/spacings": "10.18.4",
>     "@commercetools-uikit/text": "10.18.4",
>     "apollo-client": "2.6.8",
>     "aws4": "^1.9.1",
>     "aws4-axios": "^1.12.0",
>     "axios": "^0.18.1",
>     "crypto": "^1.0.1",
>     "deploy-aws-s3-cloudfront": "^3.2.3",
>     "dinero.js": "^1.8.1",
>     "hex-to-uuid": "^1.0.1",
>     "moment": "^2.25.3",
>     "prop-types": "15.7.2",
>     "react": "16.13.1",
>     "react-apollo": "3.1.5",
>     "react-dom": "16.13.1",
>     "react-intl": "3.4.0",
>     "react-redux": "7.2.0",
>     "react-router-dom": "5.1.2",
>     "redux": "4.0.5"
>   },
>   "devDependencies": {
>     "@commercetools-frontend/jest-preset-mc-app": "16.8.2",
>     "@commercetools-frontend/mc-scripts": "^16.12.0",
>     "@testing-library/react": "10.0.4",
>     "enzyme": "3.11.0",
>     "jest": "26.0.1"
>   }

PS: After removing PageUnauthorized:
```

 <MaintenancePageLayout
    imageSrc={LockedDiamondSVG}
    title="Not enough permissions to access this resource"
    paragraph1="We recommend to contact your project administrators for further questions."
  />
```

Project works good, but

> const user = useApplicationContext(context => context.user)

Is undefined

**Comment by tdeekens** [comment]
👋 Thanks for reporting. Our template starter E2E should catch this. So I am curious where we are missing this and what causes it 🤔. 

Are your version of application-shell and application-shell-connectors the same? The connectors is where the useApplicationContext comes from and the application-shell is the data provider so they have to be in sync as I recall.

**Comment by Sheryorov** [comment]
Yes, you right it was version difference.

**Comment by tdeekens** [comment]
No problem. Glad we figured it out. Ran into it myself.
