### ISSUE TITLE
connect to external graphql API

### ISSUE THREAD

**Issue by jamesgongqantas** [commercetools/merchant-center-application-kit#1623]
I have read the documentation from the following:

https://docs.commercetools.com/custom-applications/main-concepts/data-fetching#connecting-to-an-external-graphql-api

however when trying the code snippet from the above link, I have the following error message returned in response

`Missing required header "X-Forward-To".`

the request sends to `https://mc-api.australia-southeast1.gcp.commercetools.com/proxy/forward-to` which is expected I think, but the example in documentation doesn't specify how to add the missing header, or if I did something wrong?

Also what if I need to add some extra header? Do I have to create my own Apollo client for doing this?

**Comment by tdeekens** [comment]
1. X-Foward-To header missing

The `createApolloContextForProxyForwardTo` maps the `uri` onto the `x-forward-to` header [here](https://github.com/commercetools/merchant-center-application-kit/blob/fd818e3a131ce71f02b738b5c9ff93978ae526fe/packages/application-shell/src/utils/apollo-context.ts#L19).

Can you check if the request which is sent to `/forward-to` contains the `x-foward-to` header?

2. Extra headers

Extra headers are not supported when proxying through the MC API itself. We have a list of allowed headers. What kind of headers would you want to forward and why?

**Comment by jamesgongqantas** [comment]
> 1. X-Foward-To header missing
> 
> The `createApolloContextForProxyForwardTo` maps the `uri` onto the `x-forward-to` header [here](https://github.com/commercetools/merchant-center-application-kit/blob/fd818e3a131ce71f02b738b5c9ff93978ae526fe/packages/application-shell/src/utils/apollo-context.ts#L19).
> 
> Can you check if the request which is sent to `/forward-to` contains the `x-foward-to` header?
> 
> 1. Extra headers
> 
> Extra headers are not supported when proxying through the MC API itself. We have a list of allowed headers. What kind of headers would you want to forward and why?

1. the request doesn't have the `x-forward-to` header
2. as the external graphql api expect that header, which is `accesstoken` in my case

**Comment by emmenko** [comment]
Maybe let's take a step back.

You don't need to use the forward-to endpoint to connect to your API. You can talk to it directly if you want, and take care of the auth stuff. If you do that, you also have to adjust your CSP config to allow the API domain.

The forward-to endpoint can be used to secure your API with low effort, as most of the auth validation is done by the MC API for you.

---

As for why the request doesn't have the headers, I can look into that and try to reproduce it.

**Comment by jamesgongqantas** [comment]
> Maybe let's take a step back.
> 
> You don't need to use the forward-to endpoint to connect to your API. You can talk to it directly if you want, and take care of the auth stuff. If you do that, you also have to adjust your CSP config to allow the API domain.
> 
> The forward-to endpoint can be used to secure your API with low effort, as most of the auth validation is done by the MC API for you.
> 
> As for why the request doesn't have the headers, I can look into that and try to reproduce it.

true, so in my case, I can use an custom Apollo Client I guess?

**Comment by emmenko** [comment]
Either a custom apollo client or you override things using the `context` option, for example by passing the `uri` and the `headers`:

https://github.com/commercetools/merchant-center-application-kit/blob/fd818e3a131ce71f02b738b5c9ff93978ae526fe/packages/application-shell/src/utils/apollo-context.ts#L18-L22

I'll double check that this setup works though.

**Comment by tdeekens** [comment]
You should be able to overwrite the `context` of the Apollo query just like we do through our `createApolloContextForProxyForwardTo`. 

```js
const { loading, data, error } = useQuery(MyQuery, {
  context: {
    uri: externalApiUrl,
  },
});
```

However, how do you envision auth with your service and header to work in interplay with Custom App and your backing API with the `accesstoken` header? Where does it come from and when is it set?

**Comment by emmenko** [comment]
I can reproduce the issue with the missing header, when using the `createApolloContextForProxyForwardTo`.
I'll open a PR with the fix. Sorry about that.

**Comment by emmenko** [comment]
PS: if you do use the `context` option for the default Apollo Client, and you don't use the `createApolloContextForProxyForwardTo`, you need to pass the `skipGraphQlTargetCheck: true` option.

**Comment by emmenko** [comment]
@jamesgongqantas FYI: the bug fix has been released
https://github.com/commercetools/merchant-center-application-kit/releases/tag/%40commercetools-frontend%2Fapplication-shell%4016.14.1

**Comment by jamesgongqantas** [comment]
Thanks I’ll give  it a try. I probably will still go with the custom client
option instead of using forward with context. Because I need to set some
required key value pairs in the request header.

On Wed, 8 Jul 2020 at 6:12 pm, Nicola Molinari <notifications@github.com>
wrote:

> @jamesgongqantas
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jamesgongqantas&d=DwMCaQ&c=8bHjhITO0F85Cmi91C_4TA&r=UvwrQO1QbCridNLVbqgDZRVhTYMtyPNPyMWPI8FUMN4&m=9WkYmbgOa0QU6OCkO2aNpbm-8R0zwfcyOznOhgHq9oQ&s=WrbfsFL1GITUfZ26oVyBn2e8yw45uBhPx1hiOcmjPRk&e=>
> FYI: the bug fix has been released
>
> https://github.com/commercetools/merchant-center-application-kit/releases/tag/%40commercetools-frontend%2Fapplication-shell%4016.14.1
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_commercetools_merchant-2Dcenter-2Dapplication-2Dkit_releases_tag_-2540commercetools-2Dfrontend-252Fapplication-2Dshell-254016.14.1&d=DwMCaQ&c=8bHjhITO0F85Cmi91C_4TA&r=UvwrQO1QbCridNLVbqgDZRVhTYMtyPNPyMWPI8FUMN4&m=9WkYmbgOa0QU6OCkO2aNpbm-8R0zwfcyOznOhgHq9oQ&s=b_Qi5J21QcXV0fnBVZjcn_SMp0M_yF2Xz5fEQxLQjWU&e=>
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_commercetools_merchant-2Dcenter-2Dapplication-2Dkit_issues_1623-23issuecomment-2D655363313&d=DwMCaQ&c=8bHjhITO0F85Cmi91C_4TA&r=UvwrQO1QbCridNLVbqgDZRVhTYMtyPNPyMWPI8FUMN4&m=9WkYmbgOa0QU6OCkO2aNpbm-8R0zwfcyOznOhgHq9oQ&s=oeSeiFOVQlylF8bBqP15T4DjrRwykLgF6mWVw8nGwWw&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOW4XKV4JX37D6Q3VJJ3YP3R2QS5BANCNFSM4OS3ULOQ&d=DwMCaQ&c=8bHjhITO0F85Cmi91C_4TA&r=UvwrQO1QbCridNLVbqgDZRVhTYMtyPNPyMWPI8FUMN4&m=9WkYmbgOa0QU6OCkO2aNpbm-8R0zwfcyOznOhgHq9oQ&s=4NJTTR8-yF3ihpfq5NQbBrd88S80AqFWvNQlpMWUfSQ&e=>
> .
>

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
************** PLEASE CONSIDER OUR ENVIRONMENT BEFORE PRINTING *************
******************* Confidentiality and Privilege Notice *******************

This e-mail is intended only to be read or used by the addressee. It is confidential and may contain legally privileged information. If you are not the addressee indicated in this message (or responsible for delivery of the message to such person), you may not copy or deliver this message to anyone, and you should destroy this message and kindly notify the sender by reply e-mail. Confidentiality and legal privilege are not waived or lost by reason of mistaken delivery to you. 

Qantas Airways Limited
ABN 16 009 661 901
Visit Qantas online at http://qantas.com
****************************************************************************

**Comment by jamesgongqantas** [comment]
> @jamesgongqantas FYI: the bug fix has been released
> https://github.com/commercetools/merchant-center-application-kit/releases/tag/%40commercetools-frontend%2Fapplication-shell%4016.14.1

Thanks I’ll give  it a try. I probably will still go with the custom client
option instead of using forward with context. Because I need to set some
required key value pairs in the request header.

**Comment by emmenko** [comment]
I'll mark this issue as closed for now, if you still have problem or questions feel free to comment here again or open a new issue. Thanks
