### ISSUE TITLE
Environment values are not being coerced when using the <ApplicationShellProvider>

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#1659]
**Describe the issue**

When using the `<ApplicationShellProvider>` (mostly for internal usage, you probably ony need the `<ApplicationShell>`), the `environment` prop is not being coerced, when passing it as `environment={window.app}`, causing possible values to be strings (e.g. `"false"`).

**Expected behavior**

The `context.environment` should contain coerced values (e.g. `false` instead of `"false"`) when using only the `<ApplicationShellProvider>`.

**Comment by tdeekens** [comment]
Thanks. I suppose this yields the bug discussed internally?
