### ISSUE TITLE
Forward-to external graphql with Authorization?

### ISSUE THREAD

**Issue by jamesgongqantas** [commercetools/merchant-center-application-kit#1682]
Hi there

I'm using the forward-to to call external API by using Graphql client following this doc:
https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api#usage-for-apollo

I cannot find the the 60 seconds temp JWT token addressed in the documentation https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api#authenticating-requests-from-the-external-api in the request header

Is there something wrong or the JWT token is only for REST api?

**Comment by emmenko** [comment]
Hi, 

I checked the logs and (assuming it's you), I saw that you're possibly targeting a local server

```
x-forward-to: http://localhost:3333/graphql
```

Can you confirm that? If so, the proxy does not support forwarding requests to `http` URLs, only `https` is supported.

If you're testing things locally, I would suggest for now to have a logic in your custom app to either send the request through the proxy (when you're targeting your production server, which should run on `https`) or to send the request to your local server directly (no proxy involved).

We will check on our side if we can make this process a bit simpler.

Please let me know if this helps you and if you're still having different issues related to the `forward-to` functionality. Thanks!

**Comment by jamesgongqantas** [comment]
> Hi,
> 
> I checked the logs and (assuming it's you), I saw that you're possibly targeting a local server
> 
> ```
> x-forward-to: http://localhost:3333/graphql
> ```
> 
> Can you confirm that? If so, the proxy does not support forwarding requests to `http` URLs, only `https` is supported.
> 
> If you're testing things locally, I would suggest for now to have a logic in your custom app to either send the request through the proxy (when you're targeting your production server, which should run on `https`) or to send the request to your local server directly (no proxy involved).
> 
> We will check on our side if we can make this process a bit simpler.
> 
> Please let me know if this helps you and if you're still having different issues related to the `forward-to` functionality. Thanks!

Hi Emmenko

Yes I tried with localhost http API first and the request complains about the http support, so I change to a https endpoint later.

Both cases I didn't see the Authorization  header in the request. Also regardless the request success or failed, I should see the request headers anyway right?

**Comment by emmenko** [comment]
Which `@commercetools-frontend/application-shell` version are you using? There was a [bug fix](https://github.com/commercetools/merchant-center-application-kit/blob/master/packages/application-shell/CHANGELOG.md#16141) in `16.14.1` related to the Apollo Client and the `forward-to` functionality.

**Comment by jamesgongqantas** [comment]
I’m using the latest one which is 16.15.9 I believe

**Comment by emmenko** [comment]
How are you sending the request from the frontend? Are you using the `createApolloContextForProxyForwardTo` function?

If so, in the logs I should see the `accept-version: v2` HTTP header but I don't see it.

Also, I assume you're getting some kind of error response. Can you tell me what kind of error do you get?

FYI: If the `forward-to` request is OK, your server should get 3 additional headers:
- `authorization`
- `x-mc-api-cloud-identifier`
- `x-mc-api-forward-to-version`

**Comment by emmenko** [comment]
You can also try to debug things using this curl command:

```
curl -X POST \
  -H "accept: application/json" \
  -H "accept-version: v2" \
  -H "content-type: application/json" \
  -H "cookie: mcAccessToken=<jwt>" \
  -H "x-forward-to: <target_url>" \
  -H "x-project-key: <project_key>" \
  "https://mc-api.australia-southeast1.gcp.commercetools.com/proxy/forward-to"
```

The `jwt` for the `mcAccessToken` can be retrieved from your browser dev tools, in the storage cookies section.

**Comment by jamesgongqantas** [comment]
> How are you sending the request from the frontend? Are you using the `createApolloContextForProxyForwardTo` function?
> 
> If so, in the logs I should see the `accept-version: v2` HTTP header but I don't see it.
> 
> Also, I assume you're getting some kind of error response. Can you tell me what kind of error do you get?
> 
> FYI: If the `forward-to` request is OK, your server should get 3 additional headers:
> 
> * `authorization`
> * `x-mc-api-cloud-identifier`
> * `x-mc-api-forward-to-version`

yes the request was sent from the FE and using `createApolloContextForProxyForwardTo`, something as follows:

```
{
      context: createApolloContextForProxyForwardTo({
        // The URL to your external API
        uri: window.app.middlewareUrl,
      }),
    }
```
and the request headers are as following image:

![image](https://user-images.githubusercontent.com/61721514/90407377-cd9f6a80-e0e9-11ea-838b-dab8f8b668fa.png)

The request failed because of the API I called (500 error code), I don't have the 3 additional headers you mentioned, but I don't understand why the request header will be different based on the call successful or not

**Comment by emmenko** [comment]
The 3 additional headers are attached by the MC API, when the request is being forwarded to the target URL.
The frontend only needs to send the headers as documented here: https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api#proxying-requests-to-the-external-api

Can you try the curl request maybe (filling the correct values of course)?

**Comment by jamesgongqantas** [comment]
> The 3 additional headers are attached by the MC API, when the request is being forwarded to the target URL.
> The frontend only needs to send the headers as documented here: https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api#proxying-requests-to-the-external-api
> 
> Can you try the curl request maybe (filling the correct values of course)?

tried the curl and it works.

**Comment by emmenko** [comment]
Let me try to prepare a small example of making a graphql request with Apollo.

**Comment by jamesgongqantas** [comment]
> Let me try to prepare a small example of making a graphql request with Apollo.

thanks. The thing is I can make the request successful but I cannot see the temp token in request header, from FE.

![image](https://user-images.githubusercontent.com/61721514/90474004-ac7d5f00-e167-11ea-94ee-13f95e1bf69d.png)

**Comment by emmenko** [comment]
Only your server receives the token header, the FE doesn't have that. This is because the FE makes the request to the MC API `forward-to` endpoint, which then generates an exchange token and it attaches it to the forwarding request to your server.

Did you check the request coming into your server?
Are you also using the express package to verify the request, as documented?

**Comment by jamesgongqantas** [comment]
> Only your server receives the token header, the FE doesn't have that. This is because the FE makes the request to the MC API `forward-to` endpoint, which then generates an exchange token and it attaches it to the forwarding request to your server.
> 
> Did you check the request coming into your server?
> Are you also using the express package to verify the request, as documented?

no I haven't done the server side yet. I was thinking the token should be visible in the FE request, now I'm gonna verify that on server side. If it works as that, we probably should put some more info in the documentation?

**Comment by emmenko** [comment]
Ok.

The token is only exchanged between servers, for security reasons.

> we probably should put some more info in the documentation?

I'm happy to improve the documentation if necessary. Can you maybe point me to what part wasn't clear and what would you expect from that? Thanks!

**Comment by jamesgongqantas** [comment]
> Ok.
> 
> The token is only exchanged between servers, for security reasons.
> 
> > we probably should put some more info in the documentation?
> 
> I'm happy to improve the documentation if necessary. Can you maybe point me to what part wasn't clear and what would you expect from that? Thanks!

if the token only exchange between servers, which means I have to make the changes on middleware public instead of local testing? If not what can I do to testing local FE and local middleware?

**Comment by gaganssohi** [comment]
In addition to above James comment, we have tried setting the audience as the middleware URL that also returned the same error.

Can you please help us with more details on audience attribute that should be set to.

message:"jwt audience invalid. expected: https://4b7be5ca27aa.ngrok.io/"
name:"UnauthorizedError"
stack:"UnauthorizedError: jwt audience invalid.

**Comment by emmenko** [comment]
@jamesgongqantas The `audience` value must be the URL where your API server is hosted, as [documented here](https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api#usage-for-expressjs).

<img width="776" alt="image" src="https://user-images.githubusercontent.com/1110551/90602537-35dd7180-e1fa-11ea-8995-cbab6ac8563e.png">

**Comment by gaganssohi** [comment]
We followed this comment and tried setting the audience as the middleware URL but that also returned the same error.

Can you please help us with more details on the audience attribute that should be set to. Is this source path or destination url or MC url ?? We have tried setting couple of values but still the same error


message:"jwt audience invalid. expected: https://4b7be5ca27aa.ngrok.io/"
name:"UnauthorizedError"
stack:"UnauthorizedError: jwt audience invalid.

**Comment by emmenko** [comment]
To answer the other questions:

> if the token only exchange between servers, which means I have to make the changes on middleware public instead of local testing? If not what can I do to testing local FE and local middleware?

Local testing between your Custom Application and your "API server" does not work using the `forward-to` endpoint of the Merchant Center API Gateway. We don't have a proper solution for this yet. I suppose you would need to use some kind of local tunnel or something. In that case, you need to make sure that e.g. your audience is properly set.

> also because the exchange is between your server and my server, what data will be logged from your side and do you have any documentation about security and privacy in that regard? as all request will be proxied by your server.

Our server logs request metadata like URL, HTTP headers, etc. If you need more detailed information about the privacy policy, I suggest to get in touch with our support.

---

> Can you please help us with more details on the audience attribute that should be set to. Is this source path or destination url or MC url ?? We have tried setting couple of values but still the same error

The `audience` is the same URL value that your provide to the `forward-to` header.

For example, if I use `https://my-server.com/some/sub-path?with=query-params`, the audience must exactly this value.

However, to make it simpler to verify the correct value dynamically, when you use the `@commercetools-backed/express` package, the `audience` field must be the origin URL: `https://my-server.com`.
The `@commercetools-backed/express` will then take care of constructing the FULL audience URL with the incoming request path.

https://github.com/commercetools/merchant-center-application-kit/blob/e483a004656aa38aebfafda9810eb5357610d191/packages-backend/express/src/auth.ts#L101-L113

**Comment by gaganssohi** [comment]
Thanks for your help on the same, its working now. We have another query regarding the response of sessionAuthVerifier. We can see it returns empty response. Is there any way to get the details of request initiator, just for audit purpose?

const response = await sessionAuthVerifier(req, res);
    logger.info('Session Auth Verifier response - ', response);

**Comment by emmenko** [comment]
> Thanks for your help on the same, its working now. 

Glad to hear that.

---

```js
const response = await sessionAuthVerifier(req, res);
logger.info('Session Auth Verifier response - ', response);
```

The `sessionAuthVerifier` function does not return any value. Instead it writes the session to the `request` object.

https://github.com/commercetools/merchant-center-application-kit/blob/e483a004656aa38aebfafda9810eb5357610d191/packages-backend/express/src/auth.ts#L178-L179

https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api#usage-for-serverless-functions

<img width="762" alt="image" src="https://user-images.githubusercontent.com/1110551/90727865-3cd0b680-e2c4-11ea-8af5-45556400282f.png">

<img width="718" alt="image" src="https://user-images.githubusercontent.com/1110551/90727905-4e19c300-e2c4-11ea-9add-ac678c4820e7.png">

**Comment by jamesgongqantas** [comment]
Hi I have another question about the forward-to, from the FE perspective, is there a way that we know the destination URL from the request? currently this information is not visible in the request header, as for debugging purpose, I have no idea is this proxy request actually goes to the right destination or not

**Comment by tdeekens** [comment]
The destination is what is being set ultimately as the x-forward-to header which if used our SDK sets. It is what is being specified on the FE. So your FE sets it and our API forwards the request after an project access check for the user. The header is visible in the e.g. Chrome Dev Tools. Is that what you where after knowing?

**Comment by jamesgongqantas** [comment]
> The destination is what is being set ultimately as the x-forward-to header which if used our SDK sets. It is what is being specified on the FE. So your FE sets it and our API forwards the request after an project access check for the user. The header is visible in the e.g. Chrome Dev Tools. Is that what you where after knowing?

yes thanks, I missed that one

**Comment by tdeekens** [comment]
Thanks. Glad I could help. I will close this as a result.

**Comment by jamesgongqantas** [comment]
> Thanks. Glad I could help. I will close this as a result. If this becomes relevant again let's re-open this. Also feel free to open small issues for non-related follow-up questions. It eases documenting solutions through closed issues for our community :)

I also have a related question, I have the following errors when making a proxy request

```
1:1 Access to fetch at 'https://mc-api.australia-southeast1.gcp.commercetools.com/proxy/forward-to' from origin 'https://mc.australia-southeast1.gcp.commercetools.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
Did I miss anything in frontend when making the proxy request? or this is up to the service side that receiving the forwarded request?
