### ISSUE TITLE
error: the jwk source must not be null, when reloading custom application

### ISSUE THREAD

**Issue by ct-jenny** [commercetools/merchant-center-application-kit#1683]
after adding custom application in Merchant Center it can be seen in the menu bar. But when the page is reloaded multiple times an error occurs. 

error:
Request processing failed; nested exeption is java.lang.IllegalArgumentExeption: The JWK source must not be null

Can you tell if this is a general issue or if there are more information needed to see what's going on?

**Comment by emmenko** [comment]
This looks like an error on the customer side (where the custom application is hosted).

The server should respond with the compiled HTML, I'm not sure why they require a JWK.

**Comment by sergiiManko** [comment]
Yes, server should respond if we get mcAccessToken from header, but in some cases we have not

**Comment by emmenko** [comment]
I'm sorry but I sense some confusion here. Can you describe your setup a bit more?

Your Custom Application should not concern itself with the `mcAccessToken`, only the Merchant Center API Gateway handles that. What are you trying to do here?

Your server (if you have one), should only serve the compiled `index.html`, which the Merchant Center will serve under the *.commercetools.com domain.

Or are you talking about using an external API for your Custom Application? https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api

**Comment by sergiiManko** [comment]
Yes, I am talking about using an external API for my Custom Application, and after our custom server serve the compiled index.html we are waiting requests with `mcAccessToken`

**Comment by emmenko** [comment]
The `mcAccessToken` is only used for the user session between the `mc` and `mc-api` domains.

When your Custom Application sends requests to your API server, you should send them using the `forward-to` endpoint, as documented.
Then, your API server receives a request with an `Authorization: Bearer <exchange_token>`, as documented here: https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api#authenticating-requests-from-the-external-api

Your API server should then verify that this token is valid and has been signed by the Merchant Center API Gateway.

If your server is a Node.js server, you can use our `@commercetools-backend/express` package to take care of the authentication check, otherwise you should implement this according to the programming language of your choice.
The implementation should follow the openid connect spec to use the `jwks.json` endpoint.

Does that help you?

**Comment by sergiiManko** [comment]
So, my API server receives a request with an Authorization: Bearer <exchange_token> sometimes, but if I reload page my API server receives null instead Bearer token

**Comment by emmenko** [comment]
I'm not sure what you mean by "reloading" the page in regards to the API server.

Can you maybe describe how your setup looks like, where is your Custom App hosted and your API server, and so on? (you don't need to provide your real URL, a fake URL is ok as long as e.g. the URL structure is the same)

**Comment by sergiiManko** [comment]
https://commercetools-dev.vertexconnectors.com/connector-config it is our app host

**Comment by sergiiManko** [comment]
https://commercetools-dev.vertexconnectors.com/  api host

**Comment by sergiiManko** [comment]
@emmenko I mean `reload page` on Merchant Centre with our custom app

**Comment by emmenko** [comment]
When you access the Custom Application through the Merchant Center, we forward the request to the URL that you specified when you registered the Custom Application. That URL should simply return the `index.html`. There is no token involved here.

When your Custom Application is rendered in the browser, some part of your code would need to talk to your API server.
The request should go to the `forward-to` endpoint, to take advantage of the built-in authentication within the Merchant Center session.
The Merchant Center API Gateway then, upon authenticating the user, forwards the request to the URL specified in the forward-to [HTTP header](https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api#proxying-requests-to-the-external-api).
This is where your API server will receive the request with the `Authorization: Bearer <exchange_token>`, which you should verify.

---

This is a broader overview of how the frontend and backend works.
I'm not sure where your confusion lies...maybe your application routing is not properly configured or something?

**Comment by sergiiManko** [comment]
@emmenko Thank you so much for your help! Now it is working as expected

**Comment by emmenko** [comment]
Awesome 👏

Can you share for future references maybe what you had to do/change? 

Also, please let us know if there was anything unclear in the documentation. We're happy to improve it where necessary. Thanks!

**Comment by sergiiManko** [comment]
When we develop this API for our custom application in previous year, we are waiting that all requests from Merchant Center(or proxy) should contain Bearer token, but now we disable check token when we get out index.html

**Comment by emmenko** [comment]
Closing as the issue seems to be solved.
