### ISSUE TITLE
Provide documentation and example on developing an external API from localhost

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#1686]
**Which part of the documentation does it affect and which topic does it refer to?**

How to work with and develop an external API.

Ref: #1682 

**Describe what needs to be improved**

Developing a Custom Application locally, together with an external API, has some limitations.
For example, using the `forward-to` endpoint of the Merchant Center API Gateway with a target URL pointing to `http` is not allowed. Only `https` targets are allowed.
Furthermore, the Merchant Center API Gateway cannot proxy a request to `localhost`.

Therefore, the user needs to either use the production URL of its external API or use some kind of local tunnel solution.

Using the production URL obviously works but it has the downside of not being able to develop both Custom Application and external API together, locally.

Using a local tunnel seems to be the only solution to allow local development for both frontend and backend.
In this case, we need to provide some examples and documentation on possible solutions to do so.

**Comment by mmaltsev-ct** [comment]
To be copied to the JIRA "Docs Improvements" epic. Close after moving it
