### ISSUE TITLE
Validating MCAccessToken

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#1708]
**Describe the issue**

We want to make a call from MC custom application to an external server, we want to send token when a call is been made and validate the token on the external server before we process a request.

**To Reproduce**

1. Agent logged-in into the MC and got the mcAccessToken. 

2. We sent the MC token to middleware and tried validating the token using the introspect API. But this API does not work:

https://auth.australia-southeast1.gcp.commercetools.com/oauth/introspect

**Expected behavior**

We want to validate the token issued within MC from external server.

**Screenshots**

We need your assistance with the step mentioned in red color:

![image](https://user-images.githubusercontent.com/29213153/91857516-0127dc00-ec36-11ea-8350-0693a9136c06.png)

**Comment by adnasa** [comment]
Hey @michaelashe,
were the previous answers helpful to you?

**Comment by michaelashe** [comment]
Hey @adnasa ,
I will update the ticket from the customer with the feedback provided here and wait for the response.
Thanks for the help!
