### ISSUE TITLE
Wrong main application route path in custom application starter docs

### ISSUE THREAD

**Issue by anilkk** [commercetools/merchant-center-application-kit#1710]
**Which part of the documentation does it affect and which topic does it refer to?**
[Renaming the application main route path section](https://docs.commercetools.com/custom-applications/getting-started/installing-a-starter-application#renaming-the-application-main-route-path)

It's a very small name change. 
[Renaming the application main route path section](https://docs.commercetools.com/custom-applications/getting-started/installing-a-starter-application#renaming-the-application-main-route-path) refers The starter application defines `example-starter`. But, it should be `examples-starter`.

**Describe what needs to be improved**
Update the starter application name reference in the docs.
 
Now: `example-starter`
<img width="306" alt="Screenshot 2020-09-04 at 00 48 43" src="https://user-images.githubusercontent.com/1124415/92180950-7bc84580-ee48-11ea-8039-76e7ca403870.png">

should be: `examples-starter`
<img width="306" alt="Screenshot 2020-09-04 at 00 48 52" src="https://user-images.githubusercontent.com/1124415/92180938-75d26480-ee48-11ea-8415-d120e2ddc2ca.png">

**Comment by adnasa** [comment]
thanks for opening your first issue already! 
I'll have a look at this :)
