### ISSUE TITLE
Long notification styles issue

### ISSUE THREAD

**Issue by islam3zzat** [commercetools/merchant-center-application-kit#1711]
**Describe the issue**

There are two issues with notifications, I came across

1. For long notifications, the `x` button is showing in the middle, but it should be the top right.
2. The link text is provided color in the notification component which is the same color as the text, but the user should have the flexibility accent it to distinguish it from the text.

https://github.com/commercetools/merchant-center-application-kit/blob/1edcf22af850519116ec20a9469eb292b5f13160/packages/react-notifications/src/components/notification/notification.styles.ts#L85

<img width="536" alt="Screenshot 2020-09-04 at 14 31 31" src="https://user-images.githubusercontent.com/7680511/92239582-8f60c400-eebb-11ea-85ad-6f00a8324f2d.png">

**To Reproduce**

1. Render a notification with long text.

**Screenshots**

**Additional context**

**Comment by islam3zzat** [comment]
I don't think that we should style the link with the same color as the text, but I guess it was styled like this for some reason. If not then we should remove it and style only the paragraph.

**Comment by tdeekens** [comment]
Your concerns and finding looks right 👍🏼. Thanks for reporting. I presume we never needed or had such rich notifications. 

Have you looked already in providing a fix or even PR?

**Comment by tdeekens** [comment]
I think it's not intentional. I would however contact UX/Design to make sure. I don't think we have a design decision record of this.

**Comment by emmenko** [comment]
Thanks for reporting. I think the notification component can definitely get some maintenance.

@jonnybel @adnasa can some of you take over this and also check with UX? Thanks

**Comment by coolmilo** [comment]
@islam3zzat thank you for the valid feedback. 
1. The close button was always aligned at the top right as seen on the screenshot.
2. Any text links included should be underlined. 

We will review the rest of them further as we also had feedback on the positioning of the notifications.

![notifications](https://user-images.githubusercontent.com/9841247/92377107-ee187e80-f103-11ea-9829-3548449690fe.png)

**Comment by islam3zzat** [comment]
Thanks, @coolmilo for the quick response.
And regarding the links' color, can it be green like in the following design?
![image](https://user-images.githubusercontent.com/7680511/92399994-73635980-f12b-11ea-83e1-c3297dc4d24e.png)

**Comment by Shecki** [comment]
@islam3zzat  yes, the green is the correct color!
as its a link and our UI-KIT provide links with underline, it should also have the underline.

Thanks for sharing the findings!

**Comment by tdeekens** [comment]
> as its a link and our UI-KIT provide links with underline, it should also have the underline.

For completeness. The `Link`'s underline is configurable. We have had cases where it was requested to show have it. I am not sure what the design recommendations are when to use which. However, the `hasUnderline` property configures it. I am fine either way but now am a bit curious when we would be recommended to use an underline and when not.

**Comment by Shecki** [comment]
ok interesting.
From my side, if its a link within it should always include the underline.
only on the BTN-Flat and Link-BTN, it should not have an underline.

@tdeekens  would it be easy to get a list with all places of the mc, where we use "links" with and without underline?

**Comment by tdeekens** [comment]
> @tdeekens would it be easy to get a list with all places of the mc, where we use "links" with and without underline?

Let's take this internally to DMs.

**Comment by islam3zzat** [comment]
My only problem in the link, was that the notification overrides the links' color, otherwise the user is responsible for the notification's content and its styles.
I think it's all clear for me now, and will start working on the fix.

**Comment by Shecki** [comment]
@islam3zzat  good :)
the other thing: @tdeekens, and myself could clarify it

**Comment by tdeekens** [comment]
For additional context: https://github.com/commercetools/ui-kit/issues/1548.
