### ISSUE TITLE
where are the app.chunk.js, runtime-app.js and vendors~app.chunk.js

### ISSUE THREAD

**Issue by jamesgongqantas** [commercetools/merchant-center-application-kit#1720]
I specified CDN url in the property files, and when starting the app, I saw the following errors complains about those files:

![image](https://user-images.githubusercontent.com/61721514/92436059-1b8a2880-f1e7-11ea-9d86-3d96705d9db4.png)

I check the `dist` folder and cannot found those files. my start script is `"start": "mc-scripts start",`

**Comment by anilkk** [comment]
@jamesgongqantas Can you please check our docs here https://docs.commercetools.com/custom-applications/deployment/runtime-configuration#content-security-policy?
Have you already listed your **domains** in the `headers.json` file?

**Comment by adnasa** [comment]
Hello, thank you for your request.
Are you attempting to run your application locally or in production?

**For information**
When you want to run your application locally with `mc-scripts start`, the application runs using the webpack dev server which doesn’t generate a `dist`folder.

The `cdnUrl` is only needed on production.
Please read more about it here: [Application Config in Custom Applications](https://docs.commercetools.com/custom-applications/development/application-config#envproductioncdnurl)

**Comment by jamesgongqantas** [comment]
FYI I'm trying to run the application in a testing environment. does it picking up the dev ones as local or prod ones?

**Comment by emmenko** [comment]
Can you describe how are you testing the application? Are you using something like Cypress for E2E tests?
