### ISSUE TITLE
Forward-to request get CORS error

### ISSUE THREAD

**Issue by jamesgongqantas** [commercetools/merchant-center-application-kit#1724]
Hi I'm getting the following errors when trying to make a proxy call from custom app.
```
Access to fetch at 'https://mc-api.australia-southeast1.gcp.commercetools.com/proxy/forward-to' from origin 'https://mc.australia-southeast1.gcp.commercetools.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

from the error it looks like the https://mc-api.australia-southeast1.gcp.commercetools.com is not having https://mc.australia-southeast1.gcp.commercetools.com allowed in header? could you guys please check it?

**Comment by jamesgongqantas** [comment]
![image](https://user-images.githubusercontent.com/61721514/92568246-3d0c1280-f2c2-11ea-94fd-368dbbe37832.png)
![image](https://user-images.githubusercontent.com/61721514/92568311-53b26980-f2c2-11ea-9a5d-1b51e0260494.png)


I send the same request from my localhost via forward-to and it works, however when testing it on deployed version, I get the CORS error. If the request routings are both from "frontend => CT => external API", then why the local one doesn't have the CORS issue?

**Comment by github-aji** [comment]
Console error details
![image](https://user-images.githubusercontent.com/29443279/92568645-cfacb180-f2c2-11ea-80a8-b23f5b4e7050.png)

**Comment by emmenko** [comment]
Hmm this is weird. Is this happening only for the `/forward-to` endpoint or for every request?

The CORS config is configured correctly (I double checked). I also checked the MC with my account and there are no CORS issues that I can see.

Do you have this issue only in your Custom Application? Which browser are you using? Have you tried other browsers?

**Comment by jamesgongqantas** [comment]
> Hmm this is weird. Is this happening only for the `/forward-to` endpoint or for every request?
> 
> The CORS config is configured correctly (I double checked). I also checked the MC with my account and there are no CORS issues that I can see.
> 
> Do you have this issue only in your Custom Application? Which browser are you using? Have you tried other browsers?

this is happening only for the forward-to request. I only tested the custom application. I tried latest Chrome in Mac and also Safari on Mac, both returns the same error. here's the screenshot for Safari

![image](https://user-images.githubusercontent.com/61721514/92583371-916cbd80-f2d5-11ea-8a22-42f17f3ce025.png)

**Comment by emmenko** [comment]
I looked into our server logs and I can see this:

<img width="1948" alt="image" src="https://user-images.githubusercontent.com/1110551/92601899-a9304b80-f2ad-11ea-8bf9-22a0f992d37b.png">

The first request matches the one you have in your screenshot with the correlation ID

```
mc/sit-qantas-loyalty-retail/fc7ee01d-9fa4-4d23-a70d-9c464955ea3d/c25f56ef-0ca2-44bf-bcd3-8026d56dabcc
```

As you can see from the screenshot, the response status code is `500`.

Our server is configured that the CORS middleware comes before the access log middleware, so I assume that if we get the access log then the CORS check succeded.

I'm wondering then if it's something related to your external server that blocks the request. In the logs the response status code is sometimes 200 and sometimes 500.

Can you maybe check if you need to configure something on your server? I can't think of a reason for our server to cause this issue, given that all other requests work fine.

You can also maybe try forwarding the request to any other URL, just to see if you still get an error.

Let us know what you can find, thanks.

**Comment by timothy-stokes** [comment]
From the investigation we did today it looks like the behaviour of our API is fine, responding in a timely manner with 200 response codes. Then somewhere between there and the reply back to the browser there is some latency (30 seconds) and then an error rather than the 200 response.

**Comment by timothy-stokes** [comment]
other network layers include nginx which is reporting the 200s ok. Akamai which we are looking into. Just out of curiosity do you have any timeouts set on your proxy at around 30 seconds? Comfortable with this setting (actully tones of time) but may help us diagnose if that is the case.

**Comment by emmenko** [comment]
> Just out of curiosity do you have any timeouts set on your proxy at around 30 seconds?

We don't have any default timeout set. We only have an agent "keep alive" timeout of 60s.
For proxying requests we use this library: https://github.com/http-party/node-http-proxy

---

Have you tried forwarding the request to another URL, just for testing purposes?

**Comment by jamesgongqantas** [comment]
> > Just out of curiosity do you have any timeouts set on your proxy at around 30 seconds?
> 
> We don't have any default timeout set. We only have an agent "keep alive" timeout of 60s.
> For proxying requests we use this library: https://github.com/http-party/node-http-proxy
> 
> Have you tried forwarding the request to another URL, just for testing purposes?

yes forwarding to another URL works

**Comment by emmenko** [comment]
> yes forwarding to another URL works

So does that meant that you only get CORS errors (or some error) when forwarding to your API?

**Comment by jamesgongqantas** [comment]
> > yes forwarding to another URL works
> 
> So does that meant that you only get CORS errors (or some error) when forwarding to your API?

seems like, but the thing is our API did show the request has been received and the data actually get updated successfully without any error. Not sure why you guys get a 500 response code. We are still trying to identify what's possible wrong between MC server and our API layer.

**Comment by jakespur** [comment]
Looks like chrome is blocking this due to **CORS not being correctly configured on your subdomain**.

Are you able to wildcard this or perform a check to see if the domain ends with 'commercetools.com' and add the appropriate headers.

`
if (req.hostname.endsWith('commercetools.com ')) {
        res.setHeader('Access-Control-Allow-Origin', 'http://' + req.hostname);
       res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,Content-Type');
      res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, DELETE');
}
`

Also how is this configured across over regions is the request going back to itself hence why you don't see this issue elsewhere?

**Comment by jakespur** [comment]
Even with CORS disabled at the browser level we still hit a 502 error.

Looks to me like you have an issue with Google Cloud platform, could you check your load balancer.

Or is it possible we are being rate limited?

![image (6)](https://user-images.githubusercontent.com/273312/92841461-b7a17300-f425-11ea-989e-9867685edfc4.png)

**Comment by jamesgongqantas** [comment]
> Hmm this is weird. Is this happening only for the `/forward-to` endpoint or for every request?
> 
> The CORS config is configured correctly (I double checked). I also checked the MC with my account and there are no CORS issues that I can see.
> 
> Do you have this issue only in your Custom Application? Which browser are you using? Have you tried other browsers?

Also can I use my own Apollo client instead of the pre-configured one? as a workaround I probably will discard any errors including the network error in this case and treat the request successful regardless.

If I can what config details I need to put in my own client, so it still can use the forward-to method

Regards

**Comment by jakespur** [comment]
**UPDATE**

We were actually running into an issue upstream with one rogue API call was taking greater than 30 seconds to respond, hence the actual request was taking 40 seconds to respond back with a valid result.

When this delay happens we are seeing the /forward-to endpoint timeout and return a 503 response to the frontend.

We have verified this by bypassing the /forward-to endpoint and calling the API direct and the API does eventually resolve with a 200 response.

But if we go through the /forward-to endpoint then it consistently short circuits any API call that goes beyond 40 seconds.

From our standpoint we need the /forward-to endpoint to not timeout with a 503 status code as this was masking the underlying issue.

**Comment by jakespur** [comment]
Agree, the ideal scenario is to get back the response in under 500 milliseconds. We have put some additional logic our side that short-circuits this API call and returns a payload informing the end user that the call has not been successful.

408 status code would be the ideal response from the /forward-to endpoint, 503 is not the correct response in this scenario.

It would be ideal if this timeout is documented in the docs, in hindsight had we known the API would be problematic we would have thrown this request onto a background queue.

**Comment by tdeekens** [comment]
> short-circuits this API

That sounds good. Thanks

> 408 status code would be the ideal response

I agree. The team has to investigate which part of infrastructure actually gives the 503 on our end. I am not 100% sure if it's the Node.js server or even some Load Balancer. From there we can see if we can and should adjust it.

> ideal if this timeout is documented in the docs

I agree. Also something for the team. Maybe @anilkk can have an initial look where it should go and take it from there.
