### ISSUE TITLE
Improve documentation about the MC proxy matching routes logic

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#1729]
**Which part of the documentation does it affect and which topic does it refer to?**

- https://docs.commercetools.com/custom-applications/getting-started/installing-a-starter-application#renaming-the-application-main-route-path
- https://docs.commercetools.com/custom-applications/main-concepts/architecture
- https://docs.commercetools.com/custom-applications/help-needed#changes-to-the-custom-application-are-not-reflected-immediately
- https://docs.commercetools.com/custom-applications/development/application-config#entrypointuripath

**Describe what needs to be improved**

Users are still often confused about the "Main route path" (or `entryPointUriPath`). It would be useful to describe a bit more (maybe with some matching examples) how the MC proxy matches the request route towards Custom Applications.

**Comment by mmaltsev-ct** [comment]
Closing the ticket, as we've introduced a new version of the documentation.
