### ISSUE TITLE
Speed up Custom Application deployment step on Firebase, Vercel & AWS

### ISSUE THREAD

**Issue by anilkk** [commercetools/merchant-center-application-kit#1733]
**Is your feature request related to a problem? Please describe.**

Currently, I need to create a `transformer-firebase.js` file manually and paste the code from docs.
Example: I would like to deploy **my starter custom application** on **Firebase**. 
I'm following the steps described in the [docs](https://docs.commercetools.com/custom-applications/deployment/example-deployment-firebase#generate-firebasejson-function-using-a-transformer-function).

**Steps** in the docs are create file  `./config/transformer-firebase.js` and copy code to this file.

Being a beginner of Custom Applications developer, I would like to get my first application up and running quickly, without wasting my time on manually creating files and copying the code. 

**Describe the solution you'd like**

It would be nice to have some `mc-scripts` to auto-generate the transformer-function.

`mc-scripts generate-transformer-function --vercel`
`mc-scripts generate-transformer-function --firebase`
`mc-scripts generate-transformer-function --aws`
 
Example: 
**Describe alternatives you've considered**

`mc-scripts generate-transformer-function-vercel`
`mc-scripts generate-transformer-function-firebase`
`mc-scripts generate-transformer-function-aws`

**Additional context**

As a Custom Application developer, I would like to get up and running my application quickly, without wasting or worrying time in the configs.

**Comment by emmenko** [comment]
PS: @stephsprinkle you were mentioning some paint points regarding hosting and deployments of Custom Applications (as a general thing). Would something like this help easing that "pain" a bit?

**Comment by stephsprinkle** [comment]
It's definitely a start! At least for Firebase and AWS, there are a bunch of steps after the transformer to actually getting the application deployed and I think that is where the majority of the "pain" is.

**Comment by anilkk** [comment]
I noticed one more place to optimize. 
can we optimize these 3 steps to deploy into 1 step? 
[deployment vercel](https://docs.commercetools.com/custom-applications/deployment/example-deployment-vercel#deployment)

Expecting some script like this one.
`
mc-scripts deploy-to vercel
`
which basically runs all these three steps with just one script.  
`
$ yarn build
$ mc-scripts compile-html --use-local-assets --transformer $(pwd)/config/transformer-vercel.js
$ vercel
`

**Comment by emmenko** [comment]
Hmm I wouldn't go that far, as then we're locking the user into our own opinionated configuration.

For now, I would only look into the "generation" of a transformer template file.

**Comment by adnasa** [comment]
I want to take a look at this once I'm done with documentation

**Comment by emmenko** [comment]
It's also different between the different hosting providers. Firebase and AWS look definitely more complicated then e.g. Vercel, so there you already have an implicit complexity.

We should also gather more feedback from users about how far we can go around providing pre-defined deployment setups.

**Comment by anilkk** [comment]
Being a Custom Application developer, I would like to focus on working **business logic of the application**, rather than worry about **deployments**. I agree with @emmenko more user feedback will be useful.

**Comment by adnasa** [comment]
We could try to add Vercel initially and look into the other providers at a later stage

**Comment by mmaltsev-ct** [comment]
Closing the issue, as it is not relevant anymore after introducing org-level Custom Applications.
