### ISSUE TITLE
Custom App /proxy/forward-to gives 500 Unexpected Non-JSON Error Response

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#1741]
**Describe the issue**

@commercetools-frontend/sdk sdkActions.forwardTo.get always fails with 500 and no message. No indication of reaching the api.
The api has been tried through ngrok and is accessible with curl without issues. The Api responds with json.

**To Reproduce**
`{ Sdk, actions as sdkActions }
from '@commercetools-frontend/sdk';
export const fetchJobs = () => {
return sdkActions.forwardTo.get({
uri: `${source}${path}`,
});
};
<Sdk.Get
actionCreator=

{() => fetchJobs()}
render={(

{ isLoading, error, result }
) => {
if (isLoading) return <Text.Body>'Loading...'</Text.Body>;
if (error) return <Text.Body>{`Error! ${error.message}`}</Text.Body>;
return (
<table style=width: '100%'>
{
result.scheduledJobs.map((job, i) => {
return <JobItem key=

{i}
job=

{job}
start/>
})
}
</table>
);
}}
/>

Renders "Error! Unexpected non-JSON error response"
The request never hits the api.`
Renders "Error! Unexpected non-JSON error response"
The request never hits the api.

**Expected behavior**

I expect to get a json response simular to what curl gives
> {"scheduledJobs":[{"name":"TestQueueJob","description":"A queue test job",....

**Screenshots**

![image](https://user-images.githubusercontent.com/29213153/93099044-8f0fb800-f675-11ea-828a-9c3a1f7ac20a.png)

**Additional context**

Request goes through ngrok to the development api.
The Api works fine and responds with json.
I had no problems with the request on Friday last week but it dosn't work as expected now.

**Comment by emmenko** [comment]
Hmm the (error) message `Unexpected non-JSON error response` seems to come from the JS SDK:

https://github.com/commercetools/nodejs/blob/707007d026ce734f7f914d0ac933e4e70c0e3bbd/packages/sdk-middleware-http/src/http.js#L17

In our logs I can see that the response is indeed marked as `500`, but that usually means it comes from the external server.

Are you sure the ngrok link is still valid?

**Comment by OlofMoriya** [comment]
The ngrok link was tested from multiple sites. It's not currently up as it's a dev environment but it was most assuredly responding to calls both from the local host and from other host.

**Comment by OlofMoriya** [comment]
![image](https://user-images.githubusercontent.com/13721900/93125527-9366c000-f6cb-11ea-9566-5baf61c26cd9.png)
API is responding with json but calls from the merchant center app never reaches ngrok 
https://ebd96e3c20a9.ngrok.io/backend/api/scheduled-jobs/

**Comment by OlofMoriya** [comment]
Finally figured it out. The 500 comes from https://mc-api.europe-west1.gcp.commercetools.com/proxy/forward-to 
It should be a 401 as my login had expired while the UI was still showing me as logged in. Making a fetch against "https://mc-api.europe-west1.gcp.commercetools.com/proxy/forward-to" with the added headers responded with a 401 which indicated the expired login. After logging out and then back in again the request goes through both with the fetch and the sdk.

**Comment by emmenko** [comment]
@OlofMoriya Ah good to know, thanks a lot for digging into it and giving us that feedback!

We'll definitely look into this scenario and try to fix this behavior.
