### ISSUE TITLE
Requests through /proxy/forward-to only replaces authorization header, never adds one. 

### ISSUE THREAD

**Issue by OlofMoriya** [commercetools/merchant-center-application-kit#1744]
**Description**
When using the sdk to actions.forwardTo the authorization header is replaced with a bearer token. This works fine unless the Authorization header is not specified at which point the sdk does not add a bearer token to the request. This leads to ugly code with an unused authorization header added to external api calls. 

**To Reproduce**

1. Make a request with 
`actions.forwardTo.get({
        uri: omitted,
        headers: {'Authorization': 'proxy replaces this'}
    });`
2. Control that the authorization header now is replaced with a bearer token after being forwarded
3. Make a request with 
`actions.forwardTo.get({
        uri: omitted
    });`
4. The outgoing request now has no Authorization header

**Expected behavior**

The header should always be added on the outgoing calls from the proxy/forward-to

**Comment by emmenko** [comment]
Hi, I'm a bit confused by what you are trying to do here and what do you expect to happen.

> The header should always be added on the outgoing calls from the proxy/forward-to

When using the forward-to endpoint, the Merchant Center API Gateway will generate an exchange token and forward it with the request to your server as a bearer token in the `Authorization` HTTP header.

Can you describe the use case of you having to send an `Authorization` header from the Custom Application?
Thanks

**Comment by OlofMoriya** [comment]
I can no longer reproduce this issue. Most likely usage-fault on my side.
