### ISSUE TITLE
Describe the (basic) structure of the menu.json file.

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#1753]
**Which part of the documentation does it affect and which topic does it refer to?**

https://docs.commercetools.com/custom-applications/development/menu-links

**Describe what needs to be improved**

Describe the structure for the `menu.json` file.

**Comment by emmenko** [comment]
FYI: this could be partially solved by https://github.com/commercetools/merchant-center-application-kit/issues/1753 (as the menu links are documented by the JSON schema).

**Comment by mmaltsev-ct** [comment]
The outdated issue, closing the ticket.
