### ISSUE TITLE
Custom App First Deployment Error

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#1792]
**Describe the issue**

I'm trying to deploy a new custom application, I'm currently at this step - https://docs.commercetools.com/custom-applications/deployment/example-deployment-aws-s3-cloudfront#compile-the-application

but when I run a command specified in the docs
mc-scripts compile-html --use-local-assets --transformer $(pwd)/config/transformer-aws.js

I get an error:

502 ERROR
The request could not be satisfied.

The Lambda function returned invalid json: The json output must be an object type.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.

If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Generated by cloudfront (CloudFront)
Request ID: **************************

(/Users/pavelnesmelov/Projects/commercetools/commercetools/custom_applications/discounts/node_modules/@commercetools-frontend/mc-html-template/build/compile-html.js:80:19)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async generateStatic (/Users/pavelnesmelov/Projects/commercetools/commercetools/custom_applications/discounts/node_modules/@commercetools-frontend/mc-scripts/build/compile-html.js:112:20)

**Additional context**

Custom App Config JSON:
`{
  "name": "Discounts app",
  "entryPointUriPath": "discounts",
  "cloudIdentifier": "gcp-eu",
  "env": {
    "production": {
      "url": "https://d3fuh9qbwutst3.cloudfront.net"
    }
  },
  "additionalEnv": {
    "discountsMetadataCustomTypeKey": "discount-metadata",
    "discountsMetadataFieldUseInCodeGeneratorApp": "forUseInDiscountCodeGeneratorApp",
    "project": "${env:PROJECT}"
  }
}`

Also, when I debug compile-html.js file that throws an error, here is what I see:
`options: {
envPath: undefined,
cspPath: undefined,
headersPath: undefined,
publicAssetsPath: '/Users/pavelnesmelov/Projects/commercetools/commercetools/custom_applications/discounts/public',
useLocalAssets: false
}`
As you can see, useLocalAssets is false for some reason (even when it is provided as flag --use-local-assets)

One more thing that might be helpful. when I manually fix the flag inside the script, I get another error:
`ENOENT: no such file or directory, open '/Users/pavelnesmelov/Projects/commercetools/commercetools/custom_applications/discounts/public/index.html.template'`

I'm not sure why it searches for index.html.template file inside the /public dir, cause webpack puts it into dist/assets? that file in that assets dir. If I try to manually move it into /public, when I run compile, it gets removed (which is expected, probably the it clears the dir before new compile) and then throws that error again.

**Comment by emmenko** [comment]
> As you can see, useLocalAssets is false for some reason 

Hmm that's weird. Are you sure you're executing the command correctly with the correct flag name?

> I'm not sure why it searches for index.html.template file inside the /public dir, cause webpack puts it into dist/assets? that file in that assets dir. 

When you build the production bundles with `mc-scripts build`, webpack puts the bundles into `dist/assets` yes.
Then when you run the `mc-scripts compile-html` command, we copy the assets into the `public` folder, which is where the `index.html.template` is to be found.

https://github.com/commercetools/merchant-center-application-kit/blob/75a8503d141c8d00e4a13bbd98a6efcb5d9bb4de/packages/mc-scripts/src/compile-html.js#L79-L93

---

PS: the `entryPointUriPath` can't be set as `discounts`, as this is an internal route that always takes precedence, and your application won't be served. See https://docs.commercetools.com/custom-applications/getting-started/installing-a-starter-application#renaming-the-application-main-route-path
