### ISSUE TITLE
Generate document.title based on location pathname

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#1830]
**Is your feature request related to a problem? Please describe.**

At the moment, each page of the Merchant Center shows the `Merchant Center` title. This is not very good for a number of reasons:

- With many tabs open, it's hard to find the correct one, as there is no page context information available.
- Using the browser history navigation is pretty much useless:

<img width="185" alt="image" src="https://user-images.githubusercontent.com/1110551/97175580-04ea6180-1794-11eb-8b34-7221c4fe52aa.png">

**Describe the solution you'd like**

Each page should reflect its context in the `document.title` so that users can understand where they are. For that we can derive the information from the URL, as the default behavior. Users can still decide to provide a more precise value by passing a custom render function.

**Comment by emmenko** [comment]
@FilPob Do you have any update about this feature?

**Comment by FilPob** [comment]
Didn't have time to look into it yet. Thanks for reminding, will do that today
