### ISSUE TITLE
Make the Logo link a normal page redirect

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#1832]
**Describe the issue**

The Logo link currently does a client-side redirect, which eventually ends up in a full page redirect anyway.

https://github.com/commercetools/merchant-center-application-kit/blob/8537a38431c428b245a8d178651d1d90efcbb0e9/packages/application-shell/src/components/app-bar/app-bar.tsx#L56-L58

To avoid possible unnecessary re-renders of the application, we can make it a normal page redirect in the first place.

**Comment by mmaltsev-ct** [comment]
Let's include this task in the Main navigation refinement effort (#1884).
