### ISSUE TITLE
Custom Application Docker Deployment with Different CDN URL

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#1833]
**Describe the issue**
We have a custom application for Merchant Center.  Do you have any guidance if we have to deploy the same docker image to different environment with different "cdnUrl" ?  

**The deployment is using Docker and has "custom-application-config.json" below :**
{
"name": "bundles-customization",
"entryPointUriPath": "bundle-manager",
"cloudIdentifier": "gcp-us",
"env": {
"production":

{ "url": "https://mc.us-central1.gcp.commercetools.com", "cdnUrl": "https://product-bundle-test.azurewebsites.net" }
}

**And this is the Dockerfile that we used:**
FROM eu.gcr.io/ct-images/mc-http-server:v16.15.8

WORKDIR /app
COPY ./packages/bundles-customization/dist /app/dist
COPY ./packages/bundles-customization/custom-application-config.json /app/custom-application-config.json

ENV NODE_ENV production
EXPOSE 3001

ENTRYPOINT ["node", "./bin/start-mc.js", "--use-local-assets"]

**I'm looking for how to setup the cdnUrl in environment variable since we need the same docker image for different environment.**

**Comment by emmenko** [comment]
Can you describe the use case a bit more? By **environment** do you mean like GCP-EU, GCP-US, and so on? Or is it like staging/production?

Note that the application config support environment variable placeholders: https://docs.commercetools.com/custom-applications/development/application-config#using-environment-variables

---

PS: in the recent appkit v17 release the `mc-http-server` is no longer supported. Make sure to read the changes and decide how you want to deploy your app.

**Comment by tri-in** [comment]
I mean staging/production. We tried below but no luck.
File custom-application-config.json
```
{
  "name": "bundles-customization",
  "entryPointUriPath": "bundle-manager",
  "cloudIdentifier": "gcp-us",
  "env": {
    "production": {
      "url": "https://mc.us-central1.gcp.commercetools.com",
      "cdnUrl": "${env:CDN_URL_ENV}"
    }
  }
}
```
Docker run command:
`docker run -p 3001:3001 commercetools.azurecr.io/product-bundle:product-bundle-envtest -e CDN_URL_ENV=https://bundle.azurewebsites.net
`

**Comment by emmenko** [comment]
The `env.production.url` is the URL where your application is hosted, not the Merchant Center URL.

As for the `CDN_URL_ENV`, yes that would be the way to do it, by passing the value via env variable.

**Comment by MartinTormandKruso** [comment]
We are also looking for a way to deploy to multiple environments, so our customer can test before changes are deployed to production(like staging or test). Has there been found a solution to this issue?

**Comment by emmenko** [comment]
If you have multiple environments like staging/production, you would need to register different apps so that the entry point of the app itself is different.
