### ISSUE TITLE
Document some important APIs/Hooks like application context

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#1862]
**Which part of the documentation does it affect and which topic does it refer to?**

Certain important APIs/Hooks like `useApplicationContext` are not properly documented, which hints that people might not be aware of those things.

**Comment by mmaltsev-ct** [comment]
Will be covered by JIRA task [SHIELD-442](https://jira.commercetools.com/browse/SHIELD-442). Closing this one.
