### ISSUE TITLE
[RFC] Let <ApplicationShell> pre-configure the application main route

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#1886]
**Is your feature request related to a problem? Please describe.**

All applications have this `entry-point.js` file where the `<ApplicationShell>` is rendered and so the application routes.

For example:

https://github.com/commercetools/merchant-center-application-kit/blob/63b684135d0e77ebdac9e44bb6e2ed2641ec7f92/application-templates/starter/src/components/entry-point/entry-point.js#L20-L40

This is the "usual" setup. There is a main route that maps to the application entry point, which then renders the actual application.
Here the main route should obviously match what the application `entryPointUriPath` is in the application config.

**Describe the solution you'd like**

I think at this point we can make the `<ApplicationShell>` a bit smarter, in that we provide this preconfiguration which is based on the application config (source of truth).

To be backwards compatible, we can maybe introduce this feature using the `children` prop. So you can pass the application component and render it as a child, or keep using the `render` prop but then configure things on your own.

Taking the starter app example, it would look something like this:

```js
const AsyncApplicationRoutes = React.lazy(
  () => import('../../routes' /* webpackChunkName: "starter-routes" */)
);

class EntryPoint extends React.Component {
  static displayName = 'EntryPoint';
  render() {
    return (
      <ApplicationShell
        environment={window.app}
        onRegisterErrorListeners={({ dispatch }) => {
          Sdk.Get.errorHandler = (error) =>
            globalActions.handleActionError(error, 'sdk')(dispatch);
        }}
        applicationMessages={loadMessages}
        DEV_ONLY__loadNavbarMenuConfig={() =>
          import('../../../menu.json').then((data) => data.default || data)
        }
        featureFlags={FEATURE_FLAGS}
      >
        <AsyncApplicationRoutes />
      </ApplicationShell>
    );
  }
}
```

That's it.

**Comment by adnasa** [comment]
I finally took the time to read this RFC. 
tbh I'm not sure I understand the potential of this.
I suggest we talk about this some time.
