### ISSUE TITLE
`storeState` render option of `renderAppWithRedux` is unusable

### ISSUE THREAD

**Issue by ahmehri** [commercetools/merchant-center-application-kit#1900]
**Describe the issue**

The `storeState` render option of `renderAppWithRedux` is unusable, it accepts an object with only `requestsInFlight` and `notifications` as keys.

**To Reproduce**

The following example code will result in an error.

```js
renderAppWithRedux(<TestComponent />, {
  storeState: {
    products: {
      currentVisible: {
        id: "current visible product",
      },
    },
  },
});
```

```
Unexpected key "products" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: "requestsInFlight", "notifications". Unexpected keys will be ignored.
```

**Expected behavior**

To be able to use `storeState` without getting an error.

**Additional context**

The error is coming from

https://github.com/commercetools/merchant-center-application-kit/blob/fa48548e9753dcc2dac7cc327d2668254d292353/packages/application-shell/src/configure-store.ts#L79-L95

and the reason is that the requirement of using the optional `preloadedState` parameter [is not met](https://redux.js.org/api/createstore#createstorereducer-preloadedstate-enhancer).

> If you produced reducer with combineReducers, this must be a plain object with the same shape as the keys passed to it. Otherwise, you are free to pass anything that your reducer can understand.

The keys passed to `combineReducer` are only `requestsInFlight` and `notifications`.

https://github.com/commercetools/merchant-center-application-kit/blob/fa48548e9753dcc2dac7cc327d2668254d292353/packages/application-shell/src/configure-store.ts#L54-L61

and there are no injected reducers at the moment of creating the store because the injection feature is designed to be used at runtime.

https://github.com/commercetools/merchant-center-application-kit/blob/fa48548e9753dcc2dac7cc327d2668254d292353/packages/application-shell/src/configure-store.ts#L99-L100

And because of that, the only allowed preloaded state is of shape.

```js
{
  requestsInFlight,
  notifications,
}
```

**Comment by emmenko** [comment]
Thanks for reporting the detailed issue.

I suppose we would need to pass `preloadedState` to `createInternalReducer`, then it should work.

https://github.com/commercetools/merchant-center-application-kit/blob/fa48548e9753dcc2dac7cc327d2668254d292353/packages/application-shell/src/configure-store.ts#L80-L81

Can you open a PR to trying fixing that?

**Comment by ahmehri** [comment]
I see, yes that may work, I will open a PR.
