### ISSUE TITLE
[Tech Debt]: Revert the changes regarding manually updated countries list

### ISSUE THREAD

**Issue by mohib0306** [commercetools/merchant-center-application-kit#1930]
#### Summary 
- `l10n` => Revert the changes from #1929. Revert the edited `json` files and re-run the script to update the files. Whenever the new `CLDR` data is release from http://cldr.unicode.org/index/downloads/cldr-39, the changes from #1929 should be reverted.

**Comment by adnasa** [comment]
@mohib0306 
Did we set a date on when to do this?

**Comment by mohib0306** [comment]
The CLDRv39 is not released yet, which might have the changes for the `Northern Ireland` country code http://cldr.unicode.org/index/downloads/cldr-39. The CLDRv38.1 is still missing the changes for the `Northern Ireland`. See discussion here https://github.com/commercetools/merchant-center-application-kit/pull/2054.

We can't revert these changes unless we have `Northern Ireland` country code in the CLDR data
