### ISSUE TITLE
Installing templates through the create-mc-app CLI fails

### ISSUE THREAD

**Issue by contexD** [commercetools/merchant-center-application-kit#2035]
**Describe the issue**

Running the commands

```bash
$ npm install --global @commercetools-frontend/create-mc-app
$ create-mc-app my-new-custom-application-project --template starter

# or

$ npx @commercetools-frontend/create-mc-app my-new-custom-application-project --template starter
```

results in the error

`'warning: Could not find remote branch master to clone.'`

**To Reproduce**

Run the commands above

**Expected behavior**

create-mc-app successfully clones into `main` (instead of `master`)

**Comment by tdeekens** [comment]
We recently renamed out main branch from master to main. I can look into this.

**Comment by contexD** [comment]
I saw on npm that the package was last published a week ago. It seems like the necessary changes were already made for `create-mc-app`, I think publishing the package will fix it.

**Comment by tdeekens** [comment]
Yeah, I just saw that publishing will fix it. In the meantime you can `create-mc-app my-new-custom-application-project --template starter --template-version=main`.

Sorry, for the inconveniences!

**Comment by contexD** [comment]
No problem, thanks!

**Comment by tdeekens** [comment]
The linked PR should fix the issue once the release was published.

**Comment by tdeekens** [comment]
The package got published as `@commercetools-frontend/create-mc-app@18.2.3` which should fix the issue. See also [npm](https://www.npmjs.com/package/@commercetools-frontend/create-mc-app).
