### ISSUE TITLE
Modal elements overlay causes layout shift if page content has been scrolled

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#2050]
**Describe the issue**

When using the modal components (e.g. dialogs or modal pages), those elements are rendered within a `portals-container` element positioned within the `main` container.

<img width="488" alt="image" src="https://user-images.githubusercontent.com/1110551/107525950-a4065e00-6bb7-11eb-8690-4f320546a6c8.png">

If you're on a page (and do not scroll) and you open a modal component, the overlay gets rendered correctly.

However, if the page has some long content and you scroll a bit and then open the modal component, the overlay gets "pushed" up depending on how much you scrolled.

**Expected behavior**

Even if the page scrolls, the overlay should be correctly positioned.

**Screenshots**

<img width="886" alt="image" src="https://user-images.githubusercontent.com/1110551/107526565-41fa2880-6bb8-11eb-9d19-ea4f147b9ec0.png">

<img width="884" alt="image" src="https://user-images.githubusercontent.com/1110551/107526598-4cb4bd80-6bb8-11eb-9afd-b759fdb95821.png">

**Additional context**

Ref https://github.com/commercetools/ui-kit/issues/1418

**Comment by ddouglasz** [comment]
Trying to reproduce this by moving this modal component across different pages/components of varying content heights, I found out that this can most likely be fixed depending on how the components are layered. So if the component are related such that the height of the current modal is dependent on the scrolling position of its parent, then it would act like a content of the previous page and somehow, its positioning gets affected by the page scroll of its parent page(case 1). 
Just as suggested [here](https://github.com/commercetools/ui-kit/issues/1418#issuecomment-771492225), rendering in a form of layout approach would do a great job in determining how this component behaves and achieving the desired result (case 2).

Case 1
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/19975842/157648284-dbcf95e6-ecf5-49e0-bce0-a1e07e169d5e.png">

Case 2
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/19975842/157647203-e594d2a7-9217-4412-8551-96f30a4d5874.png">

**Comment by emmenko** [comment]
@ddouglasz Any specific reason for closing the issue? Is there anything we can do/change to prevent this kind of situations?
