### ISSUE TITLE
applyOrderEditTo applied as a query string parameter

### ISSUE THREAD

**Issue by csi-lund** [commercetools/merchant-center-application-kit#2058]
Hi I encountered an issue when using post requests with the frontend sdk.
I am attempting to post and 'apply' OrderEdit but when I apply it I get a malformed url resulting in a 400

```
  return sdkActions.post({
    service: SERVICEPATH.OrdersEdits,
    mcApiProxyTarget: MC_API_PROXY_TARGETS.COMMERCETOOLS_PLATFORM,
    options: { applyOrderEditTo: orderEdit?.id },
    payload: JSON.stringify(applyOrderEdit)
 })
```
Like
orders/edits?/acc7e3ca-afb4-490c-b20c-65910a06ee35/apply

It seems to originate here: https://github.com/commercetools/nodejs/blame/master/packages/api-request-builder/src/create-service.js#L141 where order edit it always false and so its appended as a query string. 

![image](https://user-images.githubusercontent.com/1974225/107962443-3f784400-6fa7-11eb-83cf-6f26ff125512.png)

I can work around it doing this:
```
 let applyOrderEdit: OrderEditApply = { editVersion: orderEdit?.version, resourceVersion: orderVersion  }
  return sdkActions.post({
    service: SERVICEPATH.OrdersEdits,
    mcApiProxyTarget: MC_API_PROXY_TARGETS.COMMERCETOOLS_PLATFORM,
    options: { id: orderEdit?.id + "/apply" },
    payload: JSON.stringify(applyOrderEdit)
  });
};
```

**Comment by adnasa** [comment]
Hello. 
Apologies for the late reply. Thanks for opening this issue.
I think the reason `applyOrderToEdit` is false is because the `service.build` is called with empty values.
And this is needed to build the appropriate URL for you 

reference https://github.com/commercetools/nodejs/blob/a72fd8424250fc50c84197b505a44756ceb407b0/packages/api-request-builder/src/create-service.js#L127-L145

I'll have a look and get back to you when I verified the problem.

Thanks

**Comment by adnasa** [comment]
Hi @csi-lund I opened this PR https://github.com/commercetools/merchant-center-application-kit/pull/2060/
I welcome your review.

**Comment by adnasa** [comment]
hey. I merged the fix
there will be a release once this PR is merged
https://github.com/commercetools/merchant-center-application-kit/pull/2061

please try it out and get back to me

**Comment by adnasa** [comment]
hi @csi-lund have you had a chance to take a look at the new version?
