### ISSUE TITLE
Uncaught TypeError: Cannot read property 'applicationName' of undefined

### ISSUE THREAD

**Issue by slaymantis** [commercetools/merchant-center-application-kit#2065]
Get this error when testing the echo-server.js example

Uncaught TypeError: Cannot read property 'applicationName' of undefined
    at Module../node_modules/@commercetools-frontend/sdk/dist/commercetools-frontend-sdk.esm.js

**Comment by adnasa** [comment]
hey @slaymantis 
thanks for your issue.

Can you elaborate further please.
What were you trying to do?

**Comment by slaymantis** [comment]
We can close this issue. I used the basic boiler plate from your examples in a fresh new project and it works great. I had pulled it into a existing project and I see it required a lot more dependencies compared to the clean test version hence the errors.
