### ISSUE TITLE
[docs] Dockerizing a Custom Application

### ISSUE THREAD

**Issue by tsmiatacz-engi** [commercetools/merchant-center-application-kit#2102]
Aside from deploying to specific providers I would appreciate an example of how to properly run a Custom Application in a Docker container.

**Comment by adnasa** [comment]
Hey,
thank you for the message.

What are your use case and business value to Dockerize a Custom Application?
In general, a Custom Application consists of static files which can be served using any HTTP server or hosting provider.

One thing to consider, being an SPA you need some "routing in front" to always serve the `index.html`.
You can for sure Dockerize a Custom Application using a `node` server.

When you do so, remember to bundle the Custom Application and build.
We described this in detail here: https://docs.commercetools.com/custom-applications/deployment/production-build

**Comment by t-smiatacz** [comment]
Hello, thanks for your answer. We're doing this just for the sake of normalization in our workflow, this way our pipelines are consistent with other microservice projects. I think this is a pretty standard practice. 

We ended up using nginx docker image with some minimal configuration.

**Comment by emmenko** [comment]
> We ended up using nginx docker image with some minimal configuration.

Sounds good. If you feel like sharing your solution, feel free to open an issue to document a new deployment example and write the step-by-step documentation for it. 😉
