### ISSUE TITLE
Dynamically resolving environment properties

### ISSUE THREAD

**Issue by tsmiatacz-engi** [commercetools/merchant-center-application-kit#2107]
**Is your feature request related to a problem? Please describe.**

We are going to deploy our Custom Applications into a bunch of environments like stage, production etc. We went with an approach of dockerizing the app. The issue is, `env.production.url` property is hardcoded in the config file and then statically compiled - that means we need to create a separate image for each environment. 

**Describe the solution you'd like**

It would be much better if this property was resolved dynamically, eg. from ENV or anything else that would allow us to set it _in runtime_, not at the build phase.

**Describe alternatives you've considered**

For now we'll be using separate images but it's a bad pattern and it complicates our pipelines. Don't see any other solution unless there is some undocumented functionality.

**Comment by emmenko** [comment]
Hi, in the custom application config you can use environment variable placeholders. Have you read about it in the docs?

https://docs.commercetools.com/custom-applications/development/application-config#using-environment-variables

**Comment by tsmiatacz-engi** [comment]
Must've missed that but I also realized this isn't really a valid issue because the production build is just static content. Only way to access envirnoment variables would be on the server side.
