### ISSUE TITLE
[question] Checking permissions for resources

### ISSUE THREAD

**Issue by tsmiatacz-engi** [commercetools/merchant-center-application-kit#2114]
In the documentation there is a set of resources that we can check permissions to:
https://github.com/commercetools/merchant-center-application-kit/tree/main/packages/permissions#available-permissions

But these are basically only the resources I can access from MC by default. Now how should I approach checking permissions for other resources, eg. I'm making a custom application to manage State Machines and I want to disable edition for users that don't have "manage state machines" permission?

**Comment by adnasa** [comment]
Hey.
Thank you for your message.

This is a good question. In fact, this is something that we are working on at the moment, where we enable this feature. 
Our goal is that you will be able to specify the OAuth-scopes that your Custom Application requires.

There will be major changes related to this topic.
We recommend waiting for this feature to be released. If you are interested, we would like to invite you to test this feature before we go for the official release.

Hoping to hear from you.

Thanks in advance.

**Comment by t-smiatacz** [comment]
Hello, sounds good, I'd like that!

**Comment by emmenko** [comment]
Great, we'll get in touch once we have things ready. Thanks.

**Comment by emmenko** [comment]
Hi @tsmiatacz-engi , today we finally released a new milestone for Custom Applications with many new features, including the ability to define your own OAuth Scopes.

You can read more about it here: https://docs.commercetools.com/custom-applications/migrating-from-project-level-custom-applications

Don't hesitate to reach out to us if you have further questions:
* You can re-open this issue.
* You can open a GitHub discussion.
