### ISSUE TITLE
Audience problem when calling External API from custom applications

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#2115]
**Describe the issue**

We use this approach to call our external API from custom applications https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api

It works great for post and get requests, except for the case when we add ?query to the GET endpoint.

on the backend of external api we're checking session via createSessionAuthVerifier from the @commercetools-backend/express package.

when adding ?query it throws error: UnauthorizedError: jwt audience invalid.

The audience is set correctly and works great for all kind of requests / routes except when the route has any query param in the url (https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api#validating-the-json-web-token)

Are we doing something wrong? or it this is a bug? if it's a bug, could you guide when approximately it could be resolved?

**Comment by emmenko** [comment]
Ah good point. I think it's a bug. We'll try to get a fix out tomorrow.

cc @adnasa let's pair on this.
