### ISSUE TITLE
Localhost endpoints with Forward-to

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#2128]
**Describe the issue**

We're using forward-to api for authorizing requests in our external api as suggested in the doc:
https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api#proxying-requests-to-the-external-api

Just wonder if you have an approach for cases when forward-to is used with backend deployed on localhost. Right now the sdkAction library sends request to https://mc-api.europe-west1.gcp.commercetools.com/proxy/forward-to with attached url it needs to forward request to. And of course with endpoints located on localhost it does not work. Our current approach requires supporting different methods, one uses forward-to and one sends requests to localhost and works only on dev as a mock. it's not very convenient in development, so I'm thinking maybe you already tackled that issue some other way?

Just seeking your advice cause you probably developed many more custom apps and would be interesting to know how you're dealing with this.

(SUPPORT-11873)

**Comment by emmenko** [comment]
Thanks for reaching out to us, this is a great question.

Short answer: the only feasible approach at the moment that we recommend is to use a local tunnel, for example https://ngrok.com/. So your Custom Application uses the forward-to endpoint as usual and points the forward URL to the tunnel URL, which then serves your local running backend API.

See related issue: #1686
