### ISSUE TITLE
[Tooling] Future improvements

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#214]
While implementing a starter example #200 , we bumped into some issues that we would like to address in the near future. Those can be grouped into different topics:

## 👶 Easy to install starter example
The objective here is to have a basic example (like the one we have in `examples/starter`) that can be installed / bootstrapped with one single command.

I guess the classic example for that would be [CRA](https://facebook.github.io/create-react-app/).

```bash
$ npx create-mc-app my-app
```

Ideally we could create **templates** that you can install using `create-react-app`

```bash
$ npx create-react-app my-app \
  --scripts-version=@commercetools-frontend/mc-scripts \
  --template-starter 
```

For that to work we just need to restructure a bit the `mc-scripts` package and start supporting templates.

## 🧘‍♀️ Loosen dependency tooling
At the moment to develop an app, our own tooling is required, such as `mc-scripts`, `mc-http-server`. While this is per-se not a problem, it however forces users to use our opinionated environment like Webpack.

Ideally, people can choose whatever bundler or setup they like in order to develop the applications.

> There are currently some problems with using different bundlers (e.g. parcel) as they don't fully support yet `core-js@3`, which causes several problems on production bundles.

#### Actions
_Checklist of what needs to be done to achieve this goal_
- [x] add script to compile html #670 

## 🚀 Deploy everywhere
At the moment, we recommend to use our `mc-http-server` as it comes with a couple of built-in features like injecting runtime stuff into the `index.html.template`, provides security headers, etc.

Until now, I found two use cases that won't work out of the box with our current setup:
- **static website like Netlify**: we need to provide some scripts or something that would help generating the necessary setup
- **serverless functions like Now (v2)**: they run on Lambda functions, which means we can't just use a docker container but we need to upload specific files for each function

#### Actions
_Checklist of what needs to be done to achieve this goal_
- [x] can deploy to Now v2 #670 
  - [ ] documentation example
- [ ] can deploy to netlify
  - [ ] documentation example

**Comment by Freyert** [comment]
We've been exploring using Google Storage/S3 buckets as these are fairly common for customers to have easy access to when they want to deploy a custom app. Most of them deploy the static assets in S3 or Google Storage today, but the `mc-http-server` is still required.

It seems like it should be possible from looking at the `now.sh` the static generator creates. The only problem is that S3/Google Storage can't take wild cards and route them to a single file (nor really route files in general).

I would expect that by pulling the `index.html` which knows the location of all the other resources it should just pull all of those resources into the SPA. It seems though that after pulling `index.html` it starts pulling resources and then triggers a redirect to a new path, instead of just changing the path (without reloading the page) and having the React router change application state accordingly.

Are there known reasons why it would not be feasible to use S3/Google Storage?

**Comment by emmenko** [comment]
Hmm the wildcard is usually necessary for serving SPA, as all requests should be served by the `index.html`, which then renders the app and the history router browser kicks in.

I'm not sure that serving the app directly from a storage/cdn is feasible, as you still need some sort of router in front. I haven't looked into the S3/Google Storage approach yet, so I can't say much about what possible solutions there are with that.

Also, to consider that it's recommended for the apps (index.html) to be served with the security headers, especially the CSP.

Also, could you open an [issue here](https://github.com/commercetools/merchant-center-application-kit/issues/new?template=feature_request_deployment_examples.md) to describe this use case to use S3/Google Storage? It's easier then to keep track of it and tackle that properly.

Thanks, let me know if I can help you any further.

**Comment by emmenko** [comment]
FYI: a quick google search led to me this article, describing how to deploy a SPA to Google Storage.

https://www.verypossible.com/blog/how-to-deploy-a-single-page-application-to-google-cloud

The _First Deployment_ section is the interesting one, to configure the "website".

**Comment by emmenko** [comment]
Also important note mentioned in the article:

> One of the technical limitations of hosting your SPA on a GCP Bucket is your SPA is only accessible via HTTP. In order to protect your users you will need to setup a load balancer so you can serve your users via HTTPS (which will be covered in another blog post).
