### ISSUE TITLE
api-request-builder error: this.markMatchingVariants is not a function

### ISSUE THREAD

**Issue by Tormand** [commercetools/merchant-center-application-kit#2156]
When trying to get product projections by search(https://docs.commercetools.com/api/projects/products-search) and setting `markMatchingVariants:true` as an option, the api-request-builder causes an error:
`TypeError: this.markMatchingVariants is not a function` in `@commercetools/api-request-builder/dist/api-request-builder.umd.js:431`.

I'm using below action:
```
export const getProductsProjections = () => {
	var options = {
		staged: true,
		markMatchingVariants: true,
	}
	return sdkActions.get({
		mcApiProxyTarget: MC_API_PROXY_TARGETS.COMMERCETOOLS_PLATFORM,
		service: 'productProjections',
		options,
	})
}
```

And function to call it:
```
const getProductsProjections = () => {
	asyncDispatch(actions.getProductsProjections())
		.then((result) => {
			console.log(result)
			dispatch({ type: 'ok', payload: result })
		})
		.catch((error) => {
			dispatch({ type: 'error', payload: error })
			showApiErrorNotification({ errors: error })
		})
}
```
Am I doing something wrong when trying to use the productProjections service?

**Comment by emmenko** [comment]
Hi, I think you need to use the `service: 'productProjectionsSearch'`.

**Comment by Tormand** [comment]
Thank you @emmenko! That was the issue. :)
