### ISSUE TITLE
Build errors do not display correctly using `mc-scripts` to build

### ISSUE THREAD

**Issue by dgoemans** [commercetools/merchant-center-application-kit#2188]
**Describe the issue**
When using the MC application starter template with `mc-scripts`, any build errors generate the error message: `message.split is not a function`.

**To Reproduce**

1. Create a project from the starter template (`create-mc-app my-new-custom-application-project --template starter`)
2. Have a blatant compilation error (for example,  change `import loadMessages from '../../load-messages';` to `import . from '../../load-messages';` in `entry-point.js`)
3. Run `yarn build`
4. Note that the error message from the build output is `message.split is not a function` instead of indicating the error in your code.

**Expected behavior**

The build output displays the error in your code

**Screenshots**

**Additional context**
This seems to be related to an issue where `react-dev-utils` doesn't work with Webpack 5's stats. I have a PR incoming with a fix until it is supported.

**Comment by tdeekens** [comment]
Thanks for opening the issue. We actually ran into it internally too. Basically, noticing that (as you) `react-dev-utils` doesn't yet support `webpack@5`. We noticed that it's related to error message formats. Not sure if we can fix it on our side but interested in how you would approach it. 🙇🏼

**Comment by dgoemans** [comment]
@tdeekens, the approach that I did locally was to write some adaptation code in the `mc-scripts` interaction with `react-dev-utils`. This will work until `react-dev-utils` updates to using webpack 5.
PR is open here:
https://github.com/commercetools/merchant-center-application-kit/pull/2189

**Comment by tdeekens** [comment]
Cool. Let's continue discussing on the PR :)

**Comment by emmenko** [comment]
Fix has been released: `@commercetools-frontend/mc-scripts@20.0.3`.

Thanks again!
