### ISSUE TITLE
provide support for view/ manage orderedits scopes 

### ISSUE THREAD

**Issue by briantomkins** [commercetools/merchant-center-application-kit#2218]
SUPPORT REQUEST:

Customer would like to create an app to manage order edits
currently it is not a supported scope
https://docs.commercetools.com/custom-applications/main-concepts/user-permissions#general-permissions

Perhaps there is already a recommended approach?

**Comment by tdeekens** [comment]
Hi,

the current version of Merchant Center Custom Applications does not support custom permissions and all platform OAuth scopes. We will be working on a future version of Custom Applications which will support custom permissions so that one could define a `Manage Order Edits` or `View Order Edits` and assign the corresponding OAuth scope `{view,manage}_order_edits` to users with that permission. This is currently however not possible.

There is also no way to currently work around this restriction. In the current beta we only support the existing permission and resulting scopes.

**Comment by emmenko** [comment]
Would you be interested in getting early beta access when the feature is ready?

**Comment by briantomkins** [comment]
asked on support ticket

**Comment by csi-lund** [comment]
Hi sorry for the late response, yes early access would be nice but the feature was for a customer and we have existing custom applications for them, so just want to ask what will the beta access entail? Who is it granted to and how is it granted? What details would you need? Are there any breaking changes to the existing custom applications?

**Comment by csi-lund** [comment]
P.S thanks for remembering us and for letting us know!

**Comment by emmenko** [comment]
@csi-lund Hi, thanks for getting back to us.

The "beta access" in this case refers specifically to upcoming new features about Custom Applications that we're working on, mostly around management, setup, etc. One of these new features is the ability to use more OAuth Scopes. But I don't want to spoil too much at the moment.

When the time is ready we will get in touch with you and we can discuss the details.

> Are there any breaking changes to the existing custom applications?

Short answer: there are no planned breaking changes in regards to code/implementation. There are though some changes and migration steps required in terms of workflow, setup, etc.

Hope this is fine for you. We'll keep you posted.

**Comment by csi-lund** [comment]
Thanks, personally I'm interested, but I also want to run it past the customer to see if they want us to investigate as well for them, or they are okay with the current. Looking forward to seeing the fruits of your labour

**Comment by emmenko** [comment]
Hi @csi-lund , today we finally released a new milestone for Custom Applications with many new features, including the ability to define your own OAuth Scopes.

You can read more about it here: https://docs.commercetools.com/custom-applications/migrating-from-project-level-custom-applications

Don't hesitate to reach out to us if you have further questions by
* Re-opening this issue.
* Opening a GitHub discussion.
