### ISSUE TITLE
Custom Applications and GraphQL

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#2219]
**Describe the issue**

I'm currently trying to call the commercetools GraphQL API while in development mode of a custom application. I was following this guide: https://docs.commercetools.com/custom-applications/main-concepts/data-fetching#requests-to-graphql-apis. Is it possible that the code in this guide (including the <Query> tag) is deprecated? As it no longer seems to work.

**To Reproduce**
I used the following guide last week: https://docs.commercetools.com/custom-applications/getting-started/installing-a-starter-application. So I should have the correct versions.

This is what my package.json looks like, with the version numbers:
```"dependencies":

{ "@apollo/client": "^3.3.19", 
"@commercetools-frontend/actions-global": "20.0.1", 
"@commercetools-frontend/application-components": "20.0.1", 
"@commercetools-frontend/application-shell": "20.0.1", 
"@commercetools-frontend/assets": "18.5.4", 
"@commercetools-frontend/i18n": "20.0.1", 
"@commercetools-frontend/permissions": "20.0.1", 
"@commercetools-uikit/data-table": "^12.0.4", 
"@commercetools-uikit/data-table-manager": "^12.0.6", 
"@commercetools-uikit/flat-button": "^12.0.4", 
"@commercetools-uikit/icons": "^12.0.0", 
"@commercetools-uikit/spacings": "^12.0.0", 
"@commercetools-uikit/text": "^12.0.0", 
"@commercetools-uikit/text-field": "^12.0.6", 
"prop-types": "15.7.2", 
"react": "17.0.2", 
"react-dom": "17.0.2", 
"react-intl": "5.17.4", 
"react-redux": "7.2.4", 
"react-router-dom": "5.2.0", 
"redux": "4.1.0" }
,
"devDependencies":

{ "@commercetools-frontend/jest-preset-mc-app": "20.0.1", 
"@commercetools-frontend/mc-dev-authentication": "19.0.0", 
"@commercetools-frontend/mc-scripts": "20.1.1", 
"@formatjs/cli": "4.2.11", 
"@manypkg/cli": "0.17.0", 
"@testing-library/react": "11.2.6", 
"jest": "26.6.3" }
```
From the page I linked earlier the following code snippet no longer works:
```import React from 'react';
import

{ Query } from '@apollo/client/react';
import Text from '@commercetools-uikit/text';
import { GRAPHQL_TARGETS } from '@commercetools-frontend/constants';
import { FetchChannelQuery } from './channels.graphql';

const target = GRAPHQL_TARGETS.COMMERCETOOLS_PLATFORM;
const ChannelDetails = props => (
<Query
query={FetchChannelQuery}
variables={{
id: props.channelId,
locale: props.locale,
}}
context={{ target }}
>
{({ loading, error, data }) => {
if (loading) return 'Loading...';
if (error) return `Error! ${error.message}`;

return (
<Text.Headline as="h1">{`Channel: ${data.channel.name}`}</Text.Headline>
);
}}
</Query>
);
export default ChannelDetails;
```

It's giving me the error I've attached. The line mentioned refers to the <Query> element. The problem seems to be that "Query" is not exported by the Apollo package imported at the start of the file:

```import { Query }```

**Screenshots**
![image](https://user-images.githubusercontent.com/29213153/118839637-a6eaac00-b894-11eb-8145-bb1930b6b340.png)

{{SUPPORT-12354}}

**Comment by dogayuksel** [comment]
Hey,
Thank you for the message.

Looks like since apollo-client version 3, it needs to be imported as such:
`import { Query } from '@apollo/client/react/components';`

More details can be found on [this PR](https://github.com/apollographql/apollo-client/pull/6558) of the apollo-client repository.
I will follow up with the documentation change.
