### ISSUE TITLE
Cant able to login the localhost:3001/login

### ISSUE THREAD

**Issue by rakesh-v-sudo** [commercetools/merchant-center-application-kit#2222]
**After installing the packages doing npm start the login screen not allowing mw to go home page even I have valid CT account**

**To Reproduce**

1. npm start
2. navigate to localhost:3001/login
3. enter valid creds to login
4. Invalid email or password 
<img width="1111" alt="Screen Shot 2021-05-21 at 9 18 26 PM" src="https://user-images.githubusercontent.com/60186789/119164502-208fbf00-ba7a-11eb-8ab4-ac6f00ba2b60.png">

**Comment by tdeekens** [comment]
👋🏼 Hi, 

thanks for opening an issue. I just tried to reproduce this myself and can not. I can certainly login using the same login screen with my own account. 

Can you ensure that you're working against the right cloud using the `cloudIdentifier` of the custom application config? When in doubt you can inspect the network requests in the Dev Tools of your browser to see what MC API is used. You can also try to login in the Merchant Center of that environment to verify if your account is working and there is no typo?

Hope this helps. Have a nice weekend!

**Comment by rakesh-v-sudo** [comment]
Thanks for your quick help here, it really worked once when I change the cloudIdentifier to the respective region

@tdeekens
