### ISSUE TITLE
Using starter application for Merchant Center Custom Applications yields error.

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#2272]
I've tried to do our first Custom Application in the Merchant Center. Therefore I installed the starter application as described here:
https://docs.commercetools.com/custom-applications/getting-started/installing-a-starter-application

Problem:
After starting the development server with npm start and log in with my Merchant Center Username and password I get always this message:

"This is the logout page for local development.
Be aware that you might still have an active session as the cookie is assigned to a production domain (e.g. commercetools.com) which we can't unset from localhost. This is only a problem on local development and we intend fix this in the future."

If I delete the cookies this page will comes up again...
Do you have any hint here, how I get the "Hello World" page?

I've also looked here https://docs.commercetools.com/custom-applications/help-needed#development-login-does-not-work-on-chrome and the setting was already toggled on.

**Comment by emmenko** [comment]
Hi, I'm not sure we can do much about this unless we have a better understanding of the issue. As far as I know there are no current problems with the login.

Have you tried using another browser?

**Comment by Burgmayr** [comment]
Hi Nicola Molinari,
could I show you this issue via desktop sharing?

**Comment by emmenko** [comment]
You can attach a video/gif if you want to.

Have you also tried using another browser? If so, does the problem still occur?

**Comment by emmenko** [comment]
Closing, assuming this is not an issue anymore.

If you have further questions:
* You can re-open this issue.
* You can open a GitHub discussion.
