### ISSUE TITLE
Accessing Project Key in Custom Application Development

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#2282]
I have a question regarding the Custom Application in the Merchant Center. How can I access the project key in the React Development?

Background: We have the same custom application in other CTP projects. Depending on the project key I must access data in the different CTP project.
Is there any possibility (like an environment variable) to access the project key in the React website?

**Comment by emmenko** [comment]
I'm not sure I understand the question. The `projectKey` is always part of the URL/route, so you can always access it via the router.

Given the route is `/:projectKey/my-app`, the router has the query parameter `projectKey`. For example:
https://github.com/commercetools/merchant-center-application-kit/blob/0bfa16134450fb0699018b2210e0da904f646140/packages/application-shell/src/components/project-container/project-container.tsx#L77

Alternatively you can get the value from the application context:

```js
const projectKey = useApplicationContext(context => context.project.key)
```

**Comment by emmenko** [comment]
Closing, assuming this is not an issue anymore.

If you have further questions:
* You can re-open this issue.
* You can open a GitHub discussion.
