### ISSUE TITLE
User language changes not propagated to intl locale

### ISSUE THREAD

**Issue by gnerkus** [commercetools/merchant-center-application-kit#230]
**Describe the bug**
When the language is changed via the dropdown in the navigation bar, the locale field in `intl` is not updated.

**To Reproduce**

1. In any view within the MC, change the language via the dropdown.
2. Inspect the `intl` provider (via `props.intl` in any component using the HoC)
3. Inspect the `locale` field of the `intl` provider.

**Expected behavior**
The `locale` field of the `intl` provider should be the same as the app language.

**Screenshots**
`en` language
<img width="1376" alt="en-language-en-locale" src="https://user-images.githubusercontent.com/3065138/50514124-8ab7fb80-0a9c-11e9-9644-e5df3379a32f.png">

`de` language
<img width="1375" alt="de-language-en-locale" src="https://user-images.githubusercontent.com/3065138/50514129-91467300-0a9c-11e9-9d0b-c046c5c925ba.png">

**Additional context**
The bug was discovered when attempting to format prices using `intl.formatNumber`. The method uses the locale stored internally within `intl`.

**Comment by dferber90** [comment]
The language propagated through `props.intl.locale` is called "user language". The user language is set from the account settings:

![bildschirmfoto 2018-12-28 um 13 41 15](https://user-images.githubusercontent.com/1765075/50515660-547f7980-0aa6-11e9-8d1d-4aab042d1e85.png)

The language you are changing in the top there is referred to as "resource language", "data language" or "project data language".

The "user language" defines the language of the MC itself. It can only be one language which we have translations for in the MC. The translations are done by us.

The "resource language" defines the language in which that projects' data is shown (like a product name etc). It can be one of the languages set for that project. The translations are done by the MC user. 

I wrote a lengthy comment with great detail about the differences in https://github.com/commercetools/merchant-center-frontend/issues/4744#issuecomment-402542467, but I hope the TLDR above helps clarify things already.

**Comment by gnerkus** [comment]
@dferber90 The TL;DR does. Thanks.

I'm currently reading the ADR proposal.

I'll close this issue now.
