### ISSUE TITLE
Proxy to external API when using sso sign-in to mc

### ISSUE THREAD

**Issue by briantomkins** [commercetools/merchant-center-application-kit#2344]
We are calling a third party API, deployed on AWS through a proxy using actions.forwardTo.post method.
The API deployed on AWS is protected through Azure AD. We also have enabled MC SSO with the same Azure AD.

When I call the third party API, the proxy generates JWT token and inserts it in the request. In our case, this request fails with HTTP 401 with error -
Bearer scope="price.override" error="invalid_token" error_description="the token does not have a valid audience".

When we decoded the JWT token we saw that the aud property is set to the merchant center URL. We have set the X-FORWARD-TO header to the right audience we wanted to have setup.

See attached a screenshot of the decoded JWT token (Aud part)

See below code -
const result = await dispatch(
actions.forwardTo.post({
uri: 'https://XXXXXX.execute-api.eu-west1.amazonaws.com/priceOverride',
headers:

{ 'X-Forward-To': 'https://XXXXXXX.execute-api.eu-west-1.amazonaws.com/priceOverride', }
,
payload: lambdaInput
})
);

See : SUPPORT-13374

**Comment by emmenko** [comment]
Hey there, apologies for the late reply.

If you use `actions.forwardTo` you don't need to specify the `X-Forward-To` header, as it's implicitly done.

The token you have decoded seems to be the normal Merchant Center user session token, which has nothing to do with the proxy to external API.

You API should verify the "exchange token" with the Merchant Center API. Have you seen the documentation about it? https://docs.commercetools.com/custom-applications/main-concepts/proxy-to-external-api#authenticating-requests-from-the-external-api

We also recommend to use our `@commercetools-backend/express` package to simplify the token validation on your server.

Let us know if you have further questions, thanks.
