### ISSUE TITLE
CORS error after deploying application on AWS

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#2345]
We're working on some changes on the custom application in the merchant center, and after deploying a change to AWS it seems that some headers are being blocked.

After deploying it to AWS, and changing the link on the Settings > Custom Application, I face this header issue and I can't see my custom application running on CT.

![image](https://user-images.githubusercontent.com/29213153/129967778-f07782f5-82d8-4db0-82e9-e4c6bdd02d55.png)

It is working on our production environment but not for the new version I deployed following the exact same steps.

More info available @ {{SUPPORT-13370}}

**Comment by tdeekens** [comment]
Thanks for opening an issue. Are the origins the Custom Application tries to interact with configured as a CSP rule in the configuration as noted [here](https://docs.commercetools.com/custom-applications/development/application-config#headerscsp).

**Comment by emmenko** [comment]
Closing, assuming this is not an issue anymore.

If you have further questions:
* You can re-open this issue.
* You can open a GitHub discussion.
