### ISSUE TITLE
Reading environment variable from .env in React Custom MC app

### ISSUE THREAD

**Issue by bengalley-e2x** [commercetools/merchant-center-application-kit#2428]
### Discussed in https://github.com/commercetools/merchant-center-application-kit/discussions/2427

<div type='discussions-op-text'>

<sup>Originally posted by **bengalley-e2x** December  9, 2021</sup>
Hi there,

I'm trying to use an environment variable to read a public key from a .env file in my Merchant Center Custom App. 

For example:

In the `.env` (in the project root):

`REACT_APP_PUBLIC_KEY_TEST=foo`

In the component code:

`process.env.REACT_APP_PUBLIC_KEY_TEST`

returns `undefined` no matter what I do.

Usually the `REACT_APP_` prefix is required for using environment variables in this way, but I also tried with `MC_APP_` prefix as well as no prefix.

Is it possible to read environment variables in this way with the Custom MC App? 

Help much appreciated 🙏 

Thanks!</div>

**Comment by emmenko** [comment]
Hi, sorry for the late reply. I answered in the discussion thread. Closing this.
