### ISSUE TITLE
Custom Application configuration issues

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#2446]
We're trying to configure Custom Application served from S3 bucket with Cloudfront on our own AWS Account. We have issues with configuring lambda and we can't generate the code for it following your documentation.

https://docs.commercetools.com/custom-applications/deployment/example-deployment-aws-s3-cloudfront#update-aws-resources

In our case file lambda.js is not generated using command ```mc-scripts compile-html \
--transformer ./config/transformer-aws.js```.

Can you provide us more detailed information or link to documentation where it is described more in depth how exactly we need to generate the lambda code?

{{SUPPORT-15032}}

**Comment by emmenko** [comment]
Hi, when using the `compile-html` command with a transformer, the transformer function should be responsible for generating any config or file necessary for your specific deployment setup.

I assume the `transformer-aws.js` is the same as the one documented here? https://docs.commercetools.com/custom-applications/deployment/example-deployment-aws-s3-cloudfront#generate-lambda-function-using-a-transformer-function

If so, you will notice at the end of the transformer that the `lambda.js` is written to the file system

```js
fs.writeFileSync(
  path.join(rootPath, 'lambda.js'),
  generateLambda(setHeaders),
  { encoding: 'utf8' }
);
```

The main purpose of the transformer is to set the security headers to your hosting configuration. Specifically, the CSP header is generated based on the runtime information so it can't be statically defined. Hence the need for the transformer.

However, we recently introduced a new CLI option `--inline-csp` to the `compile-html` command. If you pass this option, the CSP header will be injected inline into the `index.html`. With this, you might not need the transformer anymore (unless you have other logic tight to that).
Therefore, if you use `--inline-csp` and don't need the transformer anymore, you can defined the `lambda.js` file statically (and not generated).

Hopefully this helps you solving the problem. Let us know if you have any more questions.

**Comment by leszek-niewiadomski** [comment]
@emmenko Issue we are facing it that running this command: 
```
npm start mc-scripts compile-html \
  --transformer ./config/transformer-aws.js
```
Don't create the output file lambda.js. We can't properly set it up on the AWS side and encounter redirect issues.

Our custom application redirects from our custom domain to out commercetools instance for login form and then after successful login it stays on the commercetools domain. It don't redirect back to our application domain.

testdomain.com sends request to https://mc-api.testdomain.com and after two failed requests it's redirecting back to `https://mc-api.us-central1.gcp.commercetools.com/graphql`.

We don't have such domain mc-api.testdomain.com and we haven't seen anywhere in the documentation need for setting such.

What we would like to achieve is to have our custom application written and server on our custom domain.

Can you forward us to proper solution?

**Comment by emmenko** [comment]
Closing, feel free to reopen if you need more help.
