### ISSUE TITLE
Lazy load translations bundles automatically in Custom Applications

### ISSUE THREAD

**Issue by CarlosCortizasCT** [commercetools/merchant-center-application-kit#2447]
**Background**
When working with new Custom Applications, developers are required to provide the translations to the [ApplicationShell](https://docs.commercetools.com/custom-applications/components/application-shell) component. Both an object or a list of promises can be provided, the latter being preferred when the user needs to use several languages so the component can lazy-load only the translations needed for the navigation language.
There is [this documentation](https://docs.commercetools.com/custom-applications/development/translations#using-the-messages-in-the-application) explaining how to correctly generate the promises list but it seems a boilerplate code every Custom Applications developer must write.

**Describe the solution you'd like**
Since the [process of generating the translations bundles](https://docs.commercetools.com/custom-applications/development/translations#extracting-messages-for-translations) is configured to output its result in a predefined and known directory (`/src/i18n/data/*`), the `ApplicationShell` component could have the default behaviour of lazy-load the right translation bundle.
We could keep the [applicationMessages](https://docs.commercetools.com/custom-applications/components/application-shell#properties) property for more elaborated use cases a developer might find.

**Comment by emmenko** [comment]
Thanks!

To clarify one thing maybe: translations are considered optional. Technically you can use a Custom Application without i18n or translations. It's up to you to hardcode strings or to have them organized in messages.

I think we can maybe  enable this "lazy load" behavior only when the `i18n` folder is defined (and of course the `applicationMessages` prop is not provided).

One other thing to consider also is which locales should be "lazy loaded".

Let me know then how you would like to proceed.

**Comment by CarlosCortizasCT** [comment]
Thanks for the clarification.

My idea would be to add a new property to the [applicationConfig](https://docs.commercetools.com/custom-applications/development/application-config) file where developers could set the available languages in their project (if they are using translations).

Let's say we have something like this:
```
{
  "name": "Avengers app",
  "entryPointUriPath": "avengers",
  "cloudIdentifier": "gcp-eu",
  "env": {
    "production": {
      "url": "https://avengers.app"
    }
  },
  "availableLocales": ["en-GB", "en-US", "de", "es"]
}
```
As applicationConfig is passed to the `ApplicationShell` component in the `environment` property, we can then check as you suggested so, if we don't receive anything in the `applicationMessages` property but we do have a list in the new environment property, we then create the _loadMessages_ function with the configured `availableLocales`.

This would imply developers need to set that new property but we could also help with that.
As we are providing a [npm script](https://github.com/commercetools/merchant-center-application-kit/blob/main/application-templates/starter/package.json#L13) to generate translations bundle in the [starter kit](https://github.com/commercetools/merchant-center-application-kit/tree/main/application-templates/starter), maybe we can extend that script to automatically populate the new property in the `custom-application-config.json` file after the translations file are created.
This way, we make sure the `availableLocales` are in sync every time the developer updates the translations bundles.

Other option would be to make something like this at application start (when developing locally) and when building the app.

Does this make sense to you?

**Comment by tdeekens** [comment]
👋🏼 Thanks for bringing this up. I also like the idea of a configuration property. It allows us also to possibly have a bit more control while removing boilerplate. Right now any internal application has pretty much the same function determining which translation bundle to load as a dynamic import. It works well but comes at the usual downside of duplication in that for instance adding a new translation impacts many pieces. 

Upon fist thought is that the only downside I see is that we'd remove some flexibility with the configuration property. As right now a developer of Custom Applications could load the translations from anywhere. After only from a location we determine. Which one could get around with by ensuring that files are located where expected. That is something we should likely then verify.

**Comment by emmenko** [comment]
> Upon fist thought is that the only downside I see is that we'd remove some flexibility with the configuration property. As right now a developer of Custom Applications could load the translations from anywhere. After only from a location we determine. Which one could get around with by ensuring that files are located where expected. That is something we should likely then verify.

I think the idea is that this behavior is used only when the `applicationMessages` prop is not provided. If you use that prop, then you can do whatever you want.

**Comment by CarlosCortizasCT** [comment]
Thanks for your comments 👍 

Regarding translations location, the idea is to keep the `applicationMessages` property as it exists today so developers who might locate them in a different folder where we expect them, would still have the chance to implement the loader as they currently do.
Another idea would be to have the new property hold de files paths instead of the locales (idk if we could have webpack problems trying to import a complete dynamic path).

On the check for the `core.json` and `en.json` to exist, where do you think we should implement it? Should it be something to check when starting the application locally and upon building it?

**Comment by emmenko** [comment]
> where do you think we should implement it? Should it be something to check when starting the application locally and upon building it?

Yes I would say so. Check the `mc-scripts` package, there we have a `start` and `build` command files.

**Comment by CarlosCortizasCT** [comment]
Maybe I'm missing something, but I think this check should only be done when developers will use this new automatic lazy-loading translation feature. So, if they are using their custom loader (as Tobias was highlighting), those files may not exist (maybe they located the translations files in a different directory or system) and then, the startup/build process would fail (maybe we don't want to fail but only displaying a warning message).

I guess that, for this check to be implemented correctly, perhaps we can populate the new property automatically at startup/build time and then use the information in the `ApplicationShell` component so, if the developer didn't provide anything in the  `applicationMessages` property and there are no languages in the new property (`availableLocales`), then we would be sure that something is not correctly configured and do something about it (ex: show an error modal with an error explanation and a link to the translation documentation).

I don't know if I'm complicating things more than I should or missing something so please let me know what are your thoughts.

**Comment by emmenko** [comment]
Yes that's a good.

We should probably avoid trying to detect if a prop is used or not, as we would need to parse and analyze the source code (or the production bundle).

Ensuring that the `src/i18n` folder is present (even if you are not using the "lazy load" feature) is something we can decide to always do. At the end it's just creating a folder + bunch of empty files.

I don't consider this an issue to be honest, as it's not breaking anything. I think Cypress does also something similar.

The alternative is to somehow detect if the e.g. `en.json` file is present in the file system, when using dynamic imports. At the end, this is the main challenging part: to know which JSON files should be loaded (for code splitting).

**Comment by CarlosCortizasCT** [comment]
> The alternative is to somehow detect if the e.g. en.json file is present in the file system, when using dynamic imports. At the end, this is the main challenging part: to know which JSON files should be loaded (for code splitting).

Yes, my point is that locales defined in the new `availableLocales` property would imply that there is a file present for every locale.
If we have the previous fake example:
``` 
{
  "name": "Avengers app",
  "entryPointUriPath": "avengers",
  "cloudIdentifier": "gcp-eu",
  "env": {
    "production": {
      "url": "https://avengers.app"
    }
  },
  "availableLocales": ["en-GB", "en-US", "de", "es"]
}
``` 
we would assume we have this translations files:
```
/custom-application-config.json
/src
/src/i18n
/src/i18n/data
/src/i18n/data/core.json
/src/i18n/data/en-GB.json
/src/i18n/data/en-US.json
/src/i18n/data/de.json
/src/i18n/data/es.json
```

The lazy loader helper will try to load those files and, if it doesn't find the needed one we might decide to use the default one instead and show a warning in the browser console or event raise a modal letting the consumer know he does not have the needed translation.

This is the the implementation of the idea:
```
const loadMessages = (availableLanguages = []) => lang => {
  const isAvailableLanguage = availableLanguages.includes(lang);
  
  return import(
    `../../i18n/data/${isAvailableLanguage ? lang : 'core'}.json` /* webpackChunkName: "app-i18n-bundle" */
    )
    .then(i18nModule => i18nModule.default)
    .catch(error => {
      console.warn(
        `Something went wrong while loading the app messages for ${lang}`,
        error
      );

      return {};
    });
};
```
_I'm still missing how to correctly build the path as the first path in the example is tied to the starter template structure_.

Do you think this would be enough or we need to ensure the files existence any other way?

**Comment by CarlosCortizasCT** [comment]
I've created a PR so I can begin moving forward because I think we already have a common ground here.

**Comment by tdeekens** [comment]
> I think we can maybe enable this "lazy load" behavior only when the i18n folder is defined (and of course the applicationMessages prop is not provided).

Alright. If you want to keep both ways of a prop which builds a bit more on convention then and one which gives full flexibility then my concern is invalid. Maybe over time we can actually see if we can e.g. drop the loader based prop if people don't need its flexibility. 

> Currently, when a develop adds a new language to a Custom Application, he has to go to his languages loader helper function to add a new import statement. With this new approach it is kind of similar, but he only has to add the language locale to the new property.

Yes, and e.g. for us internally we have the same loader code in every of 7-8 applications.

**Comment by CarlosCortizasCT** [comment]
We found some issues while trying to implement this requirement which leads to a solution which does not add significant value over the current situation.

As there are already a discussion opened about how to generally improve the way translations are consumed at runtime, we're closing this issue and help moving forward that discussion.
