### ISSUE TITLE
Undeclared dependency in babel-preset-mc-app :  @babel/plugin-proposal-private-methods

### ISSUE THREAD

**Issue by nkuehn** [commercetools/merchant-center-application-kit#2461]
**Describe the issue**

I tested switching a repository that makes use of `@commercetools-frontend/babel-preset-mc-app` to yarn PnP, a first runtime error I got was that the Babel preset package uses but does not declare `@babel/plugin-proposal-private-methods`

**To Reproduce**

1. check out the commercetools-docs-kit repo
2. switch `nodeLinker` in `.yarnrc.yml` to `pnp`
3. `yarn install`
4. `yarn test`

**Screenshots**

```
[BABEL] /Users/nikolauskuhn/GitHub/commercetools-docs-kit/setup-test-framework.js: @commercetools-frontend/babel-preset-mc-app tried to access @babel/plugin-proposal-private-methods, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

    Required package: @babel/plugin-proposal-private-methods
    Required by: @commercetools-frontend/babel-preset-mc-app@npm:20.12.3 (via /Users/nikolauskuhn/GitHub/commercetools-docs-kit/.yarn/cache/@commercetools-frontend-babel-preset-mc-app-npm-20.12.3-29e2161973-43991a5167.zip/node_modules/@commercetools-frontend/babel-preset-mc-app/)
```

**Additional context**

It's not urgent or blockings something.  Just the result of a try how realistic using PnP is already.

**Comment by tdeekens** [comment]
👋🏼 Thanks for opening the issue.

We've also briefly experimented with yarn PnP but went for "regular" usage while migrating to yarn@3 without it. As much as we like PnP it felt almost a bit too radical to be compatible with the existing Node.js ecosystem (personal opinion). Maybe we'll evaluate it another time again.
