### ISSUE TITLE
Can't use env var for entryPointUriPath?

### ISSUE THREAD

**Issue by jtabone16** [commercetools/merchant-center-application-kit#2470]
The docs don't say you can't do that, but I'm hitting an error when trying to run the app locally. It's kinda necessary for our use case to have dev and prod versions of our custom app. We're using env vars for production.applicationId and production.url and I'm not seeing issues with those yet.

<img width="1078" alt="Screen Shot 2022-02-04 at 10 04 07 AM" src="https://user-images.githubusercontent.com/3768829/152580050-fc67eca5-6313-42b0-817a-e411702ee7a0.png">

**Comment by CarlosCortizasCT** [comment]
Hello @jtabone16,

Thanks for spotting this problem regarding the `entryPointUriPath` application configuration.

You’re right it is allowed to use environment vars in the configuration but we currently have a validation for that field which is not taking into account this kind of values.
We are going to update this validation so we allow this use cases.

**Comment by emmenko** [comment]
Released in `v21.0.1`.
