### ISSUE TITLE
How to use CT's Sentry package in custom app

### ISSUE THREAD

**Issue by jtabone16** [commercetools/merchant-center-application-kit#2478]
The docs for the org level app don't include a link to [CT's Sentry package](https://www.npmjs.com/package/@commercetools-frontend/sentry). I assume it should work with org level apps?

Furthermore, there are no examples on how to initialize Sentry. Do I call `boot`? After calling [setupGlobalErrorListener](https://docs.commercetools.com/custom-applications/api-reference/commercetools-frontend-application-shell#setupglobalerrorlistener)?

**Comment by CarlosCortizasCT** [comment]
Hello @jtabone16,

Thanks for reaching out regarding your question about using Sentry package from a Custom Application.

Actually, if you used the [starter template](https://docs.commercetools.com/custom-applications/getting-started#installing-a-starter-template) we provide for creating new Custom Applications you should already have the integration in place and there's no need to explicitly use the Sentry package.
The only think that might be missing is the configuration to activate the Sentry integration which is done by setting your own Sentry URL in the `custom-application-config` file (should be in the root folder of your Custom Application).

You should add a new attribute called `trackingSentry` to the `additionalEnv` configuration.
[Here](https://docs.commercetools.com/custom-applications/api-reference/application-config#additionalenv) you have the related documentation on configuring the additional environment properties.

Example:
![image](https://user-images.githubusercontent.com/97907068/153201326-40b0ba1e-cf57-4632-8a6b-e0d8d1d29a76.png)

**Comment by jtabone16** [comment]
thanks! got it working :)

**Comment by emmenko** [comment]
You should be able to use env placeholders in the config file.

**Comment by jtabone16** [comment]
It seems like the [env needs to be sent](https://docs.sentry.io/product/sentry-basics/environments/?utm_source=google&utm_medium=cpc&utm_campaign=11194763167&utm_content=g&utm_term=&device=c&gclid=CjwKCAiA6Y2QBhAtEiwAGHybPbE87f1lV0x60zVpff3ZRQDQly24rrQSn16_wJtZydHUAwYn6Gg80xoC4-cQAvD_BwE&gclid=CjwKCAiA6Y2QBhAtEiwAGHybPbE87f1lV0x60zVpff3ZRQDQly24rrQSn16_wJtZydHUAwYn6Gg80xoC4-cQAvD_BwE#creating-environments) with the event being tracked.

Will I need to somehow explicitly set that env tag when sending events? Or would setting an env var handle this?

**Comment by emmenko** [comment]
Ah sorry I misread your previous question.

Currently the `environment` option is pre-configured

https://github.com/commercetools/merchant-center-application-kit/blob/03972cc4769c92a9c86881c0aab8a2f8ce2a84a3/packages/sentry/src/sentry.ts#L79

The `env` option comes from the application environment (`development`, `production`)

https://github.com/commercetools/merchant-center-application-kit/blob/03972cc4769c92a9c86881c0aab8a2f8ce2a84a3/packages/application-config/src/process-config.ts#L54-L55

The `location` is the `cloudIdentifier`.

So the results would be something like `production-gcp-eu`, etc.

**Comment by emmenko** [comment]
Does that work for you or do you have other use cases / requirements in mind?

**Comment by jtabone16** [comment]
@emmenko hmmm MC_APP_ENV will be `production` for both of our deployed apps though right? So there would be no way to differentiate errors from the two in Sentry

**Comment by emmenko** [comment]
Yes that's true. I mean you could always configure search/filters to differentiate errors from one app or the other. For example by matching the entryPointUriPath

<img width="287" alt="image" src="https://user-images.githubusercontent.com/1110551/153267781-3d974647-e8cc-4acf-943a-6302d9737be9.png">


Alternatively, I think you can use 2 different Sentry projects, one for the "development" app and one for the "production" app.

You can then pass the Sentry DSN to the `trackingSentry` option using environment placeholders.

**Comment by jtabone16** [comment]
oh good point on entryPointUriPath! I'll just do that :) Thanks for the quick responses

**Comment by emmenko** [comment]
Great, thanks for providing good feedback on other use cases.

So far we have primarily used Sentry for our main applications so we have mainly our own use cases 😅

**Comment by mmaltsev-ct** [comment]
Closing the issue, since the problems seem to be resolved. @jtabone16 please feel free to reopen the ticket in case you have any questions.
