### ISSUE TITLE
[Testing] Add visual regression tests

### ISSUE THREAD

**Issue by montezume** [commercetools/merchant-center-application-kit#248]
Now that UI-Kit has a fairly mature visual regression testing setup, we should look into adding some basic visual regression tests to `ApplicationShell`. We can use a lot of the same setup that we did in UI-Kit, and we can use application-shell test-utils as well.

**Comment by emmenko** [comment]
Now that we started adding UI components here as well  #323 (besides in ui-kit) we should look into setting this VRT here as well, which can also be used for other packages (e.g. AppShell).

As @montezume pointed out though, we would have to think about the setup with the Percy integration, as we don't want to run VRT for every commit in this repo.

I guess one option might be to check the files changed within a commit and run Percy only in those files/folders are whitelisted. However, we would probably need to make the Percy GitHub check _non required_.

**Comment by montezume** [comment]
I'm working on this now

**Comment by emmenko** [comment]
Done in #375
