### ISSUE TITLE
Problem with reading user input when `create-mc-app` executed in Node v14

### ISSUE THREAD

**Issue by kark** [commercetools/merchant-center-application-kit#2484]
Hey everyone 👋 
I'm just learning the ropes here but I encountered a problem so I thought about reporting that.
I hope you don't consider it too forward that I make a PR with changes that seemed to be fixing that issue for me. 

**Describe the issue**
I noticed that in case of executing `create-mc-app` script in node 14 user’s input for `entryPointUriPath`:
```js
// packages/create-mc-app/src/parse-arguments.js
const answerEntryPointUriPath = await question(
    `Provide the Custom Application entryPointUriPath (default "${randomEntryPointUriPath}"): `
  );
```
 and `initialProjectKey`
```js
// packages/create-mc-app/src/parse-arguments.js
const initialProjectKey = await question(
    `Provide the initial project key for local development: `
  );
```
 is not stored but resolves to `undefined`. As a result the script fails silently.

Sidenote:
- `create-mc-app` executed with variables predefined via flags like 
```bash
npx @commercetools-frontend/create-mc-app \
  my-new-custom-application-project \
  --template starter \
  --entry-point-uri-path foo \
  --initial-project-key bar
```
works as expected.
- `create-mc-app` executed in Node v16 and Node v17 works as expected.

**To Reproduce**

Depending on how Node is installed in your system switch to Node v14 (in case of using `nvm` run `nvm use 14`).
Proceed with instructions of [installing a starter template](https://docs.commercetools.com/custom-applications/getting-started#installing-a-starter-template).

**Comment by emmenko** [comment]
Hi @kark , I tried reproducing this issue but I don't see the problem. The values are correctly set.

Maybe we can have a look at it together...
