### ISSUE TITLE
Custom Application - Getting Started (Package installation, starting local dev server)

### ISSUE THREAD

**Issue by donald-labajo-wimp2warrior** [commercetools/merchant-center-application-kit#2486]
I tried out installing the starter template for the custom application, based on the documentation `https://docs.commercetools.com/custom-applications/getting-started`.

**1.** Upon executing the `npx @commercetools-frontend/create-mc-app my-new-custom-application-project --template starter`, I encountered errors during the installation of the dependencies:
[2022-02-09T04_02_45_177Z-debug (CREATE-MC-APP).txt](https://github.com/commercetools/merchant-center-application-kit/files/8089699/2022-02-09T04_02_45_177Z-debug.CREATE-MC-APP.txt)

**2. (A).** I retried installing the packages using `npm install --force` && `npm install --legacy-peer-deps`. Both allowed the dependencies to be installed.
**2. (B).** Downgrading to eslint@7.32.0 (from version 8.7.0) also solved the packages installation problem.

**3.** Running `npm start` will then lead to errors:
[2022-02-09T08_29_34_140Z-debug (NPM START).txt](https://github.com/commercetools/merchant-center-application-kit/files/8089701/2022-02-09T08_29_34_140Z-debug.NPM.START.txt)

Running on node v.14.19, npm v.8.1.2, Windows 10.

**Comment by donald-labajo-wimp2warrior** [comment]
Apologies for the very late reply. Been quite preoccupied.
Thank you! Also, is there an ETA for the new app-kit version?

**Comment by CarlosCortizasCT** [comment]
Hello @donald-labajo-wimp2warrior,

We've just released a new version of app-kit where the issue you found is fixed.

Please, ensure you use this new version when running the command again adding the _latest_ keyword to the `create-mc-app` command:

```
npx @commercetools-frontend/create-mc-app@latest my-new-custom-application-project --template starter
```

You should see that `create-mc-app` version used is `21.1.0`.

Thanks.

**Comment by donald-labajo-wimp2warrior** [comment]
Hello again. I was able to install the the dependencies flawlessly this time. however, when I keyed in `npm start`, I got this error:

![image](https://user-images.githubusercontent.com/93166799/155918739-4e291c08-9a40-4796-a476-9947b17f8750.png)

**Comment by emmenko** [comment]
Hi @donald-labajo-wimp2warrior , could you share a bit more info about your OS environment?

For example:
* Node.js version
* Windows version

That would help us debugging the issue. Thanks.

**Comment by donald-labajo-wimp2warrior** [comment]
Node: 16.13.2
Windows 10 Pro
NPM 8.1.2

Also, I tried using node version 14.19.0 and i got this error log:
[2022-02-28T12_06_31_550Z-debug.log](https://github.com/commercetools/merchant-center-application-kit/files/8153169/2022-02-28T12_06_31_550Z-debug.log)

**Comment by CarlosCortizasCT** [comment]
Hello @donald-labajo-wimp2warrior,

We found the root of the problem which led to an error when trying to start the Custom Application locally in a Windows machine and released a new [`mc-scripts` package version](https://github.com/commercetools/merchant-center-application-kit/releases/tag/%40commercetools-frontend%2Fmc-scripts%4021.1.2) (**21.1.2**) which addresses this issue.

You can update the dependency in your current Custom Application or you can create a new one if you were just starting.

Please, let us know if you find any other blocking issue.
