### ISSUE TITLE
custom application configuration -- entryPointUriPath uniqueness

### ISSUE THREAD

**Issue by molly-jones** [commercetools/merchant-center-application-kit#2493]
**Describe the issue**

The uniqueness of the entryPointUriPath in the new org level custom application configuration does not seem to be limited to within one organization. 

For example, when configuring the custom application [MC GraphQL Explorer](https://github.com/commercetools/merchant-center-graphql-explorer), the [constant.js file](https://github.com/commercetools/merchant-center-graphql-explorer/blob/main/src/constants.js) holds the entry point uri path. However, when we try to configure this app in our organization, we receive an error that this path is not unique and is already in use (the app is installed on a different organization already). 

It seems the uniqueness should be limited to the organization rather than global use. 

We did check all of the projects in our organization to ensure the application was not still configured the old way on some project. It was not. 

**To Reproduce**

1. Go to 'Settings > Custom Applications'
2. Click on the redirect to new 'Accounts > Organizations' to manage Custom Applications at org level. 
3. Configure application
4. See error screenshot
![Screen Shot 2022-02-23 at 11 02 35 AM](https://user-images.githubusercontent.com/69007224/155362053-16c1d795-0e4d-4217-89b5-58838263d1a8.png)

**Expected behavior**

Expected that the app will be configured with the correct entry point uri path that is not already in use within the organization. 

**Screenshots**

**Additional context**

The organization Support is using is called "Platform Support" on GCP-EU. 
The organization that currently is successfully using the GraphQL Explorer custom app is called "commercetools" on GCP-EU.

**Comment by emmenko** [comment]
> The uniqueness of the entryPointUriPath in the new org level custom application configuration does not seem to be limited to within one organization.

That's correct, the restriction applies to the cloud region, so across all organizations, just like the platform `project_key`.

See https://docs.commercetools.com/custom-applications/api-reference/application-config#entrypointuripath

**Comment by emmenko** [comment]
If you want to use the explorer app to other organizations, this is currently not possible.

However, we're working on enabling this as part of the Custom Applications roadmap.

**Comment by emmenko** [comment]
> However, we're working on enabling this as part of the Custom Applications roadmap.

@molly-jones This feature is now available and it allows to install a Custom Application across multiple organizations that the user owns. As we are rolling out this feature to selected users first, if you are interested in this functionality let us know and we will enable it for your user/organization.
