### ISSUE TITLE
Help with axios requests to /shopping-lists

### ISSUE THREAD

**Issue by briantomkins** [commercetools/merchant-center-application-kit#2552]
I understand the login flow has changed with v21, but without that cookie, what technique do we use to make axios requests to /shopping-lists while sending the token.

Note in v21 after logging in we do have the token in sessionStorage. This is how the extension knows we are logged in and doesn’t ask us again.

I have attached the custom-application-config.json after upgrading to v21 for you to look at. If you would like access to the MC Extension git repository please let me know.

SUPPORT-16000

**Comment by emmenko** [comment]
Hi 👋,

If you use your own HTTP client you would need to make sure you send the necessary HTTP headers.

For local development, there is no cookie header anymore. Instead the session token is stored in `sessionStorage` and sent with the requests via the `Authorization` HTTP header.

```
Authorization: Bearer <sessionToken>
```

See example here for the Apollo client configuration:

https://github.com/commercetools/merchant-center-application-kit/blob/df1c8cc487d9ad550236d1666bb46dcabc329620/packages/application-shell/src/apollo-links/header-link.ts#L109-L111



FYI: I created a follow up task for us to document this use case a bit more (#2553 ).

**Comment by emmenko** [comment]
PS: in production we use cookies, so the request should still be configured to send the cookies (e.g. `credentials: include`).

**Comment by emmenko** [comment]
Hi 👋

We released better support for using custom HTTP clients. Please refer to the release note and follow the links to the related documentation parts.
https://docs.commercetools.com/custom-applications/releases/2022-08-05-support-for-configuring-custom-http-clients
