### ISSUE TITLE
CLI `config:sync` command fails to update `.ts` version of the config file

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#2560]
**Describe the issue**

Using the CLI command `config:sync` may result in creating a new Custom Application. After that, the `applicationId` value in the Custom Application config file is updated with the newly created ID.

If the config file is a `.ts` file, the CLI fails as the file cannot be properly parsed.

**To Reproduce**

1. Update the config file to be a `.ts` file.
2. Change the `entryPointUriPath` to something random, so that a new Custom Application will be created.
3. Run the `mc-scripts config:sync` command and follow the prompts.
4. The CLI fails with a `SyntaxError`.

```
SyntaxError: /path/to/project/custom-application-config.ts: Unexpected token, expected "from" (2:12)

  1 | import { entryPointUriPath, PERMISSIONS } from './src/constants';
> 2 | import type { ConfigOptions } from '@commercetools-frontend/application-config';
    |             ^
  3 |
  4 | const config: ConfigOptions = {
```

**Expected behavior**

The CLI command works also for `.ts` files.

**Additional context**

Parsing the `.ts` file can be easily solved by making sure the Babel transform uses the typescript plugin. However, writing the updated AST to the config file results in loosing the TS syntax, as Babel transformed the TS to JS when parsing the AST.

Ideally, when parsing/writing `.ts` files we should use a TS parser that preserve the syntax.

If this is not possible, we would need to drop this functionality and print out to stdout the instructions to update the `applicationId`.

**Comment by Rhotimee** [comment]
As previously discussed, we will drop the functionality and display the instructions to update the application instead.
