### ISSUE TITLE
Permission issue while accessing custom applications with custom entry-point URIs.

### ISSUE THREAD

**Issue by michaelashe** [commercetools/merchant-center-application-kit#2566]
This is wrt to configuring the custom applications in Merchant center.

As we are now having custom applications set up at organization level, we have modified the entryPoint URI from its default value “custom-objects“ to “custom-objects-<env name>-<region>“ for the custom-objects Custom Application. For eg. custom-objects-uk-dev.

Ever since we made this changes, the custom-application does not load and shows a permission error on screen.

We have tried modifying the oAuthScopes in the custom-application-config.json file, but that didnt help us.
![image-1](https://user-images.githubusercontent.com/29213153/164762042-f14b5e3e-f37d-4698-a275-5a1b29b2370f.png)

Could you please help us with this?

{{SUPPORT-16239}}

**Comment by ManjushaPillai** [comment]
Please find attach routes.js file that will give you an idea on how routes are configured. If you need more information please let us know.
[https://jira.commercetools.com/servicedesk/customershim/secure/attachment/110403/110403_routes.js?fromIssue=138729](url)

**Comment by emmenko** [comment]
@ManjushaPillai Hi,

The link you provided seems broken or not existent. Please also avoid linking to internal documents.

I would suggest to copy/paste the code of the file you want to share as a comment here (using code block for proper formatting), or take a snapshot of the file.

Thanks

**Comment by ManjushaPillai** [comment]
Hi @emmenko - Apologies!
Hopefully you will be able to see the file now

[routes.txt](https://github.com/commercetools/merchant-center-application-kit/files/8699292/routes.txt)

Thanks

**Comment by ManjushaPillai** [comment]
Also, copy-pasting the route.js file here for you:

import React from 'react';
import PropTypes from 'prop-types';
import { FormattedMessage } from 'react-intl';
import { Route, Switch } from 'react-router-dom';
import { useQuery } from '@apollo/react-hooks';
import { useIsAuthorized } from '@commercetools-frontend/permissions';
import LockedDiamondSVG from '@commercetools-frontend/assets/images/locked-diamond.svg';
import { MaintenancePageLayout } from '@commercetools-frontend/application-components';
import CustomObjectsList from './components/custom-objects-list';
import CreateCustomObject from './components/create-custom-object';
import CustomObjectDetails from './components/custom-object-details';
import ContainerList from './components/container-list';
import CreateContainer from './components/create-container';
import ContainerDetails from './components/container-details';
import GetContainers from './components/get-custom-objects.rest.graphql';
import { ContainerProvider } from './context';
import { CONTAINER, PERMISSIONS } from './constants';
import { messages } from './messages';

const PageUnauthorized = () => (
  <MaintenancePageLayout
    imageSrc={LockedDiamondSVG}
    title={<FormattedMessage {...messages.accessDeniedTitle} />}
    paragraph1={<FormattedMessage {...messages.accessDeniedMessage} />}
  />
);
PageUnauthorized.displayName = 'PageUnauthorized';

const ApplicationRoutes = ({ match }) => {
  const canManageProducts = useIsAuthorized({
    demandedPermissions: [PERMISSIONS.Manage],
  });
  const canManageOrders = useIsAuthorized({
    demandedPermissions: [PERMISSIONS.Manage],
  });
  const canManageCustomers = useIsAuthorized({
    demandedPermissions: [PERMISSIONS.Manage],
  });
  const canManageCustomObjects =
    canManageProducts && canManageOrders && canManageCustomers;

  const { data, loading } = useQuery(GetContainers, {
    variables: { limit: 500, offset: 0, where: `container="${CONTAINER}"` },
  });

  if (!canManageCustomObjects) {
    return <PageUnauthorized />;
  }

  if (loading) {
    return null;
  }

  const { customObjects } = data || {};
  const { results } = customObjects || {};

  return (
    <ContainerProvider value={results}>
      <Switch>
        <Route
          path={`${match.path}/containers/new`}
          render={(props) => <CreateContainer {...props} />}
        />
        <Route
          path={`${match.path}/containers/:id`}
          render={(props) => <ContainerDetails {...props} />}
        />
        <Route
          path={`${match.path}/containers`}
          render={(props) => <ContainerList {...props} />}
        />
        <Route
          path={`${match.path}/new`}
          render={(props) => <CreateCustomObject {...props} />}
        />
        <Route
          path={`${match.path}/:id`}
          render={(props) => <CustomObjectDetails {...props} />}
        />
        <Route render={(props) => <CustomObjectsList {...props} />} />
      </Switch>
    </ContainerProvider>
  );
};

ApplicationRoutes.displayName = 'ApplicationRoutes';
ApplicationRoutes.propTypes = {
  match: PropTypes.shape({
    path: PropTypes.string,
    params: PropTypes.shape({
      projectKey: PropTypes.string.isRequired,
    }).isRequired,
  }).isRequired,
};

export default ApplicationRoutes;

**Comment by kark** [comment]
Hi @ManjushaPillai,

We think the problem might be related to the permissions management in the routes files you provided.
Could you please provide the code of the `constants.js` file so we can double check if the issue is over there?

Thank you!

**Comment by ManjushaPillai** [comment]
Hi @kark 
PFB the contents of constants.js file:


import { entryPointUriPathToPermissionKeys } from '@commercetools-frontend/application-shell/ssr';

export const entryPointUriPath =
  window.app.entryPointUriPath ?? 'custom-objects';
export const PERMISSIONS = entryPointUriPathToPermissionKeys(entryPointUriPath);
export const SORT_OPTIONS = { ASC: 'asc', DESC: 'desc' };
export const ROOT_PATH = window.app.entryPointUriPath ?? 'custom-objects';
export const CONTAINER = 'mc-custom-object-schema';

}?

**Comment by nimesh10patil** [comment]
Hi Everyone,

We have gone through the documentations mentioned here https://docs.commercetools.com/custom-applications/migrating-from-project-level-custom-applications#oauth-scopes-and-user-permissions .

Our unit test cases have started failing with the same permissions related error that we’re seeing on the screen.

![image](https://user-images.githubusercontent.com/32710905/170931144-d95e96c8-2e3d-403c-9051-a76606294150.png)

As per the documentations we have upgrade @commercetools-frontend/* to >=21.

Following are the versions of the packages related to unit testing , do you think they are compatible ? Please do let us know.

"@testing-library/react": "11.2.6",
 "@testing-library/user-event": "^13.1.9",
"jest": "27.3.1",
 "jest-junit": "^10.0.0",



Thank you and best regards,

Nimesh

**Comment by CarlosCortizasCT** [comment]
Hello @nimesh10patil 

Migration to v21 also involved some braking changes related to how yo would mock permissions in test environment.
Please, refer to the [release note](https://docs.commercetools.com/custom-applications/releases/2022-02-02-custom-applications-v21#changes-to-test-utils) of that version for detailed information.

Perhaps you could also provide some example of how you are mock rendering in your tests if that does not help.

Thanks.
