### ISSUE TITLE
create-mc-app not working

### ISSUE THREAD

**Issue by chrisboyke** [commercetools/merchant-center-application-kit#2575]
Following the documentation to create a new mc-app (from https://docs.commercetools.com/custom-applications/getting-started)

Getting the following:

~/projects$ npx @commercetools-frontend/create-mc-app \  
  my-new-custom-application-project \
  --template starter

Need to install the following packages:
  @commercetools-frontend/create-mc-app
Ok to proceed? (y) y
Version: v20.10.6

  ✔ Downloading template
  ✔ Updating package.json
  ✖ Updating custom-application-config.json
    → ENOENT: no such file or directory, open '/Users/chrisboyke/projects/my-new-custom-application-project/custom-application-co
…
    Updating application constants
    Installing dependencies
Error: ENOENT: no such file or directory, open '/Users/chrisboyke/projects/my-new-custom-application-project/custom-application-config.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Task.task (/Users/chrisboyke/.npm/_npx/617c19204d820d3a/node_modules/@commercetools-frontend/create-mc-app/src/tasks/update-custom-application-config.js:16:12)
    at /Users/chrisboyke/.npm/_npx/617c19204d820d3a/node_modules/listr/lib/task.js:167:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/chrisboyke/projects/my-new-custom-application-project/custom-application-config.json',
  context: [Object: null prototype] {}
}

**Comment by emmenko** [comment]
Hi 👋

It seems that you are using an older version (`v20.10.6`) of `@commercetools-frontend/create-mc-app`.

Latest version (as of now) is `v21.3.4`

https://github.com/commercetools/merchant-center-application-kit/blob/d17fd7c1a79fe18bd34c489aaa08e97bd711ac33/packages/create-mc-app/package.json#L3

To force using the latest version you can pass the `@latest` to the package name:

```
npx @commercetools-frontend/create-mc-app@latest \
my-new-custom-application-project
--template starter
```

**Comment by chrisboyke** [comment]
That worked - thanks!   I'd recommend updating the docs to add @latest as probably lots of folks have the old version...

**Comment by emmenko** [comment]
We'll look into that yes. In theory the `create-mc-app` should print a hint if the version is outdated (https://github.com/commercetools/merchant-center-application-kit/blob/d17fd7c1a79fe18bd34c489aaa08e97bd711ac33/packages/create-mc-app/src/hint-outdated-version.js#L4) but apparently it's not working.
