### ISSUE TITLE
Issues with running jest test cases while migrating custom app from project level to org level

### ISSUE THREAD

**Issue by kmahadevan01** [commercetools/merchant-center-application-kit#2600]
I am creating this ticket as advised by nicholas speeter.
We are in the process of migrating our custom app, ensemble-custom-application from project-level to org-level. We are following the migration guide and have reach up till migrating eslint version and config changes.
We upgraded the following libraries to the latest version:

```json
{
"@commercetools-frontend/eslint-config-mc-app": "21.3.4",

"@commercetools-frontend/jest-preset-mc-app": "21.3.4",

"@commercetools-frontend/mc-scripts": "21.3.4",
}
```
 
In the migration guide, the dependencies for eslint are mentioned. However, we are not able to lookup for jest version and its peer dependencies which would be compatible with jest-preset-mc-app in the migration guide. So, we followed two strategies.
Initially after the version upgrade(mentioned above), we got the following error:

```
TypeError: Cannot read property 'cwd' of undefined

at Object.getCacheKey (node_modules/@commercetools-frontend/jest-preset-mc-app/node_modules/babel-jest/build/index.js:299:33)
```

After some research, we followed two strategies.
First, we downgraded jest and got 

```
TypeError: Cannot read property 'cwd' of undefined

at Object.getCacheKey (node_modules/@commercetools-frontend/jest-preset-mc-app/node_modules/babel-jest/build/index.js:299:33)
```
 

Next, we upgraded jest and its peer dependencies and got

```
FAIL   test  src/components/predicate-builder/util.spec.js

  ● Test suite failed to run

 

    TypeError: reactIntl.defineMessages is not a function

 

      2 | import map from 'lodash/map';

      3 | import trim from 'lodash/trim';

    > 4 | import { MoneyInput } from '@commercetools-frontend/ui-kit';
```

We didn’t have this issue with running test cases in jest-preset-mc-app 17.0.0 which is the current version in production.
The following ticket has the email attachment which contains the package.json for upgrading and downgrading jest

SUPPORT-16444

**Comment by selvam-murugan-nu** [comment]
@emmenko still we are getting below error.
![image](https://user-images.githubusercontent.com/71309381/167711594-21dd7142-95d6-4296-b459-8a01b6b81aca.png)

**Comment by selvam-murugan-nu** [comment]
below is my dependenct and devDependency packages and versions.`"dependencies": {
    "@apollo/client": "3.2.5",
    "@commercetools-frontend/actions-global": "21.3.0",
    "@commercetools-frontend/application-components": "21.3.2",
    "@commercetools-frontend/application-shell": "21.3.2",
    "@commercetools-frontend/application-shell-connectors": "21.3.4",
    "@commercetools-frontend/assets": "21.0.0",
    "@commercetools-frontend/constants": "17.0.0",
    "@commercetools-frontend/i18n": "21.3.0",
    "@commercetools-frontend/mc-http-server": "16.18.0",
    "@commercetools-frontend/permissions": "21.3.0",
    "@commercetools-frontend/sdk": "21.3.0",
    "@commercetools-frontend/ui-kit": "10.30.6",
    "@commercetools-uikit/i18n": "10.35.3",
    "@commercetools-uikit/localized-utils": "10.30.1",
    "@emotion/babel-preset-css-prop": "^10.0.27",
    "@emotion/react": "^11.9.0",
    "@emotion/styled-base": "^10.0.31",
    "@express-labs/mc-custom-applications-core": "1.1.39",
    "@types/prop-types": "15.7.3",
    "@types/react": "16.9.19",
    "@types/react-dom": "16.9.5",
    "@types/react-redux": "7.1.7",
    "@types/react-router": "5.1.4",
    "@types/react-router-dom": "5.1.3",
    "classnames": "2.2.6",
    "formik": "2.2.9",
    "global": "4.4.0",
    "graphql": "15.3.0",
    "lodash": "4.17.20",
    "moment": "2.24.0",
    "moment-timezone": "0.5.27",
    "omit-empty": "1.0.0",
    "pegjs": "0.10.0",
    "prop-types": "15.7.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-intl": "5.7.1",
    "react-redux": "7.1.3",
    "react-router": "5.1.2",
    "react-router-dom": "5.1.2",
    "redux": "4.0.5",
    "yup": "0.28.3"
  },
  "devDependencies": {
    "@babel/core": "7.12.3",
    "@commercetools-frontend/eslint-config-mc-app": "21.3.1",
    "@commercetools-frontend/jest-preset-mc-app": "21.3.2",
    "@commercetools-frontend/mc-scripts": "21.3.2",
    "@testing-library/react": "12.1.2",
    "babel-eslint": "10.1.0",
    "cross-env": "7.0.2",
    "enzyme": "3.11.0",
    "eslint": "8.12.0",
    "eslint-formatter-pretty": "4.1.0",
    "eslint-plugin-graphql": "4.0.0",
    "faker": "5.1.0",
    "jest": "27.5.1",
    "jest-runner-eslint": "1.0.0",
    "jest-silent-reporter": "0.5.0",
    "jest-watch-typeahead": "1.0.0",
    "lint-staged": "10.4.2",
    "pegjs-jest": "0.0.2",
    "pegjs-loader": "0.5.6",
    "prettier": "2.1.2",
    "stylelint": "13.4.0",
    "stylelint-config-standard": "19.0.0",
    "stylelint-order": "4.0.0",
    "typescript": "3.9.2",
    "webpack": "4.43.0"
  }`
i have replaced a code on jest.config.js this file also.

**Comment by kmahadevan01** [comment]
@emmenko ,Our dependencies from package.json:

"dependencies": {
    "@apollo/client": "3.2.5",
    "@commercetools-frontend/actions-global": "17.0.0",
    "@commercetools-frontend/application-components": "17.0.0",
    "@commercetools-frontend/application-config": "17.0.0",
    "@commercetools-frontend/application-shell": "17.0.0",
    "@commercetools-frontend/application-shell-connectors": "17.0.0",
    "@commercetools-frontend/assets": "21.0.0",
    "@commercetools-frontend/constants": "17.0.0",
    "@commercetools-frontend/i18n": "17.0.0",
    "@commercetools-frontend/mc-http-server": "16.18.0",
    "@commercetools-frontend/permissions": "17.0.0",
    "@commercetools-frontend/sdk": "17.0.0",
    "@commercetools-frontend/ui-kit": "10.30.6",
    "@commercetools-uikit/i18n": "10.35.3",
    "@commercetools-uikit/localized-utils": "10.30.1",
    "@emotion/babel-preset-css-prop": "^10.0.27",
    "@emotion/react": "^11.9.0",
    "@emotion/styled-base": "^10.0.31",
    "@express-labs/mc-custom-applications-core": "1.1.39",
    "@types/prop-types": "15.7.3",
    "@types/react": "16.9.19",
    "@types/react-dom": "16.9.5",
    "@types/react-redux": "7.1.7",
    "@types/react-router": "5.1.4",
    "@types/react-router-dom": "5.1.3",
    "classnames": "2.2.6",
    "formik": "2.2.9",
    "global": "4.4.0",
    "graphql": "15.3.0",
    "lodash": "4.17.20",
    "moment": "2.24.0",
    "moment-timezone": "0.5.27",
    "omit-empty": "1.0.0",
    "pegjs": "0.10.0",
    "prop-types": "15.7.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-intl": "5.24.8",
    "react-redux": "7.1.3",
    "react-router": "5.1.2",
    "react-router-dom": "5.1.2",
    "redux": "4.0.5",
    "yup": "0.28.3"
  },
  "devDependencies": {
    "@commercetools-frontend/eslint-config-mc-app": "21.3.4",
    "@commercetools-frontend/jest-preset-mc-app": "21.3.4",
    "@commercetools-frontend/mc-scripts": "21.3.4",
    "@testing-library/react": "12.1.2",
    "babel-eslint": "10.1.0",
    "cross-env": "7.0.2",
    "enzyme": "3.11.0",
    "eslint": "8.12.0",
    "eslint-formatter-pretty": "4.1.0",
    "eslint-plugin-graphql": "4.0.0",
    "faker": "5.1.0",
    "jest": "27.5.1",
    "jest-plugin-filename": "0.0.1",
    "jest-runner-eslint": "1.0.0",
    "jest-runner-stylelint": "2.3.3",
    "jest-validate": "24.9.0",
    "lint-staged": "10.4.2",
    "pegjs-jest": "0.0.2",
    "pegjs-loader": "0.5.6",
    "prettier": "2.1.2",
    "stylelint": "13.4.0",
    "stylelint-config-standard": "19.0.0",
    "stylelint-order": "4.0.0",
    "typescript": "3.9.2",
    "webpack": "4.43.0"
  }
}
We are still getting the same error after updating jest:
● Test suite failed to run

    TypeError: reactIntl.defineMessages is not a function

      2 | import map from 'lodash/map';
      3 | import trim from 'lodash/trim';
    > 4 | import { MoneyInput } from '@commercetools-frontend/ui-kit';
        | ^
      5 | import { ENSEMBLE_TYPES } from '../../constants';
      6 | import { isBoolean } from '../predicate-builder/util';
      7 | import { LOGIC } from '../predicate-builder/constants';

      at Object.<anonymous> (node_modules/@commercetools-uikit/field-errors/dist/field-errors.cjs.js:88:26)
      at Object.<anonymous> (node_modules/@commercetools-uikit/text-field/dist/text-field.cjs.js:13:19)
      at Object.<anonymous> (node_modules/@commercetools-uikit/fields/dist/fields.cjs.js:5:17)
      at Object.<anonymous> (node_modules/@commercetools-frontend/ui-kit/dist/ui-kit.cjs.js:7:14)
      at Object.<anonymous> (src/components/ensemble-form/util.js:4:1)
      at Object.<anonymous> (src/test-util/index.js:8:1)
      at Object.<anonymous> (src/components/predicate-builder/util.spec.js:3:1)

**Comment by emmenko** [comment]
Hi @kmahadevan01 and @selvam-murugan-nu 

Thanks for sharing the `package.json`, this give us the information we need.

It appears that you are using different versions of the appkit and uikit packages, for example v17 and v21, and this is likely the source of the issues.

You should try to keep the dependencies of appkit and uikit to the same versions respectively and especially avoid using different major versions.

For instance, for appkit packages `@commercetools-frontend/*` the latest versions are on `v21.x` and for uikit packages `@commercetools-uikit/*` the latest version is `v15.x`.

Note that the `@commercetools-frontend/ui-kit` is a preset package of uikit that exports all uikit packages. If you use that, you don't need to specify any other uikit package. In general though we recommend to use each individual package of uikit to keep the bundle size a bit smaller.

To help updating these packages to their latest versions, you can usually use a command such as `manypkg upgrade @commercetools-frontend` (which updates all packages starting with the npm scope `@commercetools-frontend`).

Regarding the appkit updates from v17 to v21, we recommend to follow the migration steps in each of the major release notes (https://docs.commercetools.com/custom-applications/releases).
In particular, for the v21 (Org-level Custom Applications) make sure to also read the migration guide: https://docs.commercetools.com/custom-applications/migrating-from-project-level-custom-applications

Same for uikit from v10 to v15.

In addition to that, we also recommend to upgrade all other packages more recent versions, for example React to v17, etc.

It also seems that several dependencies defined in the `package.json` are not necessary, for example `webpack`, `babel-eslint`, etc.
We strongly suggest to compare the minimal required dependencies with the starter template package: https://github.com/commercetools/merchant-center-application-kit/blob/main/application-templates/starter/package.json

**Comment by kmahadevan01** [comment]
Hi @emmenko 
We updated the dependencies as advised, by referencing the migration guide. Please find our dependencies from package.json below:
"dependencies": {
    "@apollo/client": "3.2.5",
    "@commercetools-frontend/actions-global": "21.3.4",
    "@commercetools-frontend/application-components": "21.5.1",
    "@commercetools-frontend/application-config": "17.0.0",
    "@commercetools-frontend/application-shell": "21.5.1",
    "@commercetools-frontend/application-shell-connectors": "21.3.4",
    "@commercetools-frontend/assets": "21.0.0",
    "@commercetools-frontend/constants": "21.3.4",
    "@manypkg/cli": "0.19.1",
    "@commercetools-frontend/i18n": "21.4.0",
    "@commercetools-frontend/mc-http-server": "16.18.0",
    "@commercetools-frontend/permissions": "21.3.4",
    "@commercetools-frontend/sdk": "21.3.4",
    "@commercetools-frontend/ui-kit": "^15.0.0",
    "@commercetools-uikit/i18n": "15.0.0",
    "@commercetools-uikit/localized-utils": "10.30.1",
    "@emotion/babel-preset-css-prop": "^10.0.27",
    "@emotion/react": "^11.9.0",
    "@emotion/styled-base": "^10.0.31",
    "@express-labs/mc-custom-applications-core": "1.1.39",
    "@types/prop-types": "15.7.5",
    "@types/react": "17.0.2",
    "@types/react-dom": "17.0.2",
    "@types/react-redux": "7.2.8",
    "@types/react-router": "5.1.4",
    "@types/react-router-dom": "5.3.1",
    "classnames": "2.2.6",
    "formik": "2.2.9",
    "global": "4.4.0",
    "graphql": "15.3.0",
    "lodash": "4.17.20",
    "moment": "2.24.0",
    "moment-timezone": "0.5.27",
    "omit-empty": "1.0.0",
    "pegjs": "0.10.0",
    "prop-types": "15.7.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-intl": "^5.25.0",
    "react-redux": "7.1.24",
    "react-router": "5.1.2",
    "react-router-dom": "5.1.2",
    "redux": "4.0.5",
    "yup": "0.28.3"
  },
  "devDependencies": {
    "@commercetools-frontend/eslint-config-mc-app": "21.3.4",
    "@commercetools-frontend/jest-preset-mc-app": "21.3.4",
    "@commercetools-frontend/mc-scripts": "21.3.4",
    "@testing-library/react": "12.1.5",
    "@testing-library/react-hooks": "7.0.2",
    "cross-env": "7.0.2",
    "enzyme": "3.11.0",
    "eslint": "8.12.0",
    "eslint-formatter-pretty": "4.1.0",
    "eslint-plugin-graphql": "4.0.0",
    "faker": "5.1.0",
    "jest": "27.5.1",
    "jest-plugin-filename": "0.0.1",
    "jest-runner-eslint": "1.0.0",
    "jest-runner-stylelint": "2.3.3",
    "jest-validate": "24.9.0",
    "lint-staged": "10.4.2",
    "pegjs-jest": "0.0.2",
    "pegjs-loader": "0.5.6",
    "prettier": "2.1.2",
    "stylelint": "13.4.0",
    "stylelint-config-standard": "19.0.0",
    "stylelint-order": "4.0.0",
    "typescript": "3.9.2"
  }
We are still getting the same error

**Comment by emmenko** [comment]
Thanks for getting back to us.

I still see some minor inconsistencies in the dependencies:
* `"@commercetools-frontend/application-config": "17.0.0",` should be updated to e.g. `21.5.0`
* `"@commercetools-frontend/mc-http-server": "16.18.0",` has been deprecated and not maintained anymore for a long time. You should remove it.
* `"@commercetools-uikit/localized-utils"` should be updated to `v15`
* `"@emotion/babel-preset-css-prop"` should be removed
* `"@emotion/styled-base"` should be removed and instead use `"@emotion/styled"` `v11`
* `"jest-validate"` should be updated to `v27`
* `"lint-staged"` should be updated to `v12`
* `"stylelint"` should be updated to `v14`
* `"stylelint-config-standard"` should be updated to `v24`
* `"stylelint-order"` should be updated to `v5`
* `"typescript"` should be updated to `v4`

Also, what is the package `@express-labs/mc-custom-applications-core`? You might want to check the dependencies there as well.

**Comment by kmahadevan01** [comment]
@emmenko 
We have updated the package.json for mc-custom-applications-core and ensemble-custom-application. We still face the same issues
Package.json for mc-custom-applications-core
"dependencies": {
    "@apollo/react-hooks": "4.0.0",
    "@babel/runtime-corejs3": "7.8.4",
    "@emotion/core": "10.0.27",
    "@emotion/styled": "^11.0.0",
    "apollo-cache": "1.3.5",
    "apollo-link": "1.2.14",
    "apollo-client": "^2.6.4",
    "apollo-utilities": "1.3.4",
    "aws-sdk": "2.610.0",
    "classnames": "2.2.6",
    "lodash": "4.17.21",
    "lodash-es": "4.17.21",
    "prop-types": "15.7.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.10.5",
    "@babel/core": "7.8.4",
    "@babel/plugin-transform-modules-commonjs": "^7.10.4",
    "@babel/preset-env": "^7.10.4",
    "@babel/preset-react": "^7.10.4",
    "@babel/preset-typescript": "^7.10.4",
    "@commercetools-frontend/actions-global": "21.3.4",
    "@commercetools-frontend/application-shell-connectors": "21.3.4",
    "@commercetools-frontend/babel-preset-mc-app": "21.3.4",
    "@commercetools-frontend/constants": "21.3.4",
    "@commercetools-frontend/eslint-config-mc-app": "21.3.4",
    "@commercetools-frontend/jest-preset-mc-app": "21.3.4",
    "@commercetools-uikit/icons": "^15.0.0",
    "@commercetools-uikit/flat-button": "^15.0.0",
    "@commercetools-uikit/spacings": "^15.0.0",
    "@commercetools-uikit/text": "^15.0.0",
    "@commercetools-uikit/primary-button": "^15.0.0",
    "@commercetools-uikit/secondary-button": "^15.0.0",
    "@commercetools-uikit/loading-spinner": "^15.0.0",
    "@commercetools-uikit/async-select-input": "^15.0.0",
    "@commercetools-uikit/select-input": "^15.0.0",
    "@commercetools-uikit/text-input": "^15.0.0",
    "@commercetools-uikit/secondary-icon-button": "^15.0.0",
    "@commercetools-uikit/table": "11.2.1",
    "@emotion/styled": "^11.0.0",
    "@rollup/plugin-multi-entry": "^3.0.1",
    "@testing-library/react": "12.1.5",
    "@types/react": "16.9.19",
    "@types/react-redux": "7.1.7",
    "babel-eslint": "10.0.3",
    "babel-plugin-import-graphql": "2.7.0",
    "babel-plugin-react-intl": "5.1.18",
    "babel-plugin-transform-rename-import": "2.3.0",
    "cross-env": "7.0.0",
    "enzyme": "3.11.0",
    "eslint": "8.12.0",
    "eslint-formatter-pretty": "4.1.0",
    "eslint-plugin-graphql": "4.0.0",
    "faker": "4.1.0",
    "graphql": "14.6.0",
    "graphql-tag": "2.10.1",
    "jest": "27.5.1",
    "jest-plugin-filename": "0.0.1",
    "jest-runner-eslint": "1.0.0",
    "jest-runner-stylelint": "2.2.3",
    "jest-validate": "^27.0.0",
    "lint-staged": "^12.0.0",
    "moment": "2.24.0",
    "moment-timezone": "0.5.27",
    "postcss-color-mod-function": "3.0.3",
    "postcss-custom-properties": "9.0.2",
    "prettier": "2.6.2",
    "@emotion/react": "^11.9.0",
    "react": "17.0.2",
    "react-apollo": "3.1.5",
    "react-dom": "17.0.2",
    "react-intl": "^5.25.0",
    "react-redux": "7.2.8",
    "react-router": "5.1.2",
    "react-router-dom": "5.3.1",
    "redux": "4.2.0",
    "rollup": "1.29.1",
    "rollup-plugin-babel": "4.3.3",
    "rollup-plugin-commonjs": "10.1.0",
    "rollup-plugin-copy": "^3.3.0",
    "rollup-plugin-node-builtins": "2.1.2",
    "rollup-plugin-node-resolve": "5.2.0",
    "rollup-plugin-peer-deps-external": "2.2.0",
    "rollup-plugin-postcss": "2.0.5",
    "rollup-plugin-terser": "5.2.0",
    "stylelint": "^14.0.0",
    "stylelint-config-standard": "^24.0.0",
    "stylelint-order": "^5.0.0",
    "typescript": "^4.0.0"
  },
  "peerDependencies": {
    "@commercetools-frontend/actions-global": "21.3.4",
    "@commercetools-frontend/application-shell-connectors": "21.3.4",
    "@commercetools-frontend/constants": "21.3.4",
    "react": ">=16.8.0",
    "react-apollo": "3.x",
    "react-dom": ">=16.8.0",
    "react-intl": "3.x",
    "react-redux": "7.x",
    "react-router": "5.x",
    "react-router-dom": "5.x",
    "redux": "4.x"
  }
  Package.json for ensemble-custom-application
  "dependencies": {
    "@apollo/client": "3.2.5",
    "@commercetools-frontend/actions-global": "21.3.4",
    "@commercetools-frontend/application-components": "21.5.1",
    "@commercetools-frontend/application-config": "17.0.0",
    "@commercetools-frontend/application-shell": "21.5.1",
    "@commercetools-frontend/application-shell-connectors": "21.3.4",
    "@commercetools-frontend/assets": "21.0.0",
    "@commercetools-frontend/constants": "21.3.4",
    "@manypkg/cli": "0.19.1",
    "@commercetools-frontend/mc-http-server": "16.18.0",
    "@commercetools-frontend/permissions": "21.3.4",
    "@commercetools-frontend/sdk": "21.3.4",
    "@commercetools-frontend/i18n": "21.4.0",
    "@commercetools-uikit/localized-utils": "10.30.1",
    "@commercetools-uikit/icons": "^15.0.0",
    "@commercetools-uikit/spacings": "^15.0.0",
    "@commercetools-uikit/icon-button": "^15.0.0",
    "@commercetools-uikit/text": "^15.0.0",
    "@commercetools-uikit/toggle-input": "^15.0.0",
    "@commercetools-uikit/localized-text-input": "^15.0.0",
    "@commercetools-uikit/card": "^15.0.0",
    "@commercetools-uikit/checkbox-input": "^15.0.0",
    "@commercetools-uikit/collapsible-panel": "^15.0.0",
    "@commercetools-uikit/constraints": "^15.0.0",
    "@commercetools-uikit/date-time-field": "^15.0.0",
    "@commercetools-uikit/field-label": "^15.0.0",
    "@commercetools-uikit/flat-button": "^15.0.0",
    "@commercetools-uikit/localized-multiline-text-field": "^15.0.0",
    "@commercetools-uikit/localized-text-field": "^15.0.0",
    "@commercetools-uikit/number-field": "^15.0.0",
    "@commercetools-uikit/primary-button": "^15.0.0",
    "@commercetools-uikit/radio-input": "^15.0.0",
    "@commercetools-uikit/secondary-button": "^15.0.0",
    "@commercetools-uikit/tooltip": "^15.0.0",
    "@commercetools-uikit/money-input": "^15.0.0",
    "@commercetools-uikit/select-input": "^15.0.0",
    "@commercetools-uikit/text-input": "^15.0.0",
    "@commercetools-uikit/messages": "^15.0.0",
    "@commercetools-uikit/number-input": "^15.0.0",
    "@commercetools-uikit/select-field": "^15.0.0",
    "@commercetools-uikit/money-field": "^15.0.0",
    "@emotion/babel-preset-css-prop": "^10.0.27",
    "@emotion/react": "^11.9.0",
    "@emotion/styled-base": "^10.0.31",
    "@express-labs/mc-custom-applications-core": "1.1.39",
    "@types/prop-types": "15.7.5",
    "@types/react": "17.0.2",
    "@types/react-dom": "17.0.2",
    "@types/react-redux": "7.1.24",
    "@types/react-router": "5.1.4",
    "@types/react-router-dom": "5.3.1",
    "classnames": "2.2.6",
    "formik": "2.2.9",
    "global": "4.4.0",
    "graphql": "15.3.0",
    "lodash": "4.17.20",
    "moment": "2.24.0",
    "moment-timezone": "0.5.27",
    "omit-empty": "1.0.0",
    "pegjs": "0.10.0",
    "prop-types": "15.7.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-intl": "^5.25.0",
    "react-redux": "7.2.8",
    "react-router": "5.1.2",
    "react-router-dom": "5.1.2",
    "redux": "4.0.5",
    "yup": "0.28.3"
  },
  "devDependencies": {
    "@commercetools-frontend/eslint-config-mc-app": "21.3.4",
    "@commercetools-frontend/jest-preset-mc-app": "21.3.4",
    "@commercetools-frontend/mc-scripts": "21.3.4",
    "@testing-library/react": "12.1.5",
    "@testing-library/react-hooks": "7.0.2",
    "cross-env": "7.0.2",
    "enzyme": "3.11.0",
    "eslint": "8.12.0",
    "eslint-formatter-pretty": "4.1.0",
    "eslint-plugin-graphql": "4.0.0",
    "faker": "5.1.0",
    "jest": "27.5.1",
    "jest-plugin-filename": "0.0.1",
    "jest-runner-eslint": "1.0.0",
    "jest-runner-stylelint": "2.3.3",
    "jest-validate": "24.9.0",
    "lint-staged": "10.4.2",
    "pegjs-jest": "0.0.2",
    "pegjs-loader": "0.5.6",
    "prettier": "2.1.2",
    "stylelint": "13.4.0",
    "stylelint-config-standard": "19.0.0",
    "stylelint-order": "4.0.0",
    "typescript": "3.9.2"
  }

**Comment by selvam-murugan-nu** [comment]
@emmenko 
**import { defineMessages } from 'react-intl';**
i could suspect **react-intl** plugin right now doesn't have the **defineMessages** as function
so i just changed to below line
import { defineMessages } from '@formatjs/intl';
i can resolve the following issue
    TypeError: reactIntl.defineMessages is not a function

Still the same issue coming from **@commercetools-uikit** kindly refer the below screenshot.
![image](https://user-images.githubusercontent.com/71309381/168396531-8426c724-f927-49f0-9116-18306896098f.png)


When i investigate the @commercetools-uikit repo i could see below code in many places.
 **import { defineMessages } from 'react-intl';**
![image](https://user-images.githubusercontent.com/71309381/168396445-1c95f7d3-63ba-44e0-bfb2-e6659d69cb4b.png)

could you please check and let me know?

Thanks & regards,
Selvam

**Comment by CarlosCortizasCT** [comment]
Hi @selvam-murugan-nu 

Still difficult to exactly know what the problem is in your configuration but we have seen some other problems with `react-intl` dependency where there are different versions of that package in the same repository.

Perhaps you could run `yarn why react-intl` to check if this is happening in your context.
(_[more info](https://github.com/commercetools/ui-kit/discussions/2182)_)

**Comment by selvam-murugan-nu** [comment]
i run the following command in my repo and getting below details.
yarn why react-intl
i dont see any conflicts on react-intl version.
![image](https://user-images.githubusercontent.com/71309381/168644251-d5b5391b-7600-4ce7-b3a9-ba2e36ba657f.png)

**Comment by kmahadevan01** [comment]
@CarlosCortizasCT 
We have ensemble-custom-application which is dependent on mc-custom-applications-core
We fixed the error associated with react-intl plugin by modifying the import in mc-custom-applications-core
`import { defineMessages } from '@formatjs/intl';`
As @selvam-murugan-nu  pointed out, react-intl plugin doesn't have the defineMessages as function
After implementing the above change, our build is successful locally. However, our test cases are failing since our test cases refer to @commercetools-uikit which has react-intl plugin which doesn't have the defineMessages function.
In the previous thread, we have included the package.json for both ensemble-custom-application and mc-custom-applications-core. Only when we get the mc-custom-applications-core build successful for test cases, we can proceed with build and use the latest tag in ensemble-custom-application. Since we need to migrate the custom application sooner, could you please help us with the error associated with this dependency (@commercetools-uikit)

**Comment by CarlosCortizasCT** [comment]
Hello @kmahadevan01 

Thanks for sharing more info regarding this issue.
Could we also ask for you to also share the output of `yarn why react-intl` in the **ensemble-custom-application** project?

The `defineMessages` function do actually exists in the `react-intl` package ([here](https://github.com/formatjs/formatjs/blob/main/packages/react-intl/index.ts#L69) is the source code and they mention [it in the docs](https://formatjs.io/docs/getting-started/message-declaration#pre-declaring-using-definemessage-for-later-consumption-less-recommended)) so it's quite weird you have that message when running your tests.

We created a simplistic example to use `react-intl` in isolation so we can be sure the `defineMessages` function can be used.
You can find it [here](https://codesandbox.io/s/silly-currying-1gdrn4?file=/src/App.js).

Also, we would also know about your projects structure. You mentioned two projects:
1.  mc-custom-applications-core
2. ensemble-custom-application (depends on the previous one)

Do both projects live in the same repository or are they independent?

Thanks.

**Comment by selvam-murugan-nu** [comment]
Hello @CarlosCortizasCT,
Here is the ensemble-custom-application why react-intl log's.
![image](https://user-images.githubusercontent.com/71309381/169050066-7de2e269-2740-44b7-90d3-a1637571854c.png)
mc-custom-application we will publish as a npm package and we will consume the latest version in ensemble-custom-app.
we have to first fix mc-custom-application-core once we fixed we will use the latest version into ensemble-custom-app.
Thanks,
Selvam M

**Comment by CarlosCortizasCT** [comment]
Hello @selvam-murugan-nu 

So both `yarn why` logs seem correct but that was not what we expected.

To further debug the problem, I would suggest these other steps:
* fix the `react-intl` version: currently you use a range version in both projects (`^5.25.0`) but you could try to set a fixed version (eg: `5.25.1`). You could also try to set some [resolution](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to a fixed version in both projects.
* use the `manypkg upgrade @commercetools-frontend` command @emmenko suggested: I see some packages were not updated to the latest version (eg: `@commercetools-frontend/application-config` is still in an old version: `17.0.0` when it should be in 21.x as its counterparts).
* Try to find how the `react-intl` object looks like when testing: the error says the `defineMessages` property is not a function, but it does not say that it's _null_ or _undefined_ so I would try to update the code locally to set some logs trying to figure out what it is instead. On doing so, you could potentially find what `react-intl` file the test environment is using and perhaps gain some helpful clue.

**Comment by selvam-murugan-nu** [comment]
@CarlosCortizasCT 
**@commercetools-frontend/application-config** this package we have not used in mc-custom-application-core.
I have added resolution also not worked.
![image](https://user-images.githubusercontent.com/71309381/169114935-e6ced680-7300-4e22-907c-4fcf90053411.png)
![image](https://user-images.githubusercontent.com/71309381/169114999-d236d62c-59a6-47f3-83f4-f8fa9b328b12.png)

**Comment by selvam-murugan-nu** [comment]
@CarlosCortizasCT below is my jest.test.config.js file is there anything i should change to support react-intl in test cases.

const jestPreset = require('@commercetools-frontend/jest-preset-mc-app');
const applyJestPresetWithEnzyme = require('@commercetools-frontend/jest-preset-mc-app/enzyme/apply-jest-preset-with-enzyme');

module.exports = {
  ...applyJestPresetWithEnzyme({
    enzymeAdapterVersion: 16,
    jestPreset,
  }),
};

**Comment by CarlosCortizasCT** [comment]
Hi @selvam-murugan-nu 

One thing we noticed with your jest configuration is that you are setting it up to use the `enzyme` adapter version **16** but in your `package.json` you are using React version **17** so you should also update that configuration.

Thanks.

**Comment by selvam-murugan-nu** [comment]
@CarlosCortizasCT Sorry i was noticed that and updated after took the screenshot still the issue exsists.
<img width="367" alt="image" src="https://user-images.githubusercontent.com/71309381/169547722-337dfb73-9f67-4362-9d23-6c6e6d17b094.png">
<img width="877" alt="image" src="https://user-images.githubusercontent.com/71309381/169547753-fd63f9f3-a8d2-4721-a685-5ba608f2a6ec.png">

**Comment by CarlosCortizasCT** [comment]
@selvam-murugan-nu, @kmahadevan01 

Regarding the problem running the tests of *mc-custom-application* project, we realized during our call the problem came from a jest mock file for the `react-intl` dependency with a missing _export_.

That file should have this content:
```js
import { intlMock } from '../test-util';

const useIntl = jest.fn(() => intlMock);
export * from 'react-intl';
export { useIntl };
```

After that file was updated, the tests passed without errors but the *lint* command failed with an error like this one:
```
/src/__mocks__/react-intl.js
  4:1   error  Multiple exports of name 'useIntl'  import/export
  5:10  error  Multiple exports of name 'useIntl'  import/export
```

This error comes from the `import/export` EsLint rule which aims for helping developers be aware (for example) if they accidentally try to export the same named export several times from the same module.

In the context of the `react-intl` mock, that rule complains because all named exports from the original module are being re-exported (which includes `useIntl`) but we also have another named module with `useIntl` because we want to override that function in the tests. So we are effectively exporting the same name twice.

I see two solutions here:
1. Ignore that rule for the mock file since the duplication here is intended. We know that we are duplicating the named export but that's exactly what we want because we need to override that function (the second export will take precedence over the first one when importing anything from this module).
The file would have an EsLint disable directive at the beginning:
```
/* eslint import/export: "off" */
import { intlMock } from '../test-util';

const useIntl = jest.fn(() => intlMock);
export * from 'react-intl';
export { useIntl };
```
2. Use _commonjs_ syntax for this module so the EsLint plugin is not triggered:
```
const testUtil = require('../test-util');
const reactIntl = require('react-intl');

module.exports = {
  ...reactIntl,
  useIntl: jest.fn(() => testUtil.intlMock)
};
```

I would suggest to go with the number 1 because it's easier and makes sense in the context of jest tests mocking.

**Comment by kmahadevan01** [comment]
Hi @CarlosCortizasCT ,
After ignoring the rule for the mock file, we are able to get past the error. 
However, we are getting some failure in test cases which we are debugging to fix it. Once that is completed, we will generate the new tag and add it in ensemble-custom-application to see whether we are able to build successfully and not getting the error which we discussed in our call. We will keep you posted here. Thank you.

**Comment by kmahadevan01** [comment]
We are able to build mc-custom-application core successfully. Hence closing this ticket
