### ISSUE TITLE
Custom application works locally but does not work when deployed on AWS cloud

### ISSUE THREAD

**Issue by hemantkumar-pawar** [commercetools/merchant-center-application-kit#2605]
Custom application works locally but does not work when deployed on AWS cloud.

To Reproduce

1. select project "custom-application-wa1" 
2. Click on rocket icon Vertex Config 
3. See error "Not found"

**Expected behavior**

It works when running locally but does not work on cloud.

![image](https://user-images.githubusercontent.com/73798651/167653269-cadef03e-4490-4d37-962b-5025a377b7ba.png)

Error on cloud - 
![image](https://user-images.githubusercontent.com/73798651/167653428-91fb0224-7a46-4527-9f9c-68168ae49902.png)

**Comment by emmenko** [comment]
Hi @hemantkumar-pawar 👋

Thanks for reaching out.

It appears that the URL where the application is hosted is not returning anything (404), both from the root URL or subroutes (like `/custom-application-wa1/vertex-config`.

This seems to be an issue with your AWS setup and there is not much we can do from our side.

Can I ask if this is the first time developing a Custom Application or is this a new issue you encountered (for example regarding the migration to Org-level Custom Applications)?
In case you haven't seen it, we have some documentation about deployments, for example for AWS (https://docs.commercetools.com/custom-applications/deployment-examples/aws-s3-cloudfront).

We're happy to assist if you have further questions. Thanks

**Comment by hemantkumar-pawar** [comment]
Hi @emmenko , this is not first time development of custom application but its encountered while doing migration to Org-level Custom Applications. So, there is no issue with deployment it is successful.

**Comment by emmenko** [comment]
From what I can see, if you try to directly access the URL configured for the `vertex-config` Custom Application it also returns a 404.

Did you check that?

**Comment by hemantkumar-pawar** [comment]
which url ?

**Comment by emmenko** [comment]
In the Merchant Center, where you configured the Custom Application `vertex-config`, there is a field to provide the URL where the application is hosted.

<img width="669" alt="image" src="https://user-images.githubusercontent.com/1110551/167825558-a0b1002b-d87b-47b9-9aec-a6b66fe047d2.png">

This is the URL used to serve your Custom Application when you try to access it in the Merchant Center.

This is also the same URL you should provide in the Custom Application config file at `env.production.url`.
https://docs.commercetools.com/custom-applications/api-reference/application-config#envproductionurl

**Comment by hemantkumar-pawar** [comment]
That is the problem it works for project level custom application but does not work for org level custom application.

![image](https://user-images.githubusercontent.com/73798651/167832355-c84ec088-f0c2-4b35-b716-65e90723813e.png)

**Comment by emmenko** [comment]
Again, as much as I would like to help I image something in the AWS setup is not correctly configured. I can't do much without knowing a bit more about the deployment setup, the AWS setup, etc.

One thing for sure that I would expect is for the URL provided to return the application `index.html`. The server also should be configured to handle rewrite rules to rewrite all requests to serve the `index.html`, as the Custom Application is a Single-Page Application.

**Comment by hemantkumar-pawar** [comment]
Which url commerce tools hitting in internally ?

**Comment by CarlosCortizasCT** [comment]
Hello @hemantkumar-pawar 

Merchant Center internally uses the URL you set up when configuring your Custom Application as @emmenko mentioned in a [previous message](https://github.com/commercetools/merchant-center-application-kit/issues/2605#issuecomment-1123503299).

Every Custom Application has a different configuration for every organization you want to use it into. 
We would like to ask if you could provide which organization you are testing against.

Thanks.

**Comment by CarlosCortizasCT** [comment]
Hi @hemantkumar-pawar,

We've checked the configuration set up for the `vertex-config` app in the **Mercury** organization and the deployment URL for your custom application is this one: https://commercetoolsdevconnector.vertexsmb.com

That's the URL the Merchant Center uses to try to fetch the Custom Applications assets when you navigate to https://mc.us-central1.gcp.commercetools.com/custom-application-wa1/vertex-config.

When we try to load your Custom Application deployment URL, we get a 404:
![image](https://user-images.githubusercontent.com/97907068/171597795-be3f605d-7e9f-4e23-b02d-7c54a0523cff.png)

We expect that URL to return the `index.html` file of your custom application.

So perhaps there was some problem with your deployment or some configuration in missing in your environment.

Hope this helps.

**Comment by arunmanglick-code** [comment]
Hi @CarlosCortizasCT - Can we connect over a call and go over the issue. You might be facing the issue as the url shared are of lower/restrictive env. Thanks

**Comment by arunmanglick-code** [comment]
Hi @CarlosCortizasCT - Can we connect over a call and go over the issue. You might be facing the issue as the url shared are of lower/restrictive env. Thanks

**Comment by hemantkumar-pawar** [comment]
Hi @CarlosCortizasCT ,, we tried after cache update but it seems that no luck there. 
![image](https://user-images.githubusercontent.com/73798651/172841240-55be77f6-1cd4-4b52-973b-6dad7636d81b.png)

![image](https://user-images.githubusercontent.com/73798651/172841364-b56d1829-b359-4031-a217-163a21239940.png)

**Comment by CarlosCortizasCT** [comment]
Hi @hemantkumar-pawar 

That's bad news.

We will keep investigating what can be happening with that specific Custom Application and let you now when we have any news about it.

**Comment by CarlosCortizasCT** [comment]
Hello @hemantkumar-pawar 

After looking at the problem again we found out the configured URL as "Application URL" cannot have the filename at the end.
In your case, I guess it should be something like this: `https://commercetoolsdevconnector.vertexsmb.com/connector/js/`.

But there's also another thing you should set up in your end. As @emmenko [already commented](https://github.com/commercetools/merchant-center-application-kit/issues/2605#issuecomment-1123741472), you need to configure your server so any request under that path "**/connector/js/**" (which is not an static asset like a `js` or `css` file) returns the `index.html` file.
These are known as rewrite rules and I guess you can set them up in any of your AWS service or even in the Tomcat server you showed us.
For the Tomcat use case, I think these links could be relevant:
* [Tomcat rewrites configuration](https://tomcat.apache.org/tomcat-9.0-doc/rewrite.html)
* [Example of a user with a similar context](https://stackoverflow.com/a/28865340)

**Comment by hemantkumar-pawar** [comment]
@CarlosCortizasCT - The issue is resolved now. There was problem with Index.html. Closing the ticket.

![image](https://user-images.githubusercontent.com/73798651/177476872-fbf80c58-5ee5-49b3-8130-e683008a6a67.png)
