### ISSUE TITLE
Can't resolve `@babel/runtime-corejs3`

### ISSUE THREAD

**Issue by planetcrypton** [commercetools/merchant-center-application-kit#2607]
**Can't resolve @babel/runtime-corejs3**

After upgrading all `@commercetools-frontend/*` packages I get the errors mentioned below when starting the app (building gives no issues) regarding `@babel/runtime-corejs3` (which is a dependency of many `@commercetools-frontend/*` packages - I don't have it in my project's dependencies myself):

**To Reproduce**
Node v16.14.2
Installed:
```
    "@commercetools-frontend/mc-scripts": "21.5.0",
    "@commercetools-frontend/application-shell": "21.5.1",
    "@commercetools-frontend/application-components": "21.5.1",
    "@commercetools-frontend/actions-global": "21.3.4",
    "@commercetools-frontend/ui-kit": "15.0.0",
```
`start` the application.
The errors get printed, but nevertheless the application starts and runs in the browser.

**Expected behavior**

Expected no errors to be printed 😀

**Errors**

```
ERROR in ./lib/views/sticker-template/StickerTemplateFormModal.js 1:0-81
Module not found: Error: Can't resolve '@babel/runtime-corejs3/core-js-stable/object/assign' in '/Users/abc/Documents/SallingGroup/test/merchandise-ui/apps/sticker/lib/views/sticker-template'
 @ ./lib/views/sticker-template/StickertTemplateView.js 24:0-99 37:11-38 96:41-65
 @ ./lib/App.js 7:9-9:3
 @ ./lib/index.js 5:0-43 29:44-62

ERROR in ./lib/views/sticker-template/StickerTemplateFormModal.js 2:0-86
Module not found: Error: Can't resolve '@babel/runtime-corejs3/core-js-stable/instance/map' in '/Users/abc/Documents/SallingGroup/test/merchandise-ui/apps/sticker/lib/views/sticker-template'
 @ ./lib/views/sticker-template/StickertTemplateView.js 24:0-99 37:11-38 96:41-65
 @ ./lib/App.js 7:9-9:3
 @ ./lib/index.js 5:0-43 29:44-62

ERROR in ./lib/views/sticker-template/StickerTemplateFormModal.js 3:0-92
Module not found: Error: Can't resolve '@babel/runtime-corejs3/core-js-stable/instance/concat' in '/Users/abc/Documents/SallingGroup/test/merchandise-ui/apps/sticker/lib/views/sticker-template'
 @ ./lib/views/sticker-template/StickertTemplateView.js 24:0-99 37:11-38 96:41-65
 @ ./lib/App.js 7:9-9:3
 @ ./lib/index.js 5:0-43 29:44-62

ERROR in ./lib/views/sticker-template/StickerTemplateFormModal.js 4:0-90
Module not found: Error: Can't resolve '@babel/runtime-corejs3/core-js-stable/instance/slice' in '/Users/abc/Documents/SallingGroup/test/merchandise-ui/apps/sticker/lib/views/sticker-template'
 @ ./lib/views/sticker-template/StickertTemplateView.js 24:0-99 37:11-38 96:41-65
 @ ./lib/App.js 7:9-9:3
 @ ./lib/index.js 5:0-43 29:44-62

ERROR in ./lib/views/sticker-template/StickertTemplateView.js 1:0-81
Module not found: Error: Can't resolve '@babel/runtime-corejs3/core-js-stable/object/assign' in '/Users/abc/Documents/SallingGroup/test/merchandise-ui/apps/sticker/lib/views/sticker-template'
 @ ./lib/App.js 7:9-9:3
 @ ./lib/index.js 5:0-43 29:44-62

ERROR in ./lib/views/sticker-template/useStickerTemplateEvents.js 1:0-92
Module not found: Error: Can't resolve '@babel/runtime-corejs3/core-js-stable/instance/concat' in '/Users/abc/Documents/SallingGroup/test/merchandise-ui/apps/sticker/lib/views/sticker-template'
 @ ./lib/views/sticker-template/StickertTemplateView.js 25:0-70 41:2-26
 @ ./lib/App.js 7:9-9:3
 @ ./lib/index.js 5:0-43 29:44-62
```

Any idea 😬 ?
Thanks
Sjoerd

**Comment by emmenko** [comment]
Hi @planetcrypton 👋

Thanks for reaching out.

This looks like some kind of dependency version resolution issue.

Could you check with `yarn why @babel/runtime-corejs3` and see if there are different versions of the package installed? Usually this is one of the causes of such issues.

Let me know what you find, thanks.

**Comment by planetcrypton** [comment]
Yes, there's two versions:
`'@babel/runtime-corejs3': 7.14.7` (dependency of `@commercetools-community-kit/i18n/0.2.7`)
`'@babel/runtime-corejs3': 7.17.9 (dependency of the other commercetools packages)`

**Comment by emmenko** [comment]
I see thanks.

I would suggest to try defining a yarn resolution (in `package.json` define a `resolutions` object, for example [like this](https://github.com/commercetools/merchant-center-application-kit/blob/8d3fe74b7987dd62c535e367a9a76bf3d7816c1a/package.json#L160)) for this dependency.

```json
{
  "resolutions": {
    "@babel/runtime-corejs3": "7.17.9"
  }
}
```

This might help with resolving the package correctly.

Let me know how it goes.

**Comment by planetcrypton** [comment]
I tried just that, but with our Rush / pnpm setup; it does not solve the issue.
But in the meanwhile I've spun up a 'plain' app with `create-mc-app` (that has the same versions for the packages I mentioned above) and found out that this does _not_ give any errors, even though _it also has v`7.17.9` and `7.14.7`_ of `@babel/runtime-corejs3`.
So I suspect our Rush stack to cause this somehow - though still clueless why and where..

**Comment by emmenko** [comment]
Ah I never used or heard about https://rushjs.io/ to be honest. I don't know how dependencies are resolved, so probably the suggestion `resolutions` won't do anything because it's specific to Yarn workspaces.

Let me know if I can assist you in any other way.

**Comment by planetcrypton** [comment]
I can't figure out why pnpm does not resolve this `@babel/runtime-corejs3` package. But a workaround is just to add the package to `package.json`.
