### ISSUE TITLE
Custom Application works locally, but does not work when deployed into Netlify

### ISSUE THREAD

**Issue by Nadeera-Gayashan** [commercetools/merchant-center-application-kit#2642]
**Describe the issue**

**### SUPPORT-16824**

Custom Application works locally, but does not work when deployed into Netlify

I have used this "https://github.com/commercetools/merchant-center-application-kit/tree/main/application-templates/starter" template to generate the custom application and changed the values in "custom-application-config.mjs" according to the my project.

The application runs locally without any error and it can be viewed the channel list.

When it deployed into Netlify, we can access to the home page but cannot view the channel list with the error of "_Insufficient scope. One of the following scopes is missing: view_products_"

**To Reproduce**

1. Go to Netlify 'https://frolicking-gumption-973e94.netlify.app/'
2. Click on 'Starter B02e61/Channels'
3. See error

**Expected behavior**

Show the channel list

**Screenshots**

This is the channel list obtain at the local deployment.
![image](https://user-images.githubusercontent.com/88052829/173485702-c5418470-3c10-4db9-83d5-e79f0979777f.png)

This is the error that get at the Netlify.
![image](https://user-images.githubusercontent.com/88052829/173485903-4b328fdf-460a-454e-8ce6-d30c8c9f1291.png)

**Additional context**

Here are some findings obtain through the troubleshooting

1. Graphql responses for each local and Netlify deployments get different results

Graphql response for Local deployment
![image](https://user-images.githubusercontent.com/88052829/173486531-f2cdb95a-84b1-4ad9-afe7-42ec46dfaf6a.png)

Graphql response for Netlify deployment
![image](https://user-images.githubusercontent.com/88052829/173486509-b4182314-cd97-418b-b120-9f8dee1055c1.png)

2. Variables of Session storages are not available for Netlify deployment

Session storage for local deployment
![image](https://user-images.githubusercontent.com/88052829/173486736-8648122e-91a4-40fa-99b8-4dd7809cc0c1.png)

Session storage for Netlify deployment
![image](https://user-images.githubusercontent.com/88052829/173486859-ff97e2dc-e626-451f-83e8-ff0a7caf134c.png)

**Comment by Rhotimee** [comment]
Hi @Nadeera-Gayashan, thank you for reporting the issue! We'll take a look at the problem shortly and let you know.

**Comment by Nadeera-Gayashan** [comment]
Hi @emmenko,

The issue was fixed after implementing the provided resolution. Thank you for the given support 👍
