### ISSUE TITLE
Commerce tools - Permissions not working after upgrading to v21 - Org level

### ISSUE THREAD

**Issue by jbsethi** [commercetools/merchant-center-application-kit#2647]
I have followed the migration guide and upgraded to ORG level settings but i am not able to access the permissions

Following is the config changes

```js
const config = {
    name: "Custom Merchant App",
    entryPointUriPath: entryPointUriPath,
    cloudIdentifier: "gcp-eu",
    env: {
      production: {
        applicationId: "*******************",
        url: envConfig.cdnUrl,
      },
      development: {
        initialProjectKey: "*****************"
      }
    },
    oAuthScopes: {
      view: ["view_customers", "view_orders", "view_types", "view_api_clients", "view_products", "view_project_settings"],
      manage: ["manage_customers", "manage_products", "manage_project_settings"]
    },
    headers: headerConfig,
    icon: "${path:@commercetools-frontend/assets/application-icons/rocket.svg}",
    mainMenuLink: {
      key: "custom_configurations",
      uriPath: "custom_configurations",
      permissions: [PERMISSIONS.View],
      featureToggle: null,
      submenu: [],
      defaultLabel: "Custom Configurations",
      labelAllLocales: [
        {
          locale: "en",
          value: "Custom Configurations"
        },
        {
          locale: "de",
          value: "Custom Configurations"
        },
        {
          locale: "es",
          value: "Custom Configurations"
        }
      ]
    }
  }

  export default config
```
  
  
  
  Following is const file
  
```js
import { entryPointUriPathToPermissionKeys } from '@commercetools-frontend/application-shell/ssr';

export const entryPointUriPath = 'custom_configurations';

export const FEATURE_FLAGS = {};

export const PERMISSIONS = entryPointUriPathToPermissionKeys(entryPointUriPath);
```

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/27204988/174060941-3a8b8ca8-a357-4f84-b1f2-fa9997011c8d.png">

i know i can just remove this part but i need to use permissions and its not working

**Comment by mmaltsev-ct** [comment]
Hi @jbsethi, thank you for reaching out regarding the bug. We need to take a closer look at the problem and will get back soon.

**Comment by Rhotimee** [comment]
Hello @jbsethi, the problem is not very clear. 

Are you trying to get the user permissions? If that is the case, you can get the userPermissions using the `useApplicationContext` hook.
```
const userPermissions = useApplicationContext((appContext) => appContext.permissions);
```

But, if the problem is that you're getting an unexpected `Unauthorized page`,  that may mean that the team you belong to does not have the right permissions.

Kindly clarify the problem and provide the team you belong to so we can help you better. 

Additionally, the View Permission check is automatically done in the ApplicationShell component and can be removed in the routes file.

**Comment by jbsethi** [comment]
i am using useIsAuthorized to check if i can view the app or redirect. i have the permission to view application but for some reason i am not able to when i remove my custom useIsAuthorized the app works fine but i need that check in order to understand what might be wrong.

I also tried creating a new custom app just to test and in new app it works perfectly fine and useIsAuthorized is returning true but in old that i updated its not working and returning false.

**Comment by emmenko** [comment]
@jbsethi Hi 👋

Can you clarify if this is happening in development or production?

**Comment by jbsethi** [comment]
tried both in both cases it returns false

**Comment by emmenko** [comment]
In development it's not possible that it returns `false`, as you are supposed to be an administrator of the project.

In development, open the devtools and check the GraphQL query `FetchProject` in the console tab. Look for the field `data.project.allAppliedPermissions`.

Can you provide that data or a screenshot of it?

**Comment by jbsethi** [comment]
![image](https://user-images.githubusercontent.com/27204988/174747173-cc052324-1f88-4bcf-8b25-227156e8872d.png)

**Comment by jbsethi** [comment]
Yeah but it is evaluating to false

**Comment by jbsethi** [comment]
Any fix for the issue ? @emmenko , @Rhotimee , @mmaltsev-ct
