### ISSUE TITLE
The new View/Manage CUSTOM APP scopes are limiting - need to be able to create additional scopes 

### ISSUE THREAD

**Issue by luddilo** [commercetools/merchant-center-application-kit#2649]
**Is your feature request related to a problem? Please describe.**

Our custom application uses granular access controls to control certain aspects of the app, like creating discount codes and viewing payments. Creating discount codes only certain people in the organization should be able to do. The same people should also be the only people that can view (and manage) payments. 

The new custom-app specific View and Manage permissions are VERY limited and would force us to split our custom app into many different apps which seems highly inefficient. 

Why was this decided upon and what is the rationale? I get that the apps was coupled to user-permissions and that technically that might not be ideal, but since this takes custom app access control SEVERAL steps back, how can you not provide an alternate solution for it - like allowing us to create more than the View and Manage permissions for the custom app for example?

**Describe the solution you'd like**

Probably allow us to create additional scopes other than ViewCustomApp and ManageCustomApp.

**Describe alternatives you've considered**

We would have to split our custom app into several smaller pieces..

**Additional context**

**Comment by luddilo** [comment]
Cool, thanks for the information. And good that you extend the deadline, I
think that makes sense. We definitely underestimated the amount of work
needed going from 18.x to 21.x.

/L
-

Ludvig Linse
***@***.***

<https://www.linkedin.com/in/ludviglinse>


Den tis 21 juni 2022 kl 18:18 skrev Maxim ***@***.***>:

**Comment by luddilo** [comment]
@mmaltsev-ct when will we know if the migration period will be extended or not?

**Comment by mmaltsev-ct** [comment]
Hey @luddilo, the migration period will be extended, at least by one month. We will decide on the exact date in the next few days and prepare a notification for the Merchant Center.

**Comment by rahulparkhe-vizio** [comment]
Hi @mmaltsev-ct , Was this concern addressed in any version? 
We are facing the same issue and had created a support ticket https://jira.commercetools.com/servicedesk/customer/portal/1/SUPPORT-17475. Please let us know when more granular permissions are available.

**Comment by mmaltsev-ct** [comment]
Hi @rahulparkhe-vizio, we're finalizing the RFC for introducing extra permissions at the moment, but there is no implementation in place yet. This feature has quite a high priority for us, so I'll be posting updates here as soon as we have something to share.

**Comment by rahulparkhe-vizio** [comment]
Hi @mmaltsev-ct , following up on this issue, is the update out?

As we approach the dead line of v21 upgrade (Sept 15 2022), this issue is a blocker for us. While we wait for the fix version, we would really appreciate if you could suggest us a workaround to be functional post 09/15.

**Comment by mmaltsev-ct** [comment]
Hi @rahulparkhe-vizio,

we've started the development, but the finalized feature would be introduced after 09/15. I will schedule a call shortly and invite you to discuss how to proceed with your use case.

**Comment by luddilo** [comment]
Hey @mmaltsev-ct 

What is the status of this now, a few months later? We are considering to write a customer support application outside of the MC custom app ecosystem mostly due to this limitation. I would really like to avoid this though..

**Comment by emmenko** [comment]
Hey @luddilo 👋

We're currently in the process of finalizing the release. You can see here (#2806) the upcoming documentation updates in case you want to see how the new feature works.

We have had some delays with other internal projects and black friday but we're almost ready now.

We don't have a release date but it will happen within the next couple of weeks for sure. Does that work with your timeline?

**Comment by emmenko** [comment]
Hi, we are happy to announce that the multiple permissions feature has been released: https://docs.commercetools.com/custom-applications/releases/2022-12-09-custom-applications-multiple-permissions

If you have questions or issues don't hesitate to reach out to us. Thanks.
