### ISSUE TITLE
New org-level custom app gets stuck in redirect loop

### ISSUE THREAD

**Issue by jvanmaaren** [commercetools/merchant-center-application-kit#2668]
**Describe the issue**

Hi, we’ve created a new org-level custom application (based on the Merchant Center template), which works fine on local development machine. It doesn’t work in the test env however, it gets stuck in a redirect loop, with no errors debug, so we don't know how to continue from here on.

**To Reproduce**

We’re trying the most basic test possible:

- In order to test what’s going wrong, we’ve now uploaded the MC default app (using npx @commercetools-frontend/create-mc-app). We added the app in custom-application-config.mjs and in online configuration.
- We ran yarn build and uploaded the contents to the root of the s3 bucket
- We added a cloudfront distribution. So for instance you can see that stats.json exists: https://d1l8crytc8fa95.cloudfront.net/stats.json
- We redirected error pages to index.html with status code 200 on both s3 and cloudfront
- We added MC allowed origins as a custom origin to prevent CSP errors

**Expected behavior**

We expect the MC template apps to load

**Screenshots**

Here is all our config:

![cloudfront error page redirect](https://user-images.githubusercontent.com/53424491/176184315-f8720f66-b4c0-4d0e-9e96-08282bff5e49.png)
![cloudfront origins](https://user-images.githubusercontent.com/53424491/176184322-2dc8c206-705d-4556-927c-643576f0cf01.png)
![MC configuration](https://user-images.githubusercontent.com/53424491/176184324-57dc3311-4810-43da-a185-c769637b9344.png)
![MC custom application mjs](https://user-images.githubusercontent.com/53424491/176184330-4499d131-5e60-4835-b373-5afa3b5d83c3.png)
![s3 public available](https://user-images.githubusercontent.com/53424491/176184337-4719866f-a7cf-4b2c-8530-70859b2e1d7b.png)
![s3 static hosting settings](https://user-images.githubusercontent.com/53424491/176184341-66cd3e2f-e0dc-4c0a-8f71-6d3153c2736f.png)
![s3 static hosting](https://user-images.githubusercontent.com/53424491/176184345-326c2588-231c-4f99-877b-a8a1cababce2.png)

**[EDIT: SOLVED]**

Our original problem originated in the s3 bucket. We had multiple apps in one bucket, which the redirect couldn't handle.
 We needed to have redirect between our pages and the SPA app, so that the SPA app could take over routing properly. The same goes for the cloud front setup. So as a tip, make sure you use a new bucket with your app in the root, so there won't be any confusion between which apps are loaded.

**Comment by jvanmaaren** [comment]
Hi @kark thanks for your reply. It seems we didn't update the entryPointUriPath in the last changes, thanks!

We do still have a second problem, which is that the "/channels" path doesn't load

- It shows the PageUnauthorized component ("_We could not find what you are looking for. The module you are looking for either does not exist for this project or you are not authorized to view it._")
- This strange, since I'm an administrator, and we didn't change any of the template code?
- The oAuthScopes are the same in the custom-application-config and the app settings in MC (view_products, manage_products).
- On localhost `/channels` **does** load! We do see a warning `22271.js:sourcemap:176299 Warning: @commercetools-frontend/permissions: It is recommended not to use 'shouldMatchSomePermissions' but instead use the hook, HoC or component multiple times`

**Comment by kark** [comment]
Hi again @jvanmaaren 👋 

Glad to hear about the first issue.

Regarding the other one, would it be possible for you to share a screenshot of the result of the `FetchProject` GraphQL query run from within the application in the Merchant Center (in case you use Chrome it’s in the Developer tools > Network tab)?

Also, would you mind applying the following snippet in your Custom Application and sharing the `permissions` from the application context with us:
```jsx 
// src/routes.jsx
// …
import { useApplicationContext } from '@commercetools-frontend/application-shell-connectors';

// …
const ApplicationRoutes = () => {
  const match = useRouteMatch();
  const permissions = useApplicationContext((context) => context.permissions);
  console.log({ permissions });
  // …
}
```
That should log the permissions value in the browser's console when your deployed Custom Application is accessed from the Merchant Center.

Thanks

**Comment by kark** [comment]
Hello again,

Would you also mind sharing the list of dependencies in your `package.json`?

Thank you

**Comment by jvanmaaren** [comment]
Hi Kark, this is very strange but after uploading the permissions console.logs, the channels page suddenly works

We do see a difference between local and test environment:

Local has both 'view' and 'manage'

<img width="490" alt="permissions-local" src="https://user-images.githubusercontent.com/53424491/176861677-57402a3f-8527-4f8f-ad34-8ee20053aea9.png">

Test only has 'manage'
<img width="699" alt="permissions-test" src="https://user-images.githubusercontent.com/53424491/176861681-f7c1bc15-c62c-4c44-a6ee-35a75b058740.png">


For now our problems seem solved, thank you for you support!
