### ISSUE TITLE
Authentication Request to AWS Lambda Graphql API Failed

### ISSUE THREAD

**Issue by Nadeera-Gayashan** [commercetools/merchant-center-application-kit#2673]
**Describe the issue**

I am trying to implement authorization between a commercetools custom application and an eternal Graphql API hosted on AWS Lambda function using ‘Express.js’. But it was getting failed with the below error.

```
{{2022-06-30T09:49:10.968Z ae9a1d9f-231f-4516-bb18-9867c908c1e2 INFO sessionAuthVerifier - ERROR: }}Error: Missing "X-MC-API-Cloud-Identifier" header.
at getFirstOrThrow (/var/task/node_modules/@commercetools-backend/express/dist/commercetools-backend-express.cjs.dev.js:61:11)
at _callee$ (/var/task/node_modules/@commercetools-backend/express/dist/commercetools-backend-express.cjs.dev.js:192:39)
at tryCatch (/var/task/node_modules/@babel/runtime-corejs3/helpers/regeneratorRuntime.js:105:17)
at Generator._invoke (/var/task/node_modules/@babel/runtime-corejs3/helpers/regeneratorRuntime.js:85:24)
at Generator.next (/var/task/node_modules/@babel/runtime-corejs3/helpers/regeneratorRuntime.js:139:21)
at asyncGeneratorStep (/var/task/node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:5:24)
at _next (/var/task/node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:27:9)
at /var/task/node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:34:7
at new Promise (<anonymous>)
at new Wrapper (/var/task/node_modules/core-js-pure/internals/export.js:18:24)
```

I have attached screenshots of custom application and lambda function code snippets.
Note: I have checked both with and without `X-MC-API-Cloud-Identifier` header.

Also I have attached the network request originated from custom app.

**Expected behavior**

User need to be authorized

**Screenshots**

Code Snippet of Custom App
![Code Snippet of Custom App](https://user-images.githubusercontent.com/88052829/176736473-e5519e6b-86f2-4a6f-a9e7-a2d848e9fdc4.PNG)

Code Snippet of Lambda Function
![Code Snippet of Lambda Function](https://user-images.githubusercontent.com/88052829/176736524-15c8a77b-4650-454e-832c-3dda66849772.PNG)

Network Request
![Network Request - General](https://user-images.githubusercontent.com/88052829/176736605-a094526a-2a4c-4d7f-b9f6-4f84f8878252.PNG)
![Network Request - Request Header - Part 1](https://user-images.githubusercontent.com/88052829/176736608-455b6285-19ae-406b-b7a4-281647aa716d.PNG)
![Network Request - Request Header - Part 2](https://user-images.githubusercontent.com/88052829/176736610-f47fccbe-cb34-4421-b443-b4fa4358f1a1.PNG)
![Network Request - Response Header](https://user-images.githubusercontent.com/88052829/176736612-fad6d4e0-2a4e-44e4-b7a0-efbcdd58836b.PNG)

**Additional context**

SUPPORT-17025

**Comment by emmenko** [comment]
Hi @Nadeera-Gayashan  👋

Thanks for the detailed report.

The `X-MC-API-Cloud-Identifier` header is set by the Merchant Center API so you don't need to set it on your own. For instance, the `headers` object of `createApolloContextForProxyForwardTo` is only meant to send custom headers to your API.

Also the value of the `X-MC-API-Cloud-Identifier` is one of the cloud identifiers, not a URL:
https://github.com/commercetools/merchant-center-application-kit/blob/21b8cc2febac35b205565cbfa56318c6596a265e/packages-backend/express/src/constants.ts#L1-L7

Could you maybe add a debug log like `console.log(event.headers)` in your lambda function to print out the incoming request headers?

```js
exports.handler = async function (event, context) {

  console.log(event.headers);

  try {
    await sessionAuthVerifier(event, context);
  } catch (error) {
    return {
      statusCode: 401,
      body: JSON.stringify({ message: 'Unauthorized' }),
    };
  }
  // `event.session` contains the useful information
};
```

I'm interested to see how the `X-MC-API-*` headers are defined.
Thanks, looking forward to your reply.

**Comment by Nadeera-Gayashan** [comment]
Hi emmenko,

Here is the result that I got. There is the mentioned header.

```
2022-07-01T02:00:50.457Z	f2359e4`5-d652-4`5a0-afa0-89b87fbc9ef3	INFO	{
  Accept: 'application/json',
  'Accept-Encoding': 'gzip, deflate, br',
  'Accept-Language': 'en-US,en;q=0.9',
  Authorization: 'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlVLdmJld2tiNzZ1YXNTSmpXNmluNXRETEJ6UDNpVTNETkFlWVpVR250d0UifQ.eyJleHAiOjE2NTY2NDA5MDksInN1YiI6IjM3OWYxNWZiLTM4YzEtNDNkYi1hZGMzLWI4YTk4MWFiODNiMyIsImlzcyI6Imh0dHBzOi8vbWMtYXBpLnVzLWNlbnRyYWwxLmdjcC5jb21tZXJjZXRvb2xzLmNvbSIsImF1ZCI6Imh0dHBzOi8vN3p3N3B1d3lrNy5leGVjdXRlLWFwaS51cy1lYXN0LTEuYW1hem9uYXdzLmNvbS9kZXYvZ3JhcGhxbCIsInR5cGUiOiJleGNoYW5nZSIsImh0dHBzOi8vbWMtYXBpLnVzLWNlbnRyYWwxLmdjcC5jb21tZXJjZXRvb2xzLmNvbS9jbGFpbXMvcHJvamVjdF9rZXkiOiJsaWhpbmktcHJhY3Rpc2UiLCJpYXQiOjE2NTY2NDA4NDl9.kBXlDLdP-mNg5ALyTPaxJjRT22tF1gt2H5IYxf0e2TTML9nEijUYN3Wcnd177JVSPUT-I60FWq-0uxdY83PK7nrc-DOJQ1lE1Muw6yc-0BUqZhUVYfwKLMMzSy9kPZJ1cohs3QP8hzf1PK2duLe92cf1pFDl6htCYev5231B_y3TKcdomCCrfuyIxLxJqAbSt9prvUzTIZWPYRPN3SPWT5AwO2XlK85jD1rfl5IN60a1jHugQ-_paFek0yZUvDJLehWcbeOgoV9lipQD3eCc8iujjqc5swvjm4AIneoIXtSXbNCjJqB8gP7q-mU8xW-tPAir0WrZJRmcXa0unPNFcw',
  'CloudFront-Forwarded-Proto': 'https',
  'CloudFront-Is-Desktop-Viewer': 'true',
  'CloudFront-Is-Mobile-Viewer': 'false',
  'CloudFront-Is-SmartTV-Viewer': 'false',
  'CloudFront-Is-Tablet-Viewer': 'false',
  'CloudFront-Viewer-Country': 'US',
  'content-type': 'application/json',
  Host: '7zw7puwyk7.execute-api.us-east-1.amazonaws.com',
  origin: 'http://localhost:3001',
  'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"',
  'sec-ch-ua-mobile': '?0',
  'sec-ch-ua-platform': '"Windows"',
  'sec-fetch-dest': 'empty',
  'sec-fetch-mode': 'cors',
  'sec-fetch-site': 'cross-site',
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36',
  Via: '1.1 google, 1.1 1bfeca785e36f5deb3a11ad4668f4a70.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'wndUA1ZGeyqlrADjGOKmPeJUY7NbpaYPaNZXeejXIJZrSOnUCqr5wA==',
  'X-Amzn-Trace-Id': 'Root=1-62be5551-54395c3a02ec444c07b30656',
  'x-app-http-client-name': 'apollo-client',
  'x-app-http-client-version': '',
  'x-app-name': 'Auth',
  'x-app-package-name': 'application-shell',
  'x-app-package-version': '21.7.0',
  'x-application-id': '__local:clouda-auth',
  'x-cloud-trace-context': 'b2ec974f1436bb2604f5a68640f02f36/223560750634262;o=1',
  'X-Forwarded-For': '112.134.137.178, 35.201.83.117, 35.222.235.13, 130.176.11.147',
  'X-Forwarded-Port': '443',
  'X-Forwarded-Proto': 'https',
  'x-graphql-operation-name': 'FetchAWSGraphqlAPI',
  **'X-MC-API-Cloud-Identifier': 'gcp-us',**
  'X-MC-API-Forward-To-Version': 'v2',
  'x-user-agent': 'apollo-client Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36 Clouda Auth/application-shell/21.7.0 (+https://git.io/fjuyC; +support@commercetools.com)'
}
```


But still got the same error.

```
2022-07-01T02:00:50.491Z	f2359e45-d652-45a0-afa0-89b87fbc9ef3	INFO	sessionAuthVerifier - ERROR:  Error: Missing "X-MC-API-Cloud-Identifier" header.
    at getFirstOrThrow (/var/task/node_modules/@commercetools-backend/express/dist/commercetools-backend-express.cjs.dev.js:61:11)
    at _callee$ (/var/task/node_modules/@commercetools-backend/express/dist/commercetools-backend-express.cjs.dev.js:192:39)
    at tryCatch (/var/task/node_modules/@babel/runtime-corejs3/helpers/regeneratorRuntime.js:105:17)
    at Generator._invoke (/var/task/node_modules/@babel/runtime-corejs3/helpers/regeneratorRuntime.js:85:24)
    at Generator.next (/var/task/node_modules/@babel/runtime-corejs3/helpers/regeneratorRuntime.js:139:21)
    at asyncGeneratorStep (/var/task/node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:5:24)
    at _next (/var/task/node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:27:9)
    at /var/task/node_modules/@babel/runtime-corejs3/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new Wrapper (/var/task/node_modules/core-js-pure/internals/export.js:18:24)

```

Thanks

**Comment by emmenko** [comment]
@Nadeera-Gayashan Thanks for the info.

This is a bug in our `@commercetools-backend/express` package as we expected the incoming request header to always be lowercase: `X-MC-API-Cloud-Identifier` vs `x-mc-api-cloud-identifier`.
This was causing the check to throw an error.

Apparently this seems to happen only in lambda functions.

We'll let you know once the fix is released.

Apologies for the inconvenience.

**Comment by Nadeera-Gayashan** [comment]
Hi emmenko,

Thank you for the quick response.

Is there any workaround to solve this issue until the fix is released?

Thanks

**Comment by emmenko** [comment]
Hi, the fix has been released in `v12.8`. See also [release notes](https://docs.commercetools.com/custom-applications/releases/2022-07-01-custom-applications-v218) for other useful info about the new release.

**Comment by emmenko** [comment]
Let us know if still have questions or other problems. Thanks

**Comment by emmenko** [comment]
Yes we released it about an hour ago.

**Comment by Nadeera-Gayashan** [comment]
Hi emmenko,

I have updated express to v21.8 and deployed. Now the header issue is sorted. But the below error is given.

The audience value that I have set: https://7zw7puwyk7.execute-api.us-east-1.amazonaws.com
```
2022-07-01T11:48:57.088Z	d0416a9b-4986-4671-ae99-30e8c3852f2d	INFO	sessionAuthVerifier - ERROR:  Error [UnauthorizedError]: jwt audience invalid. expected: https://7zw7puwyk7.execute-api.us-east-1.amazonaws.comundefined/
    at new UnauthorizedError (/var/task/node_modules/express-jwt/dist/errors/UnauthorizedError.js:22:28)
    at /var/task/node_modules/express-jwt/dist/index.js:159:35
    at step (/var/task/node_modules/express-jwt/dist/index.js:56:23)
    at Object.next (/var/task/node_modules/express-jwt/dist/index.js:37:53)
    at fulfilled (/var/task/node_modules/express-jwt/dist/index.js:28:58) {
  code: 'invalid_token',
  status: 401,
  inner: JsonWebTokenError: jwt audience invalid. expected: https://7zw7puwyk7.execute-api.us-east-1.amazonaws.comundefined/
      at /var/task/node_modules/jsonwebtoken/verify.js:167:21
      at getSecret (/var/task/node_modules/jsonwebtoken/verify.js:90:14)
      at Object.module.exports (/var/task/node_modules/jsonwebtoken/verify.js:94:10)
      at /var/task/node_modules/express-jwt/dist/index.js:156:33
      at step (/var/task/node_modules/express-jwt/dist/index.js:56:23)
      at Object.next (/var/task/node_modules/express-jwt/dist/index.js:37:53)
      at fulfilled (/var/task/node_modules/express-jwt/dist/index.js:28:58)
}
```

**Comment by emmenko** [comment]
Hi @Nadeera-Gayashan ,

It looks like the issue might be caused by returning a wrong value in the `getRequestUrl` function.
As [documented in our docs](https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api#usage-for-serverless-functions) for using this in lambda functions, the `getRequestUrl` function should be used to correctly map the request URL based on the request object available in the lambda function.

Apparently, this request object (called [event](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) in lambda functions) differs based on the lambda version used.
For example v2 has the property `rawPath` but v1 doesn't.

The example we provide in the documentation is based on v2 using `rawPath` but it might be that your lambda uses a different version and thus `event.rawPath` yields `undefined`.

```js
// Using v2
getRequestUrl: (event) => `${event.rawPath}${event.rawQueryString ? '?' + event.rawQueryString : ''}`
```

Can you double check that please?

**Comment by Nadeera-Gayashan** [comment]
Hi @emmenko,

I have checked that and find out that is Lambda v1. I corrected the logic and get the expected results.

Thank you for the given support.
