### ISSUE TITLE
[docs] Request deployment example for [Authorization of an External Graphql/REST API in AWS Lambda Function]

### ISSUE THREAD

**Issue by Nadeera-Gayashan** [commercetools/merchant-center-application-kit#2674]
**Where would you like to deploy your Custom Application?**
gcp-us

**Additional context**
Add any other context or information about the requested example.

**Comment by emmenko** [comment]
Hi @Nadeera-Gayashan 

I suppose this is related to the other issue you opened #2673 . Is this still relevant?

We do have some documentation about integrating this with serverless functions: https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api#usage-for-serverless-functions
Is there something missing on unclear about that document?

PS: This issue template is meant more for [deployment example](https://docs.commercetools.com/custom-applications/deployment-examples), for the hosting part.
