### ISSUE TITLE
[docs] Request deployment example for Azure Cloud

### ISSUE THREAD

**Issue by lucbard-sap** [commercetools/merchant-center-application-kit#2683]
**Where would you like to deploy your Custom Application?**
Azure Cloud

**Additional context**
Can we deploy it using a Function or do we need an App Service ?

**Comment by Rhotimee** [comment]
Hi @lucbard-sap, 
Thank you, we will consider the request for the deployment example for Azure cloud. 

In addition, the process to deploy a Custom Application is essentially the same process as other client-side applications. 
See resources below on deploying a react app on Azure. This can guide you to doing the same for a Custom Application.

https://www.pluralsight.com/guides/deploy-a-react-app-to-azure
https://medium.com/geekculture/easiest-way-to-host-your-react-app-azure-vs-code-8046f9f7fb0b
