### ISSUE TITLE
[docs] Request deployment example for google cloud platform

### ISSUE THREAD

**Issue by JonYeb** [commercetools/merchant-center-application-kit#2685]
**Where would you like to deploy your Custom Application?**
We would like to deploy a custom application to google cloud platform. So it would be great to have a deployment example like you have for the other services.

**Comment by Rhotimee** [comment]
Hi @JonYeb,
Thank you, we will consider the request for the deployment example for the Google cloud platform.

**Comment by emmenko** [comment]
Hi @JonYeb 

Is there any specific setup you were looking for? For example using AppEngine or Storage buckets or something else?

Also, if you don't mind us asking, is there a specific reason for choosing Google Cloud for this case?

Thanks.

**Comment by JonYeb** [comment]
HI @emmenko 
After getting back to my team we would use the Storage buckets. After looking at the AWS example it would be the most similar for us. From that we could figure the deployment out our-self but it would always be nice to have an official documentation to double check ;)

As for the reason it is simply that we use google cloud platform internally already for a bunch of other projects so it would be the most convenient for us.

**Comment by emmenko** [comment]
Hi @JonYeb 

Thanks for the feedback.

To be honest, hosting a Single Page Application on Google Cloud is not straight forward and vary depending on the setup and services that you want to use.

Of course using Google Cloud Storage seems like the easy option but there is one important point to consider in a SPA setup: configuring the rewrite rules for always serving the `index.html`.

A cloud storage like GCS or S3 do not have any such built-in functionality so you would need something in front to be able to handle that.

There are some workarounds like enabling "Static site hosting" and configuring both the "index" document and the "error" document to be pointing to the `index.html` but it's not an ideal setup.

Then there are other services like App Engine or Firebase hosting but you need to consider if the pricing offer is acceptable for you or not.

Could you share maybe which approach/solution you are currently using or planning to use?
