### ISSUE TITLE
[docs] Request deployment example for AWS Lambda

### ISSUE THREAD

**Issue by Nadeera-Gayashan** [commercetools/merchant-center-application-kit#2692]
**Where would you like to deploy your Custom Application?**
AWS

**Additional context**
Can I call  commercetools Composable Commerce APIs from AWS Lambda function? If so, please provide an example

**Comment by Rhotimee** [comment]
Hello @Nadeera-Gayashan, could you describe what you're trying to achieve and how this relates to the Custom Applications?

**Comment by Nadeera-Gayashan** [comment]
Hello @Rhotimee,

Please refer to the below instance.

1. I need to call an external Graphql API hosted at AWS Lambda function, using a custom application
2. This Graphql API need to get data from commercetools using composable commerce API 

I need to know how I call composable commerce APIs from AWS Lambda function.

Thanks & BR,
Nadeera

**Comment by Rhotimee** [comment]
Hi @Nadeera-Gayashan,

From what we understand, it seems like you are looking to use the `/proxy/forward-to` endpoint to [integrate with your own API](https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api). This allows you to securely authenticate your Custom Application with your external API.

From your GraphQL API is then up to you to securely connect to the Composable Commerce APIs. Usually, this is done [using an API client](https://docs.commercetools.com/getting-started/create-api-client).

In case this is not what you were looking for, could you maybe share more details about your use case and requirements?
Thanks

**Comment by Nadeera-Gayashan** [comment]
Hi @Rhotimee, 

Thank you for the quick response.

I need to write a Lambda function which can call to commercetools API (just assume to get the product list). That is my requirement.

I need some guide/examples to study about how to write that mentioned Lambda function.

Thanks & BR,
Nadeera

**Comment by Rhotimee** [comment]
Hello @Nadeera-Gayashan, 

If you're only trying to access the commercetools API from the Custom Application, you can do that directly without a lambda function.  You can get more information from the [MC-API](https://docs.commercetools.com/custom-applications/concepts/merchant-center-api) docs. Also, you can get more information from the [docs](https://docs.commercetools.com/api/projects/products) for the product API. 

However, if that's not what you want to achieve, we will need more information about your use case to provide some help.  
Thanks.
