### ISSUE TITLE
Content Security Policy is getting in the way of my app loading

### ISSUE THREAD

**Issue by webwiebe** [commercetools/merchant-center-application-kit#2720]
**Describe the issue**

The meta tag Content Security Policy generated by the index.template is getting in the way of the example "Channels" application. See screenshot. An error following an error about a CSP policy is the only lead you'll get for debugging this issue; 

```Uncaught TypeError: Cannot read properties of undefined (reading 'replace')```

which is about this line

```Re.p = "".concat(window.app.cdnUrl.replace(/\/$/, ""), "/")```

Apparently the inline script defining app on window hasn't been able to run.

Removing the tag fixes the problem.

```
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'self' www.googletagmanager.com/gtm.js www.google-analytics.com/analytics.js 'sha256-10kKQEp2S6U/f4Jjk+THj3d4b9c1/YDfYO5CUs5deBk=' 'sha256-t/NQzJGX6+PlodebcbyH/MHODAdoE348PBEFoUvRfTE=' 'sha256-w76HeW8gP2ql6pVqTMudOZNQpTPhS/eYgpSO8aFuoHA=' 'sha256-iCsbBoM8bmUkPtv6ycSYza0igOOTRcTlRPlJQRsSWb4=' https://api.redacted.net/example-mc-app/; connect-src 'self' app.launchdarkly.com clientstream.launchdarkly.com events.launchdarkly.com app.getsentry.com *.sentry.io www.google-analytics.com https://mc-api.europe-west1.gcp.commercetools.com https://api.redacted.net/example-mc-app/; img-src * data:; style-src 'self' fonts.googleapis.com data: 'unsafe-inline' https://api.redacted.net/example-mc-app/; font-src 'self' fonts.gstatic.com data:; upgrade-insecure-requests ">
```

I would like to know what I did wrong here, how to remove the tag entirely from the template or rather how to fix this issue without disabling the CSP meta tag. 

**Expected behavior**

The page to load without giving content security policy warnings

**Screenshots**

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/2797441/179521461-419891a6-a51f-4cf7-a5df-5c32b8cbc803.png">

**Additional context**

This application is running from within a lambda function behind API gateway in AWS, so not the default setup.

**Comment by Rhotimee** [comment]
Hi @webwiebe, we believe the issue is related to the fact that you're running your app through a lambda function. 
Could you provide more information about the setup and how you use the lambda function to serve the app?

**Comment by webwiebe** [comment]
Hi @Rhotimee,
Thanks for coming back to me so quickly. The Lambda function is a simple node script that serves out the static files that are requested, response only includes the status code, mime-type headers and the actual file-content. The urls are exposed via api-gateway which maps a route to our lambda. 

In order to accommodate for MC's dynamic routing the function will return the contents of index.html if a requested file is not found. (Think of it as a poor-mans .htaccess rewrite-rule)

The setup with a lambda function is a requirement for application landscape, we deploy all our services / components from our infrastructure orchestration file. This is where the second function of the lambda comes in, it replaces the application id and entrypoint in the javascript block because these are configurable using our orchestration layer (apps can be deployed multiple times across multiple clients / environments this way). I guess this changes the hash of this javascript block causing the browser to block it from executing. 

So the question is; how can I prevent hashes from showing up in the CSP meta tag so that I can use the `'unsafe-inline'` policy, or remove the entire CSP tag?
