### ISSUE TITLE
[docs] Request deployment example for [Azure (Docker =>Azure Container Registry =>Azure App Service)]

### ISSUE THREAD

**Issue by patilamit828** [commercetools/merchant-center-application-kit#2721]
**Where would you like to deploy your Custom Application?**
List one of the cloud providers that you would be interested to use, that are not listed in the examples.
**_### [Azure (Docker =>Azure Container Registry =>Azure App Service)]_**

**Additional context**
Add any other context or information about the requested example.

1. To migrate custom application from Project level to Organization level
     a. Followed the documentation and successfully updated the configuration and the development changes
     b. For deployment overridden the output directory with: public.
2. We are deploying the application using  [Azure (Docker =>Azure Container Registry =>Azure App Service)]
3. For docker image we are referring to base image "FROM eu.gcr.io/ct-images/mc-http-server:v16.15.8"

**Error details:**

1.  Error: Could not find "dist/assets" folder. Did you run `yarn build` before starting the server?

2. Error:  should NOT have additional properties: oAuthScopes
    at validateConfig (/app/node_modules/@commercetools-frontend/application-config/build/validate-config.js:53:11)
    at processConfig (/app/node_modules/@commercetools-frontend/application-config/build/process-config.js:64:31)
    at compileHtml (/app/node_modules/@commercetools-frontend/mc-html-template/build/compile-html.js:52:29)
    at start (/app/bin/start-mc.js:88:26)
    at Object. (/app/bin/start-mc.js:110:1)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)

**Packages Used for Migration/Development:**

    "@commercetools-frontend/actions-global": "^21.3.4",
    "@commercetools-frontend/application-components": "^21.3.5",
    "@commercetools-frontend/application-shell": "^21.3.5",
    "@commercetools-frontend/assets": "^21.0.0",
    "@commercetools-frontend/constants": "^21.3.4",
    "@commercetools-frontend/i18n": "^21.3.4",
    "@commercetools-frontend/permissions": "^21.3.4",
    "@commercetools-frontend/ui-kit": "^14.0.6",
    "@commercetools-uikit/flat-button": "^14.0.6",
    "@commercetools-uikit/icons": "^14.0.1",
    "@commercetools-uikit/link": "^14.0.6",
    "@commercetools-uikit/loading-spinner": "^14.0.6",
    "@commercetools-uikit/spacings": "^14.0.6",
    "@commercetools-uikit/text": "^14.0.1",
     "@commercetools-frontend/jest-preset-mc-app": "^21.3.4",
    "@commercetools-frontend/mc-dev-authentication": "^21.0.0",
    "@commercetools-frontend/mc-scripts": "^21.3.4",

**Comment by ddouglasz** [comment]
@patilamit828 , from your **additional context point 3**: the `mc-http-server` has been deprecated and is not used/maintained anymore. It should not be used.
Instead, just use any other alternative server to serve the static files.
The important part is to configure the rewrite rules for serving the `index.html`

**Comment by patilamit828** [comment]
Hello @ddouglasz,
Thanks for your help.

Could you please guide me for any other alternative server /documentation to serve the static files.
Which we can use base image for create app build docker image and deploy it on azure app service.

Thank You,
Amit

**Comment by ddouglasz** [comment]
The server you are using does not really matter as long as the files are served correctly. Some options may include `express`, `serve` or `nginx`.
Also, you need to instruct your server to rewrite all requests to serve the `index.html`.
You can see an example here too https://create-react-app.dev/docs/deployment

**Comment by patilamit828** [comment]
Hello @ddouglasz,
We are trying to deploy CT custom application in azure blob storage, functionality working as expected.
but some of default static CSS and JS are not applied for header and sidebar so look and feel is messed. we are using default css and js provided by CT, not using any additional customize css or js.

Is there any location from where we can download the default static content(css or js) or keep it inside build folder or store in somewhere else and pass as "cdnUrl" in custom-application-config.json

Any help or suggestions are greatly appreciated.

**Comment by ddouglasz** [comment]
Hello @patilamit828,
Please can you provide us with more information on this to help understand the issue better?

- Are there any missing files?
- Do you have errors in the browser (Please share some screenshots if possible)?
- Is this happening on development or production?
- And lastly, What versions of the Custom Apps packages are you using?

**Comment by patilamit828** [comment]
1. Are there any missing files?
- No there are none, but some of the css classes are not getting resolved for eg. headers, aside, div-region so the misplaced from is appearing.
![Custom_App_CSS_Class not resolved](https://user-images.githubusercontent.com/30568131/180767491-939c1aad-0090-4f2e-b25b-7d8bcca1ee57.png)

2. Do you have errors in the browser (Please share some screenshots if possible)?
- Yes,
![Custom_App_Error_400](https://user-images.githubusercontent.com/30568131/180768601-e91bcde2-cd8c-4c63-b40c-4585a8169a14.png)

3. Is this happening on development or production?
- Production
4. And lastly, what versions of the Custom Apps packages are you using?
-  "@apollo/client": "3.3.15",
    "@commercetools-frontend/actions-global": "^21.3.4",
    "@commercetools-frontend/application-components": "^21.3.5",
    "@commercetools-frontend/application-shell": "^21.3.5",
    "@commercetools-frontend/assets": "^21.0.0",
    "@commercetools-frontend/constants": "^21.3.4",
    "@commercetools-frontend/i18n": "^21.3.4",
    "@commercetools-frontend/permissions": "^21.3.4",
    "@commercetools-frontend/ui-kit": "^14.0.6",      // for ui-kit version >21 not available
    "@commercetools-uikit/flat-button": "^14.0.6",
    "@commercetools-uikit/icons": "^14.0.1",
    "@commercetools-uikit/link": "^14.0.6",
    "@commercetools-uikit/loading-spinner": "^14.0.6",
    "@commercetools-uikit/spacings": "^14.0.6",
    "@commercetools-uikit/text": "^14.0.1",
    
    dev dependencies: 
    "@commercetools-frontend/jest-preset-mc-app": "^21.3.4",
    "@commercetools-frontend/mc-dev-authentication": "^21.0.0",
    "@commercetools-frontend/mc-scripts": "^21.3.4",

**Comment by ddouglasz** [comment]
@patilamit828,
Thank you for the information you provided. Please can you share me the error from the console (asides from the network error) if that is also available?

**Comment by patilamit828** [comment]
Resolve the issue by upgrading the ui-kit package version

**Comment by emmenko** [comment]
Thanks for sharing
