### ISSUE TITLE
Frontend SDK forwardTo actions - support PATCH and PUT requests

### ISSUE THREAD

**Issue by alochowski** [commercetools/merchant-center-application-kit#2732]
Hello guys,

I don't see option to send `PATCH` and `PUT` action using **forwardTo** request by your SDK. Is there any chance to send that kind of type requests?
(according to this [doc](https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api#usage-for-sdk-actions))

And second question in this topic: Is there any chance to put payload to `DELETE` action by **forwardTo** request?

Regards,
Arek

**Comment by Rhotimee** [comment]
Hello @alochowski, 
We currently do not support PATCH or PUT requests using forwardTo. 
However, you can use the workaround below. 

```
const action = actions.forwardTo.post({
  uri: 'https://my-custom-app.com/graphql',
  payload: { say: 'Hello' },
});
action.payload.method = 'PUT';
```

As for the second question, you can pass a payload to the DELETE action if you wish to.

**Comment by alochowski** [comment]
Hi @Rhotimee,

Thanks for your answer and an interesting workaround :+1: 

Unfortunately doesn't work for me :/
I've got message from https://mc-api.europe-west1.gcp.commercetools.com/proxy/forward-to that Method `PUT` and `PATCH` is not allowed by Access-Control-Allow-Methods in preflight response.
Do you plan to handle these methods as well?

Regarding `DELETE` method. I've tried to add payload to this request, but unfortunately is not passed to my server by `forwarTo` feature. I don't see body in request from MC. `POST` works correctly.

**Comment by emmenko** [comment]
Hi @alochowski 👋

Sorry for the late reply.

> is not allowed by Access-Control-Allow-Methods in preflight response

Thanks for pointing it out. We will fix that, we'll let you know when it's available.

> I don't see option to send `PATCH` and `PUT` action using forwardTo request by your SDK.
> Is there any chance to put payload to `DELETE` action by forwardTo request?

Currently we don't have any plans on supporting these changes.

I would suggest maybe to use another HTTP client (instead of the `@commercetools-frontend/sdk`) to handle these requests. We actually just released some improvements in providing better support for custom HTTP clients.
You can read more about it here: https://docs.commercetools.com/custom-applications/development/data-fetching#custom-http-client

In your case it could be something like this (example using `fetch`):

```js
import createHttpUserAgent from '@commercetools/http-user-agent';
import {
  buildApiUrl,
  executeHttpClientRequest,
  selectProjectKeyFromUrl,
} from '@commercetools-frontend/application-shell';

const userAgent = createHttpUserAgent({
  name: 'fetch-client',
  version: '1.0.0',
  libraryName: window.app.applicationName,
  contactEmail: 'support@my-company.com',
});

const fetcherForwardTo = async (url, config = {}) => {
  const data = await executeHttpClientRequest(
    async (options) => {
      const res = await fetch(
        buildApiUrl('/proxy/forward-to'),
        {
          ...options,
          method: config.method,
          body: config.body,
        }
      );
      const data = res.json();
      return {
        data,
        statusCode: res.status,
        getHeader: (key) => res.headers.get(key),
      };
    },
    { 
      userAgent,
      headers: {
        ...(config.body ? { 'Content-Type': 'application/json' } : {}),
        // Required headers for `/proxy/forward-to`.
        // https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api#http-headers
        'Accept-version': 'v2',
        'X-Forward-To': url,
        'X-Forward-To-Audience-Policy': 'forward-url-full-path',
        'X-Project-Key': selectProjectKeyFromUrl(),
      }
    }
  );
  return data;
};

const Component = () => {
  useEffect(() => {
    async function execute() {
      try {
        const result = await fetcherForwardTo(
          'https://my-api.com',
          {
            method: 'PUT',
            body: JSON.stringify({ message: 'Hello' }),
          }
        );
        // Update state with `result`
      } catch (error) {
        // Update state with `error`
      }
    }
    execute();
  }, [])
  // ...
};
```

**Comment by emmenko** [comment]
FYI: we just released additional support for custom HTTP clients that use the `/forward-to` endpoint. This is available from version `v21.11.0` onwards.

See https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api#usage-for-custom-http-client

**Comment by alochowski** [comment]
Hi @emmenko ,

Thanks for your response.

Now I'm using HTTP client (instead of the `@commercetools-frontend/sdk`) according to your example, but unfortunately I've got:  `Missing required header \"X-Forward-To\"` 

Should I additionally set it? or should it be set in `options.headers` - according to my url, similar like audience policy and `X-Forward-To-Audience-Policy` header?

Here is my example code:
```const fetcherForwardTo = async (url, config = {}) => {
  const data = await executeHttpClientRequest(
      async (options) => {
        const res = await fetch(
            buildApiUrl('/proxy/forward-to'),
            {
              ...options,
              method: config.method,
              body: config.body,
            }
        );
        const data = res.json();
        return {
          data,
          statusCode: res.status,
          getHeader: (key) => res.headers.get(key),
        };
      },
      {
        userAgent,
        headers: {
          ...(config.body ? { 'Content-Type': 'application/json' } : {})
        },
        forwardToConfig: {
          url,
          audiencePolicy: 'forward-url-origin'
        }
      }
  );
  return data;
};

**Comment by emmenko** [comment]
Hi @alochowski ,

The error comes from the fact that the URL is not being provided, and the header is the omitted. In fact I can see that you are passing `url` in the `forwardToConfig`, but the option is called `uri`.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/1110551/185563630-c53bf6aa-002f-4cf6-99df-3866656b9aab.png">

I suppose we should throw an error if that value is missing, when using the `forwardToConfig`.

Thanks for letting us know.

**Comment by alochowski** [comment]
Hi @emmenko ,
aa yes you're right! Sorry sorry I didn't catch that `url` is there instead of `uri`. My fault. 

Thanks a lot for your help.

**Comment by alochowski** [comment]
Hi @emmenko ,
unfortunately I'm back with another problem.

I saw using `executeHttpClientRequest` that there is a problem with response with 204 status code, all responses with this status are rejected.

Maybe do you had a similar case and know something about it? or maybe there is no support for such a status?

**Comment by emmenko** [comment]
Hi, is this status `204` something your API returns?

In any case, I believe the response does not have a body, so calling `res.json()` would not work. I assume this is the error you are encountering?

In this case, you should try to handle this in your implementation and check for the `res.status` before calling `.json()`.

**Comment by alochowski** [comment]
Hi @emmenko, 
I think, it's already too hot for me ;-)  
You are right, this response don't have content. I didn't catch `res.json()` in source and that was a cause.

Sorry for interrupting and thanks for your help :+1:
