### ISSUE TITLE
Fetch data from external API - Custom App

### ISSUE THREAD

**Issue by lmejbar** [commercetools/merchant-center-application-kit#2742]
**Which part of the documentation does it affect and which topic does it refer to?**

Hello

I’m working on the creation of a custom app. I have to fetch data from external API. I’m able to fetch data from unprotected API.

But it’s not working when I call our protected API (only specified IP adress can make the call). I checked your documentation, but I didn’t find this case.

We are able on our side to authorize more IP, but it seems that the fetch from the custom app to our API uses different IP each time.

- Is it possible to have more information about the restricted API.
- Can we have the IP range address?
- Do you have any recommendations or advice?

Thank you

**Comment by ddouglasz** [comment]
Hello @lmejbar,
Please kindly see this part of the documentation for the information you need on how to connect with an external API. https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api

**Comment by briantomkins** [comment]
Hi @ddouglasz 

The customer is making the following request but receiving an empty response.

`    fetch("https://mc-api.europe-west1.gcp.commercetools.com/proxy/forward-to", {
        "headers": {
        "accept": "application/json",
        "accept-version": "v2",
        "authorization": "Bearer " + window.sessionStorage.getItem('sessionToken'),
        "X-Application-ID":"xxxxxxxxxxxxxx:discount",
        "x-forward-header-x-api-Key": apikey,
        "x-forward-to": url,
        "x-forward-to-audience-policy": "forward-url-full-path",
        "x-project-key": "drv-sandbox"
    },
    "method": "GET",
    "mode": "cors",
    "credentials": "include"
    }).then(response => {
        return response;
    }) 
    
};`

**Comment by CarlosCortizasCT** [comment]
Helo @briantomkins 

Would the customer be able to share with us more information about the request and response?

We would like to know:
* Which URL (`x-forward-to` header) they are using
* Which is the HTTP status code of the response 
* What are (all) the headers included in the response

Thanks a lot.

**Comment by lmejbar** [comment]
Hello @CarlosCortizasCT 

I receive from CT API a 200 status code.
Is it possible to send you in private the API URL and key token as well ?

Lina
