### ISSUE TITLE
Organization deleted, custom app didn't

### ISSUE THREAD

**Issue by Sasurtio** [commercetools/merchant-center-application-kit#2755]
**Describe the issue**

I created a testing organization to register a custom app. I used the entry point that I will use in the real organization.
After the registration was completed I proceeded to delete the testing organization.
Today I tried to register the custom app in the correct organization, but the entry point validation is triggering an error. I think that the custom app registered in the organization deleted is still there and that's why i can’t use the previous entry point. I don’t know if I have a way to delete the custom app manually, since the organization is already deleted.

**To Reproduce**

1. Create an organization
2. Register a custom app with a memorable entry point
3. Mark the custom app as ready
4. Delete organization
5. Create another organization
6. Register a new custom app with the same entry point as step 2
7. See error trying to register the custom app, also you can't delete or change the previous custom app entry point since the organization where it belongs doesn't exists

**Expected behavior**

The entry point of the custom app should be released once the organization is deleted, since you can't access anymore to that custom app/organization

**Comment by CarlosCortizasCT** [comment]
Hello @Sasurtio 

Could you share the name or the entry point you used in your Custom Application so we can take a look at the problem?

Thanks.

**Comment by Sasurtio** [comment]
Hi @CarlosCortizasCT 

The problematic entry point is `internal-admin-dev`. I think Michael Ashe sent you already the ticket, so let me know if you need anything else.

Thank you.

**Comment by CarlosCortizasCT** [comment]
Hi @Sasurtio,

We removed the Custom Application data so that entry point is available again to be used.

Thanks.

**Comment by Sasurtio** [comment]
Thank you @CarlosCortizasCT, I'm closing this issue.
