### ISSUE TITLE
Issues with build using new version of mc-scripts

### ISSUE THREAD

**Issue by kmahadevan01** [commercetools/merchant-center-application-kit#2759]
**Issues with build using new version of mc-scripts**
When we are trying to build (yarn ci-build), using the new version of mc-scripts, 21.9.0 we are getting the following error:
`$ mc-scripts compile-html --use-local-assets --transformer $(pwd)/config/transformer-aws.js
/home/runner/work/express-solution-enablement/express-solution-enablement/packages/ensemble-custom-application/node_modules/cac/dist/index.js:404
          throw new CACError(`Unknown option \`$***name.length > 1 ? `--$***name***` : `-$***name***`***\``);
          ^

CACError: Unknown option `--useLocalAssets`
    at Command.checkUnknownOptions (/home/runner/work/express-solution-enablement/express-solution-enablement/packages/ensemble-custom-application/node_modules/cac/dist/index.js:404:17)
    at CAC.runMatchedCommand (/home/runner/work/express-solution-enablement/express-solution-enablement/packages/ensemble-custom-application/node_modules/cac/dist/index.js:602:13)
    at CAC.parse (/home/runner/work/express-solution-enablement/express-solution-enablement/packages/ensemble-custom-application/node_modules/cac/dist/index.js:541:12)
    at Object.run (/home/runner/work/express-solution-enablement/express-solution-enablement/packages/ensemble-custom-application/node_modules/@commercetools-frontend/mc-scripts/cli/dist/commercetools-frontend-mc-scripts-cli.cjs.dev.js:320:7)
    at Object.<anonymous> (/home/runner/work/express-solution-enablement/express-solution-enablement/packages/ensemble-custom-application/node_modules/@commercetools-frontend/mc-scripts/bin/cli.js:3:51)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
Exit code: 1
Command: /opt/hostedtoolcache/node/14.19.1/x64/bin/node
Arguments: /home/runner/work/express-solution-enablement/express-solution-enablement/.yarn/releases/yarn-1.22.10.cjs run ci-build
Directory: /home/runner/work/express-solution-enablement/express-solution-enablement/packages/ensemble-custom-application
Output:`

In our package.json, we use the following script:
"compile-html:ci-aws": "mc-scripts compile-html --use-local-assets --transformer $(pwd)/config/transformer-aws.js",
  
It is failing here. We also tried removing the local-assets yet it failed.

**Comment by emmenko** [comment]
Hi 👋

The option `--use-local-assets` has been removed since version v17 (see [release notes](https://github.com/commercetools/merchant-center-application-kit/blob/main/packages/mc-scripts/CHANGELOG.md#1700)).

You also most likely don't need to use the `--transformer` option anymore. Please refer to the documentation https://docs.commercetools.com/custom-applications/releases/2022-02-02-custom-applications-v21#better-deployments-support

I would also recommend to follow the new simplified deployment setup. If you are using AWS, you can try following the steps described here: https://docs.commercetools.com/custom-applications/deployment-examples/aws-s3-cloudfront

In case you haven't, please make sure to read the documentation, for example [Going to Production](https://docs.commercetools.com/custom-applications/development/going-to-production).

Thanks

**Comment by leninexpress** [comment]
thanks @emmenko! could you please advise, does this is mentioned in the migration guide? we are not sure what we need to keep and remove from package.json.

**Comment by emmenko** [comment]
I would suggest to check the starter template and use the recommended setup: 

https://github.com/commercetools/merchant-center-application-kit/blob/a38c9ec4c7f36b75ad06b9b56b87e6f0d5c4c501/application-templates/starter/package.json#L8-L12

I would also suggest to set up the deployment "as if it was a new application", instead of trying migrating from the (very) old setup. That might help you figuring out what to keep and what not.

**Comment by pandiarajan-nu** [comment]
[package-json.txt](https://github.com/commercetools/merchant-center-application-kit/files/9329197/package-json.txt)

We have already updated the libraries as per your suggestions. Could you please verify whether the scripts are in alignment with the latest libraries. While our devops ar edeploying we are facing issues and hence wanted you to validate it

**Comment by leninexpress** [comment]
Can you please take a look the package.json file and help to get the successful build? Let us know if you are available for call/web ex.

**Comment by poudelpra** [comment]
Can someone from CT join our debug call; https://exp.webex.com/exp/j.php?MTID=mb149273055e682568ab4158708a36f70 and guide us?

FYI - builds are filing after node upgrade and I believe we have made necessary suggestions provided, however is still failing.

**Comment by leninexpress** [comment]
any update for us? @emmenko

**Comment by kark** [comment]
Hi @pandiarajan-nu,

Thanks for sharing your `package.json`. Does `mc-scripts build` script currently work as it is essential for successful builds and, hence, deployments. Please note that this script additionally compiles the `index.html` by default ([reference](https://docs.commercetools.com/custom-applications/releases/2022-02-02-custom-applications-v21#changes-to-the-cli))

As @emmenko noticed:
> You also most likely don't need to use the --transformer option anymore. Please refer to the documentation https://docs.commercetools.com/custom-applications/releases/2022-02-02-custom-applications-v21#better-deployments-support

If however you need to use your custom `transformer` we advice to [follow docs](https://docs.commercetools.com/custom-applications/api-reference/cli#build) and use `mc-scripts build` with `--build-only` option and separately `mc-scripts compile-html --transformer <path_to_your_transformer>`.

As @emmenko suggested, perhaps you could start from the recommended setup and add other scripts one by one. Chances are they are not needed anymore.

Thanks

**Comment by selvam-murugan-nu** [comment]
We have question:
**edit-ensemble.js** 
`    if (maxOccurrence || (maxOccurrence === '' && !type)) {
      customFields.push({
        name: 'maxOccurrence',
        ...(maxOccurrence && { value: maxOccurrence }),
      });
    }`
Following piece of code always sending maxOccurence value in update action payload. so we are getting following error.
![image](https://user-images.githubusercontent.com/71309381/184723474-dc0dbe13-3da0-4e4f-9f26-ab3c43b5d196.png)


**ensemble-form.js**
`    const changedValues = {
      ...pickBy(
        {
          ...submit,
          maxOccurrence: maxOccurrence ? JSON.stringify(maxOccurrence) : '',
        },
        (item, itemKey) => !isEqual(initialValues[itemKey], values[itemKey])
      ),
      ...(!isEqual(
        initialValues.cartPredicate.string,
        values.cartPredicate.string
      )
        ? submitCartPredicate
        : {}),
    };`
Always we are setting maxOccurrence as empty string if customer changed maxOccurrence or not. so we want to know the reason why we are setting this to empty always?
This code is there for the past two years. even though if we remove this snippet, whenever the changes occur in maxOccurrence while editing the ensemble it is working as expected. 
we are asking this just ensure we are not breaking anything as this code was always there.

**Comment by emmenko** [comment]
Regarding your last question about `maxOccurrence`, I'm afraid we can't help you much with it as this is application-specific logic and we don't have a clue about all the details.

As for the issue with the build, is this still relevant? If so, can you share what the error is? Or can you confirm it's working?

Thanks
