### ISSUE TITLE
How to set entryPointUriPath for different environment

### ISSUE THREAD

**Issue by selvam-murugan-nu** [commercetools/merchant-center-application-kit#2765]
Currently we are setting the entryPointUriPath like below. 
ROOT_PATH value is from constants file.
```
const config = {
  "name": "Ensembles Management",
  "entryPointUriPath": ROOT_PATH,
  "cloudIdentifier": "gcp-us",
  "env": {
    "production": {
      "url": "https://${env:ENSEMBLE_CUSTOM_APP_DOMAIN}",
      "cdnUrl": "https://${env:ENSEMBLE_CUSTOM_APP_DOMAIN}",
      "applicationId":"cl3x7#91601#zgck#vy"
    },
    "development": {
      "initialProjectKey":"stardust-stage-1"
    }
  },
    "oAuthScopes": {
      "view": ["view_products", "view_cart_discounts","view_discount_codes", "view_types"],
      "manage": ["manage_products","manage_discount_codes","manage_cart_discounts", "manage_types"]
    },
  "icon": "${path:@commercetools-frontend/assets/application-icons/pricetag.svg}",
  "featureToggle": null,
  "mainMenuLink": {
    "defaultLabel": "Ensemble Manager",
    "labelAllLocales": [],
    "permissions": [PERMISSIONS.View]
  },
  "submenuLinks": []
}
```
could you please let us know how to configure entryPointUriPath for different environments?

**Comment by CarlosCortizasCT** [comment]
Hello @selvam-murugan-nu 

Environment variables in Custom Application configuration file is supported using the `${env:<variable_name>}` pattern as, for instance, as you have in the `config.env.production.url` property in your code snippet. You can find more information in [this documentation section](https://docs.commercetools.com/custom-applications/api-reference/application-config#environment-variable-references).

If you want to have a different values for the `entryPointUriPath` so you can reuse the same Custom Application deployed in different environments, we have [this other section](https://docs.commercetools.com/custom-applications/help-needed#using-a-test-or-staging-environment-for-my-custom-application) which explain this use case in more detail.

Thanks.

**Comment by panditji** [comment]
@CarlosCortizasCT    @selvam-murugan-nu 
How we can pass the environment variable to 
constants.js 
1.${env:ENSEMBLE_CUSTOM_APP_DOMAIN}
2.process.env.ENSEMBLE_CUSTOM_APP_DOMAIN

both above not working

**Comment by CarlosCortizasCT** [comment]
Hello @panditji 

Could you perhaps share what you're trying to set up in your `constants.js` file so we can understand your context?
You can also maybe share the source code you want to use in that file.

Thanks.

**Comment by panditji** [comment]
@CarlosCortizasCT 
Thanks for reply

Below is my constant.js

where I'm trying to pass entryPointUriPath   through environment variable  (.env)

I'm getting error
 **process is not defined** 

`import { entryPointUriPathToPermissionKeys } from '@commercetools-frontend/application-shell/ssr';

export const entryPointUriPath =    process.env['ENTRYPOINT_URI_PATH']

export const PERMISSIONS = entryPointUriPathToPermissionKeys(entryPointUriPath);


export const ROOT_PATH = process.env['ENTRYPOINT_URI_PATH']
export const MEMBERSHIP_CONTAINER = process.env['ENTRYPOINT_URI_PATH']
export const NEW_FORM_ROOT_PATH = '**********';
export const EXPIRED_MEMBERSHIP_PATH = '***************';
export const LIMIT = ************;

export const FEATURE_FLAGS = {};
`

**Comment by CarlosCortizasCT** [comment]
Hello @panditji 

So, if you want to have a custom value for the `entryPointUriPath` per environment, you should definitely take a look at [this documentation section](https://docs.commercetools.com/custom-applications/help-needed#using-a-test-or-staging-environment-for-my-custom-application) where we explain how you can configure your code.

Bear in mind the `${env:<variable_name>}` string pattern is only allowed to be used in the configuration file (`custom-application-config.mjs`).

Thanks.

**Comment by panditji** [comment]
hi @CarlosCortizasCT 
I followed  this
 https://docs.commercetools.com/custom-applications/help-needed#using-a-test-or-staging-environment-for-my-custom-application
 
  
import { entryPointUriPathToPermissionKeys } from '@commercetools-frontend/application-shell/ssr';

export const entryPointUriPath = typeof window === 'undefined'
  ? process.env.ENTRY_POINT_URI_PATH
  : window.app.entryPointUriPath;

export const PERMISSIONS = entryPointUriPathToPermissionKeys(entryPointUriPath);

I'm getting error
**process is not defined**
same error

Thanks

**Comment by CarlosCortizasCT** [comment]
Hello @panditji 

I guess we would need some more context to try to figure out what the problem could be:
* When are you getting that error:
** is it when you build the application? (in this case, could you share which nodejs version are you using?)
** is it when you run it locally? (in this case, could you share what you see in the browser console?)
* Could you share both complete `constants.js` and `custom-application-config.mjs` files?

Thanks.

**Comment by selvam-murugan-nu** [comment]
@CarlosCortizasCT i have a small qustion on defining the env value ? when i define in lamda its not working do we need to configure in build.yml file.

**Comment by CarlosCortizasCT** [comment]
Hi @selvam-murugan-nu 

The environment variable needs to be accessible when building the application (or when starting it locally).

You can find [here](https://docs.commercetools.com/custom-applications/api-reference/application-config#using-variable-placeholders) information about how to define the env variable.

Thanks.

**Comment by panditji** [comment]
@CarlosCortizasCT 
Thanks working fine

Agenda to set environment variable 

**Steps below:**
1.  Add **additionalEnv** in custom-application-config.json
inside that whatever environment variable you want to set you can add that attribute under **additionalEnv**
and set those value through .env using  example:**${env:ENTRYPOINT_URI_PATH}**

**Example in detail:**

  "additionalEnv": {
    "entryPoint": "${env:ENTRYPOINT_URI_PATH}",
    "container":"${env:REACT_APP_ENTRYPOINT_MEMBERSHIP_CONTAINER}",
    "companyName":"${env:COMPNAY_NAME}"
  }

2. To access anywhere in Application
use **window.app.entryPoint**

**Example in detail:**

window.app.container

window.app.companyName



In this way we can set the environment variable

Thanks
Ankush

**Comment by CarlosCortizasCT** [comment]
Hello @panditji 

Using *additionalEnv* for the *entryPointUriPath* configuration is not needed. You would need to follow the instructions explained in [this section](https://docs.commercetools.com/custom-applications/help-needed#using-a-test-or-staging-environment-for-my-custom-application) of the documentation so your `constants.js` file would look something like this:
```
import { entryPointUriPathToPermissionKeys } from '@commercetools-frontend/application-shell/ssr';

export const entryPointUriPath = typeof window === 'undefined'
  ? process.env.ENTRY_POINT_URI_PATH
  : window.app.entryPointUriPath;

export const PERMISSIONS = entryPointUriPathToPermissionKeys(entryPointUriPath);
```

In your `custom-application-config.mjs` file, you would use the exported constant. Something like this:
```
const config = {
  name: 'My Custom Application',
  entryPointUriPath,
  cloudIdentifier: 'gcp-eu',
```

[additionalEnv](https://docs.commercetools.com/custom-applications/api-reference/application-config#additionalenv) config file property is useful when you need to configure some properties for the whole Custom Application.
If you want to access them, we recommend to use the `useApplicationContext` hook as we explain in [this part](https://docs.commercetools.com/custom-applications/api-reference/application-config#runtime-application-environment) of the documentation.
