### ISSUE TITLE
AWS CloudFront with the application in S3. In Cloudfront TLS version setting question.

### ISSUE THREAD

**Issue by briantomkins** [commercetools/merchant-center-application-kit#2769]
We are trying to setup custom application in our project. We have setup the custom application “Returns.

We have also setup in AWS CloudFront with the application in S3. In Cloudfront when setting TLS version we get errors with TLS 1.3 and TLS 1.2. The only version that works for us is TLSv1.1_2016.

The documentation recommends we use TLS 1.2 or TLS 1.3. https://docs.commercetools.com/api/general-concepts#security

Can you confirm if TLS 1.2 and 1.3 is supported and why it may not be working?

**Comment by CarlosCortizasCT** [comment]
Hi @briantomkins 

Could you please give some more context about the errors you get?
* Does it prevent to load the `index.html` file? 
* Does the error prevent the Custom Application to be loaded in the Merchant Center?
* What do you see in the browser console?

Thanks.
