### ISSUE TITLE
Custom Application: Query User Group for current user? (For permission handling)

### ISSUE THREAD

**Issue by cb-adesso** [commercetools/merchant-center-application-kit#2789]
Unable to implement fine-grained permission system for existing custom application.

This is a request for developer support. Details please see below:

### Discussed in https://github.com/commercetools/merchant-center-application-kit/discussions/2787

<div type='discussions-op-text'>

<sup>Originally posted by **cb-adesso** August 29, 2022</sup>
Hello there :-)

I was wondering if someone from developer team can help us with suggestion or some guidance. Any tips and suggestions are appreciated. Thanks!

Our client requested fine-grained permission system for the custom app we build. The custom application contains multiple views/pages and should only be used by specific user groups. We are currently only checking 'ViewProducts' as generic access permission test. After consulting [the ct permission docs](https://docs.commercetools.com/custom-applications/concepts/oauth-scopes-and-user-permissions#user-permissions) we concluded that, we can't create our own permissions like 'ViewCustomAuditLog', 'ViewCustomOrderHandling', 'ViewCustomDataExport' ...

Is this conclusion correct?
What is a proper way to implement this requirement? 

We're currently thinking about dirty workarounds e.g. using naming convention in user group names and stuff like this. (If user X is member of group AuditLog show audit log in custom application.)

The idea was inspired by inspecting some GraphQL calls. 'FetchLoggedInUser' in particular is interesting one, but return type 'User' misses any user group information.

```
POST https://mc-api.europe-west1.gcp.commercetools.com/graphql
x-graphql-target: mc
x-graphql-operation-name: FetchLoggedInUser
...
{
    "operationName":"FetchLoggedInUser",
    "variables":{},
    "query":"query FetchLoggedInUser { user: me { id firstName lastName email __typename}}"
}
```

Best Regards,

Chris</div>

**Comment by emmenko** [comment]
Closing as duplicated by the GitHub discussion
