### ISSUE TITLE
Static Bundle Custom Application

### ISSUE THREAD

**Issue by amilges** [commercetools/merchant-center-application-kit#2803]
Link: https://github.com/commercetools/commercetools-bundles-starter/tree/master/packages/bundles-static

I ran into a couple of issue when following the directions.

1. Issue: Errors are thrown when compiling the firebase html. It is able to compile if I remove the headers and config option but the app doesn't function properly on the price tab.

```
command: yarn deploy:firebase

Error:
$ cross-env FIREBASE_TARGET=bundles-manager mc-scripts compile-html --headers=C:/GitHub/Sunday/commercetools-bundles-starter/packages/bundles-static/production-firebase.headers.json --config=C:/GitHub/Sunday/commercetools-bundles-starter/packages/bundles-static/production-firebase.env.json --use-local-assets --transformer C:/GitHub/Sunday/commercetools-bundles-starter/packages/bundles-static/config/transformer-firebase.js
C:\\GitHub\\Sunday\\commercetools-bundles-starter\\node_modules\\cac\\dist
index.js:404
throw new CACError(Unknown option }}${name.length > 1 ? {{-${name} : ${name}}``);
^

CACError: Unknown option --headers
at Command.checkUnknownOptions (C:\\GitHub\\Sunday\\commercetools-bundles-starter\\node_modules\\cac\\dist
index.js:404:17)
at CAC.runMatchedCommand (C:\\GitHub\\Sunday\\commercetools-bundles-starter\\node_modules\\cac\\dist
index.js:602:13)
at CAC.parse (C:\\GitHub\\Sunday\\commercetools-bundles-starter\\node_modules\\cac\\dist
index.js:541:12)
at Object.run (C:\\GitHub\\Sunday\\commercetools-bundles-starter\\node_modules@commercetools-frontend\\mc-scripts\\cli\\dist
commercetools-frontend-mc-scripts-cli.cjs.dev.js:326:7)
at Object.<anonymous> (C:\\GitHub\\Sunday\\commercetools-bundles-starter\\node_modules@commercetools-frontend\\mc-scripts\\bin
cli.js:3:51)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2. Issue: This may be related to the issue above. The links for pricing and display for pricing are showing an error in the deployed application. Also the mcURL is mentioned in the documentation but this is not a configurable option.

Clicking add price has unknown for the URL.

![image](https://user-images.githubusercontent.com/23725598/190166935-99a5fc24-78c5-4aab-9631-cd8beffd1578.png)

**Comment by emmenko** [comment]
Hi @amilges 👋

It looks like you are using old CLI options for the `mc-scripts compile-html` command. For instance the `--headers` and `--config` options.
In fact, the files `*.headers.json` and `*.env.json` should be removed. All of this should be defined in the `custom-application-config` file.

Please refer to the application config documentation: https://docs.commercetools.com/custom-applications/api-reference/application-config

> The links for pricing and display for pricing are showing an error in the deployed application.

I checked the code and I see you are using `window.open()` for the links. Why? I would recommend using the React Router links.

> Also the mcURL is mentioned in the documentation but this is not a configurable option.

Not sure what you mean but in the code I see you are reading `mcURL` from the `environment` object, but it's not defined anywhere in the `custom-application-config`.
In any case, the link URL should be constructed as following (without the need for custom environment values like `mcURL`):

```diff
const getMcPriceUrl = (productId, variantId) =>
-  `https://${mcURL}/${match.params.projectKey}/products/${productId}/variants/${variantId}/prices`;
+  `${window.location.origin}/${match.params.projectKey}/products/${productId}/variants/${variantId}/prices`;
```

**Comment by emmenko** [comment]
Also the GraphQL queries are missing the `context.target`.

Example

```diff
  const { data, loading, error } = useQuery(GetProductPrices, {
    variables,
    fetchPolicy: 'no-cache',
+    context: {
+      target: GRAPHQL_TARGETS.COMMERCETOOLS_PLATFORM,
+    },
  });
```

Here is the documentation: https://docs.commercetools.com/custom-applications/development/data-fetching

**Comment by emmenko** [comment]
I would suggest in general to read and understand the documentation first, as it seems like many of the issues you are encountering are related to that.
This should also help you to clean up and restructure your application accordingly, by following the recommendations.

Thanks

**Comment by amilges** [comment]
Hi @emmenko,

I appreciate you reviewing the code.  This repository was one that was suggested for us to use as a potential option for static bundling.  I believe it was initially developed by developers at commercetools.  We are analyzing if it is a viable option to use for bundles.  I agree that the current implementation doesn't follow the custom application documentation and the options appear to be no longer supported.

Our team was under the impression that this repo was being used by others in production and was an option we would be able to quickly get running.

Is your opinion that it will need refactoring in order to be usable?

Thanks

**Comment by amilges** [comment]
I'm going to move this thread to the bundle starter repo.  Thank you for the quick responses.

**Comment by emmenko** [comment]
No problem. Ping me there also if you need more guidance. Thanks
