### ISSUE TITLE
Permission error while creating custom application

### ISSUE THREAD

**Issue by mucar3019** [commercetools/merchant-center-application-kit#2829]
Hi,

We started to get an error while creating or updating custom applications in our organization. Error message states that we need to provide both view and manage permissions to the custom application but we are already providing that.

I gathered “RegisterCustomApplication” request from my browser as cUrl command;

`curl 'https://mc-api.europe-west1.gcp.commercetools.com/graphql' \
  -H 'authority: mc-api.europe-west1.gcp.commercetools.com' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: application/json' \
  -H 'origin: https://mc.europe-west1.gcp.commercetools.com' \
  -H 'sec-ch-ua: "Google Chrome";v="105", "Not)A;Brand";v="8", "Chromium";v="105"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36' \
  -H 'x-application-id: __internal:account' \
  -H 'x-correlation-id: mc/4675ea33-0119-4b4b-97fc-064302eedd8b/6ec40fb6-f413-49ff-8cf1-f99874cc5843' \
  -H 'x-graphql-operation-name: RegisterCustomApplication' \
  -H 'x-graphql-target: settings' \
  -H 'x-user-agent: apollo-client Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Application account/application-shell/21.14.3 (+https://git.io/fjuyC; +support@commercetools.com)' \
  --data-raw $'{"operationName":"RegisterCustomApplication","variables":{"organizationId":"3b235426-475d-4358-9b1e-e411b667e40b","data":{"name":"review_management_dev","description":"review_management_dev","url":"https://review-management-tool-gmdy4llxlq-ey.a.run.app","entryPointUriPath":"review-management","permissions":[{"name":"viewReviewManagement","oAuthScopes":["view_products","view_states"]},{"name":"manageReviewManagement","oAuthScopes":["manage_products"]}],"icon":"<svg width=\\"24\\" height=\\"24\\" viewBox=\\"0 0 24 24\\" xmlns=\\"http://www.w3.org/2000/svg\\"><path d=\\"M21 3v.62c0 2.909-1.628 6.975-3.724 9.914v3.742a.62.62 0 0 1-.182.439l-3.103 3.103a.62.62 0 0 1-1.06-.439v-2.225l-1.241-1.242-.803.803a.619.619 0 0 1-.878 0L6.285 13.99a.62.62 0 0 1 0-.878l.803-.803-1.242-1.241H3.621a.62.62 0 0 1-.44-1.06l3.104-3.103a.62.62 0 0 1 .44-.182h3.741C13.405 4.628 17.471 3 20.379 3H21ZM6.103 15.414l2.483 2.483C8.586 19.612 6.088 21 3 21c0-3.088 1.388-5.586 3.103-5.586Zm9.316-8.695a1.864 1.864 0 0 0-1.862 1.862c0 1.027.835 1.862 1.862 1.862a1.864 1.864 0 0 0 1.862-1.862 1.864 1.864 0 0 0-1.862-1.862Z\\" fill=\\"#000\\" fill-rule=\\"nonzero\\"/></svg>","mainMenuLink":{"labelAllLocales":[],"defaultLabel":"Review","permissions":[]},"submenuLinks":[]}},"query":"mutation RegisterCustomApplication($organizationId: String\u0021, $data: CustomApplicationDraftDataInput\u0021) {\\n  createCustomApplication(organizationId: $organizationId, data: $data) {\\n    id\\n    __typename\\n  }\\n}"}' \
  --compressed`

And this is the response we are getting;

`{"errors":[{"message":"You must provide both view and manage permissions for every permission group, using the permission name prefix: \"viewReviewManagement\" and \"manageReviewManagement\". Got instead \"viewReviewManagement\", \"manageReviewManagement\".","locations":[{"line":2,"column":3}],"path":["createCustomApplication"],"extensions":{"invalidArgs":["permissions"],"code":"BAD_USER_INPUT","exception":{"invalidArgs":["permissions"]}}}],"data":{"createCustomApplication":null}}
`

Also you can check merchant center custom application creation form screenshots.
![image_1](https://user-images.githubusercontent.com/98164516/192571124-624f1481-1e46-432e-a7e4-ddd8a5c83b4f.png)
![image_2](https://user-images.githubusercontent.com/98164516/192571131-8b2a8a5b-8ab1-43c2-a8a8-de9bad9d511a.png)

**Comment by emmenko** [comment]
Thanks for reporting, we'll look into it asap.

**Comment by emmenko** [comment]
The fix has been released. Can you try again?

**Comment by mucar3019** [comment]
Thank you for quick response and update. It is working now.
