### ISSUE TITLE
actions.forwardTo.del does not have a request body

### ISSUE THREAD

**Issue by harm-meijer** [commercetools/merchant-center-application-kit#2847]
In the file: node_modules/@commercetools-frontend/sdk/dist/commercetools-frontend-sdk.esm.js 

Is the line: `var body = action.payload.method === 'POST' ? action.payload.payload : undefined;`
So 100% sure no body is sent on a DELETE request. Since I am using forwardTo even adding this in the client script is no guarantee the commercetools api will forward the body in the DELETE request but at the moment the client isn't even sending it.

My external api requires a body to be sent with the DELETE request.

Code I used:

```javaScript
import { useAsyncDispatch, actions } from '@commercetools-frontend/sdk';

const [application] = useState({version:1})
const dispatch = useAsyncDispatch();
const deleteApplication = useCallback(() => {
  dispatch(
    actions.forwardTo.del({
      uri: 'https://www.does-not-matter.com/',
      //no json body is sent with the delete request
      payload: { version: application.version },
    })
  )
}, [application, dispatch]);
```

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE) it is possible to send a body with a DELETE request.

**Comment by emmenko** [comment]
Hi 👋

Please read the discussion here: https://github.com/commercetools/merchant-center-application-kit/issues/2732#issuecomment-1205739658

Let us know if you have further questions 🤗

**Comment by harm-meijer** [comment]
Thank you @emmenko that does the trick if commercetools api forwards the body, have to test that later as I'm currently using mock service worker. The code in the [comment](https://github.com/commercetools/merchant-center-application-kit/issues/2732#issuecomment-1205739658) has missing uri because it is passed as url and that code should be:

'''javaScript
      forwardToConfig: {
        uri:url,
      }
'''
