### ISSUE TITLE
Change description of how Custom Application extend functionality

### ISSUE THREAD

**Issue by industrian** [commercetools/merchant-center-application-kit#2850]
From @sfernengel  on Slack: https://commercetools.slack.com/archives/C02PH5D592Q/p1666179194392269

> In the Custom Applications [documentation](https://docs.commercetools.com/custom-applications/what-is-a-custom-application#:~:text=Extend%20the%20functionality%20of%20the%20Composable%20Commerce%20APIs), it mentions that, a CA can extend the functionality of Composable Commerce APIs.
>
> Maybe we should omit the extend the functionality of Composable Commerce APIs from the [documentation](https://docs.commercetools.com/custom-applications/what-is-a-custom-application#:~:text=Extend%20the%20functionality%20of%20the%20Composable%20Commerce%20APIs). Since we are only extending the functionality of the Merchant Center.
>
> I don’t think by writing any type of Custom Application, we can change the behaviour of how Composable Commerce API responds. Does this sound reasonable?

**Comment by mmaltsev-ct** [comment]
Hey @industrian, thank you for creating the issue, we'll take a look at the wording shortly.

**Comment by mmaltsev-ct** [comment]
The content is updated, and the update is now available in the docs: https://docs.commercetools.com/custom-applications/what-is-a-custom-application.

Closing this issue. Feel free to reopen in case of questions or remarks.
