### ISSUE TITLE
Use Google Fonts API v2

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#2853]
**Is your feature request related to a problem? Please describe.**

Migrate our Google Fonts URL to use the [v2 API](https://developers.google.com/fonts/docs/css2).

Expected output: https://fonts.google.com/share?selection.family=Open%20Sans:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600;1,700

```
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet">
```

**Comment by mmaltsev-ct** [comment]
Just duplicating the internal discussion here:

Inter seems to have a [repo](https://github.com/rsms/inter) with all the necessary source files. They also say there:
> Should I use Inter from Google Fonts? No, unless you have no other choice. (outdated, no italics)

As discussed internally, we will be using the source files then instead of Google Fonts.
