### ISSUE TITLE
Space character after applicationId and entryPointUriPath

### ISSUE THREAD

**Issue by Steven-Thelin** [commercetools/merchant-center-application-kit#2867]
**Describe the issue**

I've followed [this guide](https://docs.commercetools.com/custom-applications/help-needed#using-a-test-or-staging-environment-for-my-custom-application) to allow for different projects (as we have one for staging and one for production).
Locally it works fine, however when deployed it enters the _"infinite loop"_. I dug into `window.app` which looks kind of odd.

**window.app**
```
applicationId: "THE_ID :shipping-management-org "
entryPointUriPath: "shipping-management-org "
```
I've replaced our id and uri with strings, however the format is as provided. We get a space before the first `:` and after `entryUriPoint`. However the two other envvars work fine, without any additional space occuring.

All definitions of these two keys in the project are set without any spaces. Do you have any idea what could be the problem? 🙂

Please let me know what else you need.

**constants.js**
```
import { entryPointUriPathToPermissionKeys } from "@commercetools-frontend/application-shell/ssr";

export const entryPointUriPath =
  typeof window === "undefined"
    ? `${process.env.ENTRY_POINT_URI_PATH}`
    : window.app.entryPointUriPath;

export const PERMISSIONS = entryPointUriPathToPermissionKeys(entryPointUriPath);

export const FEATURE_FLAGS = {};

```

**custom-application-config.mjs**
```
import { PERMISSIONS } from "./src/constants";

const config = {
  entryPointUriPath: "${env:ENTRY_POINT_URI_PATH}",
  name: "Shipping Management",
  cloudIdentifier: "gcp-eu",
  icon: "WorldIcon",
  key: "${env:ENTRY_POINT_URI_PATH}",
  oAuthScopes: {
    view: [
      "view_products",
      "view_types",
      "view_project_settings",
      "view_orders",
      "view_shipping_methods",
      "view_states",
    ],
    manage: ["manage_orders"],
  },
  env: {
    development: {
      initialProjectKey: "lakrids-by-blow-staging",
    },
    production: {
      applicationId: "${env:APPLICATION_ID}",
      url: "${env:URL_ENV}",
      cdnUrl: "${env:CDN_URL_ENV}",
    },
  },
  mainMenuLink: {
    defaultLabel: "Shipping (org)",
    uriPath: "${env:ENTRY_POINT_URI_PATH}",
    permissions: [PERMISSIONS.View],
    featureToggle: null,
    submenu: [],
    labelAllLocales: [
      {
        locale: "en",
        value: "Shipping (org)",
      },
      {
        locale: "de",
        value: "Versand (org)",
      },
      {
        locale: "es",
        value: "Envío (org)",
      },
    ],
  },
};

export default config;

```

Scripts
```
"azure-staging": "shx rm -rf public/ && set ENTRY_POINT_URI_PATH=order-management-org && set APPLICATION_ID=OUR_ID && set URL_ENV=OUR_URL && set CDN_URL_ENV=OUR_CDN && mc-scripts build && npm run azure-compile && shx cp -r public public_staging
```

**Comment by mmaltsev-ct** [comment]
Hey @Steven-Thelin, thank you for reaching out! We'll take a look at the issue and get back to you soon.

**Comment by Rhotimee** [comment]
Hi @Steven-Thelin, we believe the problem emanates from the way you provided the environmental variables(`ENTRY_POINT_URI_PATH`, `APPLICATION_ID`).  I suggest you define your environmental variables in a dotenv file as recommended in the [docs](https://docs.commercetools.com/custom-applications/api-reference/cli#using-dotenv-files) instead of passing the env variable inline. 

Thanks.

**Comment by Steven-Thelin** [comment]
Good morning @Rhotimee 

So the suggestion works locally, but breaks in our Azure pipeline. The only error shown is:
`##[error]Error: Npm failed with return code: 1` 🤷🏻

**Comment by Steven-Thelin** [comment]
@Rhotimee So i addressed that part differently, and that issue is now resolved. However, two of our three apps get the following error:

```
Refused to load the script 'https://lakrids-app-ordermanagement-staging.azurewebsites.net/shipping-management/app.2ce02061600b47c770b3.js' because it violates the following Content Security Policy directive: "script-src 'self'
```
(and yes, the staging environment url contains 'ordermanagement'. A mistake by a former developer)

**Comment by Rhotimee** [comment]
Hello @Steven-Thelin, A similar issue was resolved previously with this [comment](https://github.com/commercetools/merchant-center-application-kit/issues/2851#issuecomment-1289227593). 

The error is coming from the script-src directive which specifies valid sources of scripts. 


From the error, the application URL included in the `script-src` is not what is expected. As it is missing a backslash

Adding the backslash (as seen below) tells the browser it can fetch anything below the directory (`shipping-management`)  from the domain `lakrids-app-ordermanagement-staging.azurewebsites.net`. 

`https://lakrids-app-ordermanagement-staging.azurewebsites.net/shipping-management/` 

Try this and let us know if that helps.

**Comment by Steven-Thelin** [comment]
Hi @Rhotimee 

This seem to have resolved our issue. Thank you for your assistance 🙂 

Have a good day!

**Comment by Rhotimee** [comment]
You're welcome.
