### ISSUE TITLE
When I try to run merchant-center-application-kit it is opening Europe URL

### ISSUE THREAD

**Issue by satyam21041997** [commercetools/merchant-center-application-kit#2882]
When I try to run merchant-center-application-kit it is opening Europe URL

**Describe the issue**

After installing all the dependencies when I run "npm start" it is opening browser with CommerceTools login page and having Europe URL.
I have given all the environment variable for Australia only.
Please help me find out where I have to do the change.

**Comment by emmenko** [comment]
Hi @satyam21041997 👋

Can you share your Custom Application config so that we can try to identify the issue?

In any case, I would expect that the `cloudIdentifier` is set to `gcp-au` for making it work with the Australia environment.

**Comment by satyam21041997** [comment]
Hi Nicola Molinari,
It worked now. I just change gcp-eu to gcp-au.

Thank you :)
