### ISSUE TITLE
How to hit the entryPointUriPath

### ISSUE THREAD

**Issue by satyam21041997** [commercetools/merchant-center-application-kit#2885]
How to hit the entryPointUriPath after launching the application to the browser?
And also want to know how to work on its GUI part?

![image](https://user-images.githubusercontent.com/94686066/202682109-20369287-0d66-4efc-819d-11f1d8b4cd1b.png)

Getting this error after launching the application in browser.
Please help me out.

Regards,
Satyam Kumar

**Comment by emmenko** [comment]
Hi @satyam21041997 

Have you read the documentation on how to develop Custom Applications? You have all the information you need there.

https://docs.commercetools.com/custom-applications/

**Comment by satyam21041997** [comment]
Hi Nicola Molinari,
I have gone through the documentation but I didn't find anything related to this.

**Comment by satyam21041997** [comment]
Hi Nicola,
Thanks for your response. 
Currently, I am using starter template. I haven't changed anything just want to see the custom application UI in browser.
In the configuration file, I have added "entryPointUriPath" as welcome.
![image](https://user-images.githubusercontent.com/94686066/202718734-78fb9331-d382-47ac-913d-df4296a6039a.png)

There is one error in terminal also.
![image](https://user-images.githubusercontent.com/94686066/202719232-c21c05bd-218b-4365-b4af-f83bccaebf9b.png)

There is some error in the browser console also.
![image](https://user-images.githubusercontent.com/94686066/202719079-51c8817a-3024-4339-9e09-fa444c5f30fd.png)
![image](https://user-images.githubusercontent.com/94686066/202719120-0650c127-40ec-4751-a1f7-fab1b9f31148.png)

**Comment by emmenko** [comment]
If you keep the "initial setup", does it work?

Can you also share the content of the configuration file and of the `routes`?

**Comment by satyam21041997** [comment]
No its not working.
I will share the configuration file.
[custom-application-config.mjs.txt](https://github.com/commercetools/merchant-center-application-kit/files/10042388/custom-application-config.mjs.txt)

**Comment by satyam21041997** [comment]
is there any update?

**Comment by emmenko** [comment]
The config file looks fine. Just one thing that the `entryPointUriPath` should be updated in the `./src/constants` file, to allow the permission names to be properly working.

See https://docs.commercetools.com/custom-applications/development/permissions#defining-constants

Can you share what changes you made from the default template? How are you using this new `welcome` component?
If you remove it, do you still get an error? If so, which one?

Thanks

**Comment by satyam21041997** [comment]
I have updated the entryPointUriPath in the ./src/constants file. But still facing the same problem.
Currently, I haven't done any changes in the template and just want to render the default templates like welcome, channels etc.
If I will able to render all these templates then I will do the changes.
While compile I am getting two errors maybe it is happening because of that.
![image](https://user-images.githubusercontent.com/94686066/203062276-8eb12372-5ab0-4394-bcff-9a709af010ab.png)

Please help me to fix these.

**Comment by satyam21041997** [comment]
My system have NodeJs 17.9.0 and npm 8.5.5 and I am using NPM for building and all.

**Comment by emmenko** [comment]
We'll see if we can reproduce the error on our side.

In the meantime, can you try using different Node versions (v16 or v18) and maybe try using Yarn?

Just to see if the issue might be related to one of these combinations.
Thanks

**Comment by Rhotimee** [comment]
Hello @satyam21041997, we were not able to reproduce this error with Node.js v17 and npm 8. 
May I know your system's OS? 
Also, could you try using other node versions, perhaps v16 or v18 as suggested by @emmenko?

**Comment by satyam21041997** [comment]
Hi Rhotimee,
Currently I am using Windows 10 Pro 64-bit(10.0, Build 19042).
I tried with all the node versions that you have mentioned but still getting the same error.
If possible can we connect once so that it will more clear to you?

**Comment by satyam21041997** [comment]
Hi Rhotimee,
Is there update?

**Comment by kark** [comment]
Hi @satyam21041997,

we looked into that and checked the starter template on a Windows 10 machine and it seemed to us it works fine.
Did you manage to solve the issue on your side (I'm asking since you closed the issue)?

Thanks
