### ISSUE TITLE
Merchant Center custom app "request cancelled" error

### ISSUE THREAD

**Issue by nelsonfilhoOE** [commercetools/merchant-center-application-kit#2910]
I just bootstrapped a custom Merchant Center application using Commercetools' create-mc-app and configured it following the official documentation. When running the dev server, I get an error regarding an cancelled request (no stack trace), however I didn't implement any yet, still the application works regardless, so I assumed it was just something related to dev and moved on. I deployed it to a Firebase hosting and installed it to my Merchant Center, when I access it through its menu the app loads, but a similar error occurs, and it enters an infine refresh loop. I only created a very simple component that does nothing but show a string of text and added it to routes, so I believe it was nothing on my side. The custom application is correctly configured as far as the documentation says and I have the permissions to run and install it to my organization's Merchant Center

Prints of the errors are below.

1. Create a Merchant Center custom application
2. Configure it to an existing project
3. Run it

**Expected behavior**

Expected to be able to deploy the custom app and run it.

**Screenshots**

Local environment:
![local-error](https://user-images.githubusercontent.com/115007099/206716453-e1163e85-e8ab-42a2-83e7-e60ad81faf43.png)

Production:
![mc-error](https://user-images.githubusercontent.com/115007099/206717900-0ae7a030-f8c9-4501-b12b-159b318cb340.png)

**Additional context**

**Comment by CarlosCortizasCT** [comment]
Hello @nelsonfilhoOE 

Thanks for reaching out to us.

I think we would need a little more info to try to come up with an answer to this issue.

Could you perhaps provide some more details?
* Is the stack trace you shared from your local environment?
* Could you inspect in the browser dev tools the response body of the request returning a 500 status code? (also the request body)
* Could you share the info (not private data) you see in the dev tools when inspecting the `window.app` object?
* Could you double check the application entry point URI value you have configured in your custom application configuration file matches the one you configured in Merchant Center?
* What's the name of your Custom Application and in which region did you installed it?


Thanks!

**Comment by nelsonfilhoOE** [comment]
Hello @CarlosCortizasCT.

I managed to solve the problem, I had misunderstood how to configure the entry point URI and set an invalid value, after fixing it and redeploying it worked as intended.

**Comment by CarlosCortizasCT** [comment]
Hello @nelsonfilhoOE 

Great!

Thanks for letting us know.
