### ISSUE TITLE
Not able to update the Types description

### ISSUE THREAD

**Issue by satyam21041997** [commercetools/merchant-center-application-kit#2916]
Hi,
I am trying to update the 'Types' from GraphQL custom application. I am able to update the Name, Key but when I try to update the Description I am getting some error. Below is the screenshot for your reference.

![image](https://user-images.githubusercontent.com/94686066/207843589-29ca7087-9006-41c6-b309-7c4841efab3e.png)
![image](https://user-images.githubusercontent.com/94686066/207843655-b91cac77-d3df-487e-8866-c9c161ff1a95.png)

Could you please help me on this as soon as possible.

**Comment by emmenko** [comment]
I think it the update action should be:

```
[
  {
    setDescription: {
      description: [
        {
          locale: "en",
          value: "Hello"
        }
      ]
    }
  }
]
```

PS: this is not really an issue with Custom Applications, you should refer to commercetools support for that. You can also inspect [GraphiQL interface](https://docs.commercetools.com/api/graphql#interactive-graphql-console) to explore the GraphQL Schema and find out the types of queries and mutations.

**Comment by satyam21041997** [comment]
Hi Nicola Molinari,
Thanks for your response. This works for me. 
But when I use `syncTypes.buildActions(newData,oldData)` it is returning the `setDescription` not in the structure that you mentioned.
Is there any way to set the value in `setDescription` with the structured that you mentioned?

**Comment by CarlosCortizasCT** [comment]
Hello @satyam21041997,

First we want to explain the sync-actions results are tailored for the REST API but in your case you’re using the GraphQL one.

For GraphQL mutations, the results of sync-actions can be used but the need a transformation, depending on the actual mutation.
Here you can find a code snippet for a transformation function which will deal with the setDescription action so you could pass the built actions and get them transformed for the GraphQL API:
```
import {
  transformLocalizedStringToLocalizedField,
} from '@commercetools-frontend/l10n';

const convertAction = (actionName, actionPayload) => {
  switch (actionName) {
    case 'setDescription':
      return {
        [actionName]: {
          description: transformLocalizedStringToLocalizedField(actionPayload.description),
        },
      };
  }
}

const createGraphQlUpdateActions = (actions) =>
  actions.reduce(
    (previousActions, { action: actionName, ...actionPayload }) => [
      ...previousActions,
      convertAction(actionName, actionPayload),
    ],
    []
  );
```
