### ISSUE TITLE
Not able to click on last link/sublink in the nav bar

### ISSUE THREAD

**Issue by dinesh99639** [commercetools/merchant-center-application-kit#2925]
**Describe the issue**

In Merchant Center sidebar, if there are more links, the user not able to select the last option since the presence of a div which is which is giving the shading.

**To Reproduce**

1. Go to Merchant Center
2. Expand the navbar if it is collapsed
3. Scroll down to the last link (Considering scenario that more links present in navbar)
4. Its difficult to click on the last link/sublink

**Expected behavior**

Should be able to click on last link/sublink without struggling.

**Screenshots**

<div>
    <img height="300px" src="https://user-images.githubusercontent.com/48937982/210932429-d466ccb0-4a42-4ac1-b72a-79ff04af3a66.png" />
    <img height="300px" src="https://user-images.githubusercontent.com/48937982/210932499-ba620424-42cb-4fdb-a4ad-195bbc691e48.png" />
</div

Left image refers to the issue and right image refers to one of the resolution that we can use

**Additional context**

We can resolve this issue by removing that extra div or reducing the height of that div

**Comment by emmenko** [comment]
Hi @dinesh99639 

Thanks for reporting the issue! We'll start working on a fix.

**Comment by dinesh99639** [comment]
Hi @emmenko 

Thank you!

**Comment by emmenko** [comment]
I'll let you know when it's released.

**Comment by dinesh99639** [comment]
Thanks! @emmenko

**Comment by emmenko** [comment]
FYI: fix is released in `v21.22.0`

**Comment by dinesh99639** [comment]
Ok, Thank you!
Can you please let me know when it will be deployed to official merchant center website because while navigating to custom application from Merchant center dashboard, we are facing this issue as well.

**Comment by emmenko** [comment]
@dinesh99639 The fix is live on production.
