### ISSUE TITLE
[Proposal] Define CSP and Security Headers in MC Proxy, deprecate csp.json

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#293]
This proposal is part of the tooling improvements in #214 

## Motivation

At the moment, using the `mc-http-server` to run an application in production will include **security headers**, such as CSP. The `mc-http-server` comes with a pre-defined configuration that can be extended using a `csp.json` file.

While this approach is perfectly fine, it has some drawbacks:
- security headers are defined within the `mc-http-server` and are not enforced by our production system
- people can choose to deploy the application in a different way, by not using the `mc-http-server` package, which results in a "loss" of the headers (unless the user explicitly defines them again)

To support those use cases, of developing applications using other tooling (e.g. parcel), we need to rethink a bit our approach and **make it easier for people to have secured applications without much effort**.

## Proposal

Given that in production each application is served by our MC Proxy, we can define the security headers (including CSP) in the proxy server itself.

#### Local development

At the moment, the development server (webpack-dev-server) is configured to apply the security headers. In general, I find it useful to have that for development, because it's a setup that resembles production and it's useful to have the app secured.

So how should we deal with that and the MC proxy?

I suppose we could move the security headers config into a separate package, which can be used by both the MC Proxy and for whatever server is used for local development.

#### CSP for custom applications

Custom applications still need to extend the CSP based on the domains they are hosted and other possible external services used by the application.

I guess there are a couple of options that we can use to do so:
- extend the CSP config using custom HTTP headers (e.g. `"x-mx-csp-script-src"="foo.com,bar.com"`)
- extend the CSP config as settings (where you register your applications in the MC)

## Outcome

It should be possible to develop applications using different tooling and different ways to deploy them (even as static apps with e.g. Netlify) without worrying about security headers.

**Comment by tdeekens** [comment]
Sorry for loosing track of this. I think it makes sense to extract the headers into an app-kit package which just exposes them. Then anybody can use them in any way needed. We ourselves could just use them in the proxy.
