### ISSUE TITLE
Update express-jwt dependency to version ^8 in @commercetools-backend/express

### ISSUE THREAD

**Issue by mhlzr** [commercetools/merchant-center-application-kit#2930]
Currently `@commercetools-backend/express` has a dependency to `express-jwt: 7.7.5` which uses a vulnerable version of `jsonwebtoken`. It should be updated to use `express-jwt@8` to solve this vulnerability issue. 

For more info see 

- https://github.com/advisories/GHSA-27h2-hvpr-p74q
- https://github.com/auth0/node-jsonwebtoken/wiki/Migration-Notes:-v8-to-v9)

**Comment by kark** [comment]
Hi @mhlzr,
thanks for reporting!
