### ISSUE TITLE
Not able to configure the custom application in Merchant Center

### ISSUE THREAD

**Issue by Meghana-aspire** [commercetools/merchant-center-application-kit#2946]
Hi,
I built a custom application for the Merchant Center, and it is working perfectly fine in localhost.
I deployed it into AWS S3 bucket and created the configuration in AWS CloudFront. And also I have given the applicationID and url in the configuration file.
![image](https://user-images.githubusercontent.com/107937315/213997326-9fb116d0-793d-406c-ae8f-48ff61124cc0.png)

But I am getting some errors while running the application.
![image](https://user-images.githubusercontent.com/107937315/213997532-d9e7f773-65f9-4f96-a415-8130db9e6a10.png)

![image](https://user-images.githubusercontent.com/107937315/213997777-d566f8da-bdc4-4991-adf3-6cc93168a500.png)
![image](https://user-images.githubusercontent.com/107937315/213997917-5fad788c-e678-44a0-a68e-332d168cfcab.png)

Please help me on it to resolve it.

**Comment by Rhotimee** [comment]
Hello @ Meghana-aspire, the problem is probably with your bucket configuration. 
Can you confirm that you allow public access to your bucket and you updated your bucket policy?

I recommend taking a look at these articles on how to deploy react apps on Cloudfront as suggested by our [docs](https://docs.commercetools.com/custom-applications/deployment-examples/aws-s3-cloudfront) 

- [Deploy React app to S3 & CloudFront](https://dev.to/karanpratapsingh/deploy-react-app-to-s3-cloudfront-1cao)
- [Deploying create-react-app to S3 and CloudFront](https://wolovim.medium.com/deploying-create-react-app-to-s3-or-cloudfront-48dae4ce0af)

**Comment by Meghana-aspire** [comment]
Hi Rhotimee,
This is the bucket public access setting.
![image](https://user-images.githubusercontent.com/107937315/214017195-9c7a8a56-edbf-4c54-926c-81c2bdc33082.png)
![image](https://user-images.githubusercontent.com/107937315/214017418-9a939502-546f-4259-8c5b-4cb57e988a67.png)

**Comment by Meghana-aspire** [comment]
@Rhotimee I tried to allow full public access by unselecting the two blacked rules and added a custom error response.
![image](https://user-images.githubusercontent.com/107937315/214052968-5886610c-a92f-4b5b-8f37-60a67013888b.png)

![image](https://user-images.githubusercontent.com/107937315/214053046-f2cd62b6-f2f9-4923-8b5f-d1cf1bebba91.png)

But still I am facing the issue. When I tried to open Custom Application, the application is reloading automatically.

https://user-images.githubusercontent.com/107937315/214055206-ba911e65-808a-4fb1-ad7c-57f3312e6c4d.mp4

**Comment by Rhotimee** [comment]
@Meghana-aspire, The issue regarding the reloading is often related to configuration mismatch between the custom-application-config file and the config saved on Merchant Center. 

Could you confirm if the entryPointUriPath and other other config in your custom-application-config is the same with the one in Merchant Center

**Comment by Meghana-aspire** [comment]
@Rhotimee I have checked the application-config file and the config saved on Merchant Center. I am not able to find any difference.
[custom-application-config.mjs.txt](https://github.com/commercetools/merchant-center-application-kit/files/10481380/custom-application-config.mjs.txt)

[Uploading screencapture.pdf…]()

**Comment by Rhotimee** [comment]
@Meghana-aspire, from what I have noticed, the  entryPointUriPath on in your local config is `starter-b1e003` while the one on Merchant Center is `channels`. It's important to make sure they are both the same.  
Try to resolve this and let me know if that solved the problem.

**Comment by Meghana-aspire** [comment]
@Rhotimee 
It is working now :)
Thanks for your support.

**Comment by Meghana-aspire** [comment]
@Rhotimee 
It is working now :)
Thanks for your support.
