### ISSUE TITLE
Custom app permissions denied

### ISSUE THREAD

**Issue by olegbalakirev** [commercetools/merchant-center-application-kit#3101]
**Describe the issue**

We are having an interesting issue after we added a new custom app to our project we get a Not enough permissions to access this resource . This is happening for all the users including Admin.
I verified that group permissions and project permissions are all good.Custom app: `customobject-custom-app-dev`

**To Reproduce**

1. Go to Custom app `customobject-custom-app-dev`
2. See error

**Expected behavior**
Custom app should load

**Screenshots**

![image](https://github.com/commercetools/merchant-center-application-kit/assets/56317412/4b9d3432-993d-47fa-b12d-12b75de00fe8)

**Additional context**
We checked with Admin user. And the result is the same

**Comment by emmenko** [comment]
Hi @olegbalakirev 

Thanks for reaching out to us.

This error page `Not enough permissions to access this resource` is not a component that we provide but it seems it's something that you render in your own application. Can you check that in your code (probably where you have your application routes defined)?

A couple more questions:
* Is the new Custom Application based on one of the starter templates?
* What versions of the `@commercetools-frontend/*` dependencies are you using?
