### ISSUE TITLE
Custom App calling a function with secret (best approach)

### ISSUE THREAD

**Issue by lucbard-sap** [commercetools/merchant-center-application-kit#3109]
Hi,

We have a custom app to manage the permissions for the user (associate) inside a business customer. When a change is done we want to call a function to trigger an on demand indexing Azure Function. The problem is that the custom app is a static app and we don’t want to expose in the code the function secret. 

 

What would be the best approach to do such a thing ?

**Comment by just-L** [comment]
Hello Carlos.
I'm the one who is doing development.

Attempt to call an Azure function leads to this result:
`System.Private.CoreLib: Exception while executing function: Functions.proxy. System.Private.CoreLib: Result: Failure
Exception: Error: Invalid request URI path "http://c82b-129-222-204-57.ngrok-free.app/api/proxy". Please make sure that the "request" object has either a property "originalUrl" or "url". If not, 
you should implement the "getRequestUrl" function and make sure to return a valid URI path value starting with "/". More info at https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api#validating-the-json-web-token
Stack: Error: Invalid request URI path "http://c82b-129-222-204-57.ngrok-free.app/api/proxy". Please make sure that the "request" object has either a property "originalUrl" or "url". If not, you 
should implement the "getRequestUrl" function and make sure to return a valid URI path value starting with "/". More info at https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api#validating-the-json-web-token
    at C:\Repo\Digital.B2B.CustomApplications.Proxy\node_modules\@commercetools-backend\express\dist\commercetools-backend-express.cjs.dev.js:213:13
    at Object.<anonymous> (C:\Repo\Digital.B2B.CustomApplications.Proxy\dist\proxy\index.js:22:25)
    at Generator.next (<anonymous>)
    at C:\Repo\Digital.B2B.CustomApplications.Proxy\dist\proxy\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Repo\Digital.B2B.CustomApplications.Proxy\dist\proxy\index.js:4:12)
    at Object.httpTrigger [as default] (C:\Repo\Digital.B2B.CustomApplications.Proxy\dist\proxy\index.js:19:12)
    at msg (C:\Users\admdubovyil\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:21244:26)
    at WorkerChannel.invocationRequest (C:\Users\admdubovyil\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:18692:26)
    at ClientDuplexStream.<anonymous> (C:\Users\admdubovyil\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:18471:30).`

**function code:**

`import { AzureFunction, Context, HttpRequest } from "@azure/functions"
import { CLOUD_IDENTIFIERS, createSessionAuthVerifier } from "@commercetools-backend/express";

const sessionAuthVerifier = createSessionAuthVerifier({
    audience: 'https://c82b-129-222-204-57.ngrok-free.app',
    issuer: CLOUD_IDENTIFIERS.GCP_US,
  });
  

const httpTrigger: AzureFunction = async function (context: Context, req: HttpRequest): Promise<void> {
    context.log('HTTP trigger function processed a request.');

    console.log(context.req)

    const t = await sessionAuthVerifier(context.req, context.res)`

**context.res object**
`[2023-06-20T14:16:54.563Z] Executing 'Functions.proxy' (Reason='This function was programmatically called via the host APIs.', Id=dc0a7be6-9419-478a-b100-c2b054d9a4cc)
[2023-06-20T14:16:54.600Z] HTTP trigger function processed a request.
[2023-06-20T14:16:54.602Z] Request {
[2023-06-20T14:16:54.603Z]   method: 'POST',
[2023-06-20T14:16:54.604Z]   url: 'http://c82b-129-222-204-57.ngrok-free.app/api/proxy',
[2023-06-20T14:16:54.605Z]   originalUrl: 'http://c82b-129-222-204-57.ngrok-free.app/api/proxy',
[2023-06-20T14:16:54.606Z]   headers: {
[2023-06-20T14:16:54.606Z]     via: '1.1 google',
[2023-06-20T14:16:54.607Z]     'content-type': 'application/json',
[2023-06-20T14:16:54.608Z]     accept: 'application/json',`

as you can see object has all parameters

What did I do wrong?

**Comment by CarlosCortizasCT** [comment]
Hello @lucbard-sap ✋ 

So, if we take a look at the log you shared, this is the relevant part:
```
Error: Invalid request URI path "http://c82b-129-222-204-57.ngrok-free.app/api/proxy". Please make sure that the "request" object has either a property "originalUrl" or "url". If not,  you should implement the "getRequestUrl" function and make sure to return a valid URI path value starting with "/". 
More info at https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api#validating-the-json-web-token
```

The `createSessionAuthVerifier` will create a new verifier which will run the required checks.

One of those checks is the `audience` validation which involves checking the incoming URL (path + query string). In order to get it, by default the verifier expects a standard NodeJs or Express request to be provided, which will include either a `url` or `originalUrl` params with that URL part.

In your case, your providing `req` prop from the [Context](https://github.com/Azure/azure-functions-nodejs-library/blob/2b2177c7f5eee98d2451df0e59e69490391752f5/types/Context.d.ts#L11) object coming from the `@azure/functions` package. That property has [this shape](https://github.com/Azure/azure-functions-nodejs-library/blob/2b2177c7f5eee98d2451df0e59e69490391752f5/types/http.d.ts#L65) and it includes a `url` prop, which is fine. 
The issue seems to be that the `url` prop contains the full URL where we are expecting only the pathname and query string.

The verifier factory function can be customize to tell it how to get the url it is expecting so you might want to modify it like this:
```js
const sessionAuthVerifier = createSessionAuthVerifier({
  audience: 'https://c82b-129-222-204-57.ngrok-free.app/',
  issuer: CLOUD_IDENTIFIERS.GCP_US,
  getRequestUrl: (azureRequest) => {
    const url = new URL(azureRequest.url);
    return `${url.pathname}${url.search}`;
  }
});
```

You can find the related docs [here](https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api#validating-the-json-web-token).

**Comment by just-L** [comment]
Hi @CarlosCortizasCT 
Thank you for your response.

I have managed to make it work with admin API but I would like to use apollo client for the proxy because custom application using graphql. 


URL specified in the documentations doesn't work and create  **getaddrinfo ENOTFOUND api.us-central1.commercetools.com** response

After creating request to **https://mc-api.us-central1.gcp.commercetools.com/graphql**


I got response:
![image](https://github.com/commercetools/merchant-center-application-kit/assets/137191844/3f218bec-a840-4109-a3e5-21dcbcce43ba)

Same URL works for custom app itself. 

Can you point me to my mistake?

**Comment by just-L** [comment]
That is correct
`mport axios, { AxiosResponse } from "axios";
import * as https from "https";
import { GRAPHQL_TARGETS } from "@commercetools-frontend/constants";
import {
  gql,
  ApolloClient,
  HttpLink,
  InMemoryCache,
  createHttpLink
} from "@apollo/client/core";

import { setContext } from '@apollo/client/link/context';

import fetch from "cross-fetch";




// import { setContext } from 'apollo-link-context';

const sessionAuthVerifier = createSessionAuthVerifier({
  audience: "https://c82b-129-222-204-57.ngrok-free.app",
  issuer: CLOUD_IDENTIFIERS.GCP_US,
  getRequestUrl: (req: HttpRequest) => {
    //  console.log(req)
    return `/api/proxy`;
  },
});

const httpTrigger: AzureFunction = async function (
  context: Context,
  req: HttpRequest
): Promise<void> {
  context.log("HTTP trigger function processed a request.");

  await sessionAuthVerifier(req, context);

  const { data } = await axios.post(
    `https://auth.us-central1.gcp.commercetools.com/oauth/${
      (req as any).session.projectKey
    }/anonymous/token?grant_type=client_credentials`,
    {},
    {
      auth: {
        username: "ctclientid",
        password: "ctsecret",
      },
      headers: {},
    }
  );

  const client = new ApolloClient({
    cache: new InMemoryCache(),
    link: new HttpLink({
      uri: `https://mc-api.us-central1.gcp.commercetools.com/graphql`,
      fetch,
      headers: {
        ...req.headers,
        Authorization: `${data.token_type} ${data.access_token}`,
      },
    }),
  });

  const query = gql`
  mutation UpdateOrCreateCustomObject(
    $key: String!
    $container: String!
    $value: String!
    $version: Long!
  ) {
    createOrUpdateCustomObject(
      draft: {
        key: $key
        container: $container
        value: $value
        version: $version
      }
    ) {
      value
      version
      container
      key
      id
    }
  }
`

console.log(query)


  const t = await client.mutate({
    mutation: query,
    variables: { key: req.body.variables.key,
    version: req.body.variables.version,
    container: req.body.variables.container,
    value: req.body.variables.value
    }
  }).catch(e=>console.log(e));`

**Comment by emmenko** [comment]
You don't need to use the MC API at that point (within the azure function).

You have an access token, so you can call directly the CoCo APIs.

**Comment by just-L** [comment]
Thank you @emmenko  for suggestion.

You're correct I can use auth header from req but this is not solve the problem with url
`networkError: FetchError: request to https://api.us-central1.commercetools.com/graphql failed, reason: getaddrinfo ENOTFOUND api.us-central1.commercetools.com` for url in documentation

same for `networkError: FetchError: request to https://api.us-central1.commercetools.com/{project}/graphql failed, reason: getaddrinfo ENOTFOUND api.us-central1.commercetools.com`

same for ` networkError: FetchError: request to https://mc-api.us-central1.commercetools.com/{project}/graphql failed, reason: getaddrinfo ENOTFOUND mc-api.us-central1.commercetools.com`

and still same error: 
`statusCode: 404,
[2023-06-21T18:44:44.133Z]     bodyText: 'response 404 (backend NotFound), service rules for the path non-existent \n'`

for url: `https://mc-api.us-central1.gcp.commercetools.com/${(req as any).session.projectKey}/graphql`

**Comment by emmenko** [comment]
The hostnames are wrong (the `gcp` part is missing).

Please refer to this documentation:
* https://docs.commercetools.com/api/general-concepts#hosts
* https://docs.commercetools.com/api/graphql#graphql-queries-and-mutations

For CoCo, the GraphQL API endpoint is

```
https://api.us-central1.gcp.commercetools.com/{project}/graphql
```

**Comment by just-L** [comment]
As I already said this is the log:

```ts
https://api.us-central1.gcp.commercetools.com/my-project/graphql
[2023-06-21T19:02:37.352Z] {"graphQLErrors":[],"clientErrors":[],"networkError":{"name":"ServerParseError","response":{"size":0,"timeout":0},"statusCode":404,"bodyText":"response 404 (backend NotFound), service rules for the path non-existent \n"},"message":"Unexpected token r in JSON at position 0"}
```

As you can see error still persists

**Comment by just-L** [comment]
Could it be related some how to apollo client?
Then I use postman this url is working: **https://api.us-central1.gcp.commercetools.com/myproject/graphql**

**Comment by just-L** [comment]
You can close it. BTW i have to get a new token. Token from header is invalid. If I use token with auth endpoint then  apollo request goes through

**Comment by CarlosCortizasCT** [comment]
@just-L just wanted to let you know you can also close the issue once you think we've addressed your request.

Since it seems you already solved your use case, I'm closing this one, but feel free to reopen if you think otherwise.

Thanks.
