### ISSUE TITLE
Merchant Center Custom Application starter example wrong styles

### ISSUE THREAD

**Issue by xemayebenes** [commercetools/merchant-center-application-kit#311]
**Describe the bug**
The styles are wrong in the Merchant Center Custom Application starter.

**To Reproduce**
$ npx @commercetools-frontend/create-mc-app@next my-new-custom-application-project --template starter

$ cd my-new-custom-application-project
$ yarn start

**Expected behavior**
The example starter init page should not break the styles.

**Screenshots**
![captura de pantalla 2019-01-24 a las 12 28 27](https://user-images.githubusercontent.com/16824054/51675308-a4812b80-1fd3-11e9-8198-071d01c17b06.png)
![captura de pantalla 2019-01-24 a las 12 28 37](https://user-images.githubusercontent.com/16824054/51675320-a8ad4900-1fd3-11e9-89a0-22e2c2c54dd0.png)

**Comment by emmenko** [comment]
Oh thanks for reporting this. I'll take a look

**Comment by emmenko** [comment]
Oh I see, the react select styles are missing.

Add this import to the `src/index.js`:

```js
import 'react-select/dist/react-select.css';
```

**Comment by xemayebenes** [comment]
Thanks, it works
