### ISSUE TITLE
X-Forward-To-Audience-Policy can not be set to 'forward-url-origin'

### ISSUE THREAD

**Issue by XohanOtero** [commercetools/merchant-center-application-kit#3113]
I am developing a Custom Application for a project that requires me to use an external API. I want to set the audience so just the origin url, like shown in the documentation here https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api#configuring-the-audience-policy. 

The problem I have encountered is when I set the Audience policy 'forward-url-origin' the request is set as 'forward-url-full-path'
For our project this is not a huge issue as we can work around it, but it doesn't seem to work as intended, therefore this issue :)

Here are some screenshots showing the problem:
![image-20230615-124334](https://github.com/commercetools/merchant-center-application-kit/assets/122431026/f3e00f45-d0cd-42f4-9ec6-3029e84a683e)
![image-20230615-124235](https://github.com/commercetools/merchant-center-application-kit/assets/122431026/e5fbc6f7-86ef-46e7-9c3f-63ff1cfb2cb4)

And here is the code for the headers set on the request:

const headers = {
  'X-Project-Key': 'key-i-am-not-willing-to-share',
  'X-Forward-To-Audience-Policy': 'forward-url-origin',
  'X-Forward-To': forwardUrl,
  'Content-Type': 'application/json',
  'X-forward-header-ngrok-skip-browser-warning':'42069',
  'X-forward-header-Accept-version': 'v2',
};

**Comment by Rhotimee** [comment]
Hi @XohanOtero, Thank you for reporting this issue. We will look into it and get back to you.

**Comment by Rhotimee** [comment]
Hello @XohanOtero ,

According to the [documentation](https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api#configuring-the-audience-policy),  the functionality you are interested in became accessible starting from version `21.8.0`. Can you confirm if the version you're presently using is this, or a more recent one?

To provide you with more precise assistance, it would be highly beneficial if you could share the code snippet through which you are attempting to send the request. This will allow me to investigate more closely and pinpoint potential issues, if any.

Thank you, and I look forward to assisting you further.

**Comment by XohanOtero** [comment]
Hei! Thank you for the reply :) 
Here are the headers I use:
```
const headers = {
  'X-Project-Key': 'my-project-key',
  'X-Forward-To-Audience-Policy': 'forward-url-origin',
  'X-Forward-To': forwardUrl,
  'Content-Type': 'application/json',
  'X-forward-header-Accept-version': 'v2',
};
```

and here is the method I use to fetch the data:
```
    const data: PopularityRanking = await executeHttpClientRequest(
      async (options) => {
        const res = await fetch(buildApiUrl('/proxy/forward-to'), options);
        const data = res.json();
        return {
          data,
          statusCode: res.status,
          getHeader: (key) => res.headers.get(key),
        };
      },
      { userAgent, headers: prop.headers, forwardToConfig: { uri: url } }
    );
```
All packages I am using from CommerceTools are version 22.3.0 :)

**Comment by Rhotimee** [comment]
Based on your provided information, it seems like you are trying to include the 'X-Forward-To' and 'X-Forward-To-Audience-Policy' directly into your headers. However, these properties should be included in the forwardToConfig attribute as per the [documentation](https://docs.commercetools.com/custom-applications/api-reference/commercetools-frontend-application-shell#executehttpclientrequest).

The correct setup would be as follows:

```
// 'X-Forward-To-Audience-Policy' and 'X-Forward-To' were removed.
const headers = {
  'X-Project-Key': 'my-project-key',
  'Content-Type': 'application/json',
  'X-forward-header-Accept-version': 'v2',
};

const data: PopularityRanking = await executeHttpClientRequest(
  async (options) => {
    const res = await fetch(buildApiUrl('/proxy/forward-to'), options);
    const data = await res.json();
    return {
      data,
      statusCode: res.status,
      getHeader: (key) => res.headers.get(key),
    };
  },
  { 
    userAgent, 
    headers: prop.headers, 
    forwardToConfig: { 
      uri: forwardUrl, // make sure this variable is properly defined
      audiencePolicy: 'forward-url-origin' // configure the audience policy
    } 
  }
);
```

By making these adjustments, your request should be properly configured and you should start seeing the expected results.
Let me know if this was helpful.

**Comment by XohanOtero** [comment]
Thank you very much :)

**Comment by Rhotimee** [comment]
@XohanOtero, you could also specify  `X-forward-header-Accept-version`  in the `forwardToConfig` object with the field `version`.

```
const forwardToConfig = {
  uri: forwardUrl, 
  audiencePolicy: 'forward-url-origin', 
  version: 'v2', 
};
```

https://docs.commercetools.com/custom-applications/concepts/integrate-with-your-own-api#versioning
