### ISSUE TITLE
Merchant Center Custom Application fetch external data

### ISSUE THREAD

**Issue by xemayebenes** [commercetools/merchant-center-application-kit#312]
**Describe the bug**
I'm not sure if this is a bug, or a feature that is not available. 
This is my question:
¿Is it possible to fetch external data inside the Application?
I'm developing the customer application in local and try to call an external API, but CSP Policy violation error is thrown.

**Comment by emmenko** [comment]
Yes, you can whitelist the domains you want to call in the `csp.json` file. Check the playground app for an example: https://github.com/commercetools/merchant-center-application-kit/blob/master/playground/csp.json

**Comment by xemayebenes** [comment]
Hi @emmenko , thanks by the reply.

I've added the csp.json file to the root folder, but i have the same problem.
Do I have to change anything else?

If helps, i've started the App with the project starterr example
https://docs.commercetools.com/merchant-center/custom-applications/development#using-the-starter-example

Thanks

**Comment by emmenko** [comment]
How are you calling the API? Can you post the error you get?

**Comment by xemayebenes** [comment]
I'm using fetch
`fetch(http://api.test.tottus.cl/contact-point/search)`

The error:
`Refused to connect to 'http://api.test.tottus.cl/contact-point/search' because it violates the following Content Security Policy directive: "connect-src 'self' mc-api.commercetools.com mc-api.commercetools.co app.launchdarkly.com clientstream.launchdarkly.com events.launchdarkly.com app.getsentry.com www.google-analytics.com ws: localhost:8080 webpack-internal:".

Refused to connect to 'http://api.test.tottus.cl/contact-point/search' because it violates the document's Content Security Policy.
`
The csp.json file:

`{
  "script-src": ["api.test.tottus.cl"],
  "connect-src": ["api.test.tottus.cl"],
  "style-src": ["api.test.tottus.cl"]
}
`

**Comment by montezume** [comment]
I tried it locally and to me it looks like the issue is that your API has a CORS policy. I was able to add 

```js
    fetch('https://jsonplaceholder.typicode.com/todos/1')
      .then(response => response.json())
      .then(json => console.log(json))
```

to the starter app after modifying csp.json.

**Comment by emmenko** [comment]
I just tried and is working for me. It just the API that has to enable CORS for localhost.

<img width="1393" alt="screenshot 2019-01-24 at 17 17 28" src="https://user-images.githubusercontent.com/1110551/51691904-05bcf500-1ffc-11e9-8ff5-b349c7e0f377.png">

Are you sure you defined the `csp.json` correctly?

**Comment by xemayebenes** [comment]
Thanks for the reply @emmenko @montezume

**Comment by jtabone16** [comment]
Running into this issue, but not seeing a csp.json file. Does that no longer exist in the starter app?

**Comment by pa574s** [comment]
Running into the same @emmenko . I am not able to find any documentation for making a POST call to external api and how to send a payload in the request. Could you please help me with the documentation or with the sample code??
