### ISSUE TITLE
Improvement to how access is granted for local custom app development

### ISSUE THREAD

**Issue by mp-marc** [commercetools/merchant-center-application-kit#3122]
**Is your feature request related to a problem? Please describe.**

The current method for allowing access to local custom app development does not seem very practical, in the way it requires admin accounts to be used
 
**Describe the solution you'd like**

It would be great if instead of requiring admin rights for local development/login, the permission was instead at a team level

**Describe alternatives you've considered**

Given that admin access is required, there aren't many, if any alternatives that we are aware of - though any help here would be appreciated! 

**Additional context**

Hi!

Am hoping this is an issue you can help with - was advised to create an issue here by commercetools support (ticket ref https://commercetools.atlassian.net/servicedesk/customer/portal/22/SUPPORT-21751?created=true) 

For context, we’ve recently been asked to give the engineers in one of our teams the ability to develop and run the custom apps locally - however in doing so we have discovered that this is only possible if the users in question are part of the Administrators group 

This seems to us a quite strange requirement, as the normal approach with an admin team is to restrict membership to as few people as possible (who are responsible for granting access to the rest of the organisation) - whereas with the method used by CT it would mean (depending on requirements) that potentially everyone in an organisation would be an administrator. This is not an ideal situation, given the functions and options that are available (i.e. ability to do pretty much anything). 

We were wondering therefore if there are any alternatives available - for example a permission which can be set at a team level?

Also I would be grateful if could help us understand to the motivation behind this restriction on developer access, as would seem more logical and intuitive (e.g.) for this access to controlled at a team level? 

Many thanks!

Marc

**Comment by kark** [comment]
Hi @mp-marc 👋

Thank you for reaching out to us and providing feedback.

As mentioned, local development and login are restricted to users who are part of the Administrators team within an organization. This restriction is in place because, during the development of a Custom Application, there is potential for accessing any type of data within a project. Even if granular permissions are configured for the Custom Application, they are not applied in dev mode.

We will internally discuss your situation and attempt to find a solution for you.

**Comment by mp-marc** [comment]
Hi @kark 👋, hope all is good! 
Many thanks for your quick reply, and providing that additional context! 

I did wonder if this restriction is related to the type of data available - as such I do understand the desire to have some protection in place. However it does feel awkward having to grant administrator rights to potentially so many people! Also the concept of needing admin rights to perform local development does seem a strange one, and not something we have encountered before. 

If a solution could be found that did not require such access, I'm sure it would benefit all customers of Commercetools, and not just ourselves!

On additional/side note I would just like to say how much of pleasure we have found CT to work with! The UI and APIs are excellent and easy to use, plus the documentation you provide is outstanding and has helped us enormously!     

Many thanks again for your help!

**Comment by kark** [comment]
Hi @mp-marc,
Thank you for the kind words!
I just wanted to let you know that we are actively working on finding a possible solution. Rest assured, we will reach out to you as soon as we have something substantial to share.

**Comment by mp-marc** [comment]
Hi @kark, hope all is good! 

Is so amazing to see that you guys have started to carry out work on this! 💯 🥇 
Thanks so much to you and the dev team for picking it up so quickly! 

Am sure will make things so much easier for those who need to work with apps locally! 👍 

Can I just check though if there will be an update to the CT docs to explain how this new setup works? 

Thanks so much again for all your help!

**Comment by kark** [comment]
Hi @mp-marc,
Again, many thanks for your kind remarks 🙂
Please bear with us, we will inform you in this thread when this feature is released.
Kindly expect the updated documentation to come with the release notes.

**Comment by mp-marc** [comment]
Hey @kark, hope all is good! :slightly_smiling_face: 

Has been a few months since have commented here, so just wanted to check how progress is going with this! 
As we very excited to take advantage of the new functionality! 

Thanks!

**Comment by kark** [comment]
Hey @mp-marc 👋, 

Thank you for reaching out and for your patience! We appreciate your enthusiasm about the new functionality.

I'm pleased to inform you that we're on track with the implementation of this feature. Over the next few weeks, we'll be finalizing the development and consumer-facing documentation. Rest assured, we'll keep you updated on our progress and will be in contact soon with more details.

Once again, thanks for your patience and for being a valued part of our community. If you have any more questions or if there's anything else you'd like to know in the meantime, feel free to ask.

Thanks!

**Comment by kark** [comment]
Hi @mp-marc,

Thank you again for your patience. 

I wanted to point you to the [latest release note](https://docs.commercetools.com/custom-applications/releases/2023-11-08-introduced-granular-permissions-for-local-development-of-custom-applications) where we announce a workaround to address your use case. If you're using `22.5.0` or a higher version of the `app-kit` packages in your Custom Application, you can already utilize this feature. 

If you have any follow-up questions, please don't hesitate to let us know.

Thanks!

**Comment by mp-marc** [comment]
Thanks @kark - great to hear the feature is making god progress! 👍 
Also that is amazing to know about the workaround - will look into that! 

Thanks!

**Comment by kark** [comment]
Hi again,
I wanted to clarify that what I previously referred to as _a workaround_ is, in fact, _the feature_. 
I hope it suits your needs, and I apologize for the prior miscommunication 🙂

**Comment by mp-marc** [comment]
Hey Kark! 

That's amazing! 💯 🥇 
And that's ok about before - was equally excited for it to be a workaround as the feature itself! 🙂 

I'd just like to confirm something about the usage to check I understand if that's ok! 

suppose we have team url like this 
`https://mc.europe-west1.gcp.commercetools.com/account/organizations/8654-1234-8654-1234/teams/1234-5678-1234-5678/members` 

the team id would be `1234-5678-1234-5678`?  

and in the custom app config would do this e.g.?  
```
env: {
    development: { 
      initialProjectKey: 'pbx-development', 
      applicationId, 
      teamId 
    }
},
```

Again really excited to have this available - as am sure other customers of Commercetools will be! 🙂 

Thanks!

**Comment by kark** [comment]
Hey @mp-marc,

Thank you 🙂

> suppose we have team url like this
`https://mc.europe-west1.gcp.commercetools.com/account/organizations/8654-1234-8654-1234/teams/1234-5678-1234-5678/members`

> the team id would be `1234-5678-1234-5678`?

Yes, that's correct.

One small adjustment in the provided the custom app config:

```
env: {
  production: {
    applicationId, 
  },
  development: {      
    teamId,
    initialProjectKey: 'pbx-development', 
  }
},
```

**Comment by mp-marc** [comment]
Hey @kark! 

Thanks so much for confirming! 

Hope have a great weekend! 🙂

**Comment by emmenko** [comment]
Closing this as it seems it's resolved now. If you have further question feel free to comment or open a new issue.
Thanks
