### ISSUE TITLE
<PageContentWide> silently ignores 3rd child component and doesn't throw any error

### ISSUE THREAD

**Issue by jaikumar-tj** [commercetools/merchant-center-application-kit#3126]
**Is your feature request related to a problem? Please describe.**

The `PageContentWide` doesn't throw any error or warning when more than 2 childrens are passed as props. It only renders first 2 child since the column prop determines how many columns to render. It goes unnoticed and developers don't realise that 3rd component (eg: info dialog or warn on leave or save bar) is not rendered on the page after a while.

**Describe the solution you'd like**

It would be helpful if the components throw an error so developers could avoid the mistake of passing 3rd component and wrap everything under fragment.

**Describe alternatives you've considered**

Atleast a console warning message would also be helpful to shorten the debug time. But the above solution stops the mistake from happening at very early stage.

**Comment by CarlosCortizasCT** [comment]
Hi @jaikumar-tj,

Thanks for opening this feature request 👍 

We will look into it and try to improve the DX around that component.

Regarding the use cases you mention, I would say those extra components (info dialog, save bar,...) should not be wrapped in a `PageContentWide` though. This component is about laying out main content in a page and those examples are more about floating or fixed elements which might not be good candidates for this component.

Anyway, we'll try to improve this component and let you know.
