### ISSUE TITLE
Not able to debug custom application using launch.json file

### ISSUE THREAD

**Issue by Mohansharu** [commercetools/merchant-center-application-kit#3171]
Hi,

I'm not able to debug the custom application using the launch.json file, If I run the debug I get the following error in the debug console. please help me with this issue. 

thanks in advance

<img width="715" alt="image" src="https://github.com/commercetools/merchant-center-application-kit/assets/141209499/6b72e1ed-d967-4b69-83bd-75cd2c74061a">

**Comment by VictorAvelar** [comment]
Good morning @Mohansharu,

Thank you for opening this issue. I would recommend taking a look at [this other issue](https://github.com/microsoft/vscode/issues/102042#issuecomment-656402933), as it appears to be connected to your problem. As you can observe, it's unrelated to our application and therefore not a bug.

Please inform us if this proves helpful!

**Comment by Mohansharu** [comment]
Hi @VictorAvelar ,

I refer to the issue which you attached. It's not working after trying those and moreover, the issue I'm facing is different from the link which you have attached. 

<img width="734" alt="image" src="https://github.com/commercetools/merchant-center-application-kit/assets/141209499/ead89942-5042-4324-8456-75fd38ab6d95">

I have attached my launch.json file as well.

**Comment by VictorAvelar** [comment]
We are investigating and will get back to you as soon as we collect any relevant info. Please feel free to let us know any developments on your end.

**Comment by kark** [comment]
Hi @Mohansharu,

If there are any missing source maps for transitive dependencies, you can include those dependencies explicitly in your Custom Application.
For example:
```console
yarn add -D debounce-promise@^3.1.2
yarn add -D popper.js@1.15.0
```
I believe no further changes are necessary. However, if you encounter issues with the VS Code debugger not detecting these source maps, you may find @VictorAvelar's suggestion helpful in your `launch.json`:
```json
"resolveSourceMapLocations": [
  "${workspaceFolder}/**",
  "!**/node_modules/**"
]
```
Thanks

**Comment by Mohansharu** [comment]
Hi @kark @VictorAvelar 

May I know which is the recommended node version?? 
Might be node because of node version source files are missing?

**Comment by kark** [comment]
Hi,

> which is the recommended node version to use in the custom application

It depends on the version of the version of `@commercetools-frontend/*` packages you are using in your Custom Application. For the latest version it is
https://github.com/commercetools/merchant-center-application-kit/blob/f3a06a44462768241d4df1cb44f60f294ab28699/package.json#L183

> Might be node because of node version source files are missing?

With the limited information available, providing a definitive answer is not straightforward, sorry.
However, if you're considering debugging using the VS Code debugger [a new Custom Application from template](https://docs.commercetools.com/custom-applications/getting-started#installing-a-starter-template) in Node v18 you would still need to manually include the two transitive dependencies I previously recommended.

**Comment by Mohansharu** [comment]
Hi,

Thanks, Its working fine
