### ISSUE TITLE
Not able to deploy custom application into merchant center

### ISSUE THREAD

**Issue by Mohansharu** [commercetools/merchant-center-application-kit#3206]
Hi All,

After following all the procedures to deploy a custom application into the merchant center, I'm getting following page when I try to open the custom component which I worked.

<img width="608" alt="image" src="https://github.com/commercetools/merchant-center-application-kit/assets/141209499/db1478ab-fc1b-4582-948f-af4bdb30bbdb">

This is my application, If I click any component in custom which developed I'm getting the above page saying access denied.

<img width="617" alt="image" src="https://github.com/commercetools/merchant-center-application-kit/assets/141209499/96b2d86c-bfe4-478f-86b7-d173579c6e11">

this is my S3 bucket policy & CORS
<img width="670" alt="image" src="https://github.com/commercetools/merchant-center-application-kit/assets/141209499/8f8866dc-47c7-4914-964f-488a6ac6fcdf">

<img width="666" alt="image" src="https://github.com/commercetools/merchant-center-application-kit/assets/141209499/c5c1b9ef-2cb7-4b74-ba24-99cb124c2e1b">

**Comment by Mohansharu** [comment]
Hi All,

Can anyone please help me with this??

**Comment by kark** [comment]
Hi @Mohansharu,

Please refer to [the section on setting up custom error responses](https://wolovim.medium.com/deploying-create-react-app-to-s3-or-cloudfront-48dae4ce0af#:~:text=Yes%20for%20a-,custom%20error%20response,-%2C%20set/index.html) in the external documentation linked in [our AWS/S3 bucket deployment guide](https://docs.commercetools.com/custom-applications/deployment-examples/aws-s3-cloudfront). 
Feel free to inform us if this resolves the issue. If you encounter any issues or have questions, feel free to reach out and let us know how it goes.

Thanks
