### ISSUE TITLE
Adding UI components for building applications

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#323]
Now that we started moving components into the new package `@commercetools-frontend/application-components` (#316), we can continue adding more components that will help building applications.

This issue is meant to show a priority list of the components that we want to move/add first.

_Components should adhere to the same principles of components developed in ui-kit._

---

Storybook integration: #366 

#### Maintenance pages
- [x] `PageNotFound` (#316)
- [x] `ServicePageResponseLayout` (#316)
- [ ] `PageUnauthorized`

#### Dialogs
- [x] `InfoDialog` #367 
- [x] `ConfirmationDialog` #377 
- [x] `FormDialog` #399 

#### Page layouts
_These components should be implemented carefully, considering the use cases we've encountered so far. Most likely they are composed by lower-lever components that can be reused as well for special cases._
- [ ] `TabPage`
- [x] `InfoModalPage`, `FormModalPage`, `TabularModalPage` #642 
- [ ] `ListPage`

#### Controls
- [ ] `Pagination`
- [ ] `WarnOnLeave`

**Comment by montezume** [comment]
Thanks for keeping track of this! 🙌

**Comment by emmenko** [comment]
FYI: I started drafting a `ModalPage` component that we will try out first internally in the apps. If everything works fine, we will then move it here in the app-kit.

**Comment by mmaltsev-ct** [comment]
The ticket is not required anymore. Some tasks have already separate tickets in the ui-kit and app-kit repos. In case of getting back to the migration topic, the review is advised. Hence, closing.
