### ISSUE TITLE
Triggering `QuickAccess` programatically

### ISSUE THREAD

**Issue by montezume** [commercetools/merchant-center-application-kit#324]
The topic of being able to trigger `QuickAccess` has came up with regards to the new Welcome Screen.

The idea would be that, we can trigger `QuickAccess` on a button click, and when `QuickAccess` is triggered this way, it will display additional usage instructions like below

![quick-access](https://user-images.githubusercontent.com/2425013/51907225-7b430f80-23c6-11e9-83ff-bae12aa0ac3f.png)

What would the best way doing this? I came up with a few ideas.

* Simply fire a keydown event through JavaScript with some sort of custom property, and if this custom property is present, QuickAccess renders with these additional instructions
* Provide an API for triggering QuickAccess programatically, perhaps through ApplicationContext.

Any other ideas?

**Comment by emmenko** [comment]
How about via a query parameter?

- `?quickAccessMode=manual`
- `?trigger=quick-access`
- ...

**Comment by montezume** [comment]
How would we catch this route change with `QuickAcess` though? Wouldn't this require a complete refactoring?

**Comment by qmateub** [comment]
> How would we catch this route change with QuickAcess though? Wouldn't this require a complete refactoring?

Using maybe `withRouter` so you can check the route information? 🤔

**Comment by emmenko** [comment]
Quick access is already wrapped by a Route, so it shouldn't be a problem. We can have a look together if you want

**Comment by montezume** [comment]
Feels weird to either render QuickAccess based on a keydown event or a route change.

**Comment by emmenko** [comment]
Is this really necessary and worth the effort then? Why not adding a message on how to use it? Who came up with those requirements? Should we have a talk about it?

**Comment by emmenko** [comment]
To be honest, it feels also weird to me

**Comment by qmateub** [comment]
@montezume Can we have a quick chat with Sven about this feature? If it's not really worth the effort as @emmenko says I really like the idea of just showing a InfoDialog explaining how to use Quick Access. WDYT? 🤔

**Comment by emmenko** [comment]
I talked to Sven and we probably don't need a button. He's going to look at a version with a text or something and he'll get back to us.
So let's keep this on hold for now.

**Comment by montezume** [comment]
I would if it would make sense to allow consumers to bind certain keys and or actions to the `QuickAccess` trigger? 

Maybe if your locale is set to Spanish you can trigger it with `B`? 🤔 

YDYT @emmenko ?

**Comment by emmenko** [comment]
I suppose we can close this as we opted for another solution.
