### ISSUE TITLE
Unable to access custom applications locally 

### ISSUE THREAD

**Issue by mp-marc** [commercetools/merchant-center-application-kit#3265]
Hi! 

Am not sure if this the correct place to raise this issue, but would appreciate your help! 

Also fyi I have created a ticket through the service desk here https://commercetools.atlassian.net/servicedesk/customer/portal/22/SUPPORT-23454?created=true but was hoping that raising it here may go to a different team of developers, with some different knowledge e.g.! 

I was trying to run one of the custom apps locally (to prepare for a demonstration) and although was able to login saw the following message 
 
<img width="1787" alt="Screenshot 2023-10-11 at 14 32 37" src="https://github.com/commercetools/merchant-center-application-kit/assets/7997301/234b9c25-1d63-45dc-a20c-25c160c302aa"> 

Authorisation shouldn't be an issue, as I'm part of the `admin` group - and as such am confused as to what is causing this! As you can see there are no errors in the console, or obvious (to myself anyway!) messages 

It is very important that this functionality is working for us, as we are just entering into our Christmas peak period and need to be able to carry out changes/fixes etc. as required! 

Would therefore be very grateful if could suggest any reasons why this may be happening! 

Many thanks

Marc Podgorney

**Comment by kark** [comment]
Hi @mp-marc,

Thank you for bringing the issue to our attention. We've received your service desk ticket and have addressed the matter. Please check again; local development should now be enabled.
We're sorry for the inconvenience.

**Comment by mp-marc** [comment]
Hi @kark! 

I can confirm that this is working now! 

Thanks so much for fixing this so quickly! 👍 🥇

**Comment by kark** [comment]
Hi @mp-marc,

Thank you for the feedback.
I will go ahead and close this issue. If you have any further concerns or if this needs revisiting, feel free to reopen or create a new issue. 

Thanks again.
