### ISSUE TITLE
[Custom Application] Deployment to Azure blob storage with security settings

### ISSUE THREAD

**Issue by nitinkhr** [commercetools/merchant-center-application-kit#3317]
Hi,

We are developing Merchant Center custom application which is deployed on Azure blob storage account. We are deploying the production build of custom application as static web site on Azure blob storage following the documentation [Deploying to Azure with Blob Storage](https://docs.commercetools.com/custom-applications/deployment-examples/azure-blob-storage) . The application has been deployed successfully but we are not able to access the deployed custom app from Merchant Center and get error like below when accessing it-

```
The requested content does not exist.
 

HttpStatusCode: 404

ErrorCode: WebContentNotFound

RequestId : d50d44ff-301e-003a-0e77-235647000000

TimeStamp : 2023-11-30T10:23:06.9890573Z
```

I suspect this issue to be related with our Azure storage account’s (Security + networking) settings where the “Public network access“ is not enabled from all networks but enabled only from “selected virtual networks and IP addresses” due to our organization’s security policy and we are not allowed to change that.

![image](https://github.com/commercetools/merchant-center-application-kit/assets/1422643/cf3bbda0-32c2-44c9-94b0-450d54443fff)

Same custom application works fine from Merchant Center when deployed to another Azure storage account outside of organization which has "Public network access" enabled from all networks. So what I want to know that if there is a recommended way to handle this situation keeping organization’s security policy intact? Also if it would be possible to get the IP range for Commercetools Merchant Center so that I can whitelist them under the Azure Firewall IP range on the Azure storage blob network/security settings.

Looking forward to the inputs in this regard. Thank you.

**Comment by emmenko** [comment]
Closing in favor of #3318
