### ISSUE TITLE
When Trying to authenticate in localhost the credentials are showing as Invalid

### ISSUE THREAD

**Issue by saikrishnabanda1** [commercetools/merchant-center-application-kit#3385]
**Describe the issue**

I have cloned the merchant-center-application-kit repo and I am running it in the local server, It is asking for the authentication ,when I give a valid credentails it is showing as invalid token and not able to login

**Screenshots**
![Screenshot 2024-01-24 123307](https://github.com/commercetools/merchant-center-application-kit/assets/157004015/ef20ec32-241c-4a7a-b29e-293aea6157a0)

![Screenshot 2024-01-24 123703](https://github.com/commercetools/merchant-center-application-kit/assets/157004015/f0e66c9f-2a2e-4f4b-b475-4396053c658d)

**Additional context**

**Comment by saikrishnabanda1** [comment]
The browser opens a new tab pointing to **http://localhost:3001**. It is redirected to the login page of the Merchant Center where I need to enter your commercetools account credentials.

I have the access to **cloudIdentifier: 'gcp-au'**. Eventhough it is not working with valid credentails.

When I try to login here. https://mc.australia-southeast1.gcp.commercetools.com/ . It is working fine. 
Only during the authentication in localhost it is not working. In network tab it is showing token error

**Comment by CarlosCortizasCT** [comment]
Hi @saikrishnabanda1 

By default, the Custom Application will be configured to use the GCP-EU regions APIs. ([docs reference](https://docs.commercetools.com/custom-applications/getting-started#configuring-the-custom-application)).
Can you maybe double checked you have updated your Custom Application configuration to use the GCP-AU region? ([docs reference](https://docs.commercetools.com/custom-applications/api-reference/application-config#cloudidentifier)).

Thanks.

**Comment by saikrishnabanda1** [comment]
Yes, I have updated in a same way.

![image](https://github.com/commercetools/merchant-center-application-kit/assets/157004015/e3ac0878-4d20-43fb-85d4-221b7c7cdb25)

Thank you

**Comment by CarlosCortizasCT** [comment]
Hi @saikrishnabanda1 

Can you please double check the user you are using to login is part of the administrators team of your organization?
Also, could you share the project key and the Custom Application `entryPointUriPath` you are using?
You can also check the `entryPointUriPath` you are using is not one of the internal reserved ones ([reference](https://docs.commercetools.com/custom-applications/api-reference/application-config#entrypointuripath)).

It would also help if you can provide the login server response.

Thanks.

**Comment by saikrishnabanda1** [comment]
For this  api which is called by commerce tools for authentication , https://mc-api.australia-southeast1.gcp.commercetools.com/tokens

PFA of the payload and api response for the above api

![Screenshot 2024-01-25 115706](https://github.com/commercetools/merchant-center-application-kit/assets/157004015/1e04d80e-e40e-4a18-a6fd-8daf8570b8e7)
![Screenshot 2024-01-25 115819](https://github.com/commercetools/merchant-center-application-kit/assets/157004015/80f33e57-ffca-4380-a6bd-b9b0bde8463d)

In the above image it is showing as **something_demo_project**, but I am using **something-practice-retail-project** as initialProjectKey. But I am not getting response with the initialProjectKey I have used.

**Comment by CarlosCortizasCT** [comment]
Hello @saikrishnabanda1 

So what we can see in the response is that the project you're using in your Custom Application configuration does not exists.
Can you make sure the project you're using (is it `something-practice-retail-project`?) is created in an organization where you are part of the administrators team in the [Merchant Center for the GCP-AU region](https://mc.australia-southeast1.gcp.commercetools.com/)?

**Comment by saikrishnabanda1** [comment]
Let's consider **something-practice-retail-project** is used as **something-practice-project**
I am a part of the administrators team and also the project is available in the organization

PFA
![Screenshot 2024-01-25 150006](https://github.com/commercetools/merchant-center-application-kit/assets/157004015/2fcab995-5203-425f-b9c9-034190ada409)

![image](https://github.com/commercetools/merchant-center-application-kit/assets/157004015/f9ead04d-7b04-44c0-a25c-c564f26dfdb8)

**Comment by CarlosCortizasCT** [comment]
Hello @saikrishnabanda1 

The missing part to me is that you have two projects in your organization, but none of them have a key like the one you get back in the error from the login request (`*_demo_project) so it seems your trying to log in with a wrong project key.

It would be great if you can share the URL you see in the browser when you get to the login page.

Also, make sure the project key you have set up in your Custom Application [configuration file](https://docs.commercetools.com/custom-applications/api-reference/application-config#envdevelopmentinitialprojectkey) matches a key of one of the projects your organization has.

You can also maybe try to clean the browser cache and storage.

Thanks.

**Comment by jivansanchez** [comment]
Hello Support Team.

I have exactly same issue, when I execute the Custom Application locally it opens the login screen, my Merchant center is deployed in gcp-us, when I try the login with valid credentials I got a Login failed message.

<img width="681" alt="Screen Shot 2024-01-29 at 07 39 53" src="https://github.com/commercetools/merchant-center-application-kit/assets/12188257/43c729ef-71cc-4799-b5f8-ffc403b677c3">

But if I try the login directly to Merchant center with same credentials, it works.

<img width="891" alt="Screen Shot 2024-01-29 at 07 40 58" src="https://github.com/commercetools/merchant-center-application-kit/assets/12188257/267a50cf-f3a2-4512-9bcb-69d6d60e4457">

This is my configuration for Custom Application.

<img width="578" alt="Screen Shot 2024-01-29 at 07 42 28" src="https://github.com/commercetools/merchant-center-application-kit/assets/12188257/f27edb5a-6e51-4a5c-a305-2b1b700ceb62">

Thanks for your support.

**Comment by CarlosCortizasCT** [comment]
Hello @jivansanchez 

I would maybe suggest to check you are using the right project key. This should be an existing project of an organization where you should be part of the administrators team.

It seems you're using the `perf-mc-custom-application-channels` key in your Custom Application, but it seems it does not exist a project with that key.

Also, checking the response payload when the login fails, in the browser dev tools, might give some more information.

Please, let me know if this helps.

**Comment by saikrishnabanda1** [comment]
I resolved the issue. When I try normally in the browser it is not working. But when I try in the Incognito mode it is working fine. This may be because of cache issue on the browser.

**Comment by jivansanchez** [comment]
> Hello @jivansanchez
> 
> I would maybe suggest to check you are using the right project key. This should be an existing project of an organization where you should be part of the administrators team.
> 
> It seems you're using the `perf-mc-custom-application-channels` key in your Custom Application, but it seems it does not exist a project with that key.
> 
> Also, checking the response payload when the login fails, in the browser dev tools, might give some more information.
> 
> Please, let me know if this helps.

Thank you for answering.

I generated again the Custom Application using the project key that I have in MC and have same issue, please images.

<img width="760" alt="Screen Shot 2024-01-30 at 05 29 01" src="https://github.com/commercetools/merchant-center-application-kit/assets/12188257/d23253a3-40ee-4185-aa45-2946c73ef756">

![Screen Shot 2024-01-30 at 05 26 52](https://github.com/commercetools/merchant-center-application-kit/assets/12188257/11b76bdb-ebad-400e-b6fa-56311e29fa5a)

Also, I checked the console when I was trying the login and I saw a HTTP 400(Bad Request).

<img width="1178" alt="Screen Shot 2024-01-30 at 05 26 44" src="https://github.com/commercetools/merchant-center-application-kit/assets/12188257/878a90f3-9682-430d-8ce7-648b0679be2f">


Thank you.

**Comment by CarlosCortizasCT** [comment]
Hello @jivansanchez 

I think that might be because you used that project key in the past.

Could you maybe try form an incognito browser tab?

You can also try to clear browser cached data and storage.

**Comment by jivansanchez** [comment]
> Hello @jivansanchez
> 
> I think that might be because you used that project key in the past.
> 
> Could you maybe try form an incognito browser tab?
> 
> You can also try to clear browser cached data and storage.

Thanks

I did both, clear cookies and local storage of my browser and also from Incognito in both cases got same result. Login failed with same error message 

Next what I did was restart my machine to remove any temporal cache and try it again in incognito and it worked, but this behavior shouldn't be in this way, I think.

Thanks for support.

**Comment by CarlosCortizasCT** [comment]
Hello @jivansanchez 

Yes, we totally agree with you and this is not the developer experience we aim for.

We are already researching for a better solution to this problem.

Thanks for your feedback.

**Comment by CarlosCortizasCT** [comment]
Hello,

We've worked on a refactor in some of our component to avoid this situation happening again.

Please update to the new `22.17.0` [version](https://github.com/commercetools/merchant-center-application-kit/releases/tag/v22.17.0) of `app-kit` components whenever you can.

Thanks.
