### ISSUE TITLE
Error in fieldDefinitions for a valid FieldDefinitionInput type

### ISSUE THREAD

**Issue by saikrishnabanda1** [commercetools/merchant-center-application-kit#3392]
**Describe the issue**
I am using the Graphql schema in the below format for mutation

**Screenshots**
![image](https://github.com/commercetools/merchant-center-application-kit/assets/157004015/665b107a-f20d-40e2-a3e3-06e95fc452b2)

But I am getting the error even if I give the valid fieldDefinitions type which is **FieldDefinitionInput!** which contains

type: FieldTypeInput!
name: String!
label: [LocalizedStringItemInputType!]!
required: Boolean!
inputHint: TextInputHint!

as per the documnetaion

But I am getting the below response showing that  **Reason: 'type.name' Field 'name' is not defined in the input type 'FieldTypeInput'."**
Can anyone help me resolve this issue

`{
    "errors": [
        {
            "message": "Variable '$fieldDefinitions' expected value of type 'FieldDefinitionInput!' but got: {\"name\":\"test_name\",\"label\":{\"locale\":\"de-DE\",\"value\":\"multi_lingual_support\"},\"required\":false,\"type\":{\"name\":\"sai\"},\"inputHint\":\"SingleLine\"}. Reason: 'type.name' Field 'name' is not defined in the input type 'FieldTypeInput'.",
            "locations": [
                {
                    "line": 1,
                    "column": 151
                }
            ],
            "extensions": {
                "code": "InvalidInput"
            }
        }
    ]
}`

**Comment by Rhotimee** [comment]
Hey @saikrishnabanda1,

The error suggests a mismatch in the type field structure within fieldDefinitions. Instead of "type": {"name": "sai"}, the schema expects a specific structure for FieldTypeInput. Ensure your type field aligns with the schema, which might look something like this in your mutation:

mutation CreateTypeDefinition {
  createTypeDefinition(draft: {
    // Your other fields
    fieldDefinitions: {
      type: {
        // Adjust based on schema
        String: {
          dummy: "Value"
        }
      }
      // Other field definition details
    }
  }) {
    // Expected response fields
  }
}

**Comment by saikrishnabanda1** [comment]
Thank you, Issue is resolved
