### ISSUE TITLE
[docs] Request deployment example for Akamai CDN

### ISSUE THREAD

**Issue by Divya-Gunaseelan** [commercetools/merchant-center-application-kit#3569]
**Where would you like to deploy your Custom Application or Custom View?**
Customer would like to deploy custom app through Akamai CDN.

**Additional context**
Add any other context or information about the requested example.

**Comment by Rhotimee** [comment]
Hi @Divya-Gunaseelan, you should be able to deploy Custom Application or Custom View on Akamai CDN. We currently do not have any documentation regarding that however, it's practically the same process as deploying a SPA. For reference, you can look at our docs for some [deployment examples](https://docs.commercetools.com/merchant-center-customizations/deployment-examples).

**Comment by mmaltsev-ct** [comment]
@Divya-Gunaseelan please let us know if you're struggling with the deployment. In the meantime, we added your request to the list of possible improvements for the docs. Thanks so much for reaching out!

**Comment by mmaltsev-ct** [comment]
@Divya-Gunaseelan I'll close the issue for now, please reopen it if you have any follow-up questions.
