### ISSUE TITLE
Getting error has been blocked by CORS policy:Request header field ocp-apim-subscription-key is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by Shiwsahaya** [commercetools/merchant-center-application-kit#3570]
### Discussed in https://github.com/commercetools/merchant-center-application-kit/discussions/1985

I get this error while calling the APIM endpoint with the subscription key. It works with random APIM without a subscription key.

Access to fetch at 'https://mc-api.australia-southeast1.gcp.commercetools.com/proxy/forward-to' from origin 'https://mc.australia-southeast1.gcp.commercetools.com' has been blocked by CORS policy: Request header field ocp-apim-subscription-key is not allowed by Access-Control-Allow-Headers in preflight response.

Here is the my code
```

import {
    buildApiUrl,
    executeHttpClientRequest,
} from '@commercetools-frontend/application-shell';

export const fetcherForwardTo = async (targetUrl, subscriptionKey, payload) => {
    const data = await executeHttpClientRequest(
        async (options) => {
            if (payload) {
                options.method = 'POST'
                options.body = JSON.stringify(payload)
                options.headers = {
                    'Ocp-Apim-Subscription-Key': subscriptionKey,
                    "Content-Type": "application/json"
                }
            }
            const res = await fetch(buildApiUrl('/proxy/forward-to'), options);
            const data = await res.json();
            return {
                data,
                statusCode: res.status,
                getHeader: (key) => res.headers.get(key),
            };
        },
        {
            headers: { "Content-Type": "application/json" },
            forwardToConfig: {
                uri: targetUrl
            }
        }
    );
    return data;
};
```
Any suggestion on how I can resolve this issue? Thanks.

**Comment by kark** [comment]
Hi 👋,
Please be mindful of how the [custom headers](https://docs.commercetools.com/merchant-center-customizations/concepts/integrate-with-your-own-api#custom-http-headers) should be created (the name should be prefixed with `x-forward-header-`).
I encourage you to use the `createHttpClientOptions` helper which does this automatically:
```js
import {
  createHttpClientOptions,
} from '@commercetools-frontend/application-shell';

const clientOptions = createHttpClientOptions({
    headers: {
      'Content-Type': 'application/json',
    },
    forwardToConfig: {
      uri: targetUrl,
      headers: {
        'Ocp-Apim-Subscription-Key': subscriptionKey,
      },
    },
  });
```

**Comment by Shiwsahaya** [comment]
Thank you so much for your help. I really appreciate it!
