### ISSUE TITLE
Warning in the console when using Confirm Dialog

### ISSUE THREAD

**Issue by jamesgarzon** [commercetools/merchant-center-application-kit#3589]
**Describe the issue**
When a Confirm Dialog is prompted, a warning in the console indicate that the secondary button is using a deprecated property

**To Reproduce**
Create a simple code to prompt a confirm Dialog, and just with that the warning appears

**Expected behavior**
No warnings in the console

**Screenshots**
<img width="1728" alt="Screenshot 2024-08-08 at 9 57 38 AM" src="https://github.com/user-attachments/assets/35a0ac88-4225-4624-9ed7-b5c8c3cbcea5">

**Additional context**
This happens only in local

**Comment by emmenko** [comment]
Hi, sorry about that.

We fixed that in the latest version `v22.30.3`. Can you give it a try?

**Comment by jamesgarzon** [comment]
Hi thanks for solving it, with `v22.30.3` the warning disappears
