### ISSUE TITLE
[Proposal] External/Remote Navbar Config

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#37]
## Motivation

Up until now we’ve been dealing with a static configuration for the navbar links, defined within the [AppShell](https://github.com/commercetools/merchant-center-application-kit/blob/9f2f12c33b5976e14d239b96f0c3c9aed5a51987/packages/application-shell/src/components/navbar/config.js#L236-L245).
This allowed us to share the same config between all the applications, including custom applications.

However, having all the config for each application in one place has some disadvantages:
* Changes need to be released in app-kit, even while you are developing some new features (not released yet) that require a menu link
* All apps need to upgrade to the latest version to have the latest changes, including custom apps

I would say that those are becoming some very annoying problems that we should start dealing with.

Ideally, the AppShell should simply not have any hardcoded config and fetch it from a “common” place. This will allow to decouple the releasing of new changes in the Navbar from the AppShell and furthermore to ensure that all applications will get the same config on runtime, no matter which version of the AppShell is installed on each application.

## So what is this “common” config and where does it come from?

I think that for starters, each application (the ones managed by us) should contain the Navbar config for their own routes. Then, during deployment, the config will be pushed to this “common” place, that contains all the configs of all applications.
This has the advantage of having the configs co-located to the application and being decoupled from the AppShell (as mentioned). Furthermore, changes to the config will be reflected immediately to all applications once deployed together with the application.

The main question I have is around the “common” place.
Eventually, the Navbar component will need to fetch this configs from an API endpoint or something.
I suppose we can have this config defined in our mc-settings API. Managing the updates to the config from the deployment though, might require some effort to sync the updates.
Another option might be to push the config to our storage bucket, as a static file. I think the problem here would be to properly sync/merge the configs from the different apps deployments.

I think this is the only open question we have to proceed with this approach.

Let me know what do you think and if you have concerns or suggestions about it.

---

Update: the final proposal is described here https://github.com/commercetools/merchant-center-application-kit/issues/37#issuecomment-444500693

**Comment by emmenko** [comment]
> One config for all apps

The main problem I see with that is merge conflicts / concurrent updates. It can be that multiple applications are being deployed at the same time, which means that each app can potentially update "outdated" versions of the config file.

I would also advise against downloading the config when the http server starts because we might end up with stale configs. For instance, the "latest" config will be available in the app only when the app restarts as opposed to a runtime config where it's ensured to be up-to-date.

> Storing it as a settings feels more "right" (whatever that means). However also more complicated. Given that it's nothing really user nor project specific we might not have to and can just store it publicly available.

I also feel like having it stored to a setting is "more right". Given my points above, I think it should be loaded on runtime from a single API endpoint. I would drop the option of loading it from the app server, for the reasons mentioned above.
So yeah, that would be the my point of view of what we need to consider.

**Comment by emmenko** [comment]
Alright, I just had a meeting with @tdeekens, @adnasa and @pa3 about this. Here's the outcome:

- we will go with the **Google Storage** approach
- each app will have a static `menu.json` file with the configuration for the specific application menu items
- for local development, when starting a single app, the app will only show its menu configuration, since the links to the other apps are dead anyway
  - when starting all apps at once (only available in the mc-fe repo), all apps menu configs will be loaded
- during deployment, applications will upload the `menu.json` to the storage bucket where the webpack assets are uploaded. This way, we can easily determine the "normal" production apps from the branch deployments
- the http-proxy (being the only component that knows about the different apps) will expose an endpoint to fetch the aggregated menu configs. Those configs are downloaded by the proxy from the respective storage buckets
- the `Navbar` component will then simply fetch the config from the new endpoint, and render the menu items accordingly on runtime (like we do with the links for the custom apps)

I'll try to get something working soon so that we can move on with it.

**Comment by tdeekens** [comment]
Cause custom applications (built and maintained by other companies) are released on their own deployment circle. Given they are deployed rarely they may contain outdated menu entries. Given each app needs all menu entries to show the full menu this can become quite broken when navigating between 1. outdated/not recently deployed custom apps and 2. our apps which need to be deployed together too given menus change.

**Comment by emmenko** [comment]
Not only that but if you pass the config to the app, when you render it will only render the config for that app. So how do you "load" the config from the other apps?

I hope it makes sense 🙃
