### ISSUE TITLE
[Proposal] Make playground import code from `src` instead of latest npm version.

### ISSUE THREAD

**Issue by montezume** [commercetools/merchant-center-application-kit#41]
### Proposal

Playground will be a lot more useful if it can also be used when developing features for the application kit. 

#### How?

Either use a babel plugin to change the imports to come from source whenever an import is coming from `playground` (such as [babel-plugin-module-rewrite](https://www.npmjs.com/package/babel-plugin-module-rewrite),  or just rewrite the imports to read 

```js
import * as sdkActions from '../../src/packages/sdk'
```

**Comment by dferber90** [comment]
In ui-kit I've made the playground use the local build. I'm not sure whether this is possible with lerna, but if we can build continuously, we can use the local build.

I like that approach as it still uses the real local build instead of the source files while giving the ability to experiment locally. So the playground is closer to the final result as it uses the rollup production build instead of the webpack one.

Maybe this would be an idea for app-kit?

**Comment by montezume** [comment]
@dferber90 yeah, that's where I was going with this. However, I felt like we could start by having playground use the source files, and then once the rollup build is merged, switch to using that. It will also help for testing the rollup build PR.

**Comment by tdeekens** [comment]
Ultimately using the rollup build in watch mode would be closest to getting „real“ results. I think it is totally fine to use source files as an intermediary step. Lastly, I am not sure how much value testing your build tool has, don’t get me wrong. It has loads of value with UIKit. Maybe it has a little bit less value here. Anyway, the same setup across repos would be kind of cool. With an intermediate step I suppose.

**Comment by montezume** [comment]
I'm really confused now. I made a branch to do this using module plugin rewrite, etc, but then I go to master, clean node_modules, etc, and I find that this is `already working`. When you make changes in packages, webpack figures it out and you get the new version. Am I missing something? I guess I can close this. Maybe we need this after rollup config is finished, but for now it seems fine. 🤷‍♂️

**Comment by tdeekens** [comment]
Be happy, don't worry.

**Comment by montezume** [comment]
Pretty big facepalm moment though. Good thing these are private github repos...
