### ISSUE TITLE
Transifex GitHub integration

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#433]
Just for awareness.

There is a new feature to integrate transifex with github, and we have early access. We should try it out!

https://docs.transifex.com/integrations/transifex-github-integration

**Comment by emmenko** [comment]
Done, let's see what happens 😊

<img width="989" alt="image" src="https://user-images.githubusercontent.com/1110551/54015032-c77c2f00-417e-11e9-8df9-c8350ecd3808.png">

**Comment by qmateub** [comment]
Looking forward to this! I guess that if this works out the CI job for translations will be removed right Nicola? 💯
