### ISSUE TITLE
FormDialog  problem showing data in select input

### ISSUE THREAD

**Issue by FlopiVG** [commercetools/merchant-center-application-kit#533]
**Describe the bug**
I have a problem when render a FormDialog modal (i think its the same for all modals) when put a Select Input inside of it and display the data the info show inside of modal and I have to scroll down to see the values.

I try to hardcode .dialog-styles-mod_dialog-content__{dinamic} class with `overflow: visible`and work as spected.

**To Reproduce**
1. Create a FormDialog 
2. Put as children an input field.
3. Display the values and you can see it inside of modal and had to scroll down.

**Expected behavior**
See the dropdown values in front of modal.

**Screenshots**
![image](https://user-images.githubusercontent.com/9992637/55879648-67264600-5b9f-11e9-94e2-f4f12124ec58.png)

**Comment by montezume** [comment]
Thanks for reporting this! I can take it 🤓

**Comment by emmenko** [comment]
We can't use `overflow: visible` because it breaks the normal content overflow.

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/1110551/56120967-804c3f80-5f6f-11e9-99e0-fd6c0ebd9de5.png">

We need to find another solution

**Comment by emmenko** [comment]
This seems to be a known issue with react-select.

- https://github.com/JedWatson/react-select/issues/810
- https://github.com/mui-org/material-ui/issues/7431

@montezume is looking into an advanced configuration of react-select, to render the menu into a different portal (https://react-select.com/advanced#portaling).

**Comment by montezume** [comment]
I have a pull request open in ui-kit, [682](https://github.com/commercetools/ui-kit/pull/682) to help with this problem. Once that's merged and released, we can render select-inputs and fields inside of a portal, and that should solve this problem.

**Comment by emmenko** [comment]
@montezume I guess this is now fixed, right?

**Comment by montezume** [comment]
As long as users are using menuPortalTarget yes
