### ISSUE TITLE
Refactor `assets` package to contain files with semantic naming

### ISSUE THREAD

**Issue by tdeekens** [commercetools/merchant-center-application-kit#546]
**Describe the change**

The `@commercetools-frontned/assets` package currently contains assets with non semantic filenames. So files are called after where they are used `ProjectSuspended.svg` etc. This makes reuse hard as the filename already suggests a use case. Instead we could, as with icons in UIKIt, name files after what they are: `Hourglass.svg` for instance can be used for project suspension and pending initialization.

**Follow ups**

1. Come up with a clear naming policy with design /cc @filippobocik 
2. Implement the change and document the breaking change

**Comment by tdeekens** [comment]
These are files currently in the package: https://github.com/commercetools/merchant-center-application-kit/tree/master/packages/assets/images

Personally I think these require renaming:

- failed-authentication
- failed-authorization
- image__broken
- image__missing_image
- image__no_image
- link-external__broken
- link-external__working
- page-not-found
- project-expired
- project-suspended
- radio-check-icons
- unexpected-error

**Comment by filippobocik** [comment]
I agree on using the same naming pattern for this as for the UI Kit icons: https://wiki.commercetools.com/display/DD/Icons

See my suggestions bellow. Happy to hear any feedback or better suggestions :)

- failed-authentication => omg no idea :D diamond-behind-fence?
- failed-authorization => folder-full-locked
- image__broken => camera-crossed
- image__missing_image => diagonal-line
- image__no_image => camera
- link-external__broken => camera-chain-broken
- link-external__working => camera-chain
- page-not-found => fox-desert
- project-expired => sandclock
- project-suspended => doors-closed
- radio-check-icons => dont know. These are deprecated anyways. Not sure where they are still used
- unexpected-error => icecream

**Comment by tdeekens** [comment]
Nice. Thanks for jumping on it so quickly 🖤. diamond-behind-fence maybe is `locked-diamont` or sth :D

**Comment by filippobocik** [comment]
locked-diamond sounds good to me! :)

**Comment by tdeekens** [comment]
Released with v14.
