### ISSUE TITLE
@commercetools-frontend/jest-preset-mc-app > jest-plugin-filename > lodash  dependency vulnerability

### ISSUE THREAD

**Issue by FlopiVG** [commercetools/merchant-center-application-kit#548]
**Describe the bug**
When I run `yarn audit`, have a vulnerability in @commercetools-frontend/jest-preset-mc-app > jest-plugin-filename > lodash.

**To Reproduce**
Run `yarn audit` in version 12.0.0 or greater

**Expected behavior**
Pass audit without vulnerabilities

**Screenshots**
![image](https://user-images.githubusercontent.com/9992637/56204383-95949d00-6047-11e9-89f8-eeb65eaebdb8.png)

**Comment by tdeekens** [comment]
Thanks for reporting. The PR https://github.com/commercetools/merchant-center-application-kit/pull/535 should fix this as it replaces `jest-plugin-filename`. We haven't released a new version but plan to soon (this week likey).

**Comment by tdeekens** [comment]
Released as 13.3. Thanks again!
