### ISSUE TITLE
react-select v1 css should be applied by default

### ISSUE THREAD

**Issue by montezume** [commercetools/merchant-center-application-kit#554]
In applications that don't use react-select v1, it's weird to have to apply the css themselves. It would make more sense if it's done as part of the app kit.

I just refactored an app not to use react-select v1, and I tried to remove it, but broke the app as app kit is expecting it to be applied.

**Comment by montezume** [comment]
Relates to #311

**Comment by emmenko** [comment]
Yeah, I was hoping to remove react-select from the app-kit to be honest

**Comment by montezume** [comment]
@emmenko yeah it would be nice to replace the project switcher with something made with downshift, but we never got around to it and I'm not sure anyone has time to work on it...
