### ISSUE TITLE
CSP policy complains about webpack-dev-server hot reloading

### ISSUE THREAD

**Issue by montezume** [commercetools/merchant-center-application-kit#569]
Running the MC locally, you get a lot of messages like below, due to the webpack-dev-server's hot reloading breaking the CSP policy 
![Screen Shot 2019-04-24 at 11 12 12 AM](https://user-images.githubusercontent.com/2425013/56648072-e7aa7380-6682-11e9-902d-91bb6239be0e.png)

**Comment by montezume** [comment]
![Screen Shot 2019-04-24 at 11 56 38 AM](https://user-images.githubusercontent.com/2425013/56650801-1414be80-6688-11e9-97bb-8871d43f1651.png)

**Comment by tdeekens** [comment]
Do you know why it uses such a specific IP?

**Comment by montezume** [comment]
@tdeekens that's my IP

<img width="347" alt="Screen Shot 2019-04-24 at 12 01 09 PM" src="https://user-images.githubusercontent.com/2425013/56651130-ae750200-6688-11e9-8dc9-75b9fe19fc0d.png">

**Comment by tdeekens** [comment]
But your IP is not my IP. So how can we add a generic IP? Maybe it's less of an app-kit but in app concern?

**Comment by tdeekens** [comment]
I think we'd have to add all local IP adresses of all local cards to the cors whitelist. Most people seem to just `*` (disable) cors with the dev server. Which I don't really admire as the dev setup then moves away from the stage/prod setup.

**Comment by montezume** [comment]
What I don't understand is that when I run the playground app, it uses `localhost`, whereas when I use one of our apps, it uses my IP address...

**Comment by emmenko** [comment]
So is this happening only to you then?

**Comment by montezume** [comment]
I'm not sure where you got that from what I said?

Can you confirm that you don't experience this in the MC-FE?

**Comment by emmenko** [comment]
I checked both on mc-fe and playground and I get the errors in both of them.

Maybe some recent dependency update caused this? We'll have to investigate this further.

**Comment by qmateub** [comment]
After checking it with @montezume . I have this problem locally too.

![image](https://user-images.githubusercontent.com/11442895/56724490-6539b680-674b-11e9-9b2a-37018eba3fd2.png)

**Comment by emmenko** [comment]
There was a bunch of dep updates recently to the mc-scripts and webpack

https://github.com/commercetools/merchant-center-application-kit/pull/551/files#diff-442d77bd3d87889bf8a45de8767c520e

Might be worth looking into that

**Comment by tdeekens** [comment]
Tada: https://github.com/webpack/webpack-dev-server/pull/1664

**Comment by emmenko** [comment]
For example, in webpack-dev-server v3.3.0 there was this change introduced

https://github.com/webpack/webpack-dev-server/pull/1664

I don't know if it's related to the problem, we would need to test things out

**Comment by tdeekens** [comment]
https://github.com/commercetools/merchant-center-application-kit/blob/38c44ebe693f58d5d01dc732c8c00e631757623a/packages/mc-scripts/config/webpack-dev-server.config.js#L17

Maybe this should be `127.0.0.0`?
