### ISSUE TITLE
Installing starter template with npm fails to compile

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#665]
The fix: https://github.com/commercetools/merchant-center-application-kit/issues/665#issuecomment-496306434

---
**Describe the bug**
Starting the app with dependencies installed via `npm` causes webpack to fail to compile

**To Reproduce**
Install the application template starter with `npm`, then run `npm start`

**Expected behavior**
Installing the dependencies with `npm` should still work, as it does with `yarn`

**Screenshots**
<img width="424" alt="image" src="https://user-images.githubusercontent.com/1110551/58435887-0c9b6780-80c3-11e9-965a-1dd4fed8c10e.png">

**Comment by emmenko** [comment]
It's weird that it works with `yarn` but not with `npm`. Is the problem in the way the dependencies are installed, or with babel or webpack?

**Comment by tdeekens** [comment]
I would assume it resolves to a different tree of node_modules, but just a wild first guess.

**Comment by emmenko** [comment]
This seems to be related to this problem: https://github.com/webpack/webpack/issues/8656#issuecomment-456010969

**Comment by tdeekens** [comment]
Ah. So it‘s how webpack relies on acorn and how yarn and npm resolve to a different dependency graph? Maybe a package lock can help. Still maintaining it is also effort. Can we require yarn until the problem fades?

**Comment by emmenko** [comment]
```
npm install acorn --save-dev
npm dedupe
npm start
```

This seems to fix the problem. I'll see if I can add a "throubleshooting" section to document this problem.
