### ISSUE TITLE
CSS in JS should be linted

### ISSUE THREAD

**Issue by montezume** [commercetools/merchant-center-application-kit#680]
#### Summary

Since the package `application-components` makes use of CSS in JS, it would make sense to add CSS linting to it. 

This was added to ui-kit in this [pull request](https://github.com/commercetools/ui-kit/pull/815)

It should be not too difficult to get this setup for app kit as well. We need to make sure we resolve stylelint to the new version though 😆

**Comment by tdeekens** [comment]
I'll pick this this week during FLD time.
