### ISSUE TITLE
Document API contract

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#689]
We need to set up some ground rules about the process to introduce breaking changes (mostly from the MC API perspective) and some kind of "contract" between us and 3rd-party developers.

Here some thoughts on how we can go about that:

- custom applications are still under "beta" flag, which means that there might be some breaking changes along the way. We usually try to be as backwards compatible as possible but sometimes it's inevitable. As a consequence, the developers (and the customers) need to be aware of this.
  - before introducing breaking changes, we will try to do more thorough research by looking at our internal logs and metrics. We will then communicate a due date for the breaking change release, giving you (developers) time to adjust. I would say like between 1 week and 3 weeks, depending on the situation.
    - in some cases, where e.g. a breaking change only affects a few custom applications, we will try to communicate it directly with the developers/customers
  - we need to establish some sort of "last supported versions" where we will do the above mentioned steps. After that, it's not our responsibility anymore.
    - we support back to "x" versions of appkit dependencies (_although it's not a good measure, because we don't have fixed planned releases, i.e. we could potentially release 3 majors versions within a week_)
    - we support back to "x" weeks/months

---

Additional things:
- document deprecated fields of MC GraphQL API with a deadline about fields being supported

**Comment by tdeekens** [comment]
Thanks. My initally thoughts on this would be something like:

1. Backwards compatible support for two major version and a minimum of two months
   - A focus on business and feature needs can't be blocked by having to support any version
2. Breaking API changes are measured and affected users contacted through customer succcess managers or support
3. Changelogs with migration steps are provided (potentially codemods where meaningful)

**Comment by emmenko** [comment]
Done in #1205
