### ISSUE TITLE
Expose version.js file from each package

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#690]
**Is your feature request related to a problem? Please describe.**
As a consumer of the packages I want to import the version of the package within my application code, so that I can e.g. send the version of a package to an analytics or metrics service.

**Describe the solution you'd like**
Packages should expose a `version.js` file that can be imported by applications, containing the version of the given package.

**Additional context**
Read more info about this in #688

**Comment by tdeekens** [comment]
Current status of investigating things through `@flopflip`.

1. `React` and Apollo both write a version file by hand (it's not build into rollup at all)
2. lerna _does not_ invoke `postversion` or `prepublish` run scripts
   - This could've helped to generate something after things got versioned but _before_ published.

**Comment by emmenko** [comment]
Yeah, this is how apollo does it: https://github.com/apollographql/apollo-client/pull/1038

They manually publish the package though: https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/scripts/deploy.sh

I don't think there is much of a choice here: if we want to have the correct version in the bundle, we need to bump it **before** building it.
Maybe we should look into "manually" executing the lerna steps, instead of just call `lerna publish`.

**Comment by emmenko** [comment]
Yeah, I think the trick is to bump the version **before** bundling. Then we can expose the version however we want (e.g. as a file, as an export from a components, etc). This would also help to configure the user agents.

PS: a note about the user agents. We can't override the user agent because the browser sends its own. We could however send a `x-user-agent` header, which we can use in our logs.

**Comment by tdeekens** [comment]
Daheck, deep down from a lerna issue: "Also: the lifecycle scripts only run if I have a version script".

**Comment by emmenko** [comment]
Thinking out loud about a possible approach:

- run `lerna version` without creating any commit or push, the packages will contain the updated version though
- build the package, which can use the new version
- discard the changes of the version packages
- run `lerna publish` as usual

**Comment by tdeekens** [comment]
Yes, that's kind of the forward/backward-build step I was hoping to avoid.

1. `lerna release`
2. Triggers `lerna postversion`
3. Read the version from `package.json` put it into `versions.js`
4. Amend the commit
5. Publish

**Comment by emmenko** [comment]
Yeah but we probably want to know the version within the JS bundle, so we need to bump it before building it (and before triggering the release)

**Comment by tdeekens** [comment]
> Yeah but we probably want to know the version within the JS bundle, so we need to bump it before building it (and before triggering the release)

We would march into the bundle and replace a `__TO_NOT_TOUCH_THIS_STRING_ITS_OUT_VERSION_`.

**Comment by tdeekens** [comment]
It's driving me nuts. `lerna` even has tests for this but I can't get it to invoke them: https://github.com/lerna/lerna/blob/a7ad9b60d27b390fde21fd2837f2d97320c4603e/commands/version/__tests__/version-lifecycle-scripts.test.js

**Comment by tdeekens** [comment]
Okay moving closer. With `lerna version` _and_ when having a `version` run-script it nicely invokes the `preversion` and `postversion` on root and package level. I presume we only want package level. As expected the `preversion` has the __old__ version of the package. Whereas the `postversion` as the updated version number in the `npm_package_version` while there is also a `npm_package_name`.

**Comment by emmenko** [comment]
Besides the release workflow, the main question I have is if we bump the version **before** or **after** we build the JS bundles.

If we bump it before, we can access the version from the JS files and include it in the bundle.
If we bump it after, we can only try to hook into the postversion and generate a `version.js` file on-the-fly.

**Comment by emmenko** [comment]
For instance, if we want to send proper user-agent information (sdk + apollo-client), we need to know the version on build time, so that it's built-in within the app-shell.

Additionally, we can hook into `postversion` to write the `version.js` file.

**Comment by tdeekens** [comment]
Yes, the flow in my head would be

1. Run `lerna publish` or `lerna version` and then` `lerna publish` (as long as we get the `npm_package_version` at some point
2. This triggers a build (we build without the version replaced or present in bundles)
3. Hook into the `postversion` in a given package
3.1 We replace some string of write a module (in previously built files) to but the `npm_package_version` in there
3.2. We commit add and amend the change
4. Publishing finishes

Does that make somewhat sense?

**Comment by tdeekens** [comment]
Okay. I found out that `lerna` officially supports a `prepare` in each sub-package which is invokved right before publishing happens. I could not get `postversion` to be triggered when publishing - only when versioning.
