### ISSUE TITLE
Enhance and move playground into a starter template

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#704]
The idea is to:
- enhance the playground app (for managing state machines) to make it a more complete example of managing data in the UI
  - data fetching using rest (sdk)
  - list view and details view
  - basic form management
- move the playground into a starter template, so that people can actually download it and use it as a starter point

Furthermore, this would be really helpful for me to get feedback about the docs and the tooling.

**Comment by mmaltsev-ct** [comment]
For now, we concentrate on doing #2297 and #1668. Closing the issue.
