### ISSUE TITLE
Investigate usage of PullPanda

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#763]
https://twitter.com/natfriedman/status/1140666428745342976?s=21

**Comment by tdeekens** [comment]
Good issue 🤗. I already sent a message to our CTO if we‘re allowed to install it. Before requests to install Pull Reminders were denied.

**Comment by emmenko** [comment]
I've installed it for the app-kit, I'll play around a bit with it to see if it's useful.

**Comment by emmenko** [comment]
Here's a breakdown of some of the analytics. Very interesting stuff.

# Reviews
- PRs reviewed: The number of pull requests the reviewer has either approved, requested changes, or left comments on.
- Comments: The number of review comments the reviewer has posted.
- Ratio: The average number of comments per PR reviewed.

<img width="885" alt="image" src="https://user-images.githubusercontent.com/1110551/59716876-13774f00-9217-11e9-96b2-69b3e15fdd1c.png">

# Review turnaround
- Avg time: Average time elapsed between a review being requested and the reviewer responding. Reviews without a matching review request are excluded.
- Requests: The number of review requests the reviewer has responded to.

<img width="883" alt="image" src="https://user-images.githubusercontent.com/1110551/59716938-3efa3980-9217-11e9-9258-d704bbd92431.png">

# PR size
- Avg size: The average size of the author's pull requests. Size is the sum of lines changed, added, or removed.
- Max size: The size of the author's largest pull request. Size is the sum of lines changed, added, or removed.
- PRs: The number of pull requests opened by the author during this time period.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/1110551/59716996-5d603500-9217-11e9-81cc-37859437c064.png">

# PR throughput

<img width="886" alt="image" src="https://user-images.githubusercontent.com/1110551/59717146-bc25ae80-9217-11e9-9342-6e84d7f6af53.png">

# Review turnaround

<img width="884" alt="image" src="https://user-images.githubusercontent.com/1110551/59717214-da8baa00-9217-11e9-97fd-9fa03dc029a7.png">

**Comment by tdeekens** [comment]
Interesting indeed. I always worry a bit that these raw numbers without a goal can easily make people feel bad or be a bit counter productive. Maybe it's something to discuss at the FE off-site how people feel comfortable and safe dealing with this.

**Comment by emmenko** [comment]
Yeah true, it would be interesting to discuss and evaluate the "assigner" feature, with the goal of balancing a bit the workload and spread more the knowledge.

<img width="886" alt="image" src="https://user-images.githubusercontent.com/1110551/59719460-af578980-921c-11e9-81d5-043b2b2562de.png">

**Comment by tdeekens** [comment]
Feels like we didn't continue on using it as we don't have clear ideas on how to use it.

**Comment by emmenko** [comment]
I think one of the interesting parts was the slack integration for reminders and the assigner. We haven't looked into those so far. Also, since some time passed, we should have better "real" data for analytics and stuff.

Should we try out the slack integration first?

**Comment by tdeekens** [comment]
We can sure. I personally don't feel like I struggle with loosing track of reviews people expect but that's maybe also only my view :). Let's ask others if it would help them.
