### ISSUE TITLE
Investigate problems with Percy

### ISSUE THREAD

**Issue by montezume** [commercetools/merchant-center-application-kit#767]
Ever since we introduced the first iteration of the `ModalPage`, Percy has been considering every PR to be introducing this new page. We need to figure out why, and fix it, because now in App Kit Percy is not adding much value.

**Comment by emmenko** [comment]
Yeah it's weird. Should be maybe uninstall Percy in appkit and re-install it again? 🤔

**Comment by montezume** [comment]
It's worth a shot? Can you try it?

**Comment by emmenko** [comment]
I archived the project and created a new one...let's see what happens

**Comment by emmenko** [comment]
I've pushed a commit to master (https://github.com/commercetools/merchant-center-application-kit/commit/23d7ed031677e29cb8d950132321e8f7749b97ee) that should trigger percy, which will set the baseline for the VRTs.

**Comment by emmenko** [comment]
Wait, we don't run percy on master... 🙃

**Comment by emmenko** [comment]
I'll use #769 to set the baseline for the VRTs

**Comment by emmenko** [comment]
I have a feeling that when we skip the percy build, the next time it asks for approvals again. Maybe we should just run percy on each commit like in uikit?

**Comment by montezume** [comment]
The weird thing is we skip Percy in UI-Kit as well, when it's not a PR

**Comment by emmenko** [comment]
That's fine, but here we additionally skip it on PRs...I think that's the problem

**Comment by montezume** [comment]
Let's remove the skipping and see if it fixes it?

**Comment by emmenko** [comment]
Percy now runs on all PRs, let's see how it goes.

**Comment by montezume** [comment]
We are still having this issue. We need to contact Percy support about it I reckon. Can anyone volunteer to take this on?

**Comment by emmenko** [comment]
I guess...let's wait for a couple more PRs, just to make sure this problem is still there.

**Comment by emmenko** [comment]
Did it happen again? #791 

![image](https://user-images.githubusercontent.com/1110551/60248322-b3da0d00-98c2-11e9-980c-5bce7f5cba7e.png)

**Comment by montezume** [comment]
Yes, I had to approve the diff there. That's why I reopened this 😇

**Comment by emmenko** [comment]
Yeah ok...if you have time please reach out to their support. Otherwise I'll do that later/tomorrow

**Comment by montezume** [comment]
I have noticed something weird today. Take a look at two open PRs.

https://github.com/commercetools/merchant-center-application-kit/pull/827

and https://github.com/commercetools/merchant-center-application-kit/pull/825

The first PR has target master. That PR is showing all the VRTs as "new"

While the second PR has target v14 and the baselines are defined

🤔

**Comment by emmenko** [comment]
Weird...should we then get in touch with their support?
