### ISSUE TITLE
AWS Specific custom application deployment docs

### ISSUE THREAD

**Issue by robmoorman** [commercetools/merchant-center-application-kit#772]
**Where would you like to deploy your custom application?**
* AWS Lambda (with API Gateway)
* S3 Bucket (there are some options with redirect policies etc.)

**Additional context**
The Zeit Now example in the docs lacks of best practice instructions how to draw up a lambda app which also can be used to host the custom application within aws infrastructures. The new `compile-html` method of `mc-scripts` helps a bit to get the static files.

From that static file perspective it would maybe possible to host the custom application in a S3 Bucket with limited routing (Redirect Rules, issue here is that a wildcard is not supported).

**Comment by emmenko** [comment]
Hi, thanks for submitting an issue.

We are also very interested in providing more deployment examples as we want to support many different use cases.

At the moment, the playground app implements a [transformer](https://github.com/commercetools/merchant-center-application-kit/blob/master/playground/config/transformer-now.js) to generate the config for Now v2, which runs on lambda functions.

The idea with the transformer was that you can use that to generate whatever config/files you may need to host your static files.
I'm not too much familiar with using AWS lambda directly, could you maybe describe in more details how you would usually deploy there and what kind of configuration/files you need?

I'm happy to help you out as much as possible but I need to understand a bit more what is missing and how can I help you.

Thanks!

**Comment by emmenko** [comment]
FYI: @stephsprinkle is working on the documentation for this #932

**Comment by ebonertz** [comment]
Hi @robmoorman  
We have recently published a some new documentation for the App Kit that includes an AWS S3 deployment example.. Hope you find this helpful and please let us know if you have any questions of feedback. https://appkit.commercetools.com/deployment/example-aws-s3-cloudfront

**Comment by emmenko** [comment]
Closing, feel free to reopen if necessary.
