### ISSUE TITLE
More icons as options for custom application registration

### ISSUE THREAD

**Issue by robmoorman** [commercetools/merchant-center-application-kit#773]
**Is your feature request related to a problem? Please describe.**
Limited options for icon selection of custom application registration.

**Describe the solution you'd like**
Looking at the UIKit there are a lot of icons available. Only a selection of these are available from the registration form:

![Screen Shot 2019-06-19 at 09 36 29](https://user-images.githubusercontent.com/529396/59745844-e908ae80-9275-11e9-9100-45d524bb1aff.png)

A dropdown with corresponding icon (and a link to the icon section in the UIKit) would give more options.

**Additional context**
In our use-case we added a moderation review app and used the ReviewIcon. During development you can use it via the menu.json, except registration doesn't allow this icon.

**Comment by montezume** [comment]
Just to give some background - the reason why we limited the icons to a few instead of importing all of the icons from UI-Kit is because it would have blown up treeshaking and resulted in bigger bundle sizes.

However, that said, I don't see why we wouldn't be open to adding specific icons to the form.

**Comment by robmoorman** [comment]
Ah ok. What you can do is a require context and create a mapping for them (rather than including all the svg's probably and blow up the size) and place that in a dropdown (so without visual icons).

Would it be possible to add the ReviewIcon?

**Comment by emmenko** [comment]
Hi, thanks for raising this question.

This is a valid concern and we knew that from the beginning as we wanted to get feedback first and understand the use cases. The icons exposed in uikit could be used but usually they are used for speicifc cases, and using them for the menu links might be confusing at times.
If that's a valid use case though, we can think of changing that.

Furthermore, one of the ideas for custom apps was to also allow external icons to be used. This is just an idea but would that maybe be also an option for you, or in general for custom apps?

Thanks a lot, we're happy to get as much feedback as possible!

**Comment by emmenko** [comment]
Hi @csi-lund , today we finally released a new milestone for Custom Applications with many new features, including more icon options to be selected. In the future there will also be an option to include your own SVG icons.

You can read more about the new features: https://docs.commercetools.com/custom-applications/migrating-from-project-level-custom-applications

Don't hesitate to reach out to us if you have further questions:
* You can re-open this issue.
* You can open a GitHub discussion.
