### ISSUE TITLE
Define constants for the z-index of Modals and Dialogs

### ISSUE THREAD

**Issue by jonnybel** [commercetools/merchant-center-application-kit#864]
### Is your feature request related to a problem? Please describe
Following the implementation and usage of the new ModalPages, already some cases have been found where Dialogs are being displayed behind ModalPages, because they have a lower `z-index`, and they need to be set manually for each case in order to be fixed, but because there are a lot of different combinations of stacked ModalPages and Dialogs that can show in one place or another, setting the perfect values everywhere may be a difficult task.

### Describe the solution you'd like
I was thinking of defining constants for these values, shared across all apps of our MC, but I've realized this should first be defined here on the app-kit, as it could save a lot of work just by **having good defaults**.

Currently, both ModalPages and Dialogs have a default `z-index` of `1000`, and ModalPages will stay on top because they increment `1` to the base z-index per each unit of `level`, which means a level 1 ModalPage (the default) will start with z-index of `1001` and that's why it stays on top of the default Dialog.

I think it's reasonable to say that a Dialog should be on top of a ModalPage in the vast majority of cases, as a ModalPage is simply a page which can trigger other ModalPages or Dialogs on top of it, while a Dialog usually is something that appears on top of everything and usually doesn't trigger opening another Page on top of it (though it might happen, and one can set the prop manually for such cases).
That being said, I believe we should change the default values of the `z-index` for ModalPages and Dialogs so that the latter have a much higher value than the former.
* ModalPages could stay at `1000`, and with their stacking mechanic they increase by a unit with each level (1001...1002...1003, etc). So this stays the same.
* Dialogs should have a default considerably higher than that, to make sure they are rendered on top of ModalPages even if there are several ones stacked on top of each other.
Could be a z-index of `2000`.

What do you think?

**Comment by emmenko** [comment]
Yeah, I can see that having multiple layers might get confusing...I'm wondering maybe if we can solve this using context, so the calculation of the z-index is done implicitly by the components.

Not 100% sure how to properly implement it though...

Otherwise your proposal also makes sense. I'm just thinking if we can solve this issue by letting the components deal with it automatically.

**Comment by jonnybel** [comment]
Yes, I like the idea of having the z-index being set automatically through a global context. But that would have to be done on the app-level, and not bundled with the app-kit components, or could it?

Anyway, even with a context-based solution, I still think the defaults are currently not very good and it would already solve some situations by having the Dialogs stay on top of ModalPages by default.

**Comment by emmenko** [comment]
I would like us to think a bit about this and decide which direction we want to go. I would like to avoid implementing one thing and then change it again later on.
