### ISSUE TITLE
The future of `injectAuthorized` and its sublings

### ISSUE THREAD

**Issue by tdeekens** [commercetools/merchant-center-application-kit#879]
# The future of `injectAuthorized` and its sublings

> In the future our permissions package will have to receive some features. I would like to discuss how to add them from an API standpoint.

## Use Cases

Currently the `injectAuthorized`, `RestrictedByPermissions` and `useIsAuthorized` accepts a list of `TPermissions` which can be e.g. `['manageOrders', 'viewProducts']`. This list behind the scenes is mapped to the so called cancase and matched against the `permissions` on the application's context. These permissions currently come from `allAppliedPermissions` and contain resource accesses and action rights (to be released).

In the future we need to accomodate more types of permissions. Namely action rights and data fences.

### Action Rights

Strictly relate to a permission group of `MyPermission` in CTP. The API could return

```js
[
   {
      group: "products",
      resourcePermissions: ["manageProducts"],
      actionRightPermissions: ["editPrices"]
   },
   {
      group: "orders",
      resourcePermissions: ["manageOrders"],
      actionRightPermissions: ["editPrices", "deleteOrder"]
   }
];
```

This already shows that action rights will overlap across groups. Something we can not really account for in the current system without doing some sort of prefixing so that our `permissions` context looks like:

```js
{
   canManageProducts: true,
   canEditProductPrices: true,
   canEditOrderPrices: true,
}
```

This may now still sound reasonable but gets odd with action rights such as `publishProductProducts`. My general feeling is that we try to mix what does not really have to belong together just as it doesn't in the Core WS GraphQL response. More on this later.

### Data Fences

Data fences are still in its infancy but will become a quite powerful feature to restrict what the API returns. The first data fence to be introduced is the store fence in orders so that a user of the MC can only see orders of say the French store but not the Italian store.

For this we will likely add a `allAppliedDataFences` of the shape:

```js
[
   {
      type: "store",
      values: {
         storeKeys: ["frenchStore"]
      }
   }
];
```

This shape can change to feel more natural to GraphQL using Union Types but that's currently up for debate.

These two new "families" of permissions raise the question how we will integrate them into our current set of component. The topic of this issue.

### Proposed APIs

There are likely 2-3 (or even more) APIs to add these new things to the package. To summarize what we could do

#### Reuse existing components

We could use the components we have to add to them in a backwards compatible (leading to a breaking change) way. This would mean the options/props passed will change.

Now

```js
injectAuthorized(["manageOrders"]);
```

Later

```js
// Option 1:
injectAuthorized({
   type: 'permission',
   permissions: ['manageOrders']
})
injectAuthorized({
   type: 'actionRight',
   actionRights: ['editPrices']
   group: 'products'
})
injectAuthorized({
   type: 'dataFence',
   dataFence: 'store',
   access: 'viewOrders',
})
// Option 2:
injectAuthorized(['manageOrders'])
injectActionRIghts({
   actionRights: ['editPrices']
   group: 'products'
})
injectDataFence({
   dataFence: 'store',
   access: 'viewOrders',
})
```

The tricky question is how we can anticipate which API is easier to maintain. I personally like having one set of components as it's less code to deal with and keep in sync. Moreover, things often relate: data fences relate to their parent resource access etc.

**Comment by emmenko** [comment]
Thanks for looking into that.

From our meeting earlier, we also talked about (_maybe you had to leave at that point_) keeping the same API that we have now and use the **second argument** to configure the action rights / data fences.

```js
injectAuthorized(
  ['ManageProducts'],
  {
    shouldMatchSomePermissions: true,
    actionRights: ['editPrices'],
    dataFence: 'store',
    // any other option that we want
  }
)
```

**Comment by tdeekens** [comment]
Yeah, that's also a nice idea which results in less code having to move around. I think it also communicates that everything relates around a resource access.

**Comment by emmenko** [comment]
Yeah I think this would be a good starting point, without having to change much the APIs.

It also kind of implies that the _default permissions_ are still the main important part and that action rights / data fence are just additional restrictions that you apply **on top of it**.

**Comment by tdeekens** [comment]
Yeah. We need them to be objects though cause otherwise the name clash issue will remain. So options has a ‚actionRights‘ property so it can have an array of name group pairs.

**Comment by tdeekens** [comment]
I think the API will have to be

```js
injectAuthorized(
  ['ManageOrders'],
  {
    shouldMatchSomePermissions: true,
    actionRights: [{
      name: 'editPrices',
      group: 'orders',
    }]
    dataFence: {
      type: 'store',
      access: 'ManageOrders',
    },
  }
)
```

I would really like to get rid of `shouldMatchSomePermissions` it's often leads to wrong use of the components, e.g. `ViewCategories` and `ManageCategories` while both being joined with `shouldMatchSomePermissions`. I think it would be easier to advocate using multiple HoCs or hooks. So: `const isAuthoried = useIsAuthorized('ViewCartDiscounts') || useIsAuthorized('ViewDiscountCodes')`. Also cause it not is unclear what `shouldMatchSomePermissions` actually "mapps" to. Does it only mean resource access or also in confunction with the action rights (it doesn't but is confusing).

**Comment by emmenko** [comment]
> I think the API will have to be

Yes of course, I was just pointing out to use the 2nd argument which is an object.

> `const isAuthoried = useIsAuthorized('ViewCartDiscounts') || useIsAuthorized('ViewDiscountCodes')`

Hmm are you sure we can use them like this? Shouldn't each hook be defined without conditional blocks?

```js
const canViewCartDiscounts = useIsAuthorized('ViewCartDiscounts');
const canManageCartDiscounts = useIsAuthorized('ViewCartDiscounts');
const isAuthorized = canViewCartDiscounts || canManageCartDiscounts;
```

> I would really like to get rid of `shouldMatchSomePermissions` it's often leads to wrong use of the components

Hmm maybe you have more hands on experience with this but I'm not sure I fully understand what kind of confusion this might lead to.

> Also cause it not is unclear what `shouldMatchSomePermissions` actually "mapps" to. Does it only mean resource access or also in confunction with the action rights (it doesn't but is confusing)

I suppose that if we introduce action rights + data fences to the soup, we would need to rethink a couple of things yes.
However, I would like first to have concrete examples of using a mix of them with the expected output and see where things might get confusing. If you can provide some, that would be great.

**Comment by tdeekens** [comment]
> Yes of course, I was just pointing out to use the 2nd argument which is an object.

Sure. Great suggestion just iterating and making it more concrete.

> Hmm are you sure we can use them like this? Shouldn't each hook be defined without conditional blocks?

Pretty sure. I don't think you need to store the return value of a hook in a variable.

> However, I would like first to have concrete examples of using a mix of them with the expected output and see where things might get confusing. If you can provide some, that would be great.

Yeah I think we should "just get going" a bit and then remove/adjust. Right now use cases for me are just to support action rights. @adnasa will maybe use the data fence support once or twice.

**Comment by emmenko** [comment]
> Pretty sure. I don't think you need to store the return value of a hook in a variable.

I mean the rules about having hooks within a condition: https://reactjs.org/docs/hooks-rules.html

> Don’t call Hooks inside loops, conditions, or nested functions.

Isn't `a || b` a condition? 🤔

**Comment by tdeekens** [comment]
> Don’t call Hooks inside loops, conditions, or nested functions.

Ah, you're right cause the condition has an early exit and hence the order of them isn't stable. I think you could use them in an `&&` though cause them all are evaulated. What the docs mostly mean with conditions is `if`/`else` blocks to my understanding.

**Comment by emmenko** [comment]
Anyway, I think we can first experiment with this API and then see how we can make things simpler:

```js
injectAuthorized(
  ['ManageOrders'],
  {
    shouldMatchSomePermissions: true,
    actionRights: [{
      name: 'editPrices',
      group: 'orders',
    }]
    dataFence: {
      type: 'store',
      access: 'ManageOrders',
    },
  }
)
```

**Comment by adnasa** [comment]
I think there is room for experimentation here.
we can create the `dataFence` as non array for now, knowing that we may have to change it later on.

For `dataFences` to actually work, we need to read from `allAppliedDataFences` and match its values to e.g `orders.store.storeKey`, something that may [happen here](https://github.com/commercetools/merchant-center-application-kit/blob/master/packages/permissions/src/components/authorized/authorized.tsx#L73).

This will be a side affect however and the shape of `store` difference from resourceType.
